### ISSUE TITLE
Hijack Joystick Controls to Use Custom Input

### ISSUE THREAD

**Issue by 4DJR** [turtlebot/turtlebot4#100]
When using a PlayStation 4 controller to drive the Turtlebot, I understand that the joystick values are being published to the /joy ROS topic. However, when trying to find the source that is publishing the /joy topic I was unable to find the program so I could modify it to publish a different input so it could bypass the joystick values and be injected into the pipeline instead. What is the file path to the file on the Turtlebot that would allow me to publish different values to the /joy topic? Is there a better way to control the Turtlebot with a custom input? Thanks.

**Comment by roni-kreinin** [comment]
This is the default config file for the turtlebot4 controller: https://github.com/turtlebot/turtlebot4_robot/blob/galactic/turtlebot4_bringup/config/turtlebot4_controller.config.yaml

It gets used by the [joy_teleop](https://github.com/turtlebot/turtlebot4_robot/blob/galactic/turtlebot4_bringup/launch/joy_teleop.launch.py) launch file which launches the joy nodes. You can create a custom file and pass it to the joy_teleop file as the `controller_config` argument.
