### ISSUE TITLE
Can I use the Oak-D-Pro camera on the Turtlebot4 Lite and how?

### ISSUE THREAD

**Issue by jxq999** [turtlebot/turtlebot4#102]
In my experiments, I found that running "ros2 launch turtlebot4_viz view_ model.launch.py" did not appear any response pictures after replacing oak-d-lite on Turtlebot4 Lite with oak-d-pro. Did I miss any steps or is it not feasible to change the camera? Looking forward to your reply!

**Comment by roni-kreinin** [comment]
@jxq999 The launch file for the OAK-D should work with both the lite and pro. The issue with Rviz is likely that you are using the default TTB4 lite description which uses the OAK-D lite. Try running `ros2 run rqt_image_view rqt_image_view` and see if you can visualise the image on the `/color/preview/image` topic.

To fix the description and launch, you will need to modify the [lite urdf](https://github.com/turtlebot/turtlebot4/blob/galactic/turtlebot4_description/urdf/lite/turtlebot4.urdf.xacro#:~:text=%3Cxacro%3Acamera_bracket,xacro%3Aoakd%3E) to use the OAK-D Pro like the [standard urdf](https://github.com/turtlebot/turtlebot4/blob/galactic/turtlebot4_description/urdf/standard/turtlebot4.urdf.xacro#:~:text=%3Cxacro%3Acamera_bracket,xacro%3Aoakd%3E) does. Then, in the [lite launch file](https://github.com/turtlebot/turtlebot4_robot/blob/galactic/turtlebot4_bringup/launch/lite.launch.py), change the tf_prefix to `oakd_pro`.

Let me know if this fixes your issue.

**Comment by jxq999** [comment]
@roni-kreinin Thank you very much for your answer. Actually, I've done it before just as you said. But running `ros2 run rqt_image_view rqt_image_view` didn't allow me to visualize the image on the `/color/preview/image` topic. 
To fix the description and launch, I also have modified the [lite urdf](https://github.com/turtlebot/turtlebot4/blob/galactic/turtlebot4_description/urdf/lite/turtlebot4.urdf.xacro#:~:text=%3Cxacro%3Acamera_bracket,xacro%3Aoakd%3E) to use OAK-D Pro like the [standard urdf](https://github.com/turtlebot/turtlebot4/blob/galactic/turtlebot4_description/urdf/standard/turtlebot4.urdf.xacro#:~:text=%3Cxacro%3Acamera_bracket,xacro%3Aoakd%3E) does. Then, in the [lite launch file](https://github.com/turtlebot/turtlebot4_robot/blob/galactic/turtlebot4_bringup/launch/lite.launch.py), I've changed the tf_prefix to oakd_pro. But it didn't work. There were still no any response pictures after running `ros2 launch turtlebot4_viz view_ model.launch.py`. However, It's worth noting that I made these modifications on the Raspberry Pi of the turtlebot4 lite. Should I make the corresponding changes on my PC as well? Or just modify the PC?

**Comment by roni-kreinin** [comment]
The changes should be made just on the raspberry pi. 

Can you try to launch just the camera by stopping the turtlebot4 service with `sudo systemctl stop turtlebot4`, and then calling `ros2 launch turtlebot4_bringup oakd.launch.py`?

**Comment by jxq999** [comment]
```
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py
[INF0] [launch]: All log files can be found below /hone/ubuntul .ros/log/222-04-21-13-29-45-435298-ubuntu-1718[ INFO] [launch]: Default logging verbosity is set to INFO
[INFoj [rgb_stereo_node-1]: process started with pid [1720]
[rgb_stereo_node-1][18443010510E381300][10.531] [systen] [error] Attempted to start Color camera · NOTdetected!
[rgb_stereo_node-1][18443010510381300] [10.531] [systen] [error] Attenpted to start wono Left camera - NOT detected
[rgb_stereo_node-1] [18443010510E381300] [10.531] [systen] [error] Attenpted to start Mono Right camera - NOT detected!
```

Thanks again for your answer. After I did what you said, I found that the color camera was not detected,  as above. But I tested the camera using oak's demo under win10, it was fine. And I replaced another oak-d-pro camera on the tb4 lite then ran `ros2 launch turtlebot4_bringup oakd.launch.py`. The problem was the same.

**Comment by jxq999** [comment]
@roni-kreinin Good afternoon！My problem has been solved by updating the version of DepthAI.Thank you very much for your help!
