### ISSUE TITLE
Replace OAK-D Lite with Intel RealSense D455 on TB4 Lite

### ISSUE THREAD

**Issue by escortKwon** [turtlebot/turtlebot4#105]
**Describe the the feature you would like**
**I'm looking for the way to replace OAK-D Lite with Intel RealSense D455.**
I've tried SLAM with TB4 Lite on default options. But, whenever I try navigating to creating map, I always feel the FOV of OAK-D Lite is not enough for driving TB4 safely.
In my lab, there are a few D455s. Therefore, I decided to replace OAK-D Lite with those if possible. I believe the change will give more wider view and some opportunities. 

**Other notes**
I saw some demo videos of driving TB4 with RealSense. And also, in mapping process with TB4, I could `RealSense` toggle button on the left side of RViz window. With those features, is it possible for me to try maneuvering TB4 built with RealSense?
Thanks!

**Comment by roni-kreinin** [comment]
The standard oakd launch file uses a small preview window to reduce bandwidth and allow for higher fps. You can change the resolution by modifying the values [here](https://github.com/turtlebot/turtlebot4_robot/blob/galactic/turtlebot4_bringup/launch/oakd.launch.py#:~:text=%27-,previewWidth,-%27%2C).

If you want to use a realsense instead, you will have to install the realsense drivers from [here](https://github.com/IntelRealSense/realsense-ros). You may also need to make changes to the robots [urdf](https://github.com/turtlebot/turtlebot4/blob/galactic/turtlebot4_description/urdf/standard/turtlebot4.urdf.xacro#:~:text=%3Cxacro%3Acamera_bracket,xacro%3Aoakd%3E).
