### ISSUE TITLE
No display on the LED screen

### ISSUE THREAD

**Issue by 01Bob** [turtlebot/turtlebot4#106]
1. There is no display on the small LED screen.
2. We are not able to drive the robot with the controller.
3. Not able to configure.

**Comment by roni-kreinin** [comment]
@01Bob Can you detail what steps you have taken so far in setting up your turtlebot? Has it been connected to wifi?

**Comment by 01Bob** [comment]
It has not been connected to wifi. Can I get help via phone call or video call?

**Comment by roni-kreinin** [comment]
The setup process is fairly straightforward. Try to follow the [Quick Start](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html) guide to connect the robot to wifi.
