### ISSUE TITLE
Not getting odom topic

### ISSUE THREAD

**Issue by Basavaraj-PN** [turtlebot/turtlebot4#107]
After exporting ROS_DOMAIN_ID=0, I'm not able to see few topics in my laptop except below listed.

and no data on /imu topic.

```
➜  ~ ros2 topic list 
/battery_state
/cmd_vel
/color/preview/camera_info
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/joint_states
/joy
/joy/set_feedback
/mouse
/parameter_events
/robot_description
/rosout
/scan
/stereo/camera_info
/stereo/depth
/tf
/tf_static
/wheel_status
```

**Comment by Basavaraj-PN** [comment]
Getthing these inside RPI.

```
ubuntu@ubuntu:~$ ros2 topic list
/battery_state
/cmd_audio
/cmd_lightring
/cmd_vel
/color/preview/camera_info
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/ir_intensity
/ir_opcode
/joint_states
/joy
/joy/set_feedback
/kidnap_status
/mobility_monitor/transition_event
/mouse
/odom
/parameter_events
/robot_description
/robot_state/transition_event
/rosout
/scan
/slip_status
/static_transform/transition_event
/stereo/camera_info
/stereo/depth
/stop_status
/tf
/tf_static
/wheel_status
/wheel_ticks
/wheel_vels
```

**Comment by roni-kreinin** [comment]
Have you connected the Create 3 to a bridged 2.4GHz network? Also have you applied the cycloneDDS profile as mentioned [here](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html#network-configuration)?

**Comment by Basavaraj-PN** [comment]
Yes, I'm on 2.4Ghz band and also cyclone DDS profile is set as per the document.

**Comment by roni-kreinin** [comment]
Are you able to access the Create 3 webserver? If so, can you make sure that it is also using cycloneDDS?

Regarding your network, are you using a personal router, or are you on a university/corporate network? Sometimes the network can block multicast packets.

If it is an issue with the network, try configuring the robot to use the FastDDS discovery server, as described [here](https://gist.github.com/roni-kreinin/8fbb20cb4603b8eb5e3961167fb22cd4). This allows you to use the robot without having the Create 3 connected to Wi-Fi, and can eliminate issues like this one.

**Comment by Basavaraj-PN** [comment]
tried still no luck.
How to get back AP mode again? what is the button combination?

**Comment by NikoShawn** [comment]
refer this:https://turtlebot.github.io/turtlebot4-user-manual/setup/simple_discovery.html
