### ISSUE TITLE
Namespacing support for turtlebot4 teams

### ISSUE THREAD

**Issue by bjbao** [turtlebot/turtlebot4#113]
We are interested in coordinating movements among turtlebots. For this, namespacing support would be necessary. The [user manual](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/multiple_robots.html#namespacing) states that this support will be coming soon. Is there a recommended approach for this?

**Comment by roni-kreinin** [comment]
Namespacing support has been added to the `humble` branch. Because Galactic is EOL we aren't focusing on adding features to it any more. You can make a PR for it similar to the Humble [PR](https://github.com/turtlebot/turtlebot4/commit/b2f8f5c64fee5a616a9710718b4597cf8c126c09) if you are interested. Otherwise, I would recommend waiting for the Humble release.

Note that any updates to the galactic branch will not be released as new debian versions because Galactic is EOL.

**Comment by bjbao** [comment]
I think I found where the namespace [update](https://github.com/turtlebot/turtlebot4_robot/commit/e37b1c7b6d5addbb43e0e46340dc83688461e812) is.  If I update a TB4 to the humble branch today, would I need to do anything special to get basic functionality? Is there a preliminary migration guide that exists, or a preliminary new user guide? Is there a date you're targeting for the humble release?

**Comment by roni-kreinin** [comment]
I don't have a specific release date but I am expecting to start releasing debian packages by next week. Once those are out, I will upload a new RPi image that you will be able to flash to your TB4. There will also be new Create 3 firmware to use. Documentation updates will follow.

I would not recommend updating a TB4 running ubuntu 20.04 to the humble branch as there are some breaking changes.

**Comment by Jayden-F** [comment]
Hello @bbao200905,  I am sorry I didn't see this earlier. After my conversation almost a month ago with Roni. I pulled the changes into a forked repo. Here are the branches for namespacing the robot.

https://github.com/Jayden-F/turtlebot4_ws
The following are submodules of the above:
  https://github.com/Jayden-F/turtlebot4_robot/tree/galactic-namespace
  https://github.com/Jayden-F/turtlebot4/tree/galactic-namespace

To my knowledge the robot is successfully namespaced, however, I am struggling to run localization for multiple robots.

Hope it helps.

**Comment by ipa-rar** [comment]
@Jayden-F Thank you for mentioning about your fork. I tried it for my use case and it did not work as expected. I could see the topics without any namespace. Can you provide some details on what you did to include namespace?

**Comment by Jayden-F** [comment]
@ipa-rar I am assuming you have successfully uinstalled the binaries and built the packages from source. I have added a readme file to the forked repo. The readme file explains how to replace the robot upstart service.

**Comment by roni-kreinin** [comment]
Humble has been released for the robot, including namespacing support. See #119 for details.

**Comment by sumitpaulde** [comment]
Hi @roni-kreinin 
How can I read the Namespace value in the ROS2 node? Where is the value of the Namespace stored?
