### ISSUE TITLE
Cannot run Launch Files on Turtlebot4 Lite

### ISSUE THREAD

**Issue by rohanchandra-cpe** [turtlebot/turtlebot4#114]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed: Installed 
 - Package version: "sudo apt install ros-galactic-desktop" is how I installed ROS2

 **Expected behaviour**
Pressing Button1 on the Create3 produces a message in the terminal that says "Button 1 Pressed!" As per this link here: https://turtlebot.github.io/turtlebot4-user-manual/tutorials/first_node_python.html

 **Actual behaviour**
No message appears upon pressing the button. Pressing CTRL+C to halt the command yields the error message attached in the image. 

**To Reproduce**
Provide the steps to reproduce:
1. Power on the Turtlebot4 (raspberry pi was previously set up to connect to a 5GHz network via wifi.sh)
2. Go to <ip of raspberrypi>:8080 and connect the Create3 to a 2.4GHz network
3. Follow https://turtlebot.github.io/turtlebot4-user-manual/tutorials/first_node_python.html until "Test Create3 Button1 "
4. Run "ros2 run turtlebot4_python_tutorials turtlebot4_first_python_node"
5. Press Button 1 on the Create3

**Other notes**
I am currently attempting to follow the guide for the Turtlebot 4 lite. Specifically the "Creating your first node (Python)" section: https://turtlebot.github.io/turtlebot4-user-manual/tutorials/first_node_python.html. I get to the point where I need to run "ros2 run turtlebot4_python_tutorials turtlebot4_first_python_node." However, nothing happens when I press the first button on the Create3. Instead, when I CTRL+C out of the command, I get the error attached. I have connected the Raspberry Pi to a 5GHz network (wifi.sh) and the Create3 to a 2.4 GHz network. Please let me know how I can resolve this, Thanks!

![main_ros_error](https://user-images.githubusercontent.com/58828165/220740067-ba9cab8c-bc5b-4a0a-a835-c9bb84f1ec83.PNG)

**Comment by roni-kreinin** [comment]
@rohanchandra-cpe Can you call `ros2 topic list` and paste the output here?

**Comment by rohanchandra-cpe** [comment]
Sure thing. The second image is from my normal Ubuntu environment, and the first image was taken after ssh'ing into the raspberry pi. Should I be doing all of my development inside the Raspberry Pi?

I set up my workspace and did the first Python node exercise outside of the Raspberry Pi, for reference. 

![ros2topicechoraspberrypissh](https://user-images.githubusercontent.com/58828165/220746964-039b8856-e4a0-47f0-a72f-69389a60eef0.PNG)
![ros2topiclistoutside](https://user-images.githubusercontent.com/58828165/220746966-914ac18b-e9c9-4999-bedd-8b94700047a9.PNG)

**Comment by roni-kreinin** [comment]
@rohanchandra-cpe It looks like there may be some networking issues going on.

Can you confirm that the Create 3 is connected to Wi-Fi by going to the webserver and checking the "Connect" tab? It should display the IP address if connected like this: 
![image](https://user-images.githubusercontent.com/59886299/220783284-6d69906a-6ed9-4b51-83e3-f14e9bde5a5b.png)

If there is no IP address, try connecting the Create 3 again by following [these instructions](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html#access-the-webserver-v012-or-higher).

It also looks like your PC cannot see the RPi topics. Can you make sure you are using the same `ROS_DOMAIN_ID` on both, and call `ros2 multicast receive` on your PC, followed by `ros2 multicast send` on the RPi to check that multicast packets aren't being blocked by your network?

Regarding development, you should be able to run the tutorial python node on either your PC or the RPi once all of the nodes can communicate with each other properly.

**Comment by rohanchandra-cpe** [comment]
![rosmulticasrsend](https://user-images.githubusercontent.com/58828165/221215370-81ce62df-74a8-4b74-9e61-7d4e85ed1450.PNG)
![rosdomainids](https://user-images.githubusercontent.com/58828165/221215373-3aec976d-e221-42eb-8b47-4158caa096b9.PNG)
Ok, I ran the tests you wanted me to above:

1. An IP address does appear, so it looks like my Create 3 is connected
2. the second image shows the result of searching for the ros domain ids. RPI on left, PC on right
3. the first image shows what happens when I did a ros2 multicast receive on my PC, followed by a ros2 multicast send on the RPI (RPI left, PC right). Nothing happened for about 15 seconds after I did the send command, so I did a CTRL+C on the right and I get that error message.

**Comment by roni-kreinin** [comment]
@rohanchandra-cpe Are you running the robot on a university or corporate network? It's possible that your network blocks multicast packets over Wi-Fi which is used for discovery.

If your network is blocking multicast packets, I would recommend following [these instructions](https://gist.github.com/roni-kreinin/8fbb20cb4603b8eb5e3961167fb22cd4) to configure your robot to use the FastDDS discovery server.

**Comment by rohanchandra-cpe** [comment]
I am on my home network. We have a 5.0Ghz network and 2.4Ghz network. I have connected the former to the Raspberry Pi and the latter to the Create 3. According to the WiFi that I used to set up the RPi (wifi.sh), it should support multicast (image below). 

![wifi0](https://user-images.githubusercontent.com/58828165/221260946-fa9765d8-bfb4-4b9d-b1a4-c0442874ec43.PNG)

**Comment by roni-kreinin** [comment]
Your Wi-Fi interface will support multicast, but your router may still block those packets. You can try going to your router gateway and looking for any multicast settings.

**Comment by rohanchandra-cpe** [comment]
Ok, I'm going to try following the FastDDS instructions and see if that makes a difference. I'll let you know. Thanks!

**Comment by rohanchandra-cpe** [comment]
The FastDDS instructions are not working for me. I get up to the point where I need to run 

sudo systemctl daemon-reload
sudo systemctl enable ip_route.service
sudo systemctl start ip_route.service

And I get the error below. 
<img width="718" alt="rosfastddserror" src="https://user-images.githubusercontent.com/58828165/221382094-e1e50820-ef89-4480-9cfc-a6341c60a75c.png">

I am running WSL 1.0.3.0.  Also, I ran "wsl ~" within the powershell and then run the above commands. I was following this link to try and resolve these issues: https://askubuntu.com/questions/1379425/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate

**Comment by roni-kreinin** [comment]
@rohanchandra-cpe Instead of running the `ip_route` service, you can manually add the ip route by calling `sudo ip route add 192.168.186.0/24 via xxx.xxx.xxx.xxx`, replacing the x's with your RPi IP address. You can add this line to your `~/.bashrc` file to have it run every time a new terminal is opened.

**Comment by rohanchandra-cpe** [comment]
That did not work either. 
![rosiproute](https://user-images.githubusercontent.com/58828165/221636137-a34f8677-20c5-4859-9cc0-36e604514fd2.png)
I also tried with 192.168.001.171 and that didn't work either. 
Is there any other information I can give you to help resolve this error?

**Comment by rohanchandra-cpe** [comment]
Also @roni-kreinin , I already have that exact line you suggested I run in /usr/local/sbin/ip_route.sh on the remote PC. 

![rosuserlocalbin](https://user-images.githubusercontent.com/58828165/221639663-9ab8997d-a1f1-4139-bc23-479215529a59.png)

**Comment by roni-kreinin** [comment]
@rohanchandra-cpe Can you paste the output of `ip a`?

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin  There appears to be some sensitive information in that output. Is there anything specifically you want to see?

**Comment by roni-kreinin** [comment]
Your Wi-Fi interface. You may need to call something like `sudo ip route add 192.168.186.0/24 via 192.168.1.171 dev wlan0`, replacing `wlan0` with your interface name.

**Comment by rohanchandra-cpe** [comment]
This is what I currently see after starting a fresh new terminal. I added the above line to my ~/.bashrc file, and it did not cause any errors when I ran it initially. 

![image](https://user-images.githubusercontent.com/58828165/221664643-ce65f63d-487d-48a6-b7c8-bbe921f64734.png)

At one point the robot started driving towards the docking station when I pressed the button with 2 dots on it, but that does not work right now. Am I missing some additional set up steps?

Also, just as an aside, is there any documentation about what the different colors from the light ring mean?

**Comment by roni-kreinin** [comment]
Can you make sure that you can ping the Create 3 from your PC by calling `ping 192.168.186.2`? Also try calling `ros2 daemon stop` before calling `ros2 topic list`. You may need to call `ros2 topic list` a couple of times to get the topics to show up. Also, SSH into the RPi and check that you can list the topics there.

Lightring states are shown [here](https://iroboteducation.github.io/create3_docs/hw/face/).

**Comment by rohanchandra-cpe** [comment]
I am able to ping that IP address. I also did a ros2 daemon stop before calling ros2 topic list. However, nothing has appeared in the ros2 topic list output in neither the RPi nor my remote PC.  I only see /parameter_events and /rosout

**Comment by rohanchandra-cpe** [comment]
By the way, I do not see an IP address in the online portal for the Create 3. Is this an issue, or to be expected from a FastDDS setup?

![image](https://user-images.githubusercontent.com/58828165/221672029-7093f5c6-b8d7-4c9e-9037-d4726a904ca5.png)

**Comment by roni-kreinin** [comment]
Yes, the Create 3 should not be connected to Wi-Fi for the discovery server setup. Communication with it will be purely over USB-C. That is why we have to add the ip route on your PC.

Lets check a few configurations in your setup to figure out what the issue is. If you could paste the following settings that would be great.

Create 3:
- A screenshot of Application -> Configuration settings in the webserver.

RPi4:
- The contents of `/etc/sysctl.conf`, `/etc/turtlebot4_discovery/setup.bash`, `/etc/turtlebot4_discovery/discovery_super_client.xml`
- The status of the discovery service: `sudo systemctl status discovery.service`
- The status of the turtlebot4 service: `sudo systemctl status turtlebot4.service`

PC:
- ROS envars: `env | grep ROS`

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/221680658-23b8a17a-2490-44f3-921b-6bbe9070fb0a.png)

![image](https://user-images.githubusercontent.com/58828165/221680782-9d4838b0-e260-4fdd-8314-f6949b336398.png)

/etc/sysctl.conf
![image](https://user-images.githubusercontent.com/58828165/221681016-c9034c4c-2481-4342-a3c7-7fdddfac3699.png)

/etc/turtlebot4_discovery/setup.bash
![image](https://user-images.githubusercontent.com/58828165/221681382-9e94921b-b80e-4d54-b290-c1b0420cb274.png)

/etc/turtlebot4_discovery/discovery_super_client.xml
![image](https://user-images.githubusercontent.com/58828165/221681565-059809f0-b9b9-4bb5-ac88-c3e1d3fac99b.png)

systemctl stuff
![image](https://user-images.githubusercontent.com/58828165/221681884-e72230ae-bd25-43c5-84cb-1c04152d5082.png)

**Comment by roni-kreinin** [comment]
The `systemctl` status is showing a time jump from when the services were started. When you call `date` on your robot, does it display the correct time and date?

Also can you run `htop` and check that the CPU's are not being maxed out?

**Comment by rohanchandra-cpe** [comment]
Hey, sorry for the delay @roni-kreinin . Here are the screenshots you asked for.

date appears to show the correct time and date:
![image](https://user-images.githubusercontent.com/58828165/222985553-235f891f-156f-4b37-a147-ca8213700f06.png)

And here is htop on the robot:
![image](https://user-images.githubusercontent.com/58828165/222985638-b5320a34-3220-4cca-a5e0-6ff28481a203.png)

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin I am still struggling with this issue. When you get a chance please see the information I attached above. Thank you

**Comment by roni-kreinin** [comment]
Can you try stopping the turtlebot4 service with `sudo systemctl stop turtlebot4`, then restarting the discovery server service with `sudo systemctl restart discovery`. Once it has restarted, manually launch the turtlebot4 nodes with `ros2 launch turtlebot4_bringup lite.launch.py`. Then, open a new terminal in the RPi and run `ros2 daemon stop`, then `ros2 topic list`. You may need to run `ros2 topic list` twice to get a full list of available topics.

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/223802385-98d300dc-78d4-4f59-937f-d70b258ec9ed.png)

@roni-kreinin I did everything you asked for. The screenshot is from the second Rpi terminal you asked me to make. It looks like I got all the topics at first, but then with multiple "ros2 topic list" calls it went away.

Also, if it helps, this is the result of running ros2 launch turtlebot4_bringup lite.launch.py (sorry it is so small)
![image](https://user-images.githubusercontent.com/58828165/223803139-72d3e867-23e2-4091-bdd4-661edada3753.png)

**Comment by roni-kreinin** [comment]
@rohanchandra-cpe There is likely some configuration that is missing, though I am not seeing anything wrong. Would you be interested in updating to Humble? There is a new setup tool that takes care of all this configuration automatically.

See https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html#robot

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin hey, sorry for the lapse in responses, been busy with work. Since we last talked I have upgraded my Create3 to Humble 1.0, and I have attempted to update my RPi from Ubuntu 20.04 LTS to Ubuntu 22.04 LTS. This morning I was able to ssh in just fine and confirm that the upgrade worked, however, I ran a sudo reboot (following this link: https://github.com/turtlebot/turtlebot4_setup) and now I can no longer SSH in. 

![image](https://user-images.githubusercontent.com/58828165/226647967-7f1fd396-5f6b-4aa6-bb39-90ea88f8abb0.png)

I also cannot access the website for the Create3

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin If I wanted to factory reset the turtlebot4 and start all of the setup from scratch, how would I do that? Also, do you think that would be a good idea?

**Comment by roni-kreinin** [comment]
@rohanchandra-cpe Did you update the RPi4 to Ubuntu 22.04 manually? Or did you use a humble image from http://download.ros.org/downloads/turtlebot4/?

**Comment by rohanchandra-cpe** [comment]
I upgraded it manually. 

sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt autoremove
sudo do-release-upgrade

**Comment by roni-kreinin** [comment]
Can you try to follow https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image to install the official humble image?

**Comment by rohanchandra-cpe** [comment]
Will I need to ssh into the rpi and do this, because if so, I currently cannot ssh into it. The old IP address I used to ssh to does not work anymore. And if I try to ping it, I just get "Destination Host Unreachable"

**Comment by roni-kreinin** [comment]
No, you will have to remove the SD card from the RPi and flash it with a new image. Note that this will overwrite all data on the SD card, so save any changes you have made before doing so.

**Comment by rohanchandra-cpe** [comment]
Ok, I'll do that and let you know how it goes. Thanks!

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/226954101-2a9a533c-b7a6-4f4a-b4f2-5bd9b1a5cc00.png)

It said there wasn't enough space on the microsd for the pi. I noticed a lot of these files above that all have the same date (3/20/23), which is when I did the manual upgrade. Can I safely delete these?

**Comment by roni-kreinin** [comment]
Where are you seeing this error?

**Comment by rohanchandra-cpe** [comment]
Within the file explorer itself
![image](https://user-images.githubusercontent.com/58828165/226958006-d2bbe314-f1b2-4f55-8dea-8bf9723a5f0a.png)

**Comment by roni-kreinin** [comment]
You can't just move the file onto the SD card. You need to image the card with a tool like `dcfldd`. Do you have access to a linux machine that you can insert the SD card into?

**Comment by rohanchandra-cpe** [comment]
Ah yes, sorry. I do. Thanks!

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/226963215-ace5ad72-da92-4ff4-a840-b244083c5957.png)

I see /dev/sda even when I don't insert the SD Card. Nothing seems to change here when I do insert it (the image is the output of sudo fdisk -l)

**Comment by roni-kreinin** [comment]
Is this running on a VM?

**Comment by rohanchandra-cpe** [comment]
I'm on a Windows PC. I downloaded "Ubuntu 22.04 LTS" from the windows store. That is what this is

**Comment by rohanchandra-cpe** [comment]
This is what I see on the Powershell: The D: is my SD Card
![image](https://user-images.githubusercontent.com/58828165/226996312-ec791bf1-420f-4212-88f5-b503a0f053e4.png)

**Comment by roni-kreinin** [comment]
I'm not too familiar with WSL but you can try following a tutorial like this to mount the SD card. https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin I flashed the Humble image onto the Raspberry Pi SD Card and put it back on the bot. I was able to run "turtlebot4-setup" and I connected it to my 5Ghz network. However, I am still not able to see the /ip topic

![image](https://user-images.githubusercontent.com/58828165/227247766-1cfa9ba6-1615-4dfa-b9f1-4eb2cae62c3a.png)

The top window is what happened after I finished running the setup tool.  I think the RPI rebooted twice, but that top terminal has not changed at all. The bottom terminal shows what happened after I tried calling "ros2 topic echo /ip"

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin Also, this is what happened when I tried to ping the IP that the RPi used to be on, and SSH in

![image](https://user-images.githubusercontent.com/58828165/227248883-fe9482d1-4262-477f-ba68-75f485ad8f40.png)

**Comment by roni-kreinin** [comment]
Run the suggested `ssh-keygen` command in the warning message, then try to ssh again.

**Comment by roni-kreinin** [comment]
>The top window is what happened after I finished running the setup tool. I think the RPI rebooted twice, but that top terminal has not changed at all. The bottom terminal shows what happened after I tried calling "ros2 topic echo /ip"

The ssh session will freeze because the RPi has changed networks. You can close that terminal.

**Comment by rohanchandra-cpe** [comment]
Ok, I was able to ssh into it. What should I do from here?

**Comment by roni-kreinin** [comment]
Call `ros2 topic list` on the RPi and check that the expected topics show up.

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/227250307-4fae57ea-2f77-47e9-9ed4-6dd9df27ee55.png)

Seems like it. What other checks should I do?

**Comment by roni-kreinin** [comment]
Seems to be missing the Create 3 topics. Did you update the Create3 to the latest Humble firmware? https://iroboteducation.github.io/create3_docs/releases/h_1_1/

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/227251020-4a218716-4723-4ac7-b5b1-4c470b4c9f26.png)

I think so

**Comment by roni-kreinin** [comment]
Can you show me the Application->Configuration page?

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/227251691-84153ed1-1199-4d5d-b5eb-f6b0679d0046.png)

**Comment by roni-kreinin** [comment]
Are you trying to use simple discovery or the discovery server?

**Comment by rohanchandra-cpe** [comment]
I don't have a preference for one over the other. Is there you recommend I use?

**Comment by roni-kreinin** [comment]
That will depend on your use case. Are you just setting up one robot, or do you have multiple?

**Comment by rohanchandra-cpe** [comment]
Just one

**Comment by roni-kreinin** [comment]
Then I would recommend using the discovery server. Try following these instructions on the Humble tabs. https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html

**Comment by rohanchandra-cpe** [comment]
I followed the above link up until User PC (I have not done the User PC steps yet). This is what I see when I call "ros2 topic list." Am I on the right path @roni-kreinin ?

![image](https://user-images.githubusercontent.com/58828165/227261100-a95db92c-416e-48f6-8a4c-27e253f7a5c0.png)

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/227272488-786027fc-c8ef-4268-bbe7-4fdd32b12964.png)

I started the User PC config, I got this error

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/227273714-33b7f1d9-7dd5-450b-805b-a1971e9589e1.png)

Some more testing I did (ip route did have the additional ip address)

**Comment by rohanchandra-cpe** [comment]
Also @roni-kreinin I selected the defaults for the Discovery Server IP address and port

**Comment by roni-kreinin** [comment]
The `ros2 topic list` on the RPi looks correct.

I think WSL does not use `systemd` so the ip_route service won't work. You will have to add the `sudo ip route add ...` command to your `~/.bashrc` file to have it executed every time you open a terminal. If `ip route` is showing the route then you should be able to ping the Create 3 from your PC by calling `ping 192.168.168.2`.

If you are able to ping then you can check if the ros2 topics are showing up by calling 
```
ros2 daemon stop; ros2 daemon start
ros2 topic list
```

**Comment by rohanchandra-cpe** [comment]
![image](https://user-images.githubusercontent.com/58828165/227301980-4eda30da-551e-4966-9585-e919c9041d20.png)
I added the following line to the end of my bashrc. When I opened a new terminal I got that same nexthop error as before. 

Also, "ip route" did not show anything different from before.

Could this work? https://unix.stackexchange.com/questions/600961/ip-route-add-fails-with-next-hop-invalid-although-next-hop-on-directly-connected

**Comment by roni-kreinin** [comment]
You can try that. Also check `ip a` to make sure that you are on the same subnet as the RPi.

**Comment by rohanchandra-cpe** [comment]
Ok, adding the stuff at the end did work. This is now what I see when I do "ip route"
![image](https://user-images.githubusercontent.com/58828165/227304841-d59d4cf4-71cf-4ebf-903c-fdc5c2dceacb.png)

But I cannot ping 192.168.168.2
![image](https://user-images.githubusercontent.com/58828165/227305133-7a06ea60-6de5-48ce-8477-45ea7a209638.png)

**Comment by roni-kreinin** [comment]
Does your Wi-fi interface show up in WSL?

**Comment by rohanchandra-cpe** [comment]
Not according to "ifconfig"
![image](https://user-images.githubusercontent.com/58828165/227314241-7558bd79-35b0-407f-9059-995787e176e2.png)

Also, the above commands did not change anything. I still could not see all of the topics

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin Is this what I would need to check to see if my wi-fi interface is in WSL?

**Comment by roni-kreinin** [comment]
You might need to do something like [this](https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan) to get WSL on the same network as your Windows PC. Or you can try running a VM instead.

**Comment by rohanchandra-cpe** [comment]
Honestly, I think at this point a Linux VM would be the best option. If I were to go that route, I imagine I would have to do the entire User PC configuration again, but would I need to do any of the Raspberry PI/Create3 configs again?

**Comment by roni-kreinin** [comment]
You would just need to do the PC configuration.

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin I have lost the ability to ssh and ping the raspberry pi. 
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/58828165/227790073-2f8c681a-aabf-4bd6-9202-20bdfb272397.png">

As you can see I am now in rohan@asterix, which is a linux vm running Ubuntu 22.04 LTS. I am no longer using WSL.

When I went through the discovery server steps on this VM, everything worked just fine, including "ip route"

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/58828165/227790187-3c177c38-0677-409b-a7a1-e79c40f1edb8.png">

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin I tried again today, still cannot ssh in. Could this be because of the port number?

**Comment by roni-kreinin** [comment]
Which VM are you using?

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin VMWare EXSI 6.5.0 (VMKernel Release Build 4564106)

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin How would the VM I am using affect my ability to SSH into the RPi?

**Comment by roni-kreinin** [comment]
You may need to do some configuration to bridge the VM network to your PC. Try this https://www.minitool.com/backup-tips/vmware-bridged-network-not-working.html

**Comment by rohanchandra-cpe** [comment]
I'll give this a try, however, I am curious. Is there another VM that you would recommend? Do people normally just have a laptop running 22.04 Ubuntu and use that instead?

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin Even on the original thing I was using, the Ubuntu 22.04 LTS application I downloaded from the Windows playstore, I cannot ssh into the R-Pi. It just times out and says that it cannot connect 
![image](https://user-images.githubusercontent.com/58828165/228315849-89367491-7aae-44b7-bb11-3be7bdbcfc2f.png)

**Comment by roni-kreinin** [comment]
> I'll give this a try, however, I am curious. Is there another VM that you would recommend? Do people normally just have a laptop running 22.04 Ubuntu and use that instead?

Running native Ubuntu is definitely the best option, but VM's should work fine. I typically use VirtualBox but VMWare should work too.

> Even on the original thing I was using, the Ubuntu 22.04 LTS application I downloaded from the Windows playstore, I cannot ssh into the R-Pi. It just times out and says that it cannot connect

Are you able to access your router's gateway to check connected devices? Maybe the IP address has changed?

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin Ok, the RPi address changed. However, now I cannot view the topics on the RPi. This is true on both rohan@asterix (the linux VM) and on WSL. When I first SSH'd into the R-Pi I was able to see them, but then they went away. Is there anything you would like me to show you so that you can diagnose this?

![image](https://user-images.githubusercontent.com/58828165/228657155-c5a3b64f-fea2-4b8f-87ac-c791da965a6c.png)

**Comment by roni-kreinin** [comment]
Does this still happen after you restart the daemon? `ros2 daemon stop; ros2 daemon start`

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin It finally works! I was able to get the robot driving with the teleop_twist_keyboard example and I could see the topics. Thank you so much for you continuous help over the past month. :) Long story short

1. WSL Sucks
2. Use Humble
