### ISSUE TITLE
Tf has two or more unconnected trees.

### ISSUE THREAD

**Issue by Basavaraj-PN** [turtlebot/turtlebot4#117]
**Sys information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source
 - Package version: 
 - create3 version: 4.3 on 2.4Ghz

 **Expected behaviour**
 Should launch nav2 core and rviz should show map.

 **Actual behaviour**
Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.

**To Reproduce**
Provide the steps to reproduce:
1. ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=async map:=~/map_name.yaml
2. see the termianl output

**Comment by roni-kreinin** [comment]
This is likely related to the errors you were seeing [here](https://github.com/turtlebot/turtlebot4/issues/62#issuecomment-1447572362). I have asked iRobot for insight on these errors.

**Comment by roni-kreinin** [comment]
@Basavaraj-PN Sorry for the delay. 

I have a few questions:
- Can you paste the output of `ros2 topic list` from the RPi and your PC?
- What does your network look like? Are you using a router for your Wi-Fi or a mobile hotspot?
- Have you tried using the discovery server as instructed [here](https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html)?

From the errors in the other issue, it seems that your Create 3 is having issues connecting to your Wi-Fi network, so I am assuming that you are not seeing topics from the Create 3.

**Comment by Basavaraj-PN** [comment]
@roni-kreinin 

ON RPI:

/battery_state
/cmd_audio
/cmd_lightring
/cmd_vel
/color/preview/camera_info
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock
/dock_status
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/ir_intensity
/ir_opcode
/joint_states
/joy
/joy/set_feedback
/kidnap_status
/mobility_monitor/transition_event
/mouse
/odom
/parameter_events
/robot_description
/robot_state/transition_event
/rosout
/scan
/slip_status
/static_transform/transition_event
/stereo/camera_info
/stereo/depth
/stop_status
/tf
/tf_static
/wheel_status
/wheel_ticks
/wheel_vels

----------------------------------------------------------



ON PC

/battery_state
/cmd_vel
/color/preview/camera_info
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/joint_states
/joy
/joy/set_feedback
/mouse
/parameter_events
/robot_description
/rosout
/scan
/stereo/camera_info
/stereo/depth
/tf
/tf_static
/wheel_status

**Comment by roni-kreinin** [comment]
@Basavaraj-PN I would recommend trying the discovery server as mentioned earlier.

**Comment by Basavaraj-PN** [comment]
I tried that, the main issue is ntpd, time synchronisation issue

**Comment by Basavaraj-PN** [comment]
Even if I want to run everything in RPi things are failing because of time synchronisation issue. 
https://github.com/turtlebot/turtlebot4/issues/10

**Comment by roni-kreinin** [comment]
Can you show me what errors you are getting with regards to time sync?

**Comment by Basavaraj-PN** [comment]
https://github.com/turtlebot/turtlebot4/issues/10 @roni-kreinin

**Comment by roni-kreinin** [comment]
@Basavaraj-PN Can you share what your Wi-Fi setup looks like, and the actual sync errors that you are getting?

**Comment by Basavaraj-PN** [comment]
Hi @roni-kreinin , we are installing Ubunut 22.04 in RPi and humble image in create.
We will share the update to you after trying it out with latest binaries.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
