### ISSUE TITLE
Error "irobot_create_ignition_toolbox/local_setup.bash" not found

### ISSUE THREAD

**Issue by languyen14507** [turtlebot/turtlebot4#118]
I tried to follow the turtlebot4_python_tutorials but encountered an error in "source install/local_setup.bash" as shown below. I went ahead and ran the turtlebot4_first_python_node but didn't get any output message when pushing the turtlebot 4 button 1 (is it the BIN 1 button?)
![Screenshot from 2023-03-03 14-58-49](https://user-images.githubusercontent.com/12131715/222830608-b12898b1-f5b2-487a-aaaa-331595c80b58.png)
![Screenshot from 2023-03-03 15-09-26](https://user-images.githubusercontent.com/12131715/222830670-a0353146-0f42-4339-8cb9-6b2879312ead.png)

**Comment by roni-kreinin** [comment]
@languyen14507 Can you try `source install/setup.bash` instead?

**Comment by languyen14507** [comment]
Yes, I got the same error

**Comment by languyen14507** [comment]
![Screenshot from 2023-03-03 15-55-10](https://user-images.githubusercontent.com/12131715/222837018-5947f60d-2ead-49af-b77f-86098d98e061.png)

**Comment by roni-kreinin** [comment]
Did you source `irobot_create_ignition_toolbox/install/setup.bash` before building `turtlebot4_ws`? And what are the contents of `turtlebot4_ws/src`?

**Comment by languyen14507** [comment]
There isn't an "irobot_create_ignition_toolbox/install/setup.bash" file in my computer
![Screenshot from 2023-03-03 16-07-59](https://user-images.githubusercontent.com/12131715/222839008-b70e54ea-bad5-4f4d-8b27-e89225f02797.png)

Here are the contents of my turtlebot4_ws/src
![Screenshot from 2023-03-03 16-00-21](https://user-images.githubusercontent.com/12131715/222839120-5c75dd8f-b2ef-45f1-a7a8-e8b94e21b70a.png)

**Comment by roni-kreinin** [comment]
Were there any errors when you build `turtlebot4_ws`? The `irobot_create_ignition_toolbox` package should be under `turtlebot4_ws/src/create3_sim/irobot_create_ignition/` so it should have been built with the rest. 

Which branch is `create3_sim` on? If its on `main` instead of `galactic`, the build might fail because of dependency issues.

**Comment by languyen14507** [comment]
There was no error when I build only the turtlebot4_python_tutorials package.
![Screenshot from 2023-03-03 16-22-11](https://user-images.githubusercontent.com/12131715/222841984-a74191b0-831d-4cfd-aa47-2e3aebfb9906.png)

I git cloned the turtlebot4_ws b which did not

**Comment by languyen14507** [comment]
There was no error when I build only the turtlebot4_python_tutorials package.
![Screenshot from 2023-03-03 16-22-11](https://user-images.githubusercontent.com/12131715/222841984-a74191b0-831d-4cfd-aa47-2e3aebfb9906.png)

I git cloned the turtlebot4_ws b which did not

**Comment by languyen14507** [comment]
I git cloned the turtlebot4_ws back in October 2022 which did not have the turtlebot4_python_tutorials package that I added today. Now I've just build the entire turtlebot4_ws and there are several errors
![Screenshot from 2023-03-03 16-18-53](https://user-images.githubusercontent.com/12131715/222842760-72448137-716d-41a1-914a-be2c07010d70.png)

**Comment by roni-kreinin** [comment]
I think you may be on the main branch of create3_sim, which now targets Humble and is not compatible with Galactic. Try switching to the galactic branch.

**Comment by languyen14507** [comment]
We received our Turtlebot 4 about 3 weeks ago. If I do the turtlebot4_python_tutorials on it, would it be compatible? There is no turtelbot4_ws on it yet, only a folder called turtlebot4_test_results.

**Comment by roni-kreinin** [comment]
You can certainly run it on the turtlebot itself, but the examples are mostly for the simulation. You will need to generate a map with the physical robot and modify the positions to which the robot drives within the turtlebot4_tutorials examples.

**Comment by languyen14507** [comment]
I reinstalled all turtlebot4 packages on my PC to make sure everything is from Galactic branch. That appears to fix the colcon build errors. I can now "source install/local_setup.bash" with no problem. When I "ros2 run turtlebot4_python_tutorials turtlebot4_first_python_node" and push button 1, I got the following failed messages
1678064725.992839 [0]        tev: ddsi_udp_conn_write to udp/239.255.0.1:7400 failed with retcode -1
1678064733.992972 [0]        tev: ddsi_udp_conn_write to udp/239.255.0.1:7400 failed with retcode -1

**Comment by roni-kreinin** [comment]
@languyen14507 That looks like an issue with CycloneDDS. Do you have a `.xml` file you are using for `CYCLONEDDS_URI`?

**Comment by languyen14507** [comment]
**@roni-kreinin**   Yes, CYCLONEDDS_URI is defined in my .bashrc file which are shown below with the content of the cyclonedds_pc.xml 
![Screenshot from 2023-03-06 17-06-38](https://user-images.githubusercontent.com/12131715/223277372-e96e1fa6-2019-468f-9501-1cc5e4171ab5.png)

**Comment by roni-kreinin** [comment]
@languyen14507 Is your network interface called `wlo1`? Can you paste the output of `ip a`?

**Comment by languyen14507** [comment]
@roni-kreinin  I won't be able to get to the Lab until late tonight, but my network interface is called wlo1 and I have been able to communicate with both the RPi and ***@***.*** I normally get my turtlebot 4's IP address printed out with the word Data on a different line when I do the command ip a, and I can see all topics with the command "ros2 run topic list".  I can confirm this when I get to the Lab tonight.
The problem is when I run the turtlebot4_first_python_node  and push button 1, I get the failed error message "1678064725.992839 [0] tev: ddsi_udp_conn_write to udp/239.255.0.1:7400 failed with retcode -1" instead of the feedback message "Button1 pushed"

    On Thursday, March 9, 2023 at 01:48:14 PM CST, roni-kreinin ***@***.***> wrote:  
 
 


@languyen14507 Is your network interface called wlo1? Can you paste the output of ip a?

**Comment by roni-kreinin** [comment]
That `ddsi_udp_conn_write` error usually indicates an issue with the cycloneDDS configuration. Does this error occur regardless of if you run the `turtlebot4_first_python_node` on the RPi or on your PC?

**Comment by languyen14507** [comment]
I have not tried to run the turtlebot4_first_python_node on the RPi, but to answer your earlier question on the output of the command ip a, please see below
![Screenshot from 2023-03-10 14-39-21](https://user-images.githubusercontent.com/12131715/224424300-c3d063f1-46c2-4220-a3d8-5b0ead8be69e.png)

**Comment by languyen14507** [comment]
I have not tried to run the turtlebot4_first_python_node on the RPi, but to answer your earlier question on the output of the command ip a, please see below


I also need to mention that for today, first I undocked the turtlebot 4 with the controller, drove it away from the docking port, ran the turtlebot4_first_python_node, then pressed the ***@***.*** button 1, I observed that upon pressing the button 1, the turtlebot 4 acted like it received a dock command and proceeded to move and docked to the port. I undocked the bot again with the controller, drove it away from the port, then press button 1 and did not get any response from the bot or on the PC terminal. The "failed error with retcode -1" messages did not occur at all today.
    On Friday, March 10, 2023 at 09:12:07 AM CST, roni-kreinin ***@***.***> wrote:  
 
 


That ddsi_udp_conn_write error usually indicates an issue with the cycloneDDS configuration. Does this error occur regardless of if you run the turtlebot4_first_python_node on the RPi or on your PC?

**Comment by roni-kreinin** [comment]
I don't think your `ip a` output was attached correctly, but the docking behaviour is caused by the [default configuration](https://github.com/turtlebot/turtlebot4_robot/blob/702b18261ac95d2e4bd20f99499a03610603a487/turtlebot4_bringup/config/turtlebot4.yaml#LL35C6-L35C54) of the `turtlebot4_node`.

You can disable the turtlebot4 service with `sudo systemctl stop turtlebot4` if you don't want it interfering. To start it again, call `sudo systemctl start turtlebot4`.

**Comment by languyen14507** [comment]
What do I need to do to get the ip a output attached correctly?

    On Friday, March 10, 2023 at 03:14:18 PM CST, Roni Kreinin ***@***.***> wrote:  
 
 


I don't think your ip a output was attached correctly, but the docking behaviour is caused by the default configuration of the turtlebot4_node.

You can disable the turtlebot4 service with sudo systemctl stop turtlebot4 if you don't want it interfering. To start it again, call sudo systemctl start turtlebot4.

**Comment by languyen14507** [comment]
I got a response "Failed to stop turtlebot4.service: Unit turtlebot4.service not loaded." to the command "sudo systemctl stop turtlebot4"

**Comment by roni-kreinin** [comment]
> I got a response "Failed to stop turtlebot4.service: Unit turtlebot4.service not loaded." to the command "sudo systemctl stop turtlebot4"

Was this called on the RPi?

And for `ip a` you can just copy paste the output from your terminal into github.

**Comment by languyen14507** [comment]
My bad, I did not make the call sudo systemctl stop turtlebot4 to the RPi. I made the correction and the bot doesn't do docking upon pressing button 1 anymore.
Here is the output to the ip a command

languyen:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 04:d4:c4:e6:47:09 brd ff:ff:ff:ff:ff:ff
    altname enp3s0
3: wlo1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 08:71:90:66:fc:bf brd ff:ff:ff:ff:ff:ff
    altname wlp0s20f3
    inet 192.168.11.142/24 brd 192.168.11.255 scope global dynamic noprefixroute wlo1
       valid_lft 82422sec preferred_lft 82422sec
    inet6 fe80::bfd4:3c87:beb8:7f99/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
languyen:~$

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
