### ISSUE TITLE
1678064725.992839 [0] tev: ddsi_udp_conn_write to udp/239.255.0.1:7400 failed with retcode -1

### ISSUE THREAD

**Issue by languyen14507** [turtlebot/turtlebot4#122]
Hello @roni-kreinin ,

I still have the problem with the message in the title for this issue. I do have the CYCLONEDDS_URI defined in my .bashrc file as shown below together with the content of the cyclonedds_pc.xml file. Please help, thank you.

![image](https://user-images.githubusercontent.com/12131715/224133560-baf8249e-7cd5-4814-b509-35b8d8d5f4e4.png)

**Comment by roni-kreinin** [comment]
Will continue this issue in #118.
