### ISSUE TITLE
Wheel Encoders

### ISSUE THREAD

**Issue by brandon-todd** [turtlebot/turtlebot4#126]
Hello,
    My team is trying to filter data from an IMU added to the turtlebot4 with data from the onboard wheel encoders to more accurately describe the current position of the Turtlebot4. However, there is absolutely no information about the wheel_ticks topic. The topic gives wheel encoder data but does not tell you how many ticks per meter the wheel encoder would give or information of that nature. Would somebody be able to answer how many ticks per meter or centimeter the wheel encoder should give?

**Comment by roni-kreinin** [comment]
In the [simulation](https://github.com/iRobotEducation/create3_sim/blob/main/irobot_create_common/irobot_create_common_bringup/config/wheel_status_params.yaml), the encoder resolution is 508.8 ticks per revolution with a wheel radius of  0.03575m.

This should be consistent with the physical robot, but I will double check with iRobot.

**Comment by roni-kreinin** [comment]
iRobot confirmed that 508.8 is correct for the physical robot too.

**Comment by brandon-todd** [comment]
thank you!
