### ISSUE TITLE
No module named ament_package

### ISSUE THREAD

**Issue by brandon-todd** [turtlebot/turtlebot4#127]
**Please provide the following information:**
 - OS: (Ubuntu 20.04)
 - ROS Distro: Galactic
 - Built from source or installed:
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)

 **Expected behaviour**
 I am following the create first node in C++ and when running the colcon build command it exits with the error message saying 
--- stderr: odometry                                                                              Traceback (most recent call last):                                                                  File "/opt/ros/galactic/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py", line 21, in <module>                                                                                    from ament_package.templates import get_environment_hook_template_path                        ModuleNotFoundError: No module named 'ament_package'                                              CMake Error at /opt/ros/galactic/share/ament_cmake_core/cmake/ament_cmake_package_templates-extras.cmake:41 (message):                                                                                execute_process(/usr/bin/python3                                                                  /opt/ros/galactic/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py             /home/ubuntu/build/odometry/ament_cmake_package_templates/templates.cmake)                        returned error code 1                                                                           Call Stack (most recent call first):                                                                /opt/ros/galactic/share/ament_cmake_core/cmake/ament_cmake_coreConfig.cmake:41 (include)          /opt/ros/galactic/share/ament_cmake/cmake/ament_cmake_export_dependencies-extras.cmake:15 (find_package)                                                                                            /opt/ros/galactic/share/ament_cmake/cmake/ament_cmakeConfig.cmake:41 (include)                    CMakeLists.txt:12 (find_package)

**Comment by roni-kreinin** [comment]
@brandon-todd Can you try calling `source /opt/ros/galactic/setup.bash` before building?

**Comment by brandon-todd** [comment]
I tried that and it gives the same error message.

**Comment by roni-kreinin** [comment]
Is this being built on a PC or on the RPi4 of the turtlebot?

**Comment by brandon-todd** [comment]
It is running on the pi that is on the turtlebot. I have also tried downloading fresh images of galactic and humble located on the website in the setup page of the user manual (http://download.ros.org/downloads/turtlebot4/), and those had had various other issues as well, such as the humble image only allowing read access to files used by the ros2 packages, so I am not allowed to execute any ros2 commands. And just to clarify, I am not asking to help fix this issue, but just stating downloading a new image on the sd card is not necessarily an option.

**Comment by roni-kreinin** [comment]
What does your folder structure look like on the RPi4? From this error `/home/ubuntu/build/odometry/ament_cmake_package_templates/templates.cmake) returned error code 1 Call Stack (most recent call first)`, it looks like you are calling `colcon build` from the home directory. You should have a workspace folder such as `turtlebot4_ws` that contains a `src` folder.

**Comment by brandon-todd** [comment]
Yes, under the ubuntu user, the home folder structure I am calling this command from looks like ~/turtlebot4_ws, and there is a src folder which I am calling the command to use the path with. I followed the instruction given here: https://turtlebot.github.io/turtlebot4-user-manual/tutorials/first_node_cpp.html on my first attempt to create a node, and here: https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_desktop.html to try to re download galactic from the github page when the first attempt did not work.

**Comment by roni-kreinin** [comment]
Can you call the following on the RPi to install missing dependencies:
```
cd ~/turtlebot4_ws
rosdep install -r --from-paths src -i -y
```

**Comment by brandon-todd** [comment]
ubuntu@ubuntu:~/turtlebot4_ws$ cd ~/turtlebot4_ws                                                                      ubuntu@ubuntu:~/turtlebot4_ws$ ls                                                                                      src                                                                                                                    ubuntu@ubuntu:~/turtlebot4_ws$ rosdep install -r --from-paths src -i -y                                                WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3                                                                  ERROR: the following packages/stacks could not have their rosdep keys resolved                                         to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):                                                             turtlebot4_viz: Cannot locate rosdep definition for [ament_lint_common]                                                turtlebot4_desktop: Cannot locate rosdep definition for [ament_cmake]                                                  Continuing to install resolvable dependencies...                                                                       #All required rosdeps installed successfully                                                                           ubuntu@ubuntu:~/turtlebot4_ws$ rosdep install -r --from-paths src -i -y --rosdistro galactic                           WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3                                                                  ERROR: the following packages/stacks could not have their rosdep keys resolved                                         to system dependencies:                                                                                                turtlebot4_viz: Cannot locate rosdep definition for [turtlebot4_description]                                           turtlebot4_desktop: Cannot locate rosdep definition for [ament_cmake]                                                  Continuing to install resolvable dependencies...                                                                       #All required rosdeps installed successfully                                                                           ubuntu@ubuntu:~/turtlebot4_ws$

**Comment by roni-kreinin** [comment]
Is the RPi imaged with a turtlebot4 image or just a base ubuntu 20.04 image?

**Comment by brandon-todd** [comment]
It should be the turtlebot4 galactic but is there a command I can do to double check?

**Comment by brandon-todd** [comment]
also when trying to do rosdep update the galactic distro is skipped because it is "end-of-life" could this be causing an issue?

**Comment by brandon-todd** [comment]
after updating rosdep --rosdistro galactic and rerunning rosdep isntall --from-path src -yi the rosdeps says all rosdeps isntall successfully

However colcon build --symlink-install gives the following error 
ubuntu@ubuntu:~/turtlebot4_ws$ source /opt/ros/galactic/setup.bash                                                      ubuntu@ubuntu:~/turtlebot4_ws$ colcon build --symlink-install                                                           Starting >>> turtlebot4_msgs                                                                                            Starting >>> turtlebot4_description                                                                                     Starting >>> turtlebot4_diagnostics                                                                                     Starting >>> turtlebot4_navigation                                                                                      --- stderr: turtlebot4_msgs                                                                                             Traceback (most recent call last):                                                                                        File "/opt/ros/galactic/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py", line 21, in <module>        from ament_package.templates import get_environment_hook_template_path                                              ModuleNotFoundError: No module named 'ament_package'                                                                    CMake Error at /opt/ros/galactic/share/ament_cmake_core/cmake/ament_cmake_package_templates-extras.cmake:41 (message):    execute_process(/usr/bin/python3                                                                                        /opt/ros/galactic/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py                                   /home/ubuntu/turtlebot4_ws/build/turtlebot4_msgs/ament_cmake_package_templates/templates.cmake)                         returned error code 1                                                                                                 Call Stack (most recent call first):                                                                                      /opt/ros/galactic/share/ament_cmake_core/cmake/ament_cmake_coreConfig.cmake:41 (include)                                /opt/ros/galactic/share/ament_cmake/cmake/ament_cmake_export_dependencies-extras.cmake:15 (find_package)                /opt/ros/galactic/share/ament_cmake/cmake/ament_cmakeConfig.cmake:41 (include)                                          CMakeLists.txt:19 (find_package)                                                                                                                                                                                                                                                                                                                                      ---                                                                                                                     Failed   <<< turtlebot4_msgs [1.65s, exited with code 1]                                                                Aborted  <<< turtlebot4_description [1.62s]                                                                             Aborted  <<< turtlebot4_navigation [2.29s]                                                                              Aborted  <<< turtlebot4_diagnostics [2.98s]                                                                                                                                                                                                     Summary: 0 packages finished [3.83s]                                                                                      1 package failed: turtlebot4_msgs                                                                                       3 packages aborted: turtlebot4_description turtlebot4_diagnostics turtlebot4_navigation                                 3 packages had stderr output: turtlebot4_description turtlebot4_msgs turtlebot4_navigation                              5 packages not processed

**Comment by roni-kreinin** [comment]
Can you try manually installing `ament_package` with `sudo apt install ros-galactic-ament-package`?

**Comment by brandon-todd** [comment]
ubuntu@ubuntu:~$ sudo apt install ros-galactic-ament-package                                                            Reading package lists... Done                                                                                           Building dependency tree                                                                                                Reading state information... Done                                                                                       ros-galactic-ament-package is already the newest version (0.13.1-1focal.20220124.183327).                               ros-galactic-ament-package set to manually installed.                                                                   0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by roni-kreinin** [comment]
Can you call the following:

```
source /opt/ros/galactic/setup.bash
env
```
and paste the output of `env`?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.

**Comment by lix19937** [comment]
source /opt/ros/galactic/setup.bash     
or  

source /opt/ros/galactic/install/setup.bash  

will be work.
