### ISSUE TITLE
No Map received using SLAM 

### ISSUE THREAD

**Issue by Kathan-k10** [turtlebot/turtlebot4#130]
**Please provide the following information:**
 - OS: ubuntu Ubuntu 22.04.2 LTS
 - ROS Distro: Humble
 - Built from source or installed: Built from source
 - Package version: sudo apt install ros-humble-turtlebot4-navigation

 I am using RPLidar a1 and I am trying to do SLAM with that. Currently I have not connected the robot only playing with Lidar. I am following all the steps to Implement SLAM but I not not getting anything on the Rviz. and on the console with SLAM command I getting the error: Message Filter dropping message: frame 'laser' at time 1679982623.312 for reason 'discarding message because the queue is full'

**To Reproduce**
Provide the steps to reproduce: First only use Lidar connected with laptop with ros2 and turtlebot4 installed
1. run: ros2 launch turtlebot4_navigation slam.launch.py on one terminal
2.run: ros2 launch turtlebot4_viz view_robot.launch.py

**Other notes**
As I have seen from from many ss of your manual your navigation seems activated. I my Rviz I not getting map and showing error no map received 
![Screenshot from 2023-03-29 15-45-11](https://user-images.githubusercontent.com/88841915/228503977-28f78b51-e8a7-4a57-af85-c617606afccb.png)

**Comment by roni-kreinin** [comment]
You cannot do SLAM with just the RPLIDAR because the SLAM node needs to receive odometry data.
