### ISSUE TITLE
Accessing TF Frame IDs While Namespacing

### ISSUE THREAD

**Issue by BashByr** [turtlebot/turtlebot4#131]
**Please provide the following information:**
 - OS: Ubuntu 22.04.1
 - ROS Distro: Humble
 - Built from source or installed: Installed

 **Expected behaviour**
This is more of a question than anything else, but I’m not sure how to use frames from TF when I have two namespaced TurtleBots. I would expect that the published frames would at least be visible in tf2_tools using `ros2 run tf2_tools view_frames`.

 **Actual behaviour**
All frames disappear once namespacing is enabled. I tried disabling namespacing and running the same `ros2 run tf2_tools view_frames` command as above while only one robot was on, and that worked just fine and displayed everything. In my particular application, I am trying to detect an object using one TurtleBot (tbot1), find the object’s location with respect to tbot1, transform it to a global coordinate system, then let tbot2 know that an object is a particular location with respect to it. Currently, my program requires access to "base_link" and “oakd_rgb_camera_optical_frame”, which has only worked if the robot isn’t namespaced. I have tried “tbot1/base_link” and “tbot1/oakd_rgb_camera_optical_frame”, but those could not be found either. 

Interestingly, even when namespaced, all frames for a robot are displayed in Rviz under TF if I run `ros2 launch turtlebot4_viz view_model.launch.py namespace:=/tbot1`. So I know they are somehow being published and that RVIZ can access them, but I’m not sure how to do that myself, or why `ros2 run tf2_tools view_frames` can’t see them.

**To Reproduce**
1. Have two or more namespaced turtlebots
2. Run `ros2 run tf2_tools view_frames` or try to access their individual frames through a custom ROS package.

**Other notes**
Add anything else you thing is important.

**Comment by roni-kreinin** [comment]
Each robot has a `namespace/tf` and `namespace/tf_static` topic for its transforms. This follows the standard that iRobot and Nav2 are using. See https://github.com/iRobotEducation/create3_docs/discussions/39 for more details.

If you want to view them with `view_frames`, you would have to pass the namespace as an argument, as well as remap `/tf` to `tf` and `/tf_static` to `tf_static` so that the namespace is applied.

I haven't tried running multiple robots in a global frame, but you would likely need a node that subscribes to each namespaced `tf` topic, gets the transforms and appends the namespace as the link prefix, then publishes it to the global `/tf` topic. That is a tool that we are interested in making but does not (to my knowledge) exist yet.

**Comment by BashByr** [comment]
Understood, but I am a little lost about how to implement this to subscribe to a namespaced frame. Currently, I have something like:

`from tf2_ros.buffer import Buffer`
`from tf2_ros.transform_listener import TransformListener`
`self.tf_buffer = Buffer()`
`self.tf_listener = TransformListener(self.tf_buffer, self)`
`t = self.tf_buffer.lookup_transform(
                        "base_link",
                        "oakd_rgb_camera_optical_frame",
                        msg.header.stamp)`

I then use `t` for some transformations.

After namespacing, am I still able to use `tf2_buffer.lookup_transform`? If I try to change base_link to /tbot1/tf/base_link or anything with a /tbot1 prefix, I get an error saying frame IDs cannot begin with a slash. What would the namespaced frame ID be?

Apologies if this is now more of a ROS question than a TurtleBot question. I’d really appreciate any pointers.

**Comment by roni-kreinin** [comment]
You shouldn't need to do any transform lookups. The idea is to just republish the transforms you get from `namespace/tf` to the global `/tf` topic. So for example if you get a tf message on `namespace/tf` for the links `base_link` and `oakd_rgb_camera_optical_frame`, you would copy that message, rename the links to `namespace_base_link` and `namespace_oakd_rgb_camera_optical_frame`, and then publish it to `/tf`.

**Comment by BashByr** [comment]
@roni-kreinin how can I access `oakd_rgb_camera_optical_frame`? I made a node that subscribes to the `/tbot1/tf` topic, but only two TransformStamped messages are published: `base_link` and `base_footprint`. I noticed that they are the only two with `odom` as their parent frame. However, none of the frames with `base_link` as their parent frames are showing up, including `oakd_rgb_camera_optical_frame`.

Edit: Never mind! Just realized they get published to `/tf_static`.

**Comment by ipa-rar** [comment]
> I haven't tried running multiple robots in a global frame, but you would likely need a node that subscribes to each namespaced `tf` topic, gets the transforms and appends the namespace as the link prefix, then publishes it to the global `/tf` topic. That is a tool that we are interested in making but does not (to my knowledge) exist yet.

[This repo](https://github.com/swarmBots-ipa/tf_merger) exactly does the same and allows you to run multiple robots in a global frame.
