### ISSUE TITLE
Turtlebot shuts itself off after 30 Sec

### ISSUE THREAD

**Issue by Cur1ousKea** [turtlebot/turtlebot4#133]
Hello, 

i set up the turtlebot, connected the controller and the battery says its by 99% but when im moving the bot from the docking station it is shutting down after 60 seconds or so. The same happens when staying on the charging platform. And if it stays on the dock the power button pulses in red. the battery status led from the robot also is red. when im moving the robot form the platform the red status light turn to green but it still shuts down. thanks for any help

Best Regards 

Robert
[messages.txt](https://github.com/turtlebot/turtlebot4/files/11159221/messages.txt)

**Comment by roni-kreinin** [comment]
Which version of ROS2 are you using? Also what firmware is running on the Create 3?

From the logs it looks like the Create 3 is having some issues connecting to Wi-Fi. Has it been connected to a 2.4 GHz network?

**Comment by Cur1ousKea** [comment]
Ive installed the latest available Version, i think. For PC right? Just went after the steps which are provided in the manual. I didnt specifically chose any version. For Create 3 also the latest which is H1.1. It is connected to a 2.4Ghz Network. The same where the Raspi is connected to. But Raspi runs on 5Ghz. What makes me wonder is that the Battery status LED is blinking red. I dont think that this can be a WiFi issue ?

**Comment by roni-kreinin** [comment]
These errors indicate Wi-Fi issues:
```
Apr 21 22:15:57 iRobot-0226BB1F284547CCB99759A95E828C63 daemon.notice network[1476]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Apr 21 22:15:57 iRobot-0226BB1F284547CCB99759A95E828C63 daemon.warn network[1476]: [WARN] (src/gateway_pinger.c:132) no address count, 8
Apr 21 22:15:58 iRobot-0226BB1F284547CCB99759A95E828C63 user.notice ntpd: ntpd: send failed: Network unreachable
Apr 21 22:15:58 iRobot-0226BB1F284547CCB99759A95E828C63 user.notice ntpd: ntpd: send failed: Network unreachable
Apr 21 22:16:03 iRobot-0226BB1F284547CCB99759A95E828C63 user.notice create-platform: 1650579363.714025 [0]        tev: ddsi_udp_conn_write to udp/239.255.0.1:7400 failed with retcode -3
Apr 21 22:16:03 iRobot-0226BB1F284547CCB99759A95E828C63 user.notice create-platform: 1650579363.714131 [0]        tev: ddsi_udp_conn_write to udp/192.168.1.14:7412 failed with retcode -3
```

There might also be a mismatch of RMW between the RPi and the Create 3 which will cause issues like the battery message publishing all 0's. In this case, the RPi would think that the battery is at a critical level even when its not, and force the robot to power off. You can check the actual battery level by going to the Create 3 Webserver, then going to the "About" section. There should be a "system battery" entry.

I would recommend going into the `turtlebot4-setup` tool and using the ROS Setup -> Bash setup menu to change the RMW_IMPLEMENTATION to `rmw_cyclonedds_cpp`. Then save the settings and return to the main menu to apply them.

**Comment by Cur1ousKea** [comment]
I tried doing it but the results are the same. The result is the following: https://drive.google.com/file/d/19mmP9nJJaeKtymKM2Ec4BxGczpi50SpF/view?usp=share_link
 The funny thing is that when i started turtlebot after a few days, everything magically seemed fine without doing anything. I drove the robot around, it didnt shut off even when i let it stand for 5 minutes. Then i set it on the dock and after a few minutes it disconnected and shut off. Now i have the same issue again - it shuts of after 1 Min. Could there be a communication error with the controller? I noticed that every startup is different, in regards to the status leds. sometimes comm and batt will stay off the others are green. sometimes the battery blinks red until it gets removed from the dock(but shuts down no matter what). when i dont remove it and it continues blinking, it shut down after a while.:
https://drive.google.com/file/d/1ABRqQwv8Hu-pVPuRrgJKGNZhTTCIKdMN/view?usp=share_link 
But sometimes it also gets green on the dock...  After the shutdown the power button circles in red: https://drive.google.com/file/d/19yX48-hUk9dvhoJKx4fJCjeAqntrJfVv/view?usp=share_link
[messages (1).txt](https://github.com/turtlebot/turtlebot4/files/11200453/messages.1.txt)
[messages (2).txt](https://github.com/turtlebot/turtlebot4/files/11201243/messages.2.txt)
[messages (3).txt](https://github.com/turtlebot/turtlebot4/files/11201394/messages.3.txt)

**Comment by Cur1ousKea** [comment]
I wanna add that the router is not connected to the internet. could that be a reason?

**Comment by roni-kreinin** [comment]
That is strange behaviour. Can you try to remove the battery for 15 minutes, then insert it back in and allow the robot to charge full?

To remove the battery you will need to remove 5 screws on the bottom plate. See https://iroboteducation.github.io/create3_docs/hw/mechanical/#:~:text=approximately%2030%20mm.-,Bottom%20View,-Cargo%20Bay%20%2D%20Top

**Comment by Cur1ousKea** [comment]
@roni-kreinin Im editing this now after reinstalling the humble image a third time. Now it starts up with the 5 green leds flashing as it should be. 
A question i would have: The controller when being pressed slow forward for once it turns in a circle moves a bit forward and when it hits sth it turns and move on for 5 sec or so...

Furthermore when trying to update and upgrade - after the reboot the lcd screen doesnt show the ip adress any more and only the mtr and power led are green. the weird thing is that i can access the raspi via wifi and execute everything as if it was normal... Tried starting the services which were stopped and it worked but the status leds are still off. when i want to start diagnostics it doesnt show anything anymore. the topic list is smaller but the same as on rpi:
this is the status:
sudo service turtlebot4 status 
× turtlebot4.service - "bringup turtlebot4"
     Loaded: loaded (/lib/systemd/system/turtlebot4.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-05-21 21:29:38 UTC; 3s ago
    Process: 2190 ExecStart=/usr/sbin/turtlebot4-start (code=exited, status=1/FAILURE)
   Main PID: 2190 (code=exited, status=1/FAILURE)
        CPU: 8.981s

May 21 21:29:38 ubuntu turtlebot4-start[2249]:   File "/opt/ros/humble/lib/python3.10/site-packages/launch_ros/actions/load_composable_nodes.py", line 119, in _load_node
May 21 21:29:38 ubuntu turtlebot4-start[2249]:     while not self.__rclpy_load_node_client.wait_for_service(timeout_sec=1.0):
May 21 21:29:38 ubuntu turtlebot4-start[2249]:   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 176, in wait_for_service
May 21 21:29:38 ubuntu turtlebot4-start[2249]:     while self.context.ok() and not self.service_is_ready() and timeout_sec > 0.0:
May 21 21:29:38 ubuntu turtlebot4-start[2249]:   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 159, in service_is_ready
May 21 21:29:38 ubuntu turtlebot4-start[2249]:     with self.handle:
May 21 21:29:38 ubuntu turtlebot4-start[2249]: rclpy._rclpy_pybind11.InvalidHandle: cannot use Destroyable because destruction was requested
May 21 21:29:38 ubuntu systemd[1]: turtlebot4.service: Main process exited, code=exited, status=1/FAILURE
May 21 21:29:38 ubuntu systemd[1]: turtlebot4.service: Failed with result 'exit-code'.
May 21 21:29:38 ubuntu systemd[1]: turtlebot4.service: Consumed 8.981s CPU time.



And the last remark i would have is the camera. i wanted to start the depthai_demo.py but it says that it doesnt detect the necessary camera. By having the Turtlebot4 this shouldnt be the case i assume. Ich checked with lsusb and it is shown there. when trying to start it in rviz2, it says Stereo is not supported. I tried starting the service and im getting the following error 

[Neues Textdokument.txt](https://github.com/turtlebot/turtlebot4/files/11525599/Neues.Textdokument.txt)

**Comment by Hanbali11** [comment]
I think I am facing the same problem my turtlebot4 lite shutdown after 1-2m also the red light keeps blinking 
please how did you solve the problem 
:turtlebot4 is connected and can be controlled by key bored  package

**Comment by Cur1ousKea** [comment]
Hi there, it solved it for me once i completely reinstalled the turtlebot os. so erase the sd card and set everything up again. when u use sudo apt update && sudo apt upgrade let it run through, but once the window pops up where u have to press okay to restart the different services, hit cancel and manually reboot with sudo reboot
