### ISSUE TITLE
PointCloud

### ISSUE THREAD

**Issue by aduvai22** [turtlebot/turtlebot4#138]
Can I get PointCloud / PointCloud2 data from Turtlebot 4? I ran Rviz where I can see the /scan (Laserscan) and /color (Image) topic. But if I add PointCloud in Rviz, it shows "no topic to subscribe". Can you add a topic that publishes PointCloud data?

**Comment by roni-kreinin** [comment]
You can use this OAK-D launch file to produce a pointcloud https://github.com/luxonis/depthai-ros/blob/humble/depthai_ros_driver/launch/pointcloud.launch.py.
