### ISSUE TITLE
Controller issues

### ISSUE THREAD

**Issue by alexswerner** [turtlebot/turtlebot4#14]
Something seems to be wrong with our gamepad controller. When I first too it out of the box and started charging it, it turned amber which seemed fine. However after some time I disconnected it and it stayed amber. Even pressing the pairing key combo, nothing changed. Only the reset button on the back helped.

Now connecting often fails, as does driving the robot. We are still investigating if this is an issue with this particular controller or with the raspi bluetooth module.

It could well be that the controller is just not charged. When I connected to USB for charging today evening, it did not light up at all. Different cables/different USB outlets did not affect the behavior.

**Comment by roni-kreinin** [comment]
Can you try the following:

- SSH into the RPI and call `sudo bluetoothctl --agent=NoInputNoOutput`
- In the CLI type `devices`. This should show the MAC of the paired controller
- Type in `remove <MAC>` to remove the controller. Also type `untrust <MAC>` to untrust it.
- Follow the [controller setup](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html#turtlebot-4-controller-setup) instructions to re-pair.

**Comment by alexswerner** [comment]
Thanks! I'll try that tomorrow.

**Comment by alexswerner** [comment]
Since there was no signal of life (LED was always off) from the controller, I decided to investigate it. After opening it, the battery turned out to be at 4.16V. Unplugging the battery for 3 seconds brought the controller back to life. Tried before to get that by pressing the reset button, but that again did not work. Probably a power management issue with that controller.

I will further investigate the connection stability and ability to control the robot.

**Comment by alexswerner** [comment]
Quite frequently, the controller does not pair with the robot. Even when holding it right next to the robot.

**Comment by Tanjim13** [comment]
Same with my controller. It was not showing any sign of life. The reset button saved its life.

**Comment by teufelweich** [comment]
I've encountered difficulties too:
I couldn't connect after I've paired successfully. The PI stated it was connected but the controller was blinking still.
I just tried `trust` and then `connect` without the `pair`, which worked for me.

EDIT: it worked for a second, the controller turns off 10 seconds later automatically. So basically not working. Can't get it to pair and connect.

**Comment by roni-kreinin** [comment]
Closing as stale.

**Comment by schenkch** [comment]
I have the same issue. I can get it to connect and pair again using what is described above but I cannot get it to auto-connect any more by just pushing the home button. Every time it disconnects again, I have to remove to reconnect it using sudo bluetoothctl. Is there a way that I can get it to connect by pushing the home button again?
