### ISSUE TITLE
showing [0] points from [1] messages

### ISSUE THREAD

**Issue by jxq999** [turtlebot/turtlebot4#140]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic

 **Expected behaviour**
Display real-time lidar point cloud data and camera data.

 **Actual behaviour**
 Only show the camera data.

**To Reproduce**
Provide the steps to reproduce:
1. run `ros2 launch turtlebot4_viz view_model.launch.py`.
2. As shown below, there is no lidar point cloud data display.

**Other notes**
Hello! As you can see in the picture, lidar and camera datas are receiving all the time. But about _Points_, it shows 
 _showing [0] points from [1] messages_. I would like to ask what might be the cause. Looking forward to your answer！

![微信图片_20230411164612](https://user-images.githubusercontent.com/75959133/231111134-005a02d0-124e-4bf1-a958-cd28b26134ef.jpg)

**Comment by roni-kreinin** [comment]
Are you able to see laserscan data if you call `ros2 topic echo /scan`?

**Comment by jxq999** [comment]
Yes, I can see the  laserscan data while calling `ros2 topic echo /scan`.

**Comment by roni-kreinin** [comment]
What is the errors is the RobotModel showing in RVIZ? 
![image](https://user-images.githubusercontent.com/59886299/231850421-2bf7c41f-966d-4618-989f-f2bcc05bca62.png)

**Comment by jxq999** [comment]
Thank you for your reply！ The errors showed by the RobotModel in RVIZ are seemly named 'wheel_ left' / 'wheel_right' in the last two rows. But I can not remember the accurate topic name.
 It is worth mentioning that I have also had these two errors when I run` ros2 launch turtlebot4_viz view_model.launch.py`  on other PC and robot but the laser-scan data appears. 
Finally, I would like to ask, is the display of laser-scan data related to the time synchronization of the PC and the robot? Whether the PC will drop packages because the timestamp is different.
Thank you for your time!

**Comment by roni-kreinin** [comment]
It is definitely possible that time synchronization is the issue. RViz should be throwing out warnings in the terminal if the timestamps of the laserscans are too old. The RPi4 uses [this](https://github.com/turtlebot/turtlebot4_setup/blob/galactic/conf/chrony.conf) chrony config for ntp servers. You can try setting your PC to use the same ntp servers:

```
pool ntp.ubuntu.com        iburst maxsources 4
pool 0.ubuntu.pool.ntp.org iburst maxsources 1
pool 1.ubuntu.pool.ntp.org iburst maxsources 1
pool 2.ubuntu.pool.ntp.org iburst maxsources 2
```

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.

**Comment by RoboCrafty** [comment]
Hi there! I am having this exact issue. Please see the screenshots.

ros 2 humble
running these launch files:
1. ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py world:=warehouse
2. ros2 launch turtlebot4_viz view_robot.launch.py


![image](https://github.com/turtlebot/turtlebot4/assets/82392157/4ca56143-3a77-485a-85a0-7e025dfec76c)
![image](https://github.com/turtlebot/turtlebot4/assets/82392157/a9770e58-a779-4bb5-89fd-6de68a15b1ac)

Actually scan topic does have the data. Rviz2 just isnt showing it.

![image](https://github.com/turtlebot/turtlebot4/assets/82392157/dd9d17cf-ffa4-44da-b66f-081af558054a)

**Comment by Afritheos** [comment]
did you resolve this? @CraftyCranberry

**Comment by AmitNativ1984** [comment]
I have the same problem. Any update?

**Comment by hilary-luo** [comment]
@CraftyCranberry @KeneUkwueze @AmitNativ1984 If you would like help troubleshooting your issues then create a new troubleshooting issue with full information about your system. Among other things you will need to include the copy and pasted full output from the terminal windows.

**Comment by RoboCrafty** [comment]
> @CraftyCranberry @KeneUkwueze @AmitNativ1984 If you would like help troubleshooting your issues then create a new troubleshooting issue with full information about your system. Among other things you will need to include the copy and pasted full output from the terminal windows.

Thank you, I have no idea how but the issue went away for me. I do not remember what I did to fix it.
