### ISSUE TITLE
create3 automatic shutdown

### ISSUE THREAD

**Issue by ddwy** [turtlebot/turtlebot4#142]
Hello, I am using the image of the turbobot4 lite humble version. After starting create3 and Raspberry Pie, after a few minutes, it will automatically shut down.Why did this happen?

**Comment by ipa-rar** [comment]
@ddwy I have the same issue as well. I have observed my turtlebots rebooting itself after few minutes.

**Comment by roni-kreinin** [comment]
Is the robot docked when this happens? Also what is the battery level at? 

The `turtlebot4_node` starts a 60s power off timer when the Create 3 reaches 12% battery. If it is not placed back on a dock in those 60s then it will shut itself off to protect the battery.

**Comment by ddwy** [comment]
> @ddwy I have the same issue as well. I have observed my turtlebots rebooting itself after few minutes.

The problem has been resolved. After using the turbobot4 humble version, create3 also needs to update the firmware.

https://iroboteducation.github.io/create3_docs/releases/overview/
