### ISSUE TITLE
Top plate broke

### ISSUE THREAD

**Issue by MathisGodard** [turtlebot/turtlebot4#144]
Hello,

A customer recieved his TB4 but the top plate was dammaged. 

![GenerationRobot_SAV](https://user-images.githubusercontent.com/39947894/232482134-a7adf528-fb0e-46f4-9275-c7df63623f25.jpg)

What can we do ? 

Best regards, Mathis.

**Comment by roni-kreinin** [comment]
@MathisGodard Can you ask them to email our customer support team at support@clearpathrobotics.com? 
We will send a replacement part.

**Comment by MathisGodard** [comment]
Okey perfect. 

We can close this topic.

Thanks.
