### ISSUE TITLE
Humble AMCL Particle Swarm doesn't work

### ISSUE THREAD

**Issue by JasmineRosselliSUPSI** [turtlebot/turtlebot4#148]
- OS: Ubuntu 22.04.1
 - ROS Distro: Humble
 - Installed
 - (Package version: H.1.2. Create3)
 - CycloneDDS, Simple Discovery mode

 **Expected behaviour**
 Normally in RViz it is possible to see the estimated locations given by Amcl Particle Swarm.

 **Actual behaviour**
After starting RViz the Amcl Particle Swarm doesn't work.
LaserScan works only sometimes, otherwise the error is: 
> Could not transform from [rplidar_link] to [map]

**To Reproduce**
Runned code from Turtlebot4 (ssh connection)
`ros2 launch turtlebot4_navigation localization.launch.py map:=my_map.yaml`

Other terminal:
`ros2 launch turtlebot4_navigation nav2.launch.py`

Launched RViz from an Humble PC:
`ros2 launch turtlebot4_viz view_robot.launch.py`

 
**Please help!**

![rviz_screenshot_1](https://user-images.githubusercontent.com/117928648/233406599-7c20f8a5-829e-4164-b5b5-7266d6cdcc37.png)

**Comment by roni-kreinin** [comment]
Are there any errors or warning being printed in the terminal that launched rviz?

**Comment by JasmineRosselliSUPSI** [comment]
Here is the RViz terminal messages:
![RViz_map_frame_don_t_exist](https://user-images.githubusercontent.com/117928648/233602192-b75b6990-d360-4a0d-bea5-cb4571efe699.png)

For additional informations, we attach the message generated by localization and navigation terminals:
Localization: (`ros2 launch turtlebot4_navigation localization.launch.py map:=my_map.yaml`)
![Localization_terminal](https://user-images.githubusercontent.com/117928648/233601820-58f54eca-2152-4271-a411-0d85554cc12b.png)

Navigation: (`ros2 launch turtlebot4_navigation nav2.launch.py`)
![Navigation_terminal](https://user-images.githubusercontent.com/117928648/233601824-39a049d1-74a2-48cc-b15f-1881e58a1901.png)

**Comment by ddwy** [comment]
I have also encountered this problem, have you solved it?

**Comment by JasmineRosselliSUPSI** [comment]
Unfortunately not.
My colleagues and I have decided to return to Galactic at the moment, hoping that this problem will be resolved in the future.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
