### ISSUE TITLE
Turtlebot 4 scan data not available

### ISSUE THREAD

**Issue by binni08** [turtlebot/turtlebot4#150]
Hello.

I'm using Turtlebot 4, but when I turn on the robot, the scan value for the rplidar does not come out.

The topic is issued, but the inf value is showing up in the data, and it doesn't seem to have an error separately.

Even if we disconnect and re-insert the usb cable for rplidar, we still can't check scan data in rviz.

Please check.
![Screenshot from 2023-04-24 17-40-40](https://user-images.githubusercontent.com/76678147/233946885-1accc418-7bc3-4389-80cc-29a5272c608f.png)
![Screenshot from 2023-04-24 17-45-36](https://user-images.githubusercontent.com/76678147/233946889-e3c79f43-4552-420e-8d32-9b2a5463523b.png)

**Comment by roni-kreinin** [comment]
It looks like you are getting RPLIDAR data. `inf` just means that the range for those points exceeds the max range of the RPLIDAR. Since you are not publishing the robot model, RViz does not know how to transform the laser scan data to `base_link`. Try changing your Fixed Frame to `rplidar_link`.

**Comment by binni08** [comment]
Hello,

I floated the robot model and checked the laser scan data, and it seems that only the data comes out in a certain part, not 360 degrees.

Even if you change the position of the box located in the front, the scan data is not coming out.

Please refer to the attached video.

Thank you.

[simplescreenrecorder-2023-04-26_10.46.54.zip](https://github.com/turtlebot/turtlebot4/files/11328184/simplescreenrecorder-2023-04-26_10.46.54.zip)

**Comment by roni-kreinin** [comment]
Which ROS2 version are you running? Also have you made any changes to the RPLIDAR launch file?

**Comment by binni08** [comment]
Yes, I am currently using the galactic version and there are no files modified.

**Comment by roni-kreinin** [comment]
Can you try running the RPLIDAR from your PC and check if the issue persists?

You can install the package with `sudo apt install ros-galactic-rplidar-ros`, then call `ros2 launch rplidar_ros rplidar.launch.py` with the RPLIDAR plugged in.

**Comment by binni08** [comment]
The problem is that the rider scan data does not appear in the but is less than the actual obstacle.

If you look at the video that I sent you before, you can see that it's actually not scanned even though the obstacle is gone.

The rplidar_ros package is already installed, and the result is the same if you unplug and reseat the USB and run the rider alone.

**Comment by binni08** [comment]
When I checked with a normal robot in the same space, the scan data came out as shown in picture 1 attached, and the scan for the problem robot is shown in picture 2.

![pic1](https://user-images.githubusercontent.com/76678147/235838086-bb51cf97-a9c8-418e-ae85-fd82f1484599.png)
![pic2](https://user-images.githubusercontent.com/76678147/235838102-915a7640-d8eb-45cc-b503-1c7009713f51.png)

**Comment by roni-kreinin** [comment]
This might be a faulty RPLIDAR. Please contact support@clearpathrobotics.com so that we can replace it.
