### ISSUE TITLE
Turtlebot's LCD doesn't come out

### ISSUE THREAD

**Issue by rhyeonwoo** [turtlebot/turtlebot4#156]
- OS: ( Ubuntu 20.04)
 - ROS Distro: (Galactic)

Turtlebot's LCD doesn't come out and joysticks don't connect.
Raspberry Pi and Create PC Wi-Fi are connected.
If I look at the topic, I can't see it all.  I compared it with other Turtle Bot products.
I think the Raspberry Pi has a light on, so the power is on.

I think mcu is the problem, is there any other problem?
![turtlebot lcd](https://user-images.githubusercontent.com/100173088/235065859-4f5fb45e-d9c3-49d6-8a24-b019254afad8.png)

**Comment by roni-kreinin** [comment]
Are you able to SSH into the RPi?

**Comment by rhyeonwoo** [comment]
"Connection timed out"  I am receiving an error message and cannot establish a connection.

**Comment by roni-kreinin** [comment]
Are you able to SSH over ethernet as instructed [here](https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#recovering-the-raspberry-pi)?

**Comment by rhyeonwoo** [comment]
No, "No route to host" an message is displayed and it is not connecting.
