### ISSUE TITLE
Rviz fails, SLAM fails too

### ISSUE THREAD

**Issue by rohanchandra-cpe** [turtlebot/turtlebot4#158]
**Please provide the following information:**
 - OS: 22.04
 - ROS Distro: Humble
 - Built from source or installed: Installed
 - Package version: "sudo apt install ros-humble-desktop" is how I installed ROS2

 **Expected behaviour**
 I should be able to run SLAM and Rviz until I decide to quit. I should also be able to drive the robot for as long as I want and save a copy of the generated map in Rviz. 

 **Actual behaviour**
When following this tutorial: https://turtlebot.github.io/turtlebot4-user-manual/tutorials/generate_map.html, Rviz, SLAM, and the teleop_twist_keyboard run for some time, but then all fail. The teleop_twist_keyboard freezes (unable to CTRL+C out of it), errors appear in the simulator, and my robot in Rviz becomes an unmovable block dot. 

**To Reproduce**
Provide the steps to reproduce:
1. Follow this tutorial: https://turtlebot.github.io/turtlebot4-user-manual/tutorials/generate_map.html
2. Try generating a map for a period longer than 5 minutes

**Other notes**
Here is a screenshot of what it looks like when everything stop working. 
![image](https://user-images.githubusercontent.com/58828165/235753997-b8b89314-6177-479a-b46e-d537cbf52d82.png)

A couple things to notice here:
1. On RViz, my robot has become a black dot. Before it had a bunch of lines coming out of it (which I assume represented the laser scans)
2. In the top left terminal, it says that messages are being dropped because of a timestamp issue or because the queue is full. Is this normal?
3. In the top right terminal, I cannot CTRL+C out of it
4. In the bottom terminal, there are errors related to the left_wheel and right_wheel

**Comment by roni-kreinin** [comment]
It sounds like the Create 3 stops publishing data at this point. It supplies the odom->base_link transform which you need in order to see the robot on the map, and to get the left/right wheel transforms.

Are you using simple discovery or the discovery server? Also could you share the Create 3 logs from the webserver after this issue occurs?

**Comment by rohanchandra-cpe** [comment]
@roni-kreinin I'm using the Discovery Server. I only have 1 robot
Also, the RPi address changed, so I did the Discovery Server setup again, and it's running longer than I expected
![image](https://user-images.githubusercontent.com/58828165/236090704-a9945180-9357-4eb8-b8dc-180b832c6928.png)
Although here you can see I'm still getting that LidarScan error. That topic number keeps increasing btw.

Here are the Create3 logs. It keeps saying the wifi is disconnected, but I assume that's because of the discovery server
![image](https://user-images.githubusercontent.com/58828165/236091895-dbe6f365-b81d-4fa0-8497-95ef16247ae8.png)

**Comment by ipa-rar** [comment]
@rohanchandra-cpe @roni-kreinin 
I run through the same set of problems but without using a discovery server. I will update once I have figured out the problem. 

> Although here you can see I'm still getting that LidarScan error. That topic number keeps increasing btw.

Even though I do not use discovery server, I face this issue too. 

> It keeps saying the wifi is disconnected, but I assume that's because of the discovery server

With this configuration, the TurtleBot 4 is able to fully function without the Create® 3 being connected to Wi-Fi.([refer](https://turtlebot.github.io/turtlebot4-user-manual/setup/networking.html#discovery-server))

**Comment by ipa-rar** [comment]
@roni-kreinin 
The LaserScan message received number keeps increasing and throws error in rivz. I did not use discovery server in my case. 

![image](https://user-images.githubusercontent.com/49311464/236834942-1970c8b1-f60f-461f-b89b-1cc1f25e7993.png)

This is the logs from the create3 base.
![image](https://user-images.githubusercontent.com/49311464/236835395-8971b6d5-201e-4bec-b9d8-f92f2f714ad2.png)

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
