### ISSUE TITLE
Visualization in rviz not working any more after switching to discovery server

### ISSUE THREAD

**Issue by schenkch** [turtlebot/turtlebot4#160]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed: Installed
 - Package version: G.4.5 (Galactic)

I switched from the simple discovery to the discovery server. 

When running slam (synchronous or asynchronous) via 
ros2 launch turtlebot4_navigation slam_async.launch.py or 
ros2 launch turtlebot4_navigation slam_sync.launch.py
or loading a map and for navigation via ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=map_office2.yaml
the visualization with rviz via ros2 launch turtlebot4_viz view_robot.launch.py
instead of showing the robot and the map **(expected)**, it returns the following message:

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2023-05-04-15-54-37-712615-Cubi02-7297
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [7299]
[rviz2-1] [INFO] [1683208478.723074418] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1683208478.723427737] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-1] [INFO] [1683208478.778793814] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [WARN] [1683208479.052197087] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] [WARN] [1683208479.060030031] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] [WARN] [1683208479.067795566] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.

And in rviz it does not show anything apart from the grid. **(actual)**
Also I realized that when I try to stop the rplidar via ros2 service call /stop_motor std_srvs/srv/Empty {}, 
I get the following message and nothing happens:
waiting for service to become available...

And the logs of the robot keep saying that the wifi is disconnected:
May  4 14:40:38 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1683211238.805824802] [system_health]: CPU usage: max 69 [%] mean 62 [%] RAM usage: 36/59 [MB]
May  4 14:40:41 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1463]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
May  4 14:41:01 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1463]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
May  4 14:41:10 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: Script called in periodic mode
May  4 14:41:21 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1463]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected

ros2 topic list shows the topics from the RPi on the PC. Any idea on what the issue is?

**Comment by schenkch** [comment]
And in rviz it does not show anything apart from the grid. (actual)
To: Also I realized that when I try to stop the rplidar via ros2 service call /stop_motor std_srvs/srv/Empty {},
I get the following message and nothing happens:
waiting for service to become available...

I managed to fix this by reinstallation on the RPi via: sudo apt reinstall ros-galactic-rplidar-ros

**Comment by roni-kreinin** [comment]
Are you able to see all of the ros2 topics on both the RPi and your PC? Can you echo the `/odom` topic from both?

**Comment by schenkch** [comment]
Yes, it was showing them from both but something was not working with the condition. But I could not figure it out and switched back to the simple discovery server setup again. Now, at least the obstacle avoidance is working (it was not before with simple discovery server). But now, I was navigating it from a script with multiple sequential goals and when navigating sometimes to the first and sometimes to the second target at some point during trajectory recalculation it stops, rolls backwards a little, the lightring turns orange and navigation is aborted. 

The create3 logs show: 
user.notice create-platform: [WARN] [1684250478.824271438] [motion_control]: Ignoring velocities commanded while an autonomous behavior is running!

I am running ros2 launch turtlebot4_navigation nav_bringup.launch.py localization:=true slam:=async map:=map_office.yaml, ros2 launch turtlebot_viz view_robot.launch.py and modified the script from the tutorial for multiple sequential goals instead of just one. @roni-kreinin Any idea on how I can resolve this issue?

**Comment by roni-kreinin** [comment]
@schenkch It sounds like the robot is hitting the back up limit. You can go to the Create 3 webserver and in the ROS2 parameter file of the Application page, change `safety_override` to `backup_only` or `full`. This will allow the robot to drive backwards without stopping. You will need to save the parameters and restart the application for them to apply.

See https://iroboteducation.github.io/create3_docs/webserver/application/#:~:text=minutes%20to%20complete.-,Application%20Configuration,-There%20are%20two for more details.

**Comment by schenkch** [comment]
Thank you that fixed that issue. I set it to full. However, when finished with navigation now sometimes the lightring turns red and checking the logs it says the following:

May 17 15:26:47 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337207.673442571] [motion_control]: Kidnap status changed: temporarily disabling reflexes
May 17 15:26:47 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [WARN] [1684337207.674229358] [motion_control]: Disabling reflexes
May 17 15:26:47 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337207.679198058] [mobility_monitor]: New kidnap status: kidnapped
May 17 15:26:47 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337207.682399897] [mobility_monitor]: Requested to disable wheels!
May 17 15:26:47 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337207.703816385] [mobility_monitor]: Updating ready to drive: false
May 17 15:26:47 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [WARN] [1684337207.740043808] [mobility_monitor]: Robot is kidnapped! Temporarily disabling wheels!
May 17 15:26:49 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337209.201665916] [ui_mgr]: Received new Led Animation goal
May 17 15:26:49 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337209.213573424] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337214.207557871] [motion_control]: Kidnap status changed: temporarily enabling reflexes
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [WARN] [1684337214.211501715] [motion_control]: Enabling reflexes
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337214.221827741] [ui_mgr]: Received new Led Animation goal
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337214.237072227] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337214.243247883] [mobility_monitor]: New kidnap status: kidnap cleared
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337214.862724915] [mobility_monitor]: Requested to enable wheels!
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337214.873838661] [mobility_monitor]: Updating ready to drive: true
May 17 15:26:54 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337214.876119695] [mobility_monitor]: Kidnap cleared! Wheels are now enabled!
May 17 15:26:55 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337215.971523910] [ui_mgr]: Received new Led Animation goal
May 17 15:26:55 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337215.982002942] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:26:58 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337218.973720111] [ui_mgr]: Received new Led Animation goal
May 17 15:26:58 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337218.988302800] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:01 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337221.980000354] [ui_mgr]: Received new Led Animation goal
May 17 15:27:01 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337221.993118525] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:06 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337226.479879028] [ui_mgr]: Received new Led Animation goal
May 17 15:27:06 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337226.492915634] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:11 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337231.441366612] [ui_mgr]: Received new Led Animation goal
May 17 15:27:11 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337231.455482235] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:16 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337236.481091728] [ui_mgr]: Led Animation hit max_runtime, succeeded
May 17 15:27:17 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337237.428953515] [ui_mgr]: Received new Led Animation goal
May 17 15:27:17 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337237.438089570] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:22 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337242.418606421] [ui_mgr]: Received new Led Animation goal
May 17 15:27:22 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337242.430707665] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:27 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337247.426652782] [ui_mgr]: Received new Led Animation goal
May 17 15:27:27 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337247.439997894] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:32 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337252.435772156] [ui_mgr]: Received new Led Animation goal
May 17 15:27:32 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337252.448736040] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:37 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337257.482479887] [ui_mgr]: Led Animation hit max_runtime, succeeded
May 17 15:27:37 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337257.725099311] [system_health]: CPU usage: max 100 [%] mean 94 [%] RAM usage: 30/59 [MB]
May 17 15:27:37 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337257.829945153] [ui_mgr]: Received new Led Animation goal
May 17 15:27:37 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337257.838122139] [ui_mgr]: Starting Led Animation goal with animation_type BLINK_LIGHTS
May 17 15:27:38 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [WARN] [1684337258.531459020] [robot_state]: New subscription discovered on topic '/odom', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
May 17 15:27:40 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [WARN] [1684337260.308284585] [robot_state]: New subscription discovered on topic '/odom', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
May 17 15:27:42 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1684337262.565883521] [ui_mgr]: Received new Led Animation goal

What does this mean? It may be because the battery is going below a certain percentage as the battery light also turns red (to what I mentioned here: https://github.com/turtlebot/turtlebot4/issues/124) or/and related to high CPU usage as well. I have had this issue as well and published a static transform for the left and right wheel like this: ros2 run tf2_ros static_transform_publisher 0 0.1165 0.0402 -1.5707 0 0 base_link wheel_drop_left

**Comment by roni-kreinin** [comment]
The `turtlebot4_node` will publish the red lightring animation to the Create 3 when battery is low. Is the battery dropping from 60-16% instantly or just quickly decreasing as you navigate?

**Comment by schenkch** [comment]
It is quickly decreasing as I navigate but I am not navigating much. But it should not decrease that quickly, right?

**Comment by roni-kreinin** [comment]
@schenkch On a full charge the robot should last over 2 hours (depending on load). Can you share the output of `ros2 topic echo /battery_state` while navigating? It should indicate current draw, battery capacity, and other useful information.

**Comment by schenkch** [comment]
Thank you but at the moment I cannot even use the controller. I fixed the issues described here for Humble in my Galactic version https://github.com/turtlebot/turtlebot4/commit/7f6d8f0b5e348024d324346f2e0c4a9d31af8240 and https://github.com/iRobotEducation/create3_sim/commit/94131b3ea53a6c607c19f56407ec2745603cd4d1#diff-988eb1f4d57ee0bfe89f095af0b0209e6be3f5741da7eb520fe4d19724a1de04 
and then I tried to switch back to the fast discovery server using the instructions here https://gist.github.com/roni-kreinin/8fbb20cb4603b8eb5e3961167fb22cd4 but it seems like the communication is not working properly. I checked the settings on RPi and the remote PC via echo $RMW_IMPLEMENTATION, $ROS_DISCOVERY_SERVER and $FASTRTPS_DEFAULT_PROFILES_FILE and they are the same on both machines. Also all the ros topics are shown: 
**On RPi:** ros2 topic list
/battery_state
/cmd_audio
/cmd_lightring
/cmd_vel
/color/preview/camera_info
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/ir_intensity
/ir_opcode
/joint_states
/joy
/joy/set_feedback
/kidnap_status
/mobility_monitor/transition_event
/mouse
/odom
/parameter_events
/robot_description
/robot_state/transition_event
/rosout
/scan
/slip_status
/static_transform/transition_event
/stereo/camera_info
/stereo/depth
/stop_status
/tf
/tf_static
/wheel_status
/wheel_ticks
/wheel_vels

**On remote PC:** 
ros2 topic list
/battery_state
/cmd_audio
/cmd_lightring
/cmd_vel
/color/preview/camera_info
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/ir_intensity
/ir_opcode
/joint_states
/joy
/joy/set_feedback
/kidnap_status
/mobility_monitor/transition_event
/mouse
/odom
/parameter_events
/robot_description
/robot_state/transition_event
/rosout
/scan
/slip_status
/static_transform/transition_event
/stereo/camera_info
/stereo/depth
/stop_status
/tf
/tf_static
/wheel_status
/wheel_ticks
/wheel_vels

But I cannot control it with the controller although the blue light on the controller is on and when I try to run navigation via ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=async localization:=true map:=map_office3.yaml
and ros2 launch turtlebot4_viz view_robot.launch.py
Rviz gives the following output and does neither show the map nor the robot:ros2 launch turtlebot4_viz view_robot.launch.py

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2023-06-21-15-40-48-725166-Cubi02-7857
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [7859]
[rviz2-1] [INFO] [1687354849.800337877] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1687354849.800719494] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-1] [INFO] [1687354849.853571037] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [WARN] [1687354850.125187304] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] [WARN] [1687354850.133843690] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] [WARN] [1687354850.143601736] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.

Checking the logs on the robot, I get the following:
Jun 21 13:39:47 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.005128 is too high, ignoring
Jun 21 13:39:56 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:40:09 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 32s
Jun 21 13:40:09 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1687354809.665910950] [system_health]: CPU usage: max 89 [%] mean 71 [%] RAM usage: 37/59 [MB]
Jun 21 13:40:16 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:40:21 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: Script called in periodic mode
Jun 21 13:40:36 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:40:56 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:40:57 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 65s
Jun 21 13:41:09 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1687354869.666741717] [system_health]: CPU usage: max 97 [%] mean 82 [%] RAM usage: 37/59 [MB]
Jun 21 13:41:16 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:41:36 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:41:53 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: bad address '3.irobot.pool.ntp.org'
Jun 21 13:41:56 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:41:58 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: bad address '2.irobot.pool.ntp.org'
Jun 21 13:42:03 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: bad address '1.irobot.pool.ntp.org'
Jun 21 13:42:08 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: bad address '0.irobot.pool.ntp.org'
Jun 21 13:42:09 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: [INFO] [1687354929.670531006] [system_health]: CPU usage: max 81 [%] mean 76 [%] RAM usage: 37/59 [MB]
Jun 21 13:42:16 iRobot-88CBB71E65F84B2092A66425D6AA6866 daemon.notice network[1464]: [INFO] (src/gateway_pinger.c:113) wifi is disconnected
Jun 21 13:42:24 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice ntpd: ntpd: timed out waiting for 192.168.186.1, reach 0x00, next query in 64s

There seems to be a time synchronization and CPU issue as well. @roni-kreinin Do you have any idea of what else can be the problem, such that I can get communication and rviz to function properly again?
Can it be a problem that the IP is fixed for the robot on the router for the previous WIFI network, so the one that RPi is connected to or does it maybe have to be a 5g WIFI network?

**Comment by roni-kreinin** [comment]
@schenkch A 5GHz network is recommended for the RPi, but it should still work on 2.4GHz. Did you set a static IP on the RPi? If so, does it match the subnet of your network?

Also, are you able to echo any of the topics such as `/ip` or `/odom`?

**Comment by schenkch** [comment]
Okay, thank you. It is set up with a 2.4GHz network. We set a static IP for the RPi and turtlebot4 on the WIFI router in the subnet of our network for the simple discovery before and they are still fixed. So, I was wondering whether this could be an issue with switching to fast discovery. Yes, I tested it and I can echo /odom as well. I will test the /ip tomorrow.  

@roni-kreinin Galactic works with RMW_IMPLEMENTATION=rmw_fastrtps_cpp as well and not just RMW_IMPLEMENTATION=rmw_cyclonedds_cpp, right? I know that the default for Galactic is cyclonedds_cpp but what is the difference in between the two?  
Do you have any other idea of what could be going wrong?

**Comment by schenkch** [comment]
The subnets matched as well. It was showing /ip and /odom on both machines but I still got the rviz warnings as above and could not see the map. 
I changed back to simple discovery with cyclonedds for now but with that I have connection and time synchronization issues. And one moment it shows /odom on both machines and the next moment it does not respond on the remote pc any more. I assume it is some issue with the network but have not figured out what yet. 
The turtlebot logs show the following:
Jun 22 10:51:01 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: 1687431061.494050 [0]        tev: ddsi_udp_conn_write to udp/<remote_pc_IP>:49230 failed with retcode -3
Jun 22 10:51:01 iRobot-88CBB71E65F84B2092A66425D6AA6866 user.notice create-platform: 1687431061.503342 [0]    nodes_0: ddsi_udp_conn_write to udp/<RPi_IP>:37842 failed with retcode -3
@roni-kreinin Can you tell me what these mean?

**Comment by roni-kreinin** [comment]
@schenkch Those errors indicate that one of the interfaces that CycloneDDS is trying to use is down on the Create 3. Likely `wlan0` in this case. Can you check the "Connect" tab on the webserver and make sure that an IP address is showing there? Also can you send the full logs from the Create3 webserver?

**Comment by schenkch** [comment]
Yes, there is an IP address showing on the "Connect" tab. 
Please find attached the full logs. 
[messages(1).txt](https://github.com/turtlebot/turtlebot4/files/11846696/messages.1.txt)

Here are also the messages when trying to run navigation via ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=async localization:=true map:=map_office3.yaml
[log_nav.txt](https://github.com/turtlebot/turtlebot4/files/11846643/log_nav.txt)
and rviz via ros2 launch turtlebot4_viz view_robot.launch.py
[log_rviz.txt](https://github.com/turtlebot/turtlebot4/files/11846650/log_rviz.txt)
However, rviz does not show the map. @roni-kreinin Do you have any idea of what else is going wrong?

FYI: I can control it with the controller now.

**Comment by schenkch** [comment]
@roni-kreinin How can I set a static IP on the robot and raspberry pi themselves and not just on the server?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
