### ISSUE TITLE
turtlebot4 - /scan topic is empty when try to generate new map

### ISSUE THREAD

**Issue by sashag1991** [turtlebot/turtlebot4#164]
**Please provide the following information:**
 - OS: 22.04
 - ROS Distro: humble

 **Expected behaviour**
Scan topic should get rplidar results 

 **Actual behaviour**
dont see any data in /scan topic

**To Reproduce**
I'm using this tutorial- https://turtlebot.github.io/turtlebot4-user-manual/tutorials/generate_map.html1. run : 
1. ros2 launch turtlebot4_navigation slam.launch.py
2. ros2 launch turtlebot4_viz view_robot.launch.py
3. rviz is empty:
![image](https://github.com/turtlebot/turtlebot4/assets/131443912/a484ddf4-1137-4cf6-a12b-b24c3fdd7371)
4.  /scan topic is empty

**Comment by roni-kreinin** [comment]
If you change the Fixed Frame under Global Options from `map` to `base_link`, are you able to see the robot and laser scans?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
