### ISSUE TITLE
Not able to save map in humble

### ISSUE THREAD

**Issue by etigafy** [turtlebot/turtlebot4#170]
**Using:** 
- OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from source or installed: installed

 **Expected behaviour**
SaveMap service saves the map in the current location

 **Actual behaviour**
```
ros2 service call /slam_toolbox/save_map slam_toolbox/srv/SaveMap "name:
  data: 'my_map'"
requester: making request: slam_toolbox.srv.SaveMap_Request(name=std_msgs.msg.String(data='my_map'))

response:
slam_toolbox.srv.SaveMap_Response(result=255)
```

Service responds with undefined failure.

**To Reproduce**
Provide the steps to reproduce:
1. ros2 launch turtlebot4_navigation slam.launch.py
2. ros2 launch turtlebot4_viz view_robot.launch.py
3. ros2 service call /slam_toolbox/save_map slam_toolbox/srv/SaveMap "name:
  data: 'my_map'"

**Comment by roni-kreinin** [comment]
Do you have another map with the name `my_map` in the directory you call this from?

**Comment by etigafy** [comment]
No. I tried it again this morning the behavior is still the same...

**Comment by roni-kreinin** [comment]
The result code (255) isn't very helpful for determining what is causing this issue. I'm going to close this issue and I would recommend re-opening it at https://github.com/SteveMacenski/slam_toolbox. I think those devs will have better insight into what could cause this.

**Comment by ACdu22330** [comment]
Hello, I have the same trouble as @etigafy  did you succeed to fix this problem?

The error result = 255 means RESULT_UNDEFINED_FAILURE it's written in slam_toolbox documentation

**Comment by etigafy** [comment]
@ACdu22330 yes, have a look at [#607](https://github.com/SteveMacenski/slam_toolbox/issues/607#issuecomment-1579287008)
