### ISSUE TITLE
The camera's connectivity varies depending on the USB port.

### ISSUE THREAD

**Issue by gamsaon** [turtlebot/turtlebot4#171]
OS: Ubuntu 22.04
ROS Distro: Humble
turtlebot4_Humble+ Create3-H_1.2

Expected behaviour
The camera needs to work properly

Actual behaviour
If I connect the camera USB to USB 2.0, there is no problem. However, it does not work when I connect the camera to USB 3.0.

To Reproduce
1. When I connected the camera to USB 2.0.
![스크린샷 2023-05-22 11-05-33](https://github.com/turtlebot/turtlebot4/assets/128341069/8a67a17e-7d64-4294-b0b4-8753363ab13a)

As you can see from the photo, when I ran dmesg, it indicates that the connection did not get disconnected. Additionally, camera-related values are displayed correctly.

3. When I connected the camera to USB 3.0
![스크린샷 2023-05-22 10-43-53](https://github.com/turtlebot/turtlebot4/assets/128341069/1893ca9e-f2c7-4a45-8795-640cec8da666)

As shown in the photo, when I ran dmesg, it indicated that the USB got disconnected. Additionally, in the camera topic list, the camera is listed but no values are displayed. Furthermore, the camera works fine until it is connected to the PC, but as soon as it is connected, the camera connection gets interrupted. 

 Is it okay to use the camera on USB 2.0? What are the possible solutions to this issue?

**Comment by roni-kreinin** [comment]
Can you share the logs from the `turtlebot4` service when you are using USB 3.0?

`sudo journalctl -u turtlebot4 -r`

**Comment by gamsaon** [comment]
May 24 02:23:15 ubuntu turtlebot4-start[988]: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/oakd' in container '/oakd_container'
May 24 02:23:15 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894995.718442955] [oakd]: Camera ready!
May 24 02:23:15 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894995.353593053] [oakd]: Finished setting up pipeline.
May 24 02:23:15 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894995.299845955] [oakd]: Pipeline type: RGB
May 24 02:23:15 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894995.294922269] [oakd]: Device type: OAK-D-PRO-AF
May 24 02:23:15 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894995.272513090] [oakd]: USB SPEED: SUPER
May 24 02:23:15 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894995.267831923] [oakd]: Camera with MXID: 18443010B1AE361300 and Name: 1.1.1 connected!
May 24 02:23:12 ubuntu turtlebot4-start[988]: [rplidar_composition-5] [INFO] [1684894992.935454768] [rplidar_composition]: current scan mode: Sensitivity, max_distance: 12.0 m, Point number: 7.9K , angle_compensate: 2, flip_x_axis 0
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.749033742] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.749013539] [AnalyzerGroup]: Group '/Turtlebot4/Create3' has a match with my analyzer 'Mouse'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748957818] [GenericAnalyzer]: Analyzer 'Mouse' matches 'turtlebot4_diagnostics: /mouse topic status'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748715265] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748684210] [AnalyzerGroup]: Group '/Turtlebot4/Create3' has a match with my analyzer 'IMU'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748517009] [GenericAnalyzer]: Analyzer 'IMU' matches 'turtlebot4_diagnostics: /imu topic status'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748382399] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer 'Camera'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748345826] [GenericAnalyzer]: Analyzer 'Camera' matches 'turtlebot4_diagnostics: /color/preview/image topic status'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748225346] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer 'Camera'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748186828] [GenericAnalyzer]: Analyzer 'Camera' matches 'turtlebot4_diagnostics: /stereo/depth topic status'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.748035015] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer 'Lidar'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747975701] [GenericAnalyzer]: Analyzer 'Lidar' matches 'turtlebot4_diagnostics: /scan topic status'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747696446] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747677372] [AnalyzerGroup]: Group '/Turtlebot4/Create3' has a match with my analyzer 'Hazards'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747647799] [GenericAnalyzer]: Analyzer 'Hazards' matches 'turtlebot4_diagnostics: Hazard Detections'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747531022] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747509634] [AnalyzerGroup]: Group '/Turtlebot4/Create3' has a match with my analyzer 'Dock'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747478949] [GenericAnalyzer]: Analyzer 'Dock' matches 'turtlebot4_diagnostics: Dock Status'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747364025] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747346043] [AnalyzerGroup]: Group '/Turtlebot4/Create3' has a match with my analyzer 'Wheels'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747305544] [GenericAnalyzer]: Analyzer 'Wheels' matches 'turtlebot4_diagnostics: Wheel Status'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.747049881] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.746973326] [AnalyzerGroup]: Group '/Turtlebot4/Create3' has a match with my analyzer 'Battery'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.744865189] [GenericAnalyzer]: Analyzer 'Battery' matches 'turtlebot4_diagnostics: Battery Voltage'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.744081829] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.744049867] [AnalyzerGroup]: Group '/Turtlebot4/Create3' has a match with my analyzer 'Battery'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [aggregator_node-10] [INFO] [1684894992.743916683] [GenericAnalyzer]: Analyzer 'Battery' matches 'turtlebot4_diagnostics: Battery Percentage'.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [rplidar_composition-5] [INFO] [1684894992.364481798] [rplidar_composition]: Start
May 24 02:23:12 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894992.193928202] [oakd]: No ip/mxid specified, connecting to the next available device.
May 24 02:23:12 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894992.044797571] [oakd_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
May 24 02:23:12 ubuntu turtlebot4-start[988]: [component_container-6] [INFO] [1684894992.042987559] [oakd_container]: Found class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
May 24 02:23:12 ubuntu turtlebot4-start[988]: [rplidar_composition-5] [INFO] [1684894991.468558396] [rplidar_composition]: RPLidar health status : '0'
May 24 02:23:12 ubuntu turtlebot4-start[988]: [rplidar_composition-5] [INFO] [1684894991.465559048] [rplidar_composition]: Hardware Rev: 7
May 24 02:23:12 ubuntu turtlebot4-start[988]: [rplidar_composition-5] [INFO] [1684894991.465518364] [rplidar_composition]: Firmware Ver: 1.29
May 24 02:23:12 ubuntu turtlebot4-start[988]: [rplidar_composition-5] [INFO] [1684894991.465358866] [rplidar_composition]: RPLIDAR S/N: DA83EDF9C7E29BCEA7E39EF24A504304
-- Boot d1fd29f5b72e4703b7dc9ec85816d225 --
May 24 02:22:07 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894927.760029094] [turtlebot4_node]: start_motor service completed.
May 24 02:22:07 ubuntu turtlebot4-start[981]: [rplidar_composition-5] [INFO] [1684894927.759243421] [rplidar_composition]: Ingnoring start_motor request because rplidar_node is in 'auto standby' mode
May 24 02:22:07 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894927.557805530] [turtlebot4_node]: start_motor service available, sending request
May 24 02:22:06 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894926.547127274] [turtlebot4_node]: RPLIDAR started
May 24 02:22:06 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894926.546835667] [turtlebot4_node]: OAKD started
May 24 02:21:52 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894912.812771084] [turtlebot4_node]: stop_motor service completed.
May 24 02:21:52 ubuntu turtlebot4-start[981]: [rplidar_composition-5] [INFO] [1684894912.811855524] [rplidar_composition]: Ingnoring stop_motor request because rplidar_node is in 'auto standby' mode
May 24 02:21:52 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894912.546896886] [turtlebot4_node]: stop_motor service available, sending request
May 24 02:21:51 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894911.536275703] [turtlebot4_node]: RPLIDAR stopped
May 24 02:21:51 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894911.536077614] [turtlebot4_node]: OAKD stopped
May 24 02:17:06 ubuntu turtlebot4-start[981]: [ERROR] [component_container-6]: process has died [pid 1206, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container --ros-args -r __node:=oakd_container -r __ns:=/'].
May 24 02:17:05 ubuntu turtlebot4-start[981]: [component_container-6]   what():  Couldn't read data from stream: '__rpc_main' (X_LINK_ERROR)
May 24 02:17:05 ubuntu turtlebot4-start[981]: [component_container-6] terminate called after throwing an instance of 'dai::XLinkReadError'
May 24 02:16:59 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894619.749405839] [turtlebot4_node]: start_motor service completed.
May 24 02:16:59 ubuntu turtlebot4-start[981]: [rplidar_composition-5] [INFO] [1684894619.746571854] [rplidar_composition]: Ingnoring start_motor request because rplidar_node is in 'auto standby' mode
May 24 02:16:59 ubuntu turtlebot4-start[981]: [component_container-6] [INFO] [1684894619.572786278] [oakd]: No ip/mxid specified, connecting to the next available device.
May 24 02:16:59 ubuntu turtlebot4-start[981]: [component_container-6] [INFO] [1684894619.572591671] [oakd]: Starting camera.
May 24 02:16:59 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894619.570511265] [turtlebot4_node]: start_motor service available, sending request
May 24 02:16:59 ubuntu turtlebot4-start[981]: [turtlebot4_node-1] [INFO] [1684894619.569818351] [turtlebot4_node]: oakd/start_camera service available, sending request

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Based on the provided information, you requested camera service, but the camera is not connecting. So, you ran 'sudo dmesg -w' to check if the device is properly connected, and it indicated that one USB connection failed. The following information shows the status of the devices.

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[   37.039233] usb 1-1.1: USB disconnect, device number 3
[   37.784299] usb 2-1: new SuperSpeed USB device number 3 using xhci_hcd
[   37.809242] usb 2-1: New USB device found, idVendor=03e7, idProduct=f63b, bcdDevice= 1.00
[   37.809276] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   37.809282] usb 2-1: Product: Luxonis Device
[   37.809287] usb 2-1: Manufacturer: Intel Corporation
[   37.809292] usb 2-1: SerialNumber: 18443010B1AE361300
[   42.975995] usb 2-1: USB disconnect, device number 3
[   45.199974] usb 1-1.1: new high-speed USB device number 6 using xhci_hcd
[   45.304706] usb 1-1.1: New USB device found, idVendor=03e7, idProduct=2485, bcdDevice= 0.01
[   45.304730] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   45.304738] usb 1-1.1: Product: Movidius MyriadX
[   45.304745] usb 1-1.1: Manufacturer: Movidius Ltd.
[   45.304751] usb 1-1.1: SerialNumber: 03e72485

**Comment by roni-kreinin** [comment]
Does this happen with both USB 3 ports? Also can you try this again with the RPLIDAR and any other USB devices disconnected?

**Comment by kkksion** [comment]
The same issue occurs where the camera does not turn on in two USB 3.0 ports. Furthermore, as you suggested, when I disconnected the RPLIDAR and ran it on a USB 3.0 port, a new problem arose. The camera works fine until the robot finishes booting, but once the booting process is complete, the camera no longer works

**Comment by roni-kreinin** [comment]
What do you mean by `The camera works fine until the robot finishes booting`? Are you getting this from dmesg?

Also, do you have a TurtleBot 4 lite or standard?

**Comment by gamsaon** [comment]
I am currently using Turtlebot4 standard. Today, I double-checked, and it seems that what I mentioned earlier was incorrect. When I tried again after disconnecting the RPLIDAR and other USB devices, the camera connected to USB 3.0 did not work. Among many robots, only this robot seems to be unable to use the camera when it is connected to USB 3.0.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
