### ISSUE TITLE
TF etc really flaky TurtleBot Lite

### ISSUE THREAD

**Issue by CycleMark** [turtlebot/turtlebot4#173]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from installed:

I've set up the network as per https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html [I don't want the Create3 connected to the network - that seems to make matters worse]

Starting any/all of:

ros2 launch turtlebot4_bringup lite.launch.py
ros2 launch rplidar_ros rplidar.launch.py

Running:

ros2 run tf2_tools view_frames

On either the RPi or the PC (I have set up the PC as per inx above) calling:

ros2 run tf2_tools view_frames

It intermittent - Sometimes the TF tree most of the time not.

I've run through:

https://turtlebot.github.io/turtlebot4-user-manual/overview/

And can't see anything I've missed.

Could you please advise where I can check next. 

Thanks

Mark

**Comment by ipa-rar** [comment]
@CycleMark Did you set namespace to your robot. If thats the case, then ``ros2 run tf2_tools view_frames`` will not show any trees. Try this [node](https://github.com/ipa-rar/tf_relay)

**Comment by CycleMark** [comment]
@ipa-rar  - Thanks but that isn't the issue. The namespace is set correctly - plus this is only one robot which sometime does and then doesn't show TF - so intermittent

**Comment by roni-kreinin** [comment]
@CycleMark Are you stopping the `turtlebot4` service before calling `ros2 launch turtlebot4_bringup lite.launch.py`? The service runs `lite.launch.py` in the background so you would be launching duplicate nodes.

You can check if the service is running with `sudo systemctl status turtlebot4`, and view the full logs with `sudo journalctl -u turtlebot4 -r`.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
