### ISSUE TITLE
Nav2 and Battery issues

### ISSUE THREAD

**Issue by nidia-bucarelli** [turtlebot/turtlebot4#177]
I am trying to run Nav2. I get the error below. How to fix this error? The robot does not show up in Rviz and I cannot connect it to the controller. 

```
...
controller_server-3] [INFO] [1684982046.230401850] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees. 
[sync_slam_toolbox_node-2] [INFO] [1684982046.334276758] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link' at time 1684982046.200 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-2] [INFO] [1684982046.458095791] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link' at time 1684982046.335 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-2] [INFO] [1684982046.592352981] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link' at time 1684982046.458 for reason 'discarding message because the queue is full'

```
In addition to this error, I have some issues with the battery. The robot had a red light, and it did not want to work (e.g., navigate or show in Rviz). I cannot recall if I had the same error as above when I had this firt battery issue. To solve this battery issue, I changed the battery. Initially, this battery was charging. It went red again, after some days. I changed the battery again (third time), but the robot does not want to charge now. The screen keeps showing 0% for the battery (while in the docking station for hours).  When I try to echo the topic for the battery it returns nothing. After some hours the red light is red. 

How to fix this issue?  are they related?

![image](https://github.com/turtlebot/turtlebot4/assets/112603498/b01295a8-d0df-415c-acce-9f9e1c63ca11)

**Comment by roni-kreinin** [comment]
@nidia-bucarelli The issues are likely related. It looks like the RPi4 and Create 3 are not communicating.

Can you specify what ROS2 version you are using, as well as whether you are using simple discovery or the discovery server?

**Comment by nidia-bucarelli** [comment]
I am using ROS2 Galactic. 
I am not sure about the discovery. How do I check for that?

**Comment by roni-kreinin** [comment]
If you haven't gone through [these instructions](https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html) then we can assume you are on simple discovery. Have you connected your Create 3 to your Wi-Fi network? Also what is the output of `ros2 topic list` when called from the RPi4?

**Comment by nidia-bucarelli** [comment]
I went through the basic setups a long time ago. I cannot recall very well.
I have been trying to ssh into the robot so I can check the topics. But now I can't. 

- The screen is black. The light starts white, and then it goes red.
- I tried to use a USB adapter to ssh over the ethernet (following the instructions on FAQ from the TB4 git/guide). The ethernet on my computer is enabled only for ~5 seconds after I dock the robot into the docking station. Then it goes off, so I cannot ssh.   
- I can see from the router website that only the iCreate/base is connected. 
Any ideas on how I can ssh?

**Comment by roni-kreinin** [comment]
@nidia-bucarelli Check that the RPi is powering on inside the robot. There should be one red and one yellow LED on near the USB-C connector.

If you have a micro HDMI cable you can connect it to one of the HDMI ports on the Raspberry Pi. Then connect the other end to a monitor. Power on the RPi after connecting these cables and with a USB keyboard you should be able to log in.

**Comment by nidia-bucarelli** [comment]
I think it is not powering on inside the robot. I don't see a light near the USB connector.

![image](https://github.com/turtlebot/turtlebot4/assets/112603498/fd8f6bf0-fa56-4d1a-b54f-09707a72a3a3)
![image](https://github.com/turtlebot/turtlebot4/assets/112603498/badc2e3a-0bcc-4239-b683-bc0e89744c31)


As per the micro HDMI cable, I cannot see the port. Should I remove the case/cover of the robot? Or should I use the HDMI ports on the edges (on the cover)?

![image](https://github.com/turtlebot/turtlebot4/assets/112603498/41806a58-0612-4f67-acf8-1705734fc0c6)

**Comment by roni-kreinin** [comment]
I would recommend removing the top plate and standoffs so that you can look under the PCBA. Instructions are [here](https://turtlebot.github.io/turtlebot4-user-manual/mechanical/turtlebot4.html#removing-the-pcba).

The four ports on the PCBA are USB-C ports, and I don't believe you can connect a monitor to the RPi4 through that (though I haven't tested). The HDMI ports are labelled in this image: 
![image](https://github.com/turtlebot/turtlebot4/assets/59886299/c5c86570-e332-4938-b61b-9234566c198a)

**Comment by nidia-bucarelli** [comment]
I was able to remove the PCBA. I unplugged all cables, except the cable that gives power (that comes from the base). The base is ON. But the pi4 is not ON. 

I tried to change the power supply for the Pi4 using another source of power, and it worked. 
any suggestions?

**Comment by roni-kreinin** [comment]
@nidia-bucarelli Can you check that the Create 3 [Adapter board](https://iroboteducation.github.io/create3_docs/hw/adapter/) is fully inserted into the Create 3, and that the USB-C cable is connected properly? If neither of those is an issue, can you try using a different USB-C to USB-C cable if you have one?

**Comment by nidia-bucarelli** [comment]
I checked the connection, and It still does not want to stay on. It only last 2-3 seconds.  I tested a different USB-C cable (to connect from the pi to the adapter). I also changed the adapter using the one from another robot I have. 

Also, in case this is important.... the base is only ON when it is in the docking station. If I remove the base from the docking station, the base goes off.  The battery is also new. The one I had before lasted 2 days, before the robot going to red light.

**Comment by roni-kreinin** [comment]
It sounds like your battery has been fully discharged and is unable to charge again. Can you try the following:
- Remove the battery for 15 minutes
- Remove the adapter board
- Insert the battery back in and place the robot back on the dock.
- Allow it to charge fully with the adapter board removed.
- Reconnect the adapter board once it is charged.

**Comment by nidia-bucarelli** [comment]
My p4 is ON now.
But the LED screen always shows that the battery is 0%.  But, the robot is not docked and is still ON. For example, it's been 2 hours or so, showing 0% and still ON (without charging).
![image](https://github.com/turtlebot/turtlebot4/assets/112603498/cb8cf4d1-dcbe-4b21-ad47-dff88befec7e)

When I do:
ros2 topic echo /diagnostics_agg 

I get:
- level: "\x02" 
  name: '/Turtlebot4/Create3/Battery/turtlebot4_diagnostics: Battery Percentage'
  message: Critical
  hardware_id: Turtlebot4
  values:
  - key: Battery Percentage
    value: '0.00'

When I do:
ros2 topic echo /battery_state   

I don't get anything.

I also tried to run Nav2, again ... which was my initial problem. I get the error below. How to fix this error? The robot does not show up in Rviz and I cannot connect it to the controller.

```
controller_server-3] [INFO] [1684982046.230401850] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees. 
[sync_slam_toolbox_node-2] [INFO] [1684982046.334276758] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link' at time 1684982046.200 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-2] [INFO] [1684982046.458095791] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link' at time 1684982046.335 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-2] [INFO] [1684982046.592352981] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link'
```

**Comment by roni-kreinin** [comment]
@nidia-bucarelli The comms LED is off which indicates that the RPi4 cannot communicate with the Create 3. Has the Create 3 been connected to Wi-Fi? Can you check the webserver to make sure that there is an IP address showing in the Connect page?

**Comment by nidia-bucarelli** [comment]
Yes. It has been connected to Wi-Fi. I also checked the webserver and there is an IP address. 

These are the topics that my computer can see:
```
/base/battery_state
/base/cmd_audio
/base/cmd_lightring
/base/cmd_vel
/base/dock
/base/hazard_detection
/base/imu
/base/interface_buttons
/base/ir_intensity
/base/ir_opcode
/base/kidnap_status
/base/mouse
/base/odom
/base/robot_state/transition_event
/base/slip_status
/base/static_transform/transition_event
/base/stop_status
/base/system_monitor/transition_event
/base/tf
/base/tf_static
/base/wheel_status
/base/wheel_ticks
/base/wheel_vels
/battery_state
/cmd_vel
/color/preview/camera_info
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/joint_states
/joy
/joy/set_feedback
/mouse
/parameter_events
/robot_description
/rosout
/scan
/stereo/camera_info
/stereo/depth
/tf
/tf_static
/wheel_status
```

These are the topics i can see from the RPi4:

```
/base/interface_buttons
/base/robot_state/transition_event
/base/static_transform/transition_event
/base/system_monitor/transition_event
/parameter_events
/rosout
```

**Comment by roni-kreinin** [comment]
It looks like you have namespaced the Create 3 to `base`. Namespacing isn't supported in Galactic, so please change it back to an empty string in the webserver.

**Comment by nidia-bucarelli** [comment]
It is working now. Thanks much!
