### ISSUE TITLE
Documentation: Multihomed computer and Cyclone-DDS

### ISSUE THREAD

**Issue by alexswerner** [turtlebot/turtlebot4#18]
There should be a FAQ entry that Cyclone-DDS needs to be manually configured which network interface to use through this setting:
```
export CYCLONEDDS_URI='<CycloneDDS><Domain><General><NetworkInterfaceAddress>wlo1</></></></>'
```
And to give people a chance to understand what is going on with ROS2 DDS on network bridges (like all APs with 2.4Ghz 5Ghz Wi-FI) the documentation could state something like "[IGMP](https://en.wikipedia.org/wiki/Internet_Group_Management_Protocol) messages are used to subscribe [IPv4 multicast](https://en.wikipedia.org/wiki/Multicast_address) discovery messages sent by all ROS2 hosts on UDP port `7400` (in the default configuration with ROS_DOMAIN_ID=0) to `239.255.0.1`. 

This would have been useful to know in our case. Our Wi-Fi setup did only send the discovery messages to hosts which has previously send IGMP subscribe messages (done by the ROS2 daemon). Our issue was that the daemon by default sent them on the wrong interface and on the interface the robots were sitting there was no discovery messages to be seen (with tcpdump)

**Comment by roni-kreinin** [comment]
I have updated the instructions in the user manual.
