### ISSUE TITLE
Create3 unable to connect 

### ISSUE THREAD

**Issue by Tanjim13** [turtlebot/turtlebot4#185]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 20.04)
 - ROS Distro: (e.g. Galactic)
 - Built from source or installed:

 **Expected behaviour**
 Should take me to Create3 page, after assigning 192.168.0.104:8080

 **Actual behaviour**
 Unable to connect. Why??

![20230531_192729](https://github.com/turtlebot/turtlebot4/assets/18646128/bdaa8397-e3e1-4873-bd7e-646eb4c1f906)
![20230531_191545](https://github.com/turtlebot/turtlebot4/assets/18646128/ba9c5425-1ed7-4b03-9144-1599aca51dd7)

**Comment by roni-kreinin** [comment]
@Tanjim13 Which Galactic image are you running on the RPi4? This feature was only added to 0.1.3.

**Comment by Tanjim13** [comment]
I think this robot has previous galactic image. Cause most of these robots have arrived earlier, which don't have this feature. So, what should i do now? 

I think i used to press 2 side buttons in create3 and lightring node turned to blue and I somehow connect the create3 with the router Network. But I forgot that system. 
Can you tell me what to do?

**Comment by ipa-rar** [comment]
@Tanjim13 You can update your RPi to the latest image from [here](http://download.ros.org/downloads/turtlebot4/). 

More details in this issue (https://github.com/turtlebot/turtlebot4_setup/issues/5)

**Comment by roni-kreinin** [comment]
@Tanjim13 Pressing and holding Create 3 buttons 1 and 2 together for a few seconds will make the lightring turn blue and place the Create 3 into AP mode. You should then see an open Wi-Fi network called something like `CreateXXXX`. Connect to it then navigate to `192.168.10.1` in a browser to access the webserver.

**Comment by Tanjim13** [comment]
@roni-kreinin, Thank you for the guidance. It solved the issue. 
@ipa-rar, Yes you are right. Currently, I believe we're using turtlebot4_standard_galactic_0.1.2. I will consider updating this in the near future.

To both @ipa-rar @roni-kreinin, I am exploring the possibility of establishing a multi-robot setup under our institutional network. The challenge I encounter is the unavailability of separate SSIDs for 2.4 GHz and 5 GHz. We only have a single SSID, "X_wifi". Is there a potential workaround to successfully set up multiple robots under this singular SSID? Your expert advice would be greatly appreciated.

**Comment by roni-kreinin** [comment]
@Tanjim13 By multi-robot setup do you mean you are trying to run a fleet of turtlebots that interact with each other, or just have multiple individual robots on the same network?

**Comment by Tanjim13** [comment]
@roni-kreinin , I am trying to set up multiple individual robots under the same network under the institutional internet. I have already set up robot with router using $ROS_DOMAIN ID already. However, I want to avoid the limitation of using a Wi-Fi router that restricts us to a room. Instead, I'd like to use institutional wifi which is only come with wifi ssid 'Redrover'. There is no 2.4 or 5GHz. My robots are all ROS_GALACTIC with turtlebot4_standard_galactic_0.1.2 image.

How can I do that?

**Comment by roni-kreinin** [comment]
@Tanjim13 If the Create 3 is having issues connecting to the network, I would recommend using the [Discovery Server](https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html). This way you will only need to connect the RPi to Wi-Fi. Currently there are limitations to Discovery server, where a remote PC will only be able to communicate with one robot at a time. We are working on adding support for multiple robots, and that is being tracked [here](https://github.com/turtlebot/turtlebot4/issues/145).

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
