### ISSUE TITLE
Multiple Issues with ROS2 Humble communication with Turtlebot4

### ISSUE THREAD

**Issue by Kazimbalti** [turtlebot/turtlebot4#186]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 22.04)
 - ROS Distro: (e.g. Humble)
 
The image of turtlebot4_standard_humble.zip file is stored in the SD card and then inserted on the RPI, All the processes went very smoothly, and I have updated the firmware of create3. 
Following are some of the issues:
1. When I launch "ros2 run teleop_twist_keyboard teleop_twist_keyboard" or any other file, the turtlebot4 doesn't move, same with other commands the turtlebot4 doesn't respond.
2. When I connect the turtlebot4 with 2.4GHz it shows "UNKNOWN" IP, while when I connect it with 5.0GHz it shows IP address.
3. On create3  to connect robot to Wi-Fi, it shows only 2.4GHz and 5.0 GHz doesn't appear.
5. on create3 it even doesn't shows any IP Address: as shown in figure
![Screenshot from 2023-06-01 17-32-55](https://github.com/turtlebot/turtlebot4/assets/32608321/6b342808-c573-444d-b074-c42d0d9d9f31)

Following are the topic list on both PC and RPI 
ROS2 toic list 

/battery_state
/cmd_vel
/color/preview/image
/diagnostics
/diagnostics_agg
/diagnostics_toplevel_state
/dock_status
/function_calls
/hazard_detection
/hmi/buttons
/hmi/display
/hmi/display/message
/hmi/led
/imu
/interface_buttons
/ip
/joint_states
/joy
/joy/set_feedback
/mouse
/oakd/rgb/preview/camera_info
/oakd/rgb/preview/image_raw
/oakd/rgb/preview/image_raw/compressed
/oakd/rgb/preview/image_raw/compressedDepth
/oakd/rgb/preview/image_raw/theora
/parameter_events
/robot_description
/rosout
/scan
/stereo/depth
/tf
/tf_static
/wheel_status

**Comment by roni-kreinin** [comment]
@Kazimbalti If you are just using one robot I would recommend going through the [Discovery Server](https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html) setup. This way the Create 3 doesn't need to be connected to Wi-Fi.

**Comment by Kazimbalti** [comment]
Thank you for your response
But I have two turtlebot4 and I have to make a multi robot navigation but still stuck on one turtlebot4 configurations and there are many issues.

**Comment by ipa-rar** [comment]
It is very difficult to use TB4 for multirobot navigation. I have been trying this since December 2022 and still not there yet, you can check the issues opened by me to get some insights. 
However If you figure out a way to do this please submit some documentation on it.

**Comment by Kazimbalti** [comment]
thanks @ipa-rar for your response.
Yes, I am still working on it and didn't get succeeded.
Please can you share the link to the issues you opened it?
thank you

**Comment by Kazimbalti** [comment]
Secondly, @ipa-rar @roni-kreinin 
I am thinking to switch back to Ubuntu20.04, Galactic, and try to work on multi-robot navigation using NAV2.
What do you suggest?
Thank you

**Comment by roni-kreinin** [comment]
@Kazimbalti The turtlebot4 does not support namespacing in Galactic so you would only be able to use the ROS_DOMAIN_ID to separate multiple robots.

The turtlebot4 is set up for namespacing in the way that Nav2 wants, so it should be doable. I would recommend checking the Nav2 github for examples.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
