### ISSUE TITLE
Turtlebot 4 Controller iisue

### ISSUE THREAD

**Issue by HiWiQiao** [turtlebot/turtlebot4#189]
- OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from Debian Package

 the Light always stays on, can’t be turned off, can’t be paired, and can’t control the turtlebot4, i feel terrible, but i can control with my pc keyboard, and the “ dock , undock , wall Follw left /right “ also unavailable, but few days it works. What should I do!
![IMG_8065](https://github.com/turtlebot/turtlebot4/assets/131516469/a5832dc7-d86e-4a83-a223-f3fb6a2cca3f)
![IMG_8064](https://github.com/turtlebot/turtlebot4/assets/131516469/f37219fa-a375-47db-b4bd-023a226d3274)
![IMG_8062](https://github.com/turtlebot/turtlebot4/assets/131516469/858e5c9b-60fb-4e10-b66e-8cef9730cc33)

**Comment by roni-kreinin** [comment]
@HiWiQiao There is a small reset button on the back of the controller. Can you try pressing that and see if it helps?

**Comment by HiWiQiao** [comment]
> @HiWiQiao There is a small reset button on the back of the controller. Can you try pressing that and see if it helps?

Thanks for your reply, sorry I didn’t find the button,maybe you can push a Foto or exactly description

**Comment by roni-kreinin** [comment]
![image](https://github.com/turtlebot/turtlebot4/assets/59886299/c870f90c-0482-4abf-9db9-1e8274356403)
