### ISSUE TITLE
TB4 cant avoid static and dynamic obstacles 

### ISSUE THREAD

**Issue by sashag1991** [turtlebot/turtlebot4#190]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from source or installed:

 **Expected behaviour**
Avoid static and dynamic obstacles without collision 

 **Actual behaviour**
When see a static or dynamic obstacle TB4 doesn't responds and keep moving towards the obstacle

**To Reproduce**

1. run: ros2 launch turtlebot4_navigation localization.launch.py map:=map.yaml
2. run: ros2 launch turtlebot4_navigation nav2.launch.py
3. run: ros2 launch turtlebot4_viz view_robot.launch.py
4. set point to navigate to using Nav2go button in RVIZ

**Other notes**
Add anything else you thing is important.

**Comment by sashag1991** [comment]
I  tried turtlebot4-ntpd-sync before the run

**Comment by ipa-rar** [comment]
@sashag1991 This behavior is already mentioned in (#167)(#141) and this behavior is due to the CPU of the create3 base maxing out(#147 ) (#176) and issue with the time sync

Try running `turtlebot4-ntpd-sync`command from the RPi4 or accessing the Create 3 webserver and restarting ntpd from the Beta Features tab. This should help you here (#141 )

**Comment by sashag1991** [comment]
I already try turtlebot4-ntpd-sync from RPi4 and from Create 3 webserver.
Will there be some fix for the CPU issue ?

**Comment by sashag1991** [comment]
I use Discovery server with  FastRTPS.
Is moving to Discovery server with CycloneDDS can help ?

**Comment by roni-kreinin** [comment]
@sashag1991 Discovery server is only available in FastRTPS. The CPU issue is being tracked [here](https://github.com/iRobotEducation/create3_docs/issues/381).

**Comment by sashag1991** [comment]
Correct me if I'm wrong but in https://github.com/iRobotEducation/create3_docs/issues/381. said:  "The individual robots can run fine but as soon as two are on the same network they run into issues".
I that c ase running only 1 robot should work, right ?

**Comment by roni-kreinin** [comment]
@sashag1991 That will depend on what software you are running. In my experience, running the navigation stack can bring the Create 3 CPU to 100% which will cause issues such as the TF frames having old timestamps.

**Comment by sashag1991** [comment]
[roni-kreinin](https://github.com/roni-kreinin) do you have any suggestions how do I can procced ? I need complete some tasks with the robot and I cant right now.

**Comment by sashag1991** [comment]
[roni-kreinin](https://github.com/roni-kreinin), Any update?

**Comment by roni-kreinin** [comment]
@sashag1991 I would recommend updating your NTP config as mentioned in #216. Some users have reported that this improves their experience with mapping. There isn't yet a fix for the CPU usage issue.

**Comment by sashag1991** [comment]
The NTP config and latest H2.2 DIDNT helped to solve my issue with avoid obstacles. Maybe I should change some parameter in nav2 config yaml ? I have no idea how to solve it and this ability is necessary for my activity.

**Comment by sashag1991** [comment]
Any update/help ?

**Comment by hilary-luo** [comment]
@sashag1991 Can you please provide the create3 log after recreating this issue? and please clarify for me your exact setup. Are you still using Discovery Server (with Fast DDS) and operating a single robot? What firmware are you running on the create3?

After doing that, can you please download and make copies of the [nav2 configs](https://github.com/turtlebot/turtlebot4/tree/humble/turtlebot4_navigation/config). Then in your local copies, modify every occurence of `topic: scan` to indicate the global topic name, for example [here](https://github.com/turtlebot/turtlebot4/blob/d4412899e428196b0905e4edd2896b8c98ce6580/turtlebot4_navigation/config/nav2.yaml#L169). If you don't have a namespace then that would be `topic: /scan` or if you do have a namespace then `topic: /<namespace>/scan`. Then, launch navigation using these modified configs. 

```
ros2 launch turtlebot4_navigation localization.launch.py map:=map.yaml params:=path_to_config/localization.yaml
ros2 launch turtlebot4_navigation nav2.launch.py params:=path_to_config/nav2.yaml
```

If this still doesn't work then please once again provide the create3 log from the attempt.

**Comment by sashag1991** [comment]
Hi @hilary-luo, I changed the scan topic to /scan in localization.yaml and nav2.yaml, TB4 still not avoids obstacles.
Here the log from create3 : [create3_log.txt](https://github.com/turtlebot/turtlebot4/files/12461414/create3_log.txt)
I use latest FW humble H.2.2

**Comment by hilary-luo** [comment]
1. Can you confirm which version of the ros-humble-turtlebot4-navigation that you have installed (on the system where you are running the nav nodes)?

2. After having made the changes I requested and while running nav2, can you provide the full list of topics? (`ros2 topic list`)

3. When you view the system in RViz, can you see the lidar hits on the obstacle as well as the costmap around the obstacle? For example this is a picture of a robot in rviz including the lidar hits and the costmap around the mapped obstacles. 
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/9fd578f9-eae6-4b3f-b942-6c94a3d0a54d)
If I drop an additional box beside the robot, I can see on RViz where the lidar sees the side of the box and the costmap generated around those lidar hits. 
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/9b039208-7269-49ca-a5c3-7a960f37d9ac)
On top of this, you can see that there is a section of the costmap that is brighter whereas the surrounding costmap is faded. That is how the local costmap and global costmap are being represented respectively. 

Can you see both the local and global costmaps responding to your obstacles? You should be able to see this if you are running the latest packages and have made the change to the scan topics in the yaml configs.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
