### ISSUE TITLE
Issue with turtlebot4 Navigation

### ISSUE THREAD

**Issue by llyf-s** [turtlebot/turtlebot4#191]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed: Installed

 **Expected behaviour**
Able to do 2D Pose Estimate and set Nav2 Goal

 **Actual behaviour**
Map is able to produce in Rviz2, unable to set 2D Pose Estimate. Create 3 button light alternately turns red & yellow; MTR & COMM LED turns off. 

**To Reproduce**
Provide the steps to reproduce:
1. ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=map_name.yaml on turtlebot4 RPi
2. ros2 launch turtlebot4_viz view_robot.launch.py on PC 

Turtlebot4 is in Discovery Server

**Comment by hilary-luo** [comment]
Can you please replicate this situation and then provide the system logs from the Create3? https://iroboteducation.github.io/create3_docs/webserver/logs/

**Comment by llyf-s** [comment]
[messages (1).txt](https://github.com/turtlebot/turtlebot4/files/11797463/messages.1.txt)

**Comment by hilary-luo** [comment]
Unfortunately you seem to be dealing with this issue here: https://github.com/iRobotEducation/create3_docs/issues/381

You can try running the navigation node on your pc to see if that helps.

**Comment by llyf-s** [comment]
hello, 
i'm currently still facing this issue. 
From diagnostics: 
- create3 mouse & imu topic status ERROR.

fortunately i've set up some of my turtlebot4 on humble and they are running smoothly. 

the rest of my turtlebot4 are on galactic and still having the same issue where the MTR and COMMS are regularly connecting and disconnecting, even after re-flashing the ssd card for rpi4. however, i was able to run mapping.


would need some advice on trying to rectify on my turtlebot4 running on galactic

**Comment by hilary-luo** [comment]
I would advise that if switching to humble fixed the issue on some of the robots that you set them all up on humble. Galactic is end of life afterall. If your create3 logs are still showing 100% cpu (`CPU usage: max 100 [%]`) then there is nothing else I can suggest other than going to that other ticket that I linked before and sharing your input there.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
