### ISSUE TITLE
TB4 OAK-D camera launch failed

### ISSUE THREAD

**Issue by kennyS99** [turtlebot/turtlebot4#193]
**Please provide the following information:**
 - OS: Ubuntu 22.04 LTS
 - ROS Distro: ROS2 humble

 **Expected behaviour**
The camera should be launched successfully.

 **Actual behaviour**
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2023-06-12-13-27-22-903004-ubuntu-3030
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch_ros.actions.node]: Error while expanding or validating node name or namespace for 'package=rclcpp_components, executable=component_container, name=oakd_container, namespace=<launch.substitutions.launch_configuration.LaunchConfiguration object at 0xffffa56e9210>':
[ERROR] [launch]: Caught exception in launch (see debug for traceback): launch configuration 'namespace' does not exist

**Other notes**
I discovered another problem: the OAKD camera node initially works when the robot starts, but it stops running after a few seconds. I also examined the status of the turtlebot4 bring-up, which is currently running, and it appears that the camera node stops automatically. The log file can be found below.

● turtlebot4.service - "bringup turtlebot4"
     Loaded: loaded (/lib/systemd/system/turtlebot4.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-06-12 13:08:19 UTC; 6min ago
   Main PID: 2289 (turtlebot4-star)
      Tasks: 136 (limit: 4416)
     Memory: 252.3M
        CPU: 4min 46.496s
     CGroup: /system.slice/turtlebot4.service
             ├─2289 /bin/bash /usr/sbin/turtlebot4-start
             ├─2376 /usr/bin/python3 /opt/ros/humble/bin/ros2 launch /tmp/turtlebot4.launch.py
             ├─2401 /opt/ros/humble/lib/turtlebot4_node/turtlebot4_node --ros-args -r __ns:=/ --params-file /tmp/tmpbqcrbeeb --params-file /tmp/launch_params_ftplzws3
             ├─2403 /opt/ros/humble/lib/joy_linux/joy_linux_node --ros-args -r __node:=joy_linux_node -r __ns:=/ -r /diagnostics:=diagnostics
             ├─2405 /opt/ros/humble/lib/teleop_twist_joy/teleop_node --ros-args -r __node:=teleop_twist_joy_node -r __ns:=/ --params-file /tmp/tmpi498m703
             ├─2407 /opt/ros/humble/lib/rplidar_ros/rplidar_composition --ros-args -r __node:=rplidar_composition -r __ns:=/ --params-file /tmp/launch_params_ryfl3mpx
             ├─2409 /opt/ros/humble/lib/rclcpp_components/component_container --ros-args -r __node:=oakd_container -r __ns:=/
             ├─2420 /opt/ros/humble/lib/robot_state_publisher/robot_state_publisher --ros-args -r __node:=robot_state_publisher -r __ns:=/ --params-file /tmp/launch_params_h94xpfqr --params-file /tmp/la>
             ├─2430 /opt/ros/humble/lib/tf2_ros/static_transform_publisher --x 0.0 --y 0.1165 --z 0.0402 --roll -1.5707 --pitch 0.0 --yaw 0.0 --frame-id base_link --child-frame-id wheel_drop_left --ros->
             ├─2437 /opt/ros/humble/lib/tf2_ros/static_transform_publisher --x 0.0 --y -0.1165 --z 0.0402 --roll -1.5707 --pitch 0.0 --yaw 0.0 --frame-id base_link --child-frame-id wheel_drop_right --ro>
             ├─2446 /opt/ros/humble/lib/diagnostic_aggregator/aggregator_node --ros-args -r __ns:=/ --params-file /tmp/tmpjlsemtjz -r /diagnostics:=diagnostics -r /diagnostics_agg:=diagnostics_agg -r /d>
             └─2454 /usr/bin/python3 /opt/ros/humble/lib/turtlebot4_diagnostics/diagnostics_updater --ros-args -r __ns:=/ -r /diagnostics:=diagnostics -r /diagnostics_agg:=diagnostics_agg -r /diagnostic>

Jun 12 13:08:31 ubuntu turtlebot4-start[2376]: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/oakd' in container '/oakd_container'
Jun 12 13:09:00 ubuntu turtlebot4-start[2376]: [turtlebot4_node-1] [INFO] [1686575340.014893676] [turtlebot4_node]: OAKD stopped
Jun 12 13:09:00 ubuntu turtlebot4-start[2376]: [turtlebot4_node-1] [INFO] [1686575340.015052137] [turtlebot4_node]: RPLIDAR stopped
Jun 12 13:09:01 ubuntu turtlebot4-start[2376]: [turtlebot4_node-1] [INFO] [1686575341.015368789] [turtlebot4_node]: oakd/stop_camera service available, sending request
Jun 12 13:09:01 ubuntu turtlebot4-start[2376]: [turtlebot4_node-1] [INFO] [1686575341.015925172] [turtlebot4_node]: stop_motor service available, sending request
Jun 12 13:09:01 ubuntu turtlebot4-start[2376]: [component_container-5] [INFO] [1686575341.016132503] [oakd]: Stopping camera.
Jun 12 13:09:01 ubuntu turtlebot4-start[2376]: [rplidar_composition-4] [INFO] [1686575341.262744502] [rplidar_composition]: Ingnoring stop_motor request because rplidar_node is in 'auto standby' mode
Jun 12 13:09:01 ubuntu turtlebot4-start[2376]: [turtlebot4_node-1] [INFO] [1686575341.263825712] [turtlebot4_node]: stop_motor service completed.
Jun 12 13:09:03 ubuntu turtlebot4-start[2376]: [turtlebot4_node-1] [INFO] [1686575343.113110689] [turtlebot4_node]: oakd/stop_camera service got results: Success
Jun 12 13:09:03 ubuntu turtlebot4-start[2376]: [turtlebot4_node-1] [INFO] [1686575343.113240558] [turtlebot4_node]:

**Comment by kennyS99** [comment]
Apologies for the misunderstanding. It turns out that I made a mistake by connecting the camera's USB port to the USB 2.0 port on the Raspberry Pi, which caused the issue. However, after switching the cable to a USB 3.0 port, everything is now functioning properly.

**Comment by hilary-luo** [comment]
I am going to address these as 2 separate items. 

1) In the "Actual Behaviour" section you try to launch the oakd camera node manually and you get the error `launch configuration 'namespace' does not exist`. This is indicating that you need to pass in the namespace parameter. Normally this gets passed in by another launch file.

2) The core issue you seem to be reporting is that the camera is not operating when you would expect it to. Is the robot docked when this is happening? When the robot is docked it will enter power saver mode in which it will disable the camera and lidar. This behaviour can be changed here: https://github.com/turtlebot/turtlebot4_robot/blob/3d92a3f2b7ea889e198352322e231a7fab540dcf/turtlebot4_bringup/config/turtlebot4.yaml#L8 

If this addresses your concerns please close this issue, if not please provide the full journalctl logs (`sudo journalctl -u turtlebot4 -r`).

**Comment by kennyS99** [comment]
Hi Hillary,
I would like to express my sincere appreciation for your response. 
  1.Regarding my first question, I am still curious about the location within the launch file where the namespace is passed. Could you please provide a clearer explanation of where exactly the namespace is defined and passed in? Thank you for your assistance.

  2.It appears that you were right about my lack of knowledge regarding the robot's power saver mode when it is docked. I have another question regarding the config code you shared earlier. It seems that both the camera and lidar should be stopped. Should the lidar be mechanically stopped from spinning? 
However, I have noticed that the lidar continues rotating even when the robot is in power saver mode. I'm wondering if there is a coding solution that can be implemented to make the lidar stop rotating. 

Also I posted the full journalctl logs here for your information.
ubuntu@ubuntu:~$ sudo journalctl -u turtlebot4.service -r
Jun 16 16:03:05 ubuntu turtlebot4-start[961]: [turtlebot4_node-1] [INFO] [1686931385.413754663] [turtlebot4_node]: stop_motor service completed.
Jun 16 16:03:05 ubuntu turtlebot4-start[961]: [rplidar_composition-4] [INFO] [1686931385.412726237] [rplidar_composition]: Ingnoring stop_motor request because rplidar_node is in 'auto standby' mode
Jun 16 16:03:05 ubuntu turtlebot4-start[961]: [turtlebot4_node-1] [INFO] [1686931385.245456700] [turtlebot4_node]:
Jun 16 16:03:05 ubuntu turtlebot4-start[961]: [turtlebot4_node-1] [INFO] [1686931385.245332200] [turtlebot4_node]: oakd/stop_camera service got results: Success
Jun 16 16:03:05 ubuntu turtlebot4-start[961]: [turtlebot4_node-1] [INFO] [1686931385.219758608] [turtlebot4_node]: stop_motor service available, sending request
Jun 16 16:03:05 ubuntu turtlebot4-start[961]: [component_container-5] [INFO] [1686931385.219693682] [oakd]: Stopping camera.
Jun 16 16:03:05 ubuntu turtlebot4-start[961]: [turtlebot4_node-1] [INFO] [1686931385.218774533] [turtlebot4_node]: oakd/stop_camera service available, sending request
Jun 16 16:03:04 ubuntu turtlebot4-start[961]: [turtlebot4_node-1] [INFO] [1686931384.219135590] [turtlebot4_node]: RPLIDAR stopped
Jun 16 16:03:04 ubuntu turtlebot4-start[961]: [turtlebot4_node-1] [INFO] [1686931384.218246793] [turtlebot4_node]: OAKD stopped
-- Boot 91adb6c102d745debe9e99c9a7e051df --
Jun 14 11:56:06 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743766.332528590] [turtlebot4_node]:
Jun 14 11:56:06 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743766.332368931] [turtlebot4_node]: robot_power service got results: Failed
Jun 14 11:56:05 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743765.509935815] [turtlebot4_node]: robot_power service available, sending request
Jun 14 11:56:04 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [ERROR] [1686743764.509581644] [turtlebot4_node]: Power OFF
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.242234064] [oakd]: Camera already running!.
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.242107267] [oakd]: Starting camera.
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743762.234822515] [turtlebot4_node]:
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743762.234654081] [turtlebot4_node]: oakd/start_camera service got results: Success
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.234058396] [oakd]: Camera ready!
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.084769702] [oakd]: Finished setting up pipeline.
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.081355049] [oakd]: Pipeline type: RGB
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.077564002] [oakd]: Device type: OAK-D-LITE
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.054329764] [oakd]: USB SPEED: SUPER
Jun 14 11:56:02 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743762.052857825] [oakd]: Camera with MXID: 184430103124CB0F00 and Name: 1.1.1 connected!
Jun 14 11:56:00 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743760.326122592] [turtlebot4_node]: start_motor service completed.
Jun 14 11:56:00 ubuntu turtlebot4-start[4767]: [rplidar_composition-4] [INFO] [1686743760.324502269] [rplidar_composition]: Ingnoring start_motor request because rplidar_node is in 'auto standby' mode
Jun 14 11:56:00 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743760.143081619] [turtlebot4_node]: start_motor service available, sending request
Jun 14 11:56:00 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743760.143206769] [oakd]: No ip/mxid specified, connecting to the next available device.
Jun 14 11:56:00 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743760.142900910] [oakd]: Starting camera.
Jun 14 11:56:00 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743760.141990203] [turtlebot4_node]: oakd/start_camera service available, sending request
Jun 14 11:55:59 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743759.142104628] [turtlebot4_node]: RPLIDAR started
Jun 14 11:55:59 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743759.141769518] [turtlebot4_node]: OAKD started
Jun 14 11:51:09 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743469.559575810] [oakd]: Camera ready!
Jun 14 11:51:09 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743469.400358222] [oakd]: Finished setting up pipeline.
Jun 14 11:51:09 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743469.368578828] [oakd]: Pipeline type: RGB
Jun 14 11:51:09 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743469.364908810] [oakd]: Device type: OAK-D-LITE
Jun 14 11:51:09 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743469.337434281] [oakd]: USB SPEED: SUPER
Jun 14 11:51:09 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743469.334479432] [oakd]: Camera with MXID: 184430103124CB0F00 and Name: 1.1.1 connected!
Jun 14 11:51:07 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743467.372438709] [oakd]: No ip/mxid specified, connecting to the next available device.
Jun 14 11:51:07 ubuntu turtlebot4-start[4767]: [component_container-5] [WARN] [1686743467.268772517] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple>
Jun 14 11:51:07 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743467.265845211] [oakd_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camer>
Jun 14 11:51:07 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743467.265694566] [oakd_container]: Found class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
Jun 14 11:50:11 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743411.420708224] [turtlebot4_node]: stop_motor service completed.
Jun 14 11:50:11 ubuntu turtlebot4-start[4767]: [rplidar_composition-4] [INFO] [1686743411.419537266] [rplidar_composition]: Ingnoring stop_motor request because rplidar_node is in 'auto standby' mode
Jun 14 11:50:11 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743411.250742571] [turtlebot4_node]:
Jun 14 11:50:11 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743411.250618546] [turtlebot4_node]: oakd/stop_camera service got results: Success
Jun 14 11:50:11 ubuntu turtlebot4-start[4767]: [component_container-5] [INFO] [1686743411.222688574] [oakd]: Stopping camera.
Jun 14 11:50:11 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743411.221374415] [turtlebot4_node]: stop_motor service available, sending request
Jun 14 11:50:11 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743411.220450563] [turtlebot4_node]: oakd/stop_camera service available, sending request
Jun 14 11:50:10 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743410.220704511] [turtlebot4_node]: RPLIDAR stopped
Jun 14 11:50:10 ubuntu turtlebot4-start[4767]: [turtlebot4_node-1] [INFO] [1686743410.220367904] [turtlebot4_node]: OAKD stopped
Jun 14 11:49:31 ubuntu turtlebot4-start[4767]: [aggregator_node-9] [INFO] [1686743371.228140022] [AnalyzerGroup]: Group 'Turtlebot4' has a match with my analyzer '/Turtlebot4/Create3'.

**Comment by hilary-luo** [comment]
1. The namespace is passed down from standard.launch.py here: https://github.com/turtlebot/turtlebot4_robot/blob/3d92a3f2b7ea889e198352322e231a7fab540dcf/turtlebot4_bringup/launch/standard.launch.py#L36
Similarly it can be passed directly in the command line interface if there was a reason to launch this seperately.

2. It is possible to stop the lidar from spinning but it is not necessary. When launching the rplidar you can set auto_standby to false and I believe this should make the spinning line up with the service being started and stopped. Additionally you can manually turn it on and off. https://github.com/turtlebot/turtlebot4_robot/blob/3d92a3f2b7ea889e198352322e231a7fab540dcf/turtlebot4_bringup/launch/rplidar.launch.py#L34
