### ISSUE TITLE
Issues with TB4 navigation and MTR LED

### ISSUE THREAD

**Issue by nidia-bucarelli** [turtlebot/turtlebot4#196]
I am trying to run the robot navigation and i have several issues.

•	When I generate a high-resolution map using my remote PC (running ros-galactic) and then try the navigation, the robot gets stuck ( I can't move it using a joystick or publish velocity commands) MTR LED is off sometimes, other times its COMM LED, and sometimes both LEDs are off. I can still see the topics on my remote PC using "ros2 topic list". I get the following diagnostics: 
 
![image](https://github.com/turtlebot/turtlebot4/assets/112603498/73d4dcde-d824-4144-b418-1bb27491d652)

•	When I run the mapping and localization on the robot's onboard computer, the robot also gets stuck.  

•	When I use another laptop (running ros-humble) and try the navigation "ros2 launch turtlebot4_navigation nav2.launch.py" the robot gets stuck again. the COMM LED turns off and Diagnostics are as the following: 
 
![image](https://github.com/turtlebot/turtlebot4/assets/112603498/8bf35b9b-24bc-4f5a-9d12-edee694d55b0)

•	Sometimes the robot is not stuck at the previous step but when I insert a goal, the robot gets stuck, and MTR LED turns off.
•	Dock and undock actions from the HMI do not work. Neither do any action except turning on and off the LiDAR.
Overall, I am not sure why running navigation on the robot leads to COMM and MTR LED turning off and diagnostics showings issues with IMU and Wheels.

**Comment by hilary-luo** [comment]
Hello,

Can you please confirm the following information?

 - OS: (e.g. Ubuntu 20.04)
 - ROS Distro: (e.g. Galactic)
 - Built from source or installed:
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)
- Robot Model: (e.g. standard)
- Networking: (e.g. Discovery Server with FastDDS)

Can you please also replicate this situation and then provide the system logs from the Create3? https://iroboteducation.github.io/create3_docs/webserver/logs/

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
