### ISSUE TITLE
Turtlebot 4 Raspberry Pi not powered

### ISSUE THREAD

**Issue by languyen14507** [turtlebot/turtlebot4#198]
We received a new Turtlebot 4 from our customer. The RPi appears not powered. The FAQ document says to check the USB-C connection and make sure the Create 3 power adapter board is inserted fully. Is there a picture that shows what the USB-C connection and the Create 3 power adapter board look like and how do I get access to them?  Thanks.

https://github.com/turtlebot/turtlebot4/assets/12131715/0a821ddc-b053-4e6c-ae9f-e18366b67934

**Comment by hilary-luo** [comment]
The USB C connection is off the side of the raspberry pi board
![Optimized-raspberrypi](https://github.com/turtlebot/turtlebot4/assets/103377417/fa6f21bc-df55-4515-a7ed-4dae5e2060f2)

In order to clearly access the raspberry pi you will need to unscrew PCBA as directed here: https://turtlebot.github.io/turtlebot4-user-manual/mechanical/turtlebot4.html#removing-the-pcba

**Comment by languyen14507** [comment]
Hi Hilary, please see the photos below with explanations. What do I need to do next? Thanks.

![image](https://github.com/turtlebot/turtlebot4/assets/12131715/5744418a-6951-4fa2-b9f8-aa7418696018)
![image](https://github.com/turtlebot/turtlebot4/assets/12131715/21c99618-4dd3-47e3-8993-4dcef51faa91)

**Comment by hilary-luo** [comment]
Turn the robot off and remove the cargo bay
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/4b06e8dc-90be-48e5-9eb7-674bc8e771ec)

Looking in, you should be able to see the create3 user interface board. Remove the board and ensure that the cables are securely connected and then reinsert the board, making sure that it is fully inserted.
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/9ac90fc8-1a32-4fa2-80c4-367acfbd3760)

For reference, this is what the board looks like inserted without the cables. 
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/b1b5d940-298b-4048-a98d-62c106e3405d)

After doing this, power the robot up and ensure that the fan powers on and that the raspberry pi powers up.

**Comment by languyen14507** [comment]
That fixed it. Thank you very much.
