### ISSUE TITLE
Nav launch files are not in best practices, and will not use composition

### ISSUE THREAD

**Issue by SteveMacenski** [turtlebot/turtlebot4#2]
Please look over the current state of Nav2's launch files so that your users can use the best in Nav2 on Rolling. You do not want to copy-paste our launch files over. Instead, you want to make a launch file that launches Nav2's files with your custom configuration read-ins or additional nodes (like base, simulator, etc).

**Comment by roni-kreinin** [comment]
Is there a way to run async slam using the Nav2 launch files? I find the performance is much better on the RPI4 with async.

**Comment by SteveMacenski** [comment]
You can always swap out the localization launch file, but you shouldn't be overriding the navigation launch file -- only the highest level bringup which would include a localization launch include.
