### ISSUE TITLE
Changing iCreate 

### ISSUE THREAD

**Issue by nidia-bucarelli** [turtlebot/turtlebot4#201]
Can I change the base/iCreate of the TB4 with that one from the TB4 lite?
I tried to do so, but I don't know how to configure the iCreate. 

When I initially configured the iCreate for the TB4, I had to connect to the iCreate Wi-Fi and then do the configuration online. Tu turn on the Wi-Fi I had to pressed the two buttons. Then, a blue light showed up and i was able to see the iCreate Wi-Fi and access the iCreate webserver. 

I tried to do it now ,but when i pressed the two buttons it does not turn on the blue light nor the Wi-Fi shows up on my computer. I checked the starter guide, and I was not able to find these instructions (to connect to the iCreate Wi-Fi). I found the instruction below. But, I cannot access the webserver. 
Any feedback will be appreciated!
Thanks!
![image](https://github.com/turtlebot/turtlebot4/assets/112603498/4bb6bcf0-1d31-4ce3-9aaa-8dfe84fe0af6)

**Comment by hilary-luo** [comment]
To directly connect to the the create3 without setting up through the raspberry pi, please see the instructions here: https://edu.irobot.com/create3-setup on how to update the robot. 

Ensure that the robot is fully booted up (solid white light) and then that you are holding the buttons down for several seconds.

**Comment by nidia-bucarelli** [comment]
thanks
