### ISSUE TITLE
The camera's connectivity varies depending on the USB port.

### ISSUE THREAD

**Issue by rhyeonwoo** [turtlebot/turtlebot4#203]
- OS: 22.04
 - ROS Distro: Humble
 
Please refer to this link at   `https://github.com/turtlebot/turtlebot4/issues/171` 

If I connect the camera USB to USB 2.0, there is no problem. However, it does not work when I connect the camera to USB 3.0.

Other Turtlebot standard models are available on 3.0 ports without problems.
However, the camera doesn't come out data of this turtlebot standard. Two 3.0 ports on the Raspberry Pi are fine, and the cable on the camera is fine.
 (I connected the cable and camera to my laptop, and it worked well)

Is it okay to connect the camera port to 2.0 and use it? If not, is there another solution?

**Comment by hilary-luo** [comment]
You can connect the camera using USB 2.0 port if you like. 

If you would like to continue troubleshooting this then please try connecting that camera to a different raspberry pi and the camera from a different robot to this raspberry pi and test both. This will allow us to verify if the camera is causing the issue or the raspberry pi.

**Comment by rhyeonwoo** [comment]
Thank you for your answer.
I checked what you said to solve the problem.
I've tried a lot of different ways, and the camera in question works fine on other raspberry pies, but only on the same robot's raspberry pies works fail.
Connecting a camera from another robot works fine at 3.0 ports.
If this happens, can we check more if there are any other problems? Is there a way you know?

**Comment by hilary-luo** [comment]
Can you please clarify, when you say 

> Connecting a camera from another robot works fine at 3.0 ports.

Do you mean that if you connect a camera from a working robot to the 3.0 port of the raspberry pi that is having the problem, that the camera works?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
