### ISSUE TITLE
Rviz2; unable to run Nav

### ISSUE THREAD

**Issue by llyf-s** [turtlebot/turtlebot4#204]
**Please provide the following information:**
 - OS: Ubuntu 22.04 
 - ROS Distro: Humble
 - Built from source or installed: Installed

 **Expected behaviour**
To run Rviz2, and able to do navigation. 

 **Actual behaviour**
 Rviz2 able to run, but unable to do certain activities 
 

**To Reproduce**
Provide the steps to reproduce:
1. Run Rviz2 navigation 

Issue stated with PluginlibFactory:

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2023-06-22-18-42-55-949622-ubuntu-desktop-5568
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [5569]
[rviz2-1] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[rviz2-1] [INFO] [1687430578.486844014] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1687430578.487395385] [rviz2]: OpenGl version: 2.1 (GLSL 1.2)
[rviz2-1] [INFO] [1687430578.612137181] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [ERROR] [1687430578.931765348] [rviz2]: **PluginlibFactory: The plugin for class 'nav2_rviz_plugins/ParticleCloud' failed to load.** Error: According to the loaded plugin descriptions the class nav2_rviz_plugins/ParticleCloud with base class type rviz_common::Display does not exist. Declared types are  rviz_default_plugins/Axes rviz_default_plugins/Camera rviz_default_plugins/FluidPressure rviz_default_plugins/Grid rviz_default_plugins/GridCells rviz_default_plugins/Illuminance rviz_default_plugins/Image rviz_default_plugins/InteractiveMarkers rviz_default_plugins/LaserScan rviz_default_plugins/Map rviz_default_plugins/Marker rviz_default_plugins/MarkerArray rviz_default_plugins/Odometry rviz_default_plugins/Path rviz_default_plugins/PointCloud rviz_default_plugins/PointCloud2 rviz_default_plugins/PointStamped rviz_default_plugins/Polygon rviz_default_plugins/Pose rviz_default_plugins/PoseArray rviz_default_plugins/PoseWithCovariance rviz_default_plugins/Range rviz_default_plugins/RelativeHumidity rviz_default_plugins/RobotModel rviz_default_plugins/TF rviz_default_plugins/Temperature rviz_default_plugins/Wrench
[rviz2-1] [ERROR] [1687430579.370703440] [rviz2]: **PluginlibFactory: The plugin for class 'nav2_rviz_plugins/GoalTool'** failed to load. Error: According to the loaded plugin descriptions the class nav2_rviz_plugins/GoalTool with base class type rviz_common::Tool does not exist. Declared types are  rviz_default_plugins/FocusCamera rviz_default_plugins/Interact rviz_default_plugins/Measure rviz_default_plugins/MoveCamera rviz_default_plugins/PublishPoint rviz_default_plugins/Select rviz_default_plugins/SetGoal rviz_default_plugins/SetInitialPose

**Comment by hilary-luo** [comment]
Can you please clarify in your steps to reproduce, exactly what command you are using to launch rviz and navigation?

Additionally, can you verify that you have ros-humble-turtlebot4-navigation installed? If you don't, install that (`sudo apt install ros-humble-turtlebot4-navigation`). If you do have it, then try running `sudo apt install ros-humble-nav2-rviz-plugins`
