### ISSUE TITLE
Unable to connect to Turtlebot4

### ISSUE THREAD

**Issue by NitishVemuri** [turtlebot/turtlebot4#205]
Hello,

Following the basic setup tutorials, I configured TB4. 
However, while connecting the Raspberry Pi to my school WiFi network (which typically consists of SSID, username and password), since there is no provision for username in the command **sudo wifi.sh -s '<WIFI_SSID>' -p '<WIFI_PASSWORD>' -r <REGULATORY_DOMAIN> && sudo reboot**, i skipped username.
Further, I connected create3 in the same process as the Raspberry Pi.

After successful completion of installation steps, I observed the IP address on Turtlebot4 is still 10.42.0.1.
I see the solid green light if I lift the robot. Also, I could see Cyan. I attached the images.
I am not sure if turtlebot4 is not properly configured to my school network. 
Now, could you please help to reconfigure and connect Turtlebot4 to different network.

![IMG_20230620_125624](https://github.com/turtlebot/turtlebot4/assets/104766905/cbcaf0b5-932a-43d7-aa12-4eaa0811ca89)
![IMG_20230620_125305](https://github.com/turtlebot/turtlebot4/assets/104766905/29396b3f-38ff-468a-a567-235ab7b67316)

**Comment by hilary-luo** [comment]
Please connect and ssh into the raspberry pi (https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#recovering-the-raspberry-pi). Then follow the instructions here on how to connect it to your school network: https://netplan.readthedocs.io/en/stable/examples/#how-to-connect-to-wpa-enterprise-wireless-networks-with-eap-ttls 

You do need to set it up with the SSID, username and password. The additional security on this type of network may interfere with ROS 2 communication. If you want to try to set up ROS 2 communication over this network (between devices) then ensure to choose the discovery server option (https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html). Alternatively, get a router to set up a local network for ros 2 communications.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.

**Comment by HiWiQiao** [comment]
I have the same problem, but when I follow (https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#recovering-the-raspberry-pi), the terminal outputs "No route to host"

**Comment by judy33a** [comment]
@HiWiQiao how did you manage to solve the problem? i have the same issue and it is blocking my work
