### ISSUE TITLE
NTP config for Create 3

### ISSUE THREAD

**Issue by roni-kreinin** [turtlebot/turtlebot4#216]
**** UPDATE: Please do not apply this change on the latest Humble or Jazzy software. This is now handled automatically by the software ****

With the release of G.5.1 and H.2.1 firmware for Create 3, iRobot added the option to manually edit the `ntp.conf` file of the Create 3. This will allow us to set the RPi4 as the ntp server for the Create 3, which should improve time synchronisation between the two.

Here is a ntp config that sets the RPi as the preferred time server:

```
# Use RPi4 as preferred server
# Minpoll 2^4 = 16s
# Maxpoll 2^6 = 64s
server 192.168.186.3 prefer iburst minpoll 4 maxpoll 6
```

To use the config, [update your Create 3](https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#create-3) to G.5.1 for Galactic, or H.2.1 for Humble. Then, access the Create 3 webserver and navigate to **Beta Features** -> **Edit ntp.conf**. Replace the contents of `ntp.conf` with the configuration above and click save. Then click on **Beta Features** -> **Restart ntpd** for the changes to take effect. 

If this fixes your issues with time synchronisation, or you find a better configuration, please let us know!

Related issues:

- https://github.com/turtlebot/turtlebot4/issues/188
- https://github.com/turtlebot/turtlebot4/issues/176
- https://github.com/turtlebot/turtlebot4/issues/166
- https://github.com/turtlebot/turtlebot4/issues/141

**Comment by brianabouchard** [comment]
Thanks, @roni-kreinin. This definitely improved my experience with mapping.

**Comment by WaitingForAll** [comment]
@roni-kreinin thank you very much! I updated the Create3 according to your explenations, but could't test the performance just yet, while running SLAM or navigating.  I will do so tomorrow.

So far I can say that there are no more npt errors in the Create 3 logs.

**Comment by royito55** [comment]
Lately I've been getting this warning in the Create3 with this NTP config:

`user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.002502 is too high, ignoring`

I assume that this is because of the `ntp.conf` in the RPi4? Because I don't understand how there could be a high delay with a usb-c connection otherwise. 

Did anyone have to do anything special on the Pi side?

**Comment by ValkyrX** [comment]
i g et this error as well regarding it being to high ? only thing that fixes it for me is reboot create 3, its not a fix though as if i restart ntp again it appears again

**Comment by WaitingForAll** [comment]
> @roni-kreinin thank you very much! I updated the Create3 according to your explenations, but could't test the performance just yet, while running SLAM or navigating. I will do so tomorrow.
> 
> So far I can say that there are no more npt errors in the Create 3 logs.

Unfortunately, when I tested it, I encountered the same problems which @royito55  and @ValkyrX  have. Strangely, I now also get the npt error:
```
user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.002960 is too high, ignoring
```

I guess this also results in the following error while trying to navitagate:
```
[amcl-2] [INFO] [1690288848.143789419] [amcl]: Message Filter dropping message: frame 'rplidar_link' at time 1690288847.140 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
```

**Comment by roni-kreinin** [comment]
I see the "delay is too high" warnings as well, but they are sporadic. I don't believe they are causing the timing issues. The ntp server attempts to adjust time at small increments to prevent clock issues on the system, so if time difference is too high it will ignore it. 

@WaitingForAll The timestamps from the `rplidar_link` log show a difference of nearly 1 second, so its likely caused by something else.

**Comment by royito55** [comment]
It's still strange that the high delay even happens though, since that means that the response from the server in the pi takes too long, even if it's doing it through `usb0`? My intuition tells me that a response through a physical cable would be quicker than something wireless like having an ubuntu server in the config.

**Comment by imstevenpmwork** [comment]
Any updates in here? I'm experiencing a similar issue even after editing the ntp config. Using humble, cyclonedds and Firmware Version: H.2.3, when I try to launch turtlebot4_navigation localization.launch.py I get exactly the same as @WaitingForAll (https://github.com/turtlebot/turtlebot4/issues/216#issuecomment-1649777666). In addition, I get these crate logs:
```
(...)
Oct 10 12:56:19 my-iRobot user.notice ntpd: ntpd: timed out waiting for 192.168.186.3, reach 0x7e, next query in 32s
Oct 10 12:56:20 my-iRobot user.notice create-platform: 1696942580.292144 [9]        tev: ddsi_udp_conn_write to udp/239.255.0.1:9650 failed with retcode -1
(...)
Oct 10 12:59:00 my-iRobot user.notice create-platform: 1696942740.299182 [9]        tev: ddsi_udp_conn_write to udp/239.255.0.1:9650 failed with retcode -1
Oct 10 12:59:07 my-iRobot user.notice create-platform: [INFO] [1696942747.098119488] [system_health]: CPU usage: max 100 [%] mean 69 [%] RAM usage: 35/59 [MB]
Oct 10 12:59:08 my-iRobot user.notice create-platform: 1696942748.299258 [9]        tev: ddsi_udp_conn_write to udp/239.255.0.1:9650 failed with retcode -1
(...)
Oct 10 13:02:24 my-iRobot user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.002847 is too high, ignoring
Oct 10 13:02:30 my-iRobot user.notice create-platform: 1696942950.404833 [9]        tev: ddsi_udp_conn_write to udp/239.255.0.1:9650 failed with retcode -1
```
It seems to be the case also in here: https://github.com/turtlebot/turtlebot4/issues/255#issuecomment-1706774910

**Comment by hilary-luo** [comment]
@imstevenpmwork I believe your issue is not directly a time sync issue. Those create3 messages suggest that the network interface isn't set up or connected properly. I would suggest verifying to make sure that the create3 is successfully connecting to the internet and is being assigned an IP address. And then make sure that it and the turtlebot are correctly set up for cycloneDDS. If this doesn't work please open a separate ticket and we can discuss more in depth there.

**Comment by adnan-saood** [comment]
I am facing the same behavior with my TB4, I added an NTP server in my work network and also the RPI to the ntpd config file, but both are not accepted by the create 3 computer. 

```
Nov 14 11:59:15 iRobot user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.002467 is too high, ignoring

Nov 14 12:00:19 iRobot user.notice ntpd: ntpd: reply from 137.194.2.95: delay 0.010215 is too high, ignoring
``` 

I suspect that this time syncing issue is what causing my localization to by like this:


![ezgif-1-e8f2870a02](https://github.com/turtlebot/turtlebot4/assets/22562330/d1fd5db0-e34e-469f-956c-440a19758fa7)

**Comment by roni-kreinin** [comment]
@adnan-saood What is your networking configuration for the turtlebot? Are you using simple discovery with the Create 3 connected on the network?

Also, if you are using an NTP server, don't configure the Create 3 to use that and the RPi as its ntp server. Configure both the RPi and Create3 to use just your NTP server so that their clocks sync.

**Comment by schenkch** [comment]
Is there a way of turning off turtlebot4_diagnostic in galactic as well?
