### ISSUE TITLE
Lidar issue 

### ISSUE THREAD

**Issue by MathisGodard** [turtlebot/turtlebot4#220]
The affected TurtleBot seems to have a malfunctioning LiDAR. The motor rotates the LiDAR when the robot is turned on, and the motor can be turned on and off through the interface on the TurtleBot and the ROS2 service. When it is turned off, as expected, no data is published on the ROS2 topic /scan. However, when the motor is turned on, no meaningful measurement values are published; instead, all distances are indicated as ".inf" (see attached file TB_Reklamation_ROS.png). To rule out a software problem, we also tested directly with the Slamtec SDK (TB_Reklamation_SimpleGrabber.png and TB_Reklamation_SimpleGrabber2.png). The SDK also did not provide any meaningful data (every distance was exactly 0). Therefore, we believe that a hardware failure in the LiDAR is the issue (possibly the laser is not functioning correctly?).

Regarding the serial number, we are not exactly sure where we can find it. Is RCI3099J220124N101017 the correct serial number? If not, where can we find the number?

<img width="326" alt="TB_Reklamation_ROS" src="https://github.com/turtlebot/turtlebot4/assets/39947894/7e7dc5f4-cd1a-48a8-a0c1-005d0f4481a0">
<img width="326" alt="TB_Reklamation_SimpleGrabber2" src="https://github.com/turtlebot/turtlebot4/assets/39947894/0ebf8312-dfb7-44c9-9813-60b1f12b36e5">
<img width="326" alt="TB_Reklamation_SimpleGrabber" src="https://github.com/turtlebot/turtlebot4/assets/39947894/11e1d0c1-21b8-4954-a5ae-9f81726c53d6">

Best regards, Mathis.

**Comment by hilary-luo** [comment]
Hi Mathis, I am sorry to hear about these hardware troubles. Please contact [support@clearpathrobotics.com](mailto:support@clearpathrobotics.com) to have this issue addressed.
