### ISSUE TITLE
Static IP for multiple Create 3 robots

### ISSUE THREAD

**Issue by MikeDegany** [turtlebot/turtlebot4#223]
I would like to establish a static IP configuration for multiple Create 3 robots. This would ensure consistent and reliable connectivity for each robot. Could you please provide guidance on how to set up a static IP configuration for Create 3 robots?

**Comment by Jayden-F** [comment]
Hello @MikeDegany,

If you are using the Humble install, you can set a static IP address by:
- Use SSH to connect to the turtlebot 4 raspberry pi.
- run `turtlebot4-setup` .
- navigate to Wi-Fi Setup.
- Enter the your static IP Address and set DHCP to False.
- Finally save the settings and apply the settings. 

You can find more information in the turtlebot4 documentation.
https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html

**Comment by MikeDegany** [comment]
@Jayden-F  This only sets a static IP for RPi. I'd like to set a static IP for Create3.

**Comment by Jayden-F** [comment]
Yeah, you're out of luck. The create3 is never a fun time.

**Comment by hilary-luo** [comment]
Feel free to create an issue on the [create3 docs](https://github.com/iRobotEducation/create3_docs/issues) if you need additional information about the create3 base.

**Comment by m-usama-z** [comment]
Hi. I've been unable to move the TurtleBot 4 by sending twist messages to /cmd_vel after configuring a static IP address, even though /cmd_vel appears in the topic list. Can anyone kindly advise about this? Thank you very much.

**Comment by m-usama-z** [comment]
I figured it out: the robot has to be restarted after changing Wi-Fi settings, in order to move it. Would be nice for this to be mentioned in the user manual, and would be even nicer if this, or an alternative solution, were implemented to be executed automatically upon Wi-Fi reconfiguration :)

**Comment by pvg6** [comment]
If we set the static ip to raspberrypi ,. it will connect to the access point ssh ubuntu@192.168.185.3


I am unable to connect to ssh ubuntu@192.168.185.3. I want to connect to this to reset my ip how to do it....

@MikeDegany
