### ISSUE TITLE
Unable to connect to Turtlebot4

### ISSUE THREAD

**Issue by HiWiQiao** [turtlebot/turtlebot4#225]
Hello,

Following the basic setup tutorials, I configured TB4.
However, while connecting the Raspberry Pi to my school WiFi network (which typically consists of SSID, username and password), since there is no provision for username in the command sudo wifi.sh -s '<WIFI_SSID>' -p '<WIFI_PASSWORD>' -r <REGULATORY_DOMAIN> && sudo reboot, i skipped username.
Now my bot's lights and display don't light up at all and I can't ssh into the bot terminal, here's a screenshot of what I have.
I follow (https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#recovering-the-raspberry-pi), the terminal outputs "No route to host"
<img width="710" alt="截屏2023-07-18 15 25 24" src="https://github.com/turtlebot/turtlebot4/assets/131516469/35022d6d-0db1-452b-86f4-520acac7b52f">

what should I do?

**Comment by hilary-luo** [comment]
When you try to do the steps to recovering the pi and are wired into it, are you able to ping the raspberry pi?

It looks like the raspberry pi and PCBA may have lost power. Please verify that the [usb c cable is plugged into the raspberry pi securely](https://github.com/turtlebot/turtlebot4/issues/198#issuecomment-1598076029) and that the[ create3 user interface board is securely inserted](https://github.com/turtlebot/turtlebot4/issues/198#issuecomment-1599457193). The raspberry pi has a power led that should be on if it has power.

If the raspberry pi is powered then you should be able to ssh over a wired connection to recover it and follow the instructions [here](https://github.com/turtlebot/turtlebot4/issues/205#issuecomment-1608206531) for connecting to wifi networks that require a username.

**Comment by HiWiQiao** [comment]
I can Ping the raspberry pi per Lan label, but the light and display do not light. it looks not good!

**Comment by hilary-luo** [comment]
I would suggest that you reimage the pi and start fresh. The instructions on how to image the pi are found here: https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image

Make sure that you choose the right image (standard turtlebot and either humble or galactic). When you get back around to setting up your wifi ensure that you are using the correct method for the chosen ROS 2 distribution. The wifi script you mentioned is only for galactic, if you are using humble then use the turtlebot4-setup tool.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
