### ISSUE TITLE
Powersave issue

### ISSUE THREAD

**Issue by ValkyrX** [turtlebot/turtlebot4#228]
I have noticed that when power saving is activated that when the robot boots the lidar and camera are off, which is good, and they start when undocking, ok so far so good, however when i redock the robot the camera seems to power off but the lidar doesn't stop spinning ? is this expected or should it stop ?

Thanks
Kurt

**Comment by hilary-luo** [comment]
Hi Kurt, 

If there is something still subscribed to the lidar /scan topic then it will continue running.

**Comment by ValkyrX** [comment]
How do i tell if somethings subscribed, i mean it runs even from a reboot so unless something subscribes on startup then im not sure what it could be

**Comment by hilary-luo** [comment]
You can tell if something is subsribed by calling `ros2 topic info /scan`. That being said, I am seeing a similar issue. Can you confirm
1) what robot type you are running (standard vs lite)
2) which turtlebot4-robot software package you are running (e.g. Humble 1.0.1-1jammy.20230728.162203)
3) what version of rplidar-ros that you are running (e.g. 2.1.3-3jammy.20230724.202913)

**Comment by ValkyrX** [comment]
still an issue, answer to above 
1 = lite
2 = humble
3 = as in prvious post

**Comment by hilary-luo** [comment]
@ValkyrX Can you confirm if this issue is resolved in the latest update of the rplidar driver?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
