### ISSUE TITLE
Can't see oakd topics on turtlebot4

### ISSUE THREAD

**Issue by halimimaha** [turtlebot/turtlebot4#237]
Please consider the following information :

OS: Ubuntu 22.04 LTS
ROS Distro: ROS2 humble

Expected behaviour:
All of the topics should appear, including the create3 topics 

/parameter_events
/raphael/battery_state
/raphael/cmd_audio
/raphael/cmd_lightring
/raphael/cmd_vel
/raphael/color/preview/image
/raphael/diagnostics
/raphael/diagnostics_agg
/raphael/diagnostics_toplevel_state
/raphael/dock_status
/raphael/function_calls
/raphael/hazard_detection
/raphael/hmi/buttons
/raphael/hmi/display
/raphael/hmi/display/message
/raphael/hmi/led
/raphael/imu
/raphael/interface_buttons
/raphael/ip
/raphael/ir_intensity
/raphael/ir_opcode
/raphael/joint_states
/raphael/joy
/raphael/joy/set_feedback
/raphael/kidnap_status
/raphael/mobility_monitor/transition_event
/raphael/mouse/raphael/oakd/rgb/preview/camera_info 
/raphael/oakd/rgb/preview/image_raw 
/raphael/oakd/rgb/preview/image_raw/compressed 
/raphael/oakd/rgb/preview/image_raw/compressedDepth 
/raphael/oakd/rgb/preview/image_raw/theora
/raphael/odom
/raphael/robot_description
/raphael/robot_state/transition_event
/raphael/scan
/raphael/slip_status
/raphael/static_transform/transition_event
/raphael/stereo/depth
/raphael/stop_status
/raphael/tf
/raphael/tf_static
/raphael/wheel_status
/raphael/wheel_ticks
/raphael/wheel_vels
/rosout

Actual behaviour :
Every topic appears except for the oakd topics

/parameter_events
/raphael/battery_state
/raphael/cmd_vel
/raphael/color/preview/image
/raphael/diagnostics
/raphael/diagnostics_agg
/raphael/diagnostics_toplevel_state
/raphael/dock_status
/raphael/function_calls
/raphael/hazard_detection
/raphael/hmi/buttons
/raphael/hmi/display
/raphael/hmi/display/message
/raphael/hmi/led
/raphael/imu
/raphael/interface_buttons
/raphael/ip
/raphael/joint_states
/raphael/joy
/raphael/joy/set_feedback
/raphael/mouse
/raphael/robot_description
/raphael/scan
/raphael/stereo/depth
/raphael/tf
/raphael/tf_static
/raphael/wheel_status
/rosout

I encountered an additional issue during my investigation. Initially, the OAKD camera node operates correctly when the robot starts, but it unexpectedly stops running after a few seconds. 

Also when i launch : ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py namespace:=/raphael
I have this error : 
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2023-08-03-11-49-11-643568-ubuntu-1646
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [1659]
[component_container-1] [INFO] [1691063352.974123593] [raphael.oakd_container]: Load Library: /opt/ros/humble/lib/libdepthai_ros_driver.so
[component_container-1] [INFO] [1691063353.500132115] [raphael.oakd_container]: Found class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
[component_container-1] [INFO] [1691063353.502785091] [raphael.oakd_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
[component_container-1] [INFO] [1691063353.644790159] [oakd]: No ip/mxid specified, connecting to the next available device.
[component_container-1] [INFO] [1691063356.570299461] [oakd]: Camera with MXID: 18443010A145BC0800 and Name: 1.1.2 connected!
[component_container-1] [INFO] [1691063356.576222162] [oakd]: USB SPEED: SUPER
[component_container-1] [INFO] [1691063356.600231646] [oakd]: Device type: OAK-D-PRO
[component_container-1] [INFO] [1691063356.606219476] [oakd]: Pipeline type: RGBD
[ERROR] [component_container-1]: process has died [pid 1659, exit code -11, cmd '/opt/ros/humble/lib/rclcpp_components/component_container --ros-args -r __node:=oakd_container -r __ns:=/raphael'].

**Comment by hilary-luo** [comment]
The Oakd camera will not be active while the robot is docked (power saving functionality). It will initally launch and then stop until the robot is undocked. Can you confirm that your robot is undocked?

**Comment by halimimaha** [comment]
Thank you so much for your response and your help ! 
Yeaah my robot was undocked that what surprised me a bit, but I fix the problem by switching from rmw_fastrtps_cpp to rmw_cyclonedds_cpp in RMW_IMPLEMENTATION in Create® 3 webserver. 
It is normal ? is this make sense ?
Thank you so much in advance !!

**Comment by hilary-luo** [comment]
I am glad to hear that your system is now working. It does not make sense to me that switching the DDS vendor would fix the issue so perhaps something else got rectified in the process.
