### ISSUE TITLE
Question about obstacle avoidance

### ISSUE THREAD

**Issue by abhinavsagar** [turtlebot/turtlebot4#238]
Hi, I don't know if this is the correct place to ask so please excuse me if it is not. Nav2 automatically avoids obstacles. My goal is to make it work such that it avoids all obstacles except one like a person's face. I would like the robot to goal to that obstacle and stop at some threshold distance rather than avoid it. It would be great if anyone can guide me on how to solve this task.

**Comment by hilary-luo** [comment]
Hi @abhinavsagar,

The most appropriate place for this question and discussion is on [ROS Answers](https://answers.ros.org/questions/).
