### ISSUE TITLE
Has there ever been a proper gui developed for turtlebot4 ?

### ISSUE THREAD

**Issue by ValkyrX** [turtlebot/turtlebot4#240]
As the question states really, has anyone ever made (apart from foxglove that cant send messages back to tb) a gui that you can view camera on webpage etc and also be able to navigate and set routes ?

Thanks

**Comment by hilary-luo** [comment]
@ValkyrX I don't believe there is currently any gui specifically for turtlebot4. There are standalone GUI tools such as rviz and foxglove that can be used for specific functionality. It is definitely possible, feel free to share anything that you come across. It is possible to put something together although it is currently not a priority for us. 

In terms of just being able to send messages / set routes, I would encourage you to look at the [example turtlebot4 navigator python code](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/turtlebot4_navigator.html). You should be able to combine the logic here with a basic python gui framework to build something specific for your application.
