### ISSUE TITLE
TB4 Controller Power Issues.

### ISSUE THREAD

**Issue by rhyeonwoo** [turtlebot/turtlebot4#243]
Hello.
There are multiple TB4s, but one controller does not turn on.
Therefore, we connected a well-functioning controller to TB4 on a non-functioning controller and made sure that TB4 was OK.

TB4 on a non-functioning controller is working fine, so it seems that only the controller has a problem.

I thought it might not turn on because it's not charging, but it doesn't turn on even if I fully charge it.
I tried pressing the home button and pairing button but it didn't work.

Is there any other way to try?

**Comment by hilary-luo** [comment]
Please try pressing the reset button on the back for several seconds and see if that resolves the issue. If not please contact customer support at support@clearpathrobotics.com

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
