### ISSUE TITLE
Multiple Turtlebot4 setup with Discovery Server

### ISSUE THREAD

**Issue by umar788** [turtlebot/turtlebot4#244]
We are using:

1. 3 Turtlebot4 standard
2. User PC with Ubuntu 22.04 and ROS2 Humble
3. Turtlebot4 RPI has Ubuntu 22.04 server and ROS2 Humble (latest version from [http://download.ros.org/downloads/turtlebot4/])
4. Create3 with H2.2 latest firmware

We are using Discovery Server network configuration with FASTDDS. I tried to set up robots using Simple Discovery but failed. Create3 kept losing internet, robot hardly moved and the 'comm' light turned on after restarting both create3 and RPi 2-3 times with Simple Discovery. Tried to use the restart ntpd service from the create3 webserver and it hardly made any difference. The Discovery Server has much better performance. Each robot is set up with a unique static IP and ROS_DOMAIN_ID but we have only set up one of the robot with user PC. 

We are confused about the set up for multiple robots with Discovery Server. According to my understanding, we can make a separate setup file for each robot with a unique discovery setting in turtlebot4_setup workspace. But is it really possible as adding multiple ip routes is quite complex and we will need three different ip routes for three robots. Can anyone guide us on how to solve this issue? Or if there is any other way we can use to control multiple robots running Discovery Server?

Please feel free to comment, discuss and ask any further information. 

Thank you.

**Comment by MikeDegany** [comment]
Discovery server does not support multiple robots. You may want to check out [145](https://github.com/turtlebot/turtlebot4/issues/145)
