### ISSUE TITLE
Adding smoother plugin to turtlebot4 

### ISSUE THREAD

**Issue by ghost** [turtlebot/turtlebot4#249]
I am working on turtlebot4.
I created a world and vizualized in rviz2. I am working on navigation. I want to test various [smoother](https://navigation.ros.org/plugins/index.html#smoothers) plugins.

How to get a nav2_param.yaml file for turtlebot4 to add various plugins.

**Comment by hilary-luo** [comment]
The various default nav2 configs can be found here: https://github.com/turtlebot/turtlebot4/tree/humble/turtlebot4_navigation/config
