### ISSUE TITLE
Why can't Turtlebot4 Lite raspberry Pie 4 automatically start the rplidar and camera after entering the system?

### ISSUE THREAD

**Issue by ddwy** [turtlebot/turtlebot4#25]
Why can't Turtlebot4 Lite raspberry Pie 4 automatically start the rplidar and camera after entering the system?

**Comment by roni-kreinin** [comment]
Can you expand further? The RPLIDAR and camera nodes should both be running on boot if you are using the standard TurtleBot 4 image.

**Comment by EndlessLoops** [comment]
Is it the newest lite and standard's image in this [link](http://download.ros.org/downloads/turtlebot4/)?And how to set running the rplidar and camera on boot when I use the TB4 lite ? I found In the TB4 lite it alway run the turtlebot4.service after boot,but it can't run normally the lidar and camera.

**Comment by roni-kreinin** [comment]
0.1.2 is the latest image. Can you call `sudo journalctl -u turtlebot4.service -r -n 1000 --no-pager` and send over the logs from the `turtlebot4` service?

**Comment by EndlessLoops** [comment]
I will install the latest lite image and test it.
