### ISSUE TITLE
Unable to launch gazebo and rviz of maze world from terminal.

### ISSUE THREAD

**Issue by ghost** [turtlebot/turtlebot4#250]
am working on maze world. I want to implement nav2. I changed world world. I am giving world , map paths from terminal. 
 `ros2 launch turtlebot4_ignition_
[Screencast from 08-18-2023 11:28:29 AM.webm](https://github.com/turtlebot/turtlebot4/assets/51513859/af01ca99-f252-4d85-ac3c-1d2dcfaa57cf)

bringup turtlebot4_ignition.launch.py nav2:=true slam:=false localization:=true rviz:=true world:=src/simulation/xml/maze map:=src/simulation/xml/maze.yaml `

**Comment by hilary-luo** [comment]
@vamsi1961 Every time you enter an issue please use the provided templates and fill in the following information:

OS: (e.g. Ubuntu 20.04) 
ROS Distro: (e.g. Galactic) 
Built from source or installed: 
Package version: (if from repository, give version from sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE, if from source, give commit hash)

And then please provide a clear problem statement of what you tried and what the specific problem is. From the video it seems like you did launch both the gazebo and rviz for the maze world.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
