### ISSUE TITLE
ROS change suggestion

### ISSUE THREAD

**Issue by Hanbali11** [turtlebot/turtlebot4#251]
**Please provide the following information:**
 - OS: (. Ubuntu 22.04)
 - ROS Distro: (. HUMBLE)
 - Built from source 
 

 

My turtlebot4 lite working on 20.04 and it was doing good i was able to drive it through laptop keyboard but after upgrade to 22.04 and remove **galactic** Ros the system won't be able to identify the Ros system downloaded which is humble please i want your recommendation if its good idea to format the SD card and  download Ubuntu 20.04 again with galactic or re-download Ubuntu 22.04lts with humble any other suggestion would be appreciated 

Best regards
Ahmed

**Comment by hilary-luo** [comment]
Hi @Hanbali11,

Can you please confirm that you upgraded both the turtlebot _and_ your laptop to run 22.04 and ROS 2 Humble. If not, please update your laptop as well (or use a VM or docker container running Humble). 

How did you go about updating the turtlebot? Did you use the images provided? if not please try again using the [instructions and the provided image for Turtlebot Lite Humble](https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image)

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
