### ISSUE TITLE
Comm and battery LEDs do not turn on

### ISSUE THREAD

**Issue by Saurabh0325** [turtlebot/turtlebot4#252]
I am facing problems while performing  localization and Navigation. So I tried to use Discovery server after reading similar issues (https://github.com/turtlebot/turtlebot4/issues/246#issuecomment-1691845610). 
But it also didn't work for me. So I tried to switch back to simple discovery and now comm and batt LED do not turn on. Also I cannot control my robot using controller. On the robot display i can move up and down to toggle through the options but I cannot choose any of them. 
For switching back to simple discovery  I changed Discovery server in 'bash setup' in turtlebot4-setup to Enabled [false].
![IMG_20230825_143520](https://github.com/turtlebot/turtlebot4/assets/127971127/b2ee7ade-92b8-4fa2-81ce-48f5eee93ed7)

**Comment by hilary-luo** [comment]
Can you please clarify:

OS: (e.g. Ubuntu 20.04)
ROS Distro: (e.g. Galactic)
Built from source or installed:
Package version: (if from repository, give version from sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE, if from source, give commit hash)

It doesn't sound like you reverted from Discovery Server properly, but the details on how to fix it will depend on what Distro that you are running. If you provide more details about the core issues that led you to try discovery server then we can also discuss if troubleshooting the discovery server setup is worthwhile vs reverting to simple discovery.

**Comment by Saurabh0325** [comment]
I am working with
os: ubuntu 22.04.03
ROS2: Humble
Installed: "sudo apt install ros-humble-turtlebot4-desktop"

I am working on navigation using an external map that I have created using slam. I get these errors in the logs.


In localisation: frame 'rplidar_link' at time 1692872352.998 for reason 'the timestamp on the message is earlier than all the data in the transform cache'


[rviz2-1] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist



when I launch localisation and navigation launch files I need to wait for 5-10 minutes for tf tree to show map and odom as well.
and cost map also takes this much time to load.

And after I give a nav goal point the robot turns and then nothing happens and the log is like this in navigation.




[bt_navigator-5] [INFO] [1692872679.972808500] [bt_navigator]: Begin navigating from current location (0.59, 0.12) to (0.07, 0.86)
[bt_navigator-5] [WARN] [1692872680.013463789] [bt_navigator_navigate_to_pose_rclcpp_node]: Timed out while waiting for action server to acknowledge goal request for follow_path
[bt_navigator-5] [WARN] [1692872680.033798913] [bt_navigator_navigate_to_pose_rclcpp_node]: Node timed out while executing service call to local_costmap/clear_entirely_local_costmap.
[bt_navigator-5] [WARN] [1692872680.054291683] [bt_navigator_navigate_to_pose_rclcpp_node]: Node timed out while executing service call to local_costmap/clear_entirely_local_costmap.
[behavior_server-4] [INFO] [1692872680.054674974] [behavior_server]: Running spin
[behavior_server-4] [INFO] [1692872680.054769234] [behavior_server]: Turning 1.57 for spin behavior.
[ERROR] [controller_server-1]: process has died [pid 16391, exit code -11, cmd '/opt/ros/humble/lib/nav2_controller/controller_server --ros-args --log-level info --ros-args -r __ns:=/ --params-file /tmp/tmpwizu8_td -r /tf:=tf -r /tf_static:=tf_static -r cmd_vel:=cmd_vel_nav'].
[behavior_server-4] [INFO] [1692872682.555000572] [behavior_server]: spin completed successfully
[ERROR] [bt_navigator-5]: process has died [pid 16399, exit code -11, cmd '/opt/ros/humble/lib/nav2_bt_navigator/bt_navigator --ros-args --log-level info --ros-args -r __node:=bt_navigator -r __ns:=/ --params-file /tmp/tmpoidr2378 -r /tf:=tf -r /tf_static:=tf_static'].
[lifecycle_manager-8] [INFO] [1692872684.105955493] [lifecycle_manager_navigation]: Have not received a heartbeat from controller_server.
[lifecycle_manager-8] [ERROR] [1692872684.105996957] [lifecycle_manager_navigation]: CRITICAL FAILURE: SERVER controller_server IS DOWN after not receiving a heartbeat for 4000 ms. Shutting down related nodes.
[lifecycle_manager-8] [INFO] [1692872684.106006041] [lifecycle_manager_navigation]: Terminating bond timer...
[lifecycle_manager-8] [INFO] [1692872684.106012467] [lifecycle_manager_navigation]: Resetting managed nodes...
[lifecycle_manager-8] [INFO] [1692872684.106018512] [lifecycle_manager_navigation]: Deactivating velocity_smoother
[velocity_smoother-7] [INFO] [1692872684.106718762] [velocity_smoother]: Deactivating
[velocity_smoother-7] [INFO] [1692872684.106772478] [velocity_smoother]: Destroying bond (velocity_smoother) to lifecycle manager.
[lifecycle_manager-8] [INFO] [1692872684.212621190] [lifecycle_manager_navigation]: Deactivating waypoint_follower
[waypoint_follower-6] [INFO] [1692872684.212900307] [waypoint_follower]: Deactivating
[waypoint_follower-6] [INFO] [1692872684.212947148] [waypoint_follower]: Destroying bond (waypoint_follower) to lifecycle manager.
[lifecycle_manager-8] [INFO] [1692872684.320141704] [lifecycle_manager_navigation]: Deactivating bt_navigator

**Comment by hilary-luo** [comment]
@Saurabh0325 It does sound like it may be advantageous for you to try this with Discovery server. Are you on board with trying to troubleshoot discovery server? If so can you provide the following:

1. If you ssh into the turtlebot, run `cat /etc/turtlebot4/setup.bash` and share the output.

2. If you go to the [create3 webserver](https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#accessing-the-create-3-webserver), can you share a screenshot like the following:
![image](https://github.com/turtlebot/turtlebot4/assets/103377417/26d6d4b7-11de-4a22-bb2b-f03c36e2894c)

3. On your PC, can you tell me what modifications you have made to your ~/.bashrc for Turtlebot and what those files that are included contain.

**Comment by Saurabh0325** [comment]
Thank you for your reply.
I want to drive multiple robots after I am able to achieve navigation using only one robot. I went through the user manual, there I found out that controlling multiple robots using discovery server is not possible. Anyhow I was able to revert back to simple discovery successfully. 
But the navigation issue is still there. (nav2 deactivates after setting the pose and giving a goal pose). As I have mentioned above. Can you please help me with that?

**Comment by hilary-luo** [comment]
@Saurabh0325 With your system set up for simple discovery:

1. Can you please replicate the situation and then download and share the [create3 log](https://iroboteducation.github.io/create3_docs/webserver/logs/)? Please ensure to give plenty of time after the create3 boots up before starting the navigation so that it is clearly spaced out in the log. 

2. Can you please share the exact commands that you are running to launch each piece?

3. Can you please still run `cat /etc/turtlebot4/setup.bash` on the robot and share the output?

**Comment by Saurabh0325** [comment]
@hilary-luo Thank you for your reply. 
1) create3 logs: [messages.txt](https://github.com/turtlebot/turtlebot4/files/12462716/messages.txt)


2) Localisation:   ros2 launch turtlebot4_navigation localization.launch.py map:=map_3.yaml
    Nav2:   ros2 launch turtlebot4_navigation nav2.launch.py
    rviz:      ros2 launch turtlebot4_viz view_robot.launch.py
3)
![Screenshot from 2023-08-29 10-20-52](https://github.com/turtlebot/turtlebot4/assets/127971127/bfefc777-53fe-423d-9e1a-13ca2a8ca80e)

**Comment by Saurabh0325** [comment]
1) Please refer logs after time stamp 14.45 for navigation related info
[messages.txt](https://github.com/turtlebot/turtlebot4/files/12465948/messages.txt)

2) localisations: ros2 launch turtlebot4_navigation localization.launch.py map:=hiwi_raum.yaml
 navigation: ros2 launch turtlebot4_navigation nav2.launch.py
rviz: ros2 launch turtlebot4_viz view_robot.launch.py

3) 

![Screenshot from 2023-08-29 10-20-52](https://github.com/turtlebot/turtlebot4/assets/127971127/f915566d-c767-47d6-9b4a-d2cbf3e44eca)

**Comment by hilary-luo** [comment]
So it looks like you are running into the issue where the CPU maxes out on the create3. Can you try turning diagnostics off on the raspberry pi? (Can be done in the `turtlebot4-setup` tool). Let me know if that helps and if it doesn't, please provide the create3 log again of the new attempt.

**Comment by Saurabh0325** [comment]
Thank you for your help. I was able to perform navigation. There was an error with Fastdds package and after reinstallation and proper sourcing navigation started working.

**Comment by Balo-97** [comment]
@Saurabh0325 How were you able to reinstall and properly source Fastdds?
