### ISSUE TITLE
Excessive CPU load on Raspberry Pi

### ISSUE THREAD

**Issue by joergwunsch** [turtlebot/turtlebot4#254]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from source or installed: installed (as it shipped with the robot, plus some updates)
 - Package version: 
```
ros-humble-turtlebot4-base/jammy 1.0.1-1jammy.20230807.164644 arm64 [upgradable from: 1.0.1-1jammy.20230722.000608]
ros-humble-turtlebot4-bringup/jammy 1.0.1-1jammy.20230807.193953 arm64 [upgradable from: 1.0.1-1jammy.20230804.215206]
ros-humble-turtlebot4-description/jammy 1.0.3-1jammy.20230807.172230 arm64 [upgradable from: 1.0.3-1jammy.20230804.211305]
ros-humble-turtlebot4-diagnostics/jammy 1.0.1-1jammy.20230807.165914 arm64 [upgradable from: 1.0.1-1jammy.20230721.235804]
ros-humble-turtlebot4-msgs/jammy,now 1.0.3-1jammy.20230721.201332 arm64 [installed,automatic]
ros-humble-turtlebot4-navigation/jammy 1.0.3-1jammy.20230807.211522 arm64 [upgradable from: 1.0.3-1jammy.20230804.220720]
ros-humble-turtlebot4-node/jammy 1.0.3-1jammy.20230807.164105 arm64 [upgradable from: 1.0.3-1jammy.20230722.000001]
ros-humble-turtlebot4-robot/jammy 1.0.1-1jammy.20230807.194523 arm64 [upgradable from: 1.0.1-1jammy.20230804.215701]
ros-humble-turtlebot4-setup/jammy 1.0.2-1jammy.20230807.153410 arm64 [upgradable from: 1.0.2-1jammy.20230721.205906]
ros-humble-turtlebot4-tests/jammy,now 1.0.1-1jammy.20230721.205750 arm64 [installed,automatic]
```

 **Expected behaviour**
System CPU load at a "normal" level.

 **Actual behaviour**
CPU load of more than 18 while the robot is just sitting around, see attached htop screenshot.

**To Reproduce**
Hard to reproduce, but we've seen it more than once.
The question is merely how to debug it when it happens, so we can eventually avoid it.
![htop](https://github.com/turtlebot/turtlebot4/assets/143496587/a87c6f0c-39fb-46e9-b83c-870acc96e3a6)

(Edit: corrected package versions, for Raspberry Pi)

**Comment by hilary-luo** [comment]
@joergwunsch are you running any custom code or are there additional devices / nodes on the network beyond the single turtlebot4? 

We have not seen this issue before. You could try disabling the turtlebot4 diagnostics and see if that addresses the issue.

**Comment by joergwunsch** [comment]
No custom code on the RPi (only on the host PC which is of course also on the network).
My colleague already had the idea to disable diagnostics, that seems to remedy the CPU load issue.
