### ISSUE TITLE
Limited topics available to the user PC compared to Pi.

### ISSUE THREAD

**Issue by ramakrishnasakethi** [turtlebot/turtlebot4#258]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 22.04)
 - ROS Distro: (e.g. Humble)
 - Built from source or installed: Installed

 **Expected behaviour**
Both user PC and the Pi returning all available topics published by Create 3 and Pi.

 **Actual behaviour**
ros2 topic list returning only a limited set of topics compared to pi. I have attached a screenshot for your reference. I followed the instructions under Simple Discovery to setup the communication between the bot and the user PC.
![not_all_topics](https://github.com/turtlebot/turtlebot4/assets/142871633/f477536f-3b73-4620-897b-2aab5df12f9a)

**To Reproduce**
Setup [https://turtlebot.github.io/turtlebot4-user-manual/setup/simple_discovery.html](url)
Verify running `ros2 topic list` in both user PC and Pi to see that the topics accessible match.

**Comment by ramakrishnasakethi** [comment]
A snapshot of the log for your reference.
![log_snapshot](https://github.com/turtlebot/turtlebot4/assets/142871633/4064b63c-488e-4757-b01e-eff59ba96a05)

**Comment by hilary-luo** [comment]
@ramakrishnasakethi I see that you have entered a number of issues that seem inter-related. Are they all on the same robot? If you don't have the create3 connected to wifi then simple discovery will not work properly and you will not be able to see all of the ros 2 topics from your computer. As such you will not be able to run nav. 

If these are on the same robot then I can work through these issues with you but one at a time starting with getting the create3 connected to wifi. Taking them out of order may make some of the troubleshooting steps not make sense.

**Comment by ramakrishnasakethi** [comment]
@hilary-luo I tried following the steps mentioned by you in #257 to try and get the robot connected to WiFi.
1. I could not find the robot listed as Create-[xxx] in the Network Manager after pressing and holding buttons 1 and 2 for a few seconds. The light ring has the spinning blue light though.
2. The robot starts to make a maneuver that has not been mentioned by you in the procedure after pressing and holding the buttons 1 and 2 for approximately 4-5 seconds before the light ring turns spinning blue.

**Comment by sdobbelaere** [comment]
Once I took those steps to enable wifi, it showed me my available wifi networks.  Not the actual robot.

**Comment by hilary-luo** [comment]
@ramakrishnasakethi Even if you were not able to connect through the create3 acess point, this still should have turned on the wifi connection of the create3. Assuming that was the only issue, you should be able to connect the create3 base to the internet now through the original method. (connect to the create3 webserver using the raspberry pi ip address and navigate to the connection page etc). 

In regards to the fact that the robot started driving, that is fine, depending on how you pressed them or the mode that the robot is in it may do so. Individually those buttons are used for Turtlebot4 for docking and undocking as well.

**Comment by ramakrishnasakethi** [comment]
> Once I took those steps to enable wifi, it showed me my available wifi networks. Not the actual robot.

By it, do you mean the PC's network manager?

**Comment by ramakrishnasakethi** [comment]
> @ramakrishnasakethi Even if you were not able to connect through the create3 acess point, this still should have turned on the wifi connection of the create3. Assuming that was the only issue, you should be able to connect the create3 base to the internet now through the original method. (connect to the create3 webserver using the raspberry pi ip address and navigate to the connection page etc).
> 
> In regards to the fact that the robot started driving, that is fine, depending on how you pressed them or the mode that the robot is in it may do so. Individually those buttons are used for Turtlebot4 for docking and undocking as well.

I tried connecting the Create-3 through the original method now. It is the same like before. I see the following page after entering the Wi-Fi credentials and clicking on connect,
![connecting_to_tb4](https://github.com/turtlebot/turtlebot4/assets/142871633/8c9137c2-5092-4f72-b403-91e8c1e6789d)

After 15 minutes, I opened the Create3 webserver in a different page and entered the connect tab and it seems as though I have to enter the credentials all over again,
![after_15_mins](https://github.com/turtlebot/turtlebot4/assets/142871633/b32c49d4-a1cd-4a0e-b141-aadddd1676eb)´

Log file for your reference: 
[messages.txt](https://github.com/turtlebot/turtlebot4/files/12544642/messages.txt)

**Comment by hilary-luo** [comment]
Ensure that you have closed all browser windows that are connected to the webserver and then please try to follow the instructions again (from [the other page](https://github.com/turtlebot/turtlebot4/issues/257?notification_referrer_id=NT_kwDOBilqCbQ3NTkzOTkwNzk5OjEwMzM3NzQxNw#issuecomment-1705624839) and hold the buttons down until you get the **spinning** cyan light pattern as shown here: https://iroboteducation.github.io/create3_docs/hw/face/

Either you may not have held the buttons down long enough or perhaps having the webserver open through the raspberry pi maybe could have interfered.

**Comment by ramakrishnasakethi** [comment]
> 
What do you mean by computer's wifi manager?

**Comment by ramakrishnasakethi** [comment]
> Ensure that you have closed all browser windows that are connected to the webserver and then please try to follow the instructions again (from [the other page](https://github.com/turtlebot/turtlebot4/issues/257?notification_referrer_id=NT_kwDOBilqCbQ3NTkzOTkwNzk5OjEwMzM3NzQxNw#issuecomment-1705624839) and hold the buttons down until you get the **spinning** cyan light pattern as shown here: https://iroboteducation.github.io/create3_docs/hw/face/
> 
> Either you may not have held the buttons down long enough or perhaps having the webserver open through the raspberry pi maybe could have interfered.

An IP Address now appears on top of the create3 webserver when I open the connect tab, which was previously not the case. But I still am not able to connect to the robot to the network. A snapshot of the log corresponding to the failed attempt to connect to the network,
![error_wifi_create3](https://github.com/turtlebot/turtlebot4/assets/142871633/0240d2d9-60a5-41c6-a7f6-4e764fa6478c)

**Comment by ramakrishnasakethi** [comment]
List of topics available enough to do mapping after connecting Create 3 to WiFi properly using solution provided [here](https://github.com/turtlebot/turtlebot4/issues/257#issuecomment-1705624839)
