### ISSUE TITLE
Unable to map the environment using Synchronous SLAM

### ISSUE THREAD

**Issue by ramakrishnasakethi** [turtlebot/turtlebot4#259]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from source or installed: Installed

 **Expected behaviour**
Be able to map the environment after running `ros2 launch turtlebot4_navigation slam.launch.py` 

 **Actual behaviour**
Errors as can bee seen in the screenshots:
1. After running `ros2 launch turtlebot4_navigation slam.launch.py` and `ros2 launch turtlebot4_viz view_robot.launch.py` in the command terminal:
![error_running_slam](https://github.com/turtlebot/turtlebot4/assets/142871633/c9dafaee-4155-4a7a-b27e-badea093024e)

2. Error in rviz:
![rviz_error](https://github.com/turtlebot/turtlebot4/assets/142871633/b3a8aeb2-5762-4d03-b971-f45f021e710c)

**To Reproduce**
Run `ros2 launch turtlebot4_navigation slam.launch.py` and `ros2 launch turtlebot4_viz view_robot.launch.py` from the command terminal.

**Other notes**
Only a limited set of topics are available in the User PC compared to Pi.
![not_all_topics](https://github.com/turtlebot/turtlebot4/assets/142871633/1c856c10-4bfe-4ef3-8c31-71a820fc9ffc)

**Comment by hilary-luo** [comment]
Hi @ramakrishnasakethi are you using simple discovery or discovery server?

Can you show me the list of topics on each of your robot and pc when you are trying to run slam? Your rviz window doesn't seem to be receiving the information from the SLAM toolbox.

**Comment by ramakrishnasakethi** [comment]
Able to run slam after connecting Create-3 to WiFi using solution mentioned [here](https://github.com/turtlebot/turtlebot4/issues/257#issuecomment-1705624839)
