### ISSUE TITLE
Error connecting Create 3 to WiFi

### ISSUE THREAD

**Issue by ramakrishnasakethi** [turtlebot/turtlebot4#261]
[messages(1).txt](https://github.com/turtlebot/turtlebot4/files/12512010/messages.1.txt)
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Built from source or installed: Installed

 **Expected behaviour**
After entering SSD and Password, Create 3 gets connected to WiFi and an IP Address is shown in the connect tab.

 **Actual behaviour**
´The following page appears and does not end up showing an IP address.
![connection_error_create3](https://github.com/turtlebot/turtlebot4/assets/142871633/3efd7610-e315-4ca3-8713-49837d029c0d)

**To Reproduce**
Enter the SSD name and Password in the connect tab of Connect 3 webserver
.

**Comment by hilary-luo** [comment]
Can you please try again to connect it to the wifi and then provide the [create3 log](https://iroboteducation.github.io/create3_docs/webserver/logs/)?

Odds are that it is the same issue described here: https://github.com/turtlebot/turtlebot4/issues/257#issuecomment-1705624839, so feel free to attempt those steps to launch the wifi network.

**Comment by ramakrishnasakethi** [comment]
It works. Thank you :)
