### ISSUE TITLE
Turtlebot4 development state overview

### ISSUE THREAD

**Issue by teufelweich** [turtlebot/turtlebot4#263]
There are so many correlated issues (#62 #143 #158 #181 #188 #226 #246 #259 #218 ) regarding SLAM and Nav2 on the robot that my team and me starting to question if the Turtlebot4 currently can be used for what was promised. I would like to have an answer what can be expected to work and what is known to be not working currently.

Our experience based on the promised selling points is:
- [ ] Robot with SLAM and Nav2
  - [x] Galactic working before G.5.1
  - [ ] Humble no working version
  - [ ] Camera (esp. depth) working only sporadically
-  [ ] Simulator
   - [ ] no working version for Humble or Galactic
- [x] Documentation
   - [x] pretty good and up to date but suggests everything above should work 
- [ ] Lesson Material
  - [ ]  seriously incomplete 

We are trying to get these Turtlebots running since over 6 month now. And it feels like we didn't make any progress because this complex system is so difficult to debug.

**Comment by hilary-luo** [comment]
@teufelweich I am sorry to hear that you are having difficulties with your set up of the turtlebot4 and can understand that you are feeling very frustrated. 6 months is indeed a long time to be working on a set up. I can respond to you here in regards to the various issues that you are running into or if you would like you can choose to pursue these issues with the client success team. I am not in any position to discuss specifics about discussions you had when purchasing the turtlebot4, but I can speak to what the Turtlebot4 is capable of. 

I do want to take a moment to note that SLAM and Nav2 are separate and complex open source projects and as such we do not control whether or not bugs are present in those projects or in general how those projects work. We are however committed to do what is within our control to help users learn how to to use those projects and to contribute to the success of those projects.

The Turtlebot4 product is fully able to run nav2 and slam with both Galactic and Humble, with the physical robot or in simulation with the exception of some specific bugs that are being addressed which I will list below. On this line, I will note that the Turtlebot4 product is built on ROS 2 and is a great tool for learning ROS 2 and other open source tools (for example Gazebo). As much as we try to make the Turtlebot4 user friendly, users still ultimately need to learn how to operate and connect together these ROS 2 systems. I agree that these are complex systems and it does take a lot to learn how to troubleshoot them properly. That in itself is not so much a flaw of the product so much as the point of why it exists. It is also why the community is supportive of beginners and the issues that they run into. As such, most issues we see are people needing to learn ROS 2 and who made mistakes when going through the instructions or are trying to do something in a unique way that is not explicitly described. This is understandable for an educational product but is not to be conflated for deficiencies in what the robot can do. 

To my knowledge there are 3 open bugs and I am working on solutions for them when I can:
1. Create3 CPU at 100% - This can also present itself in terminal output as messages about tf timestamp mismatching. There are several potential solutions that can be tested by someone who is running into this issue but they need to commit to working with us to test things and send us results. Either way I am working on a solution to this issue that can be released to all, but it would help if someone experiencing this issue participated in the process.
2. There is an issue where the nav2 components are not subscribing to the correct scan topic which makes it ignore unmapped objects. There is a workaround available that is provided to anyone who reports this issue and a patch is also in the works.
3. Launching  nav2 + slam with namespacing all through the one simulation launch file causes the namespace to be applied to some nodes twice. The work around is to not use namespacing in sim or to launch navigation separately from the simulation using the dedicated navigation launch files when using namespacing. This is also on my list to resolve. 

I can give you some insight into the status of the issues that you listed that I have been involved with if you would like. They fit into the following categories:
a) issues where the person asking the question stopped responding and stopped participating in the troubleshooting process (https://github.com/turtlebot/turtlebot4/issues/188, https://github.com/turtlebot/turtlebot4/issues/246, https://github.com/turtlebot/turtlebot4/issues/218) 
b) issues that were closed by the user before we could respond (https://github.com/turtlebot/turtlebot4/issues/226)
c) duplicates of existing issues that already have workarounds posted (https://github.com/turtlebot/turtlebot4/issues/260)
d) Issues that are brand new so I can't speak to yet (https://github.com/turtlebot/turtlebot4/issues/259)

If your team is still running into the issues described on any of the inactive tickets then I would encourage them to respond to the tickets and they can tag me if they feel like they are not getting responses from whoever was participating in the discussion previously (or if no one has responded). If they are experiencing multiple issues in the same system please ask them to indicate in their tickets that it is running on the same system and we can help them take a more holistic approach in troubleshooting and identifying the core issues with their setup. 

In regards to your last point,I am a software developer and can't speak to the lesson material, please reach out on the appropriate repo about any lesson material. I assume that the appropriate location would be here: https://github.com/turtlebot/TurtleBot4Lessons/issues

**Comment by hilary-luo** [comment]
I forgot to mention in my previous response. I am not aware of anyone having issues with the camera so please do link me on that issue.

**Comment by NachtaktiverHalbaffe** [comment]
@hilary-luo I'm also experiencing the issue with the create3 100% CPU utilization. Can refer to all related issues with your proposed workarounds (Im only applied the new dds configuration)? Maybe I can contribute/participate, my Supervisor gave me resources/time on the turtlebot to work on this problem

**Comment by garyservin** [comment]
@hilary-luo I'm also experiencing the issue with the create3 100% CPU utilization and am available to help with the debug if necessary. In my case, I'm using the latest Humble release, and the issues I'm seeing is the create3's LEDs go to yellow or red and I can't teleop and I stop receiving ROS messages after some time mapping. Sometimes it recovers after some minutes but sometimes (especially when the LED turns red) everything stops working until the create is restarted.

**Comment by hilary-luo** [comment]
For anyone wanting to follow along or join in on the cpu at 100% troubleshooting, jump over here https://github.com/turtlebot/turtlebot4/issues/266.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. I believe every issue that is still present is being responded to and/or tracked on other tickets.
