### ISSUE TITLE
Reset the position of Turtlebot 4

### ISSUE THREAD

**Issue by ACdu22330** [turtlebot/turtlebot4#265]
Reset the position of Turtlebot 4 question : 

**Setup**
 - OS: Ubuntu 20.04)
 - ROS Distro: Humble
 - Built from source or installed: Installed

 **Expected behaviour**
Hello !

I'm using the Turtlebot 4 and I have a question about the reset_pose service.
Is it possible to reset the position of the Turtlebot 4 in a different position from the origin point ?

 **Actual behaviour**
 I've tried with this ros2 command :

ros2 service call /reset_pose irobot_create_msgs/srv/ResetPose "pose:
position:
x: 1.0
y: 2.0
z: 0.0
orientation:
x: 0.0
y: 0.0
z: 0.0
w: 0.0
"

But the robot just reste the position at 0 (as you can see in the 2 screens attached). 
Does the service reset_pose can change the position of the robot or an other topic or service is capable to do that ?

**To Reproduce**

1. Run position_subscriber node to get the current position of the TB4
2. Call the /reset-pose service with a position diffrent than (0,0,0)
3. See the robot position is going back to (0,0,0) 

Thank you for your answers !

![image](https://github.com/turtlebot/turtlebot4/assets/135013797/90843149-bee2-451c-9e25-903374ea58a4)

**Comment by hilary-luo** [comment]
In your instructions on how to reproduce please be explicit in regards to the exact commands that you are running. Specifically in this case, what position_subscriber node are you running and how are you launching it? Also, do you have any other nodes running on the network or on the robot (other than those that are started automatically by the robot)?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
