### ISSUE TITLE
Trouble starting the simulation

### ISSUE THREAD

**Issue by ramakrishnasakethi** [turtlebot/turtlebot4#271]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 22.04)
 - ROS Distro: (e.g. Humble)
 - Built from source or installed: Installed
 - Package version: H.2.2

 **Expected behaviour**
 Simulation gets launched

 **Actual behaviour**
[controller_server-49] [INFO] [1694671448.970187942] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.

**To Reproduce**
Provide the steps to reproduce:
1. run a osrf/ros:humble container following the steps [here](https://docs.ros.org/en/humble/How-To-Guides/Run-2-nodes-in-single-or-separate-docker-containers.html)
2. Install all required software packages pointed out in the [user manual](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/turtlebot4_navigator.html)
3. Execute the command `ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py nav2:=true slam:=false localization:=true rviz:=true`

**Other notes**
I run the container from Windows 11 Pro

**Comment by hilary-luo** [comment]
I do not believe that this is a turtlebot issue. Make sure that you have modified the docker container as necessary to be able to run rviz2. You should be able to enter `rviz2` into the terminal and launch rviz successfully. If you have difficulties getting this setup I would encourage you to reach out on https://robotics.stackexchange.com/. Once you are able to launch rviz, if you are still unable to launch the turtlebot4 sim feel free to reach out here again
