### ISSUE TITLE
TB4 not under control

### ISSUE THREAD

**Issue by gmz123513** [turtlebot/turtlebot4#282]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed:
 - Package version: sudo dpkg -s ros-ROS2-turtlebot4-PACKAGE_WITH_ISSUE`

 **Expected behaviour**
 The robot should be controlled by the directional keys

 **Actual behaviour**
 While driving the TurtleBot4 Lite version, the chassis does not respond to directional keys. Pressing the forward key causes it to continuously spin in place, and there have been instances where pressing the left or right keys also only makes it move forward. Rebooting the machine and upgrading the Create3 chassis have not resolved the issue. However, occasionally, it can be controlled using keyboard functions. What could be causing this, and are there any solutions?

https://github.com/turtlebot/turtlebot4/assets/75788043/aa3a0221-6fe7-4335-b3ff-409d6d76a551

**To Reproduce**
Provide the steps to reproduce:
1. run something
2. launch something else
3. see the error

**Other notes**
Add anything else you thing is important.

**Comment by hilary-luo** [comment]
@gmz123513 what tool are you using to drive the robot? By directitonal keys do you mean the arrow keys on the keyboard?

If you are using the [keyboard teleoperation](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/driving.html#keyboard-teleoperation) then please use the keys indicated by the tool. This is not a holonomic robot so `i` for forward, `j` for rotating left, `l` for rotatin right etc. Every time you start the tool it will display the full reference on the screen or you can see it on the website. I have also included an image of the instructions below:

![image](https://github.com/turtlebot/turtlebot4/assets/103377417/b043d1db-16d1-4c20-ac17-5810acd6ff76)

**Comment by gmz123513** [comment]
I may not have clearly stated this issue. My directional keys are controlled by i, j, and l, but I know they are used to indicate forward. The main problem is that when I press i to advance, TB4 rotates in place, as shown in the video, and I keep pressing i to advance

**Comment by hilary-luo** [comment]
Thank you for the clarification. Have you tried echoing the `/cmd_vel` topic to make sure that only the commands that you expect are being seen there and that they correspond with the commands that you are sending? 

If you can replicate this issue, can you please provide the [create3 log](https://iroboteducation.github.io/create3_docs/webserver/logs/) of one such occurence?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
