### ISSUE TITLE
Power outage during firmware upgrade

### ISSUE THREAD

**Issue by gmz123513** [turtlebot/turtlebot4#283]
**Please provide the following information:**
 - OS:  Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed:
 - Package version: sudo dpkg -s ros-ROS2-turtlebot4-PACKAGE_WITH_ISSUE

 **Expected behaviour**
 

 **Actual behaviour**
During the firmware upgrade process, the Create3 experienced a power interruption. Upon restarting, the STM32 bootloader failed to boot into the firmware, resulting in an inability to start the system and access web pages. When the device is placed on the charging dock, the white LED ring continuously cycles without the startup sound, and it cannot establish a connection. Is there any method to recover or reflash the firmware?

**To Reproduce**
Provide the steps to reproduce:
1. run something
2. launch something else
3. see the error

**Other notes**
Add anything else you thing is important.

**Comment by hilary-luo** [comment]
When you have the create3 on the dock are you able to access the webserver through the raspberry pi connection? That at least wouldn't require the create3 to establish its own connection. Alternatively you can also try putting the create3 in access point mode although that may not be successful it isn't able to boot up properly. 

If neither of these help then please create a ticket here https://github.com/iRobotEducation/create3_docs/issues . You can reference this one there.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
