### ISSUE TITLE
Cannot see topics in RPI terminal.

### ISSUE THREAD

**Issue by ipa-anm-sy** [turtlebot/turtlebot4#294]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: (e.g. humble)
 - Built from source or installed: Installed
 

 **Expected behaviour**
Should see topics in the remote pc and raspberrypi after ssh .

 **Actual behaviour**
topics are only visible in remote pc not in raspberrypi.

All leds are turned on. I cannaot see reboot robot option on irobot webpage.

![Screenshot from 2023-10-31 13-57-57](https://github.com/turtlebot/turtlebot4/assets/144012651/fcf856c4-7325-4029-9ef7-0979b94cf69d)
![Screenshot from 2023-10-31 13-58-41](https://github.com/turtlebot/turtlebot4/assets/144012651/17cc4ec0-0604-4391-9389-992ab769b73e)
![Screenshot from 2023-10-31 13-59-43](https://github.com/turtlebot/turtlebot4/assets/144012651/c9642045-4a76-4b4a-9fbb-ba48b619918d)

**Comment by hilary-luo** [comment]
Can you try running `ros2 daemon stop; ros2 daemon start` on the raspberry pi?

In regards to the create3, is that option still not available after you reboot the robot manually?

**Comment by ipa-anm-sy** [comment]
@hilary-luo  
Thank you for the reply. I have tried ' ros2 daemon stop; ros2 daemon start' but it did not work. I have rebooted the robot manually so many times now but I cannot see the topic as well as the reboot robot option in create3. 
Are there any other solutions to this that you can suggest? 
Thank you.

**Comment by hilary-luo** [comment]
Can you share the outputs of `env` and `ip a` from on your pi?

**Comment by ipa-anm-sy** [comment]
I reflashed the rpi, after that the issue was resolved.
