### ISSUE TITLE
rviz not showing th emap and the robot

### ISSUE THREAD

**Issue by Akalpita30** [turtlebot/turtlebot4#301]
**Please provide the following information:**
OS: Ubuntu version 22.04
ROS Distro: Humble
Built from source
Package version: H.2.2

 **Expected behaviour**
Rviz showing the map and robot ready to navigate.

 **Actual behaviour**
Rviz screen is blank. the command window is stuck in a loop. 

This is the screenshot of the command window- for command line ros2 launch turtlebot4_navigation localization.launch.py map:=hydro_nov.yaml
![Screenshot from 2023-11-06 23-50-26](https://github.com/turtlebot/turtlebot4/assets/87574208/28f5fc09-be55-469d-95c9-ee140e215b80)

The rviz screen-
![Screenshot from 2023-11-06 23-52-26](https://github.com/turtlebot/turtlebot4/assets/87574208/9d6cd0fe-3256-420c-80a4-167165419832)

Although I'm able to see the topic-
![Screenshot from 2023-11-06 23-53-52](https://github.com/turtlebot/turtlebot4/assets/87574208/4bf4178d-ef19-498f-952a-b0e2b937f2fa)

**To Reproduce**
Provide the steps to reproduce:
1.ros2 launch turtlebot4_navigation localization.launch.py map:=hydro_nov.yaml
2.ros2 launch turtlebot4_viz view_robot.launch.py
3. see the error

**Other notes**
ROS topics are publishing on Rpi too.
![Screenshot from 2023-11-06 23-56-23](https://github.com/turtlebot/turtlebot4/assets/87574208/ca0e5235-5d94-4207-87a5-a79e18881ec7)

**Comment by hilary-luo** [comment]
@Akalpita30 Can you please provide your map files? I don't see anything obvious and am currently unable to replicate what you are seeing.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
