### ISSUE TITLE
I am running ROS2 Humble on Ubuntu 22.04. The controller I got with the standard turtlebot 4 is not switching on even after keeping it on charge for 2 hours

### ISSUE THREAD

**Issue by htt2110** [turtlebot/turtlebot4#309]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 20.04)
 - ROS Distro: (e.g. Galactic)
 - Built from source or installed:
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)

 **Expected behaviour**

 **Actual behaviour**
 A clear and concise description of what you encountered.

**To Reproduce**
Provide the steps to reproduce:
1. run something
2. launch something else
3. see the error

**Other notes**
Add anything else you thing is important.

**Comment by smatarCPR** [comment]
Hello, when charging the controller, are you using an AC outlet or connecting it to the USB port of a computer? Does the light on the top of the controller come on and turn yellow?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
