### ISSUE TITLE
there is no camera oakd-lite data

### ISSUE THREAD

**Issue by ddwy** [turtlebot/turtlebot4#31]
I use a mirror image tutlebot4_ lite_ galactic_ 0.1.2.After the system is started, the camera oakd-lite cannot operate normally. When viewing the camera oakd-lite topic, there is no camera oakd-lite data.

**Comment by ddwy** [comment]
Hello, mirror image tutlebot4_ lite_ galactic_ 0.1.2, The driver of the oakd Lite camera is not installed.

**Comment by roni-kreinin** [comment]
@ddwy The driver is installed on the 0.1.2 image. Can you run `sudo journalctl -u turtlebot4.service -r ` and look for errors on the `rgb_stereo_node`?
