### ISSUE TITLE
cmd_vel with bang bang control

### ISSUE THREAD

**Issue by JavierBorquez** [turtlebot/turtlebot4#310]
**Please provide the following information:**
 - OS: Ubuntu Ubuntu 22.04.3 LTS
 - ROS Distro: Humble
 - Built from source or installed: Installed
 - Package version: Package: ros-humble-turtlebot4-base
          Status: install ok installed
          Priority: optional
          Section: misc
          Installed-Size: 479
          Maintainer: rkreinin <[rkreinin@clearpathrobotics.com](mailto:rkreinin@clearpathrobotics.com)>
          Architecture: arm64
          Version: 1.0.1-1jammy.20230920.022111
          Depends: libc6 (>= 2.34), libgcc-s1 (>= 3.3.1), libgpiod2 (>= 1.1), libstdc++6 (>= 11), libgpiod-dev, ros-humble-irobot-create-msgs, ros-humble-rclcpp, ros-humble-rclcpp-action, ros-humble-rcutils, ros-humble-sensor-msgs, ros-humble-std-msgs, ros-humble-turtlebot4-msgs, ros-humble-turtlebot4-node, ros-humble-ros-workspace
          Description: Turtlebot4 Base Node

 **Expected behaviour**
We give the turtlebot cmd_vel commands with constant linear.x and toggling angular.z speed between 1.5 and -1.5 (rad/sec) every time we get an odometry topic message.
The expected behavior is a trajectory resembling a straight line (with some kinks due to the finite time step)

 **Actual behaviour**
the result is the turtlebot spinning in a shrinking spiral.

**To Reproduce**
Provide the steps to reproduce:
1. give the turtlebot cmd_vel commands with constant linear.x and toggling angular.z speed between 1.5 and -1.5 (rad/sec) every 50ms.

**Comment by hilary-luo** [comment]
@JavierBorquez Do you have a python test code or something similar? I have not had time to try and replicate this.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
