### ISSUE TITLE
Not able to comunicate with create from ROS2, not obtaining battery levels (reporting 0 -> critical)

### ISSUE THREAD

**Issue by BorMi** [turtlebot/turtlebot4#313]
- OS: Ubuntu 20.04.03 (GNU/Linux 5.15.0-1043-raspi aarch64)
 - ROS Distro: Humble
 - Built from source or installed: installed
 - Package version: not applicable (I don't know which package is causing the problem)

 **Expected behaviour**
Obtaining battery levels in Screen and ros topics

 **Actual behaviour**
No messages published in /battery_state
/diagnostics report level=0 critical

**To Reproduce**
I am not able to avoid this behaviour

**Other notes**
I have tried restarting the robot, resetting the battery (disconnecting and waiting for more than 15 minutes), charging all the night...

**Comment by hilary-luo** [comment]
@BorMi Can you please provide the create3 log?

Is the robot actually shutting down or do you just see this response in the diagnostics tool? Are you trying to run anything when this happens?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
