### ISSUE TITLE
Unable to use localization, No 2d goal or Pose goal working

### ISSUE THREAD

**Issue by vamsikracha** [turtlebot/turtlebot4#317]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 20.04) Ubuntu 20.04
 - ROS Distro: (e.g. Galactic) Humble
 - Built from source or installed: Installed
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)

 **Expected behaviour**
Robot does not navigate to the give pose.

 **Actual behaviour**
 navigation does not work

**To Reproduce**
Provide the steps to reproduce:
1. run localization ros2 launch turtlebot4_navigation localization.launch.py map:=office.yaml
2. run navigation ros2 launch turtlebot4_navigation nav2.launch.py 
3. drive the robot using keyboard
4. set the 2d pose estimate
5. set nav goal and verify if the robot navigates to the given goal.

**Other notes**
Add anything else you thing is important.

**Comment by hilary-luo** [comment]
@vamsikracha 
1. can you confirm that you are running the correct map to match your physical environment?
2. can you confirm that you are able to communicate between the robot and your pc (can you see and echo topics)
If so, please provide the terminal outputs from each terminal where you ran these commands. If not then we need to address those items first.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
