### ISSUE TITLE
Nav2 does not work

### ISSUE THREAD

**Issue by myamo1** [turtlebot/turtlebot4#322]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 - Installed
 
 **Expected behaviour**
 Visualize the robot on the map (Rviz). Provide the initial pose estimate and the goal. Finally, the robot moves toward the destination.

 **Actual behaviour**
 The map shows on RViz but I have the errors shown on the screenshot.
![Screenshot from 2023-11-27 21-31-25](https://github.com/turtlebot/turtlebot4/assets/150306713/0f6a616c-b688-4a76-8946-a9e8894b08c7)

**Other notes**
Similar errors appear when I try it with gazebo.

**Comment by hilary-luo** [comment]
@myamo1 please provide the exact commands that you are running and the full terminal output. Overall I don't see anything specifically alarming here, it looks like the normal status as different nodes are waiting for each other. How long have you given it in this state for everything to get started? Can you also provide your create3 logs from when you run this? If you wish to also troubleshoot the simulation then also give the exact commands and terminal outputs from when you ran it with simulation.

**Comment by myamo1** [comment]
It worked, finally. I just needed to give it a longer time. Sometimes, it works quickly, but other times, I have to wait longer.
Thanks.
