### ISSUE TITLE
Could not subscribe odom topic after firmware update

### ISSUE THREAD

**Issue by atinfinity** [turtlebot/turtlebot4#325]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 22.04)
 - ROS Distro: (e.g. Humble)
 - Built from source or installed: installed
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)

 **Expected behaviour**

After user updated the latest firmware, user run ros2 topic echo /odom.
I expect that user can subscribe /odom topic.

 **Actual behaviour**

After user updated the latest firmware, user run `ros2 topic echo /odom`.
But, I could not subscribe `/odom` topic.

**To Reproduce**

1. updated the latest firmware(<https://iroboteducation.github.io/create3_docs/releases/h_2_3/>)
2. performed a factory reset
3. boot TurtleBot4
4. do `ros2 topic echo /odom`

**Other notes**

> * Update to the latest firmware using the webserver.
> * Once updated, perform a factory reset to disconnect the Create® 3 from any Wi-Fi networks.

https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html

I read the above description.
So, I updated firmware to [iRobot Create 3 Release H.2.3](https://iroboteducation.github.io/create3_docs/releases/h_2_3/).
And, I performed a factory reset. As a result, I could not subscribe `odom` topic.

```
$ ros2 node list
/analyzers
/joint_state_publisher
/joy_linux_node
/launch_ros_1022
/oakd
/oakd_container
/robot_state_publisher
/rplidar_composition
/teleop_twist_joy_node
/turtlebot4_base_node
/turtlebot4_diagnostics
/turtlebot4_node
```

**Comment by atinfinity** [comment]
I downgrade to <https://iroboteducation.github.io/create3_docs/releases/h_2_2/>. This problem was not resolved.

**Comment by atinfinity** [comment]
```shell
$ ros2 node list
/analyzers
/joint_state_publisher
/joy_linux_node
/launch_ros_1022
/oakd
/oakd_container
/robot_state_publisher
/rplidar_composition
/teleop_twist_joy_node
/turtlebot4_base_node
/turtlebot4_diagnostics
/turtlebot4_node
```

It seem that iRobot Create 3 node failed to launch.

**Comment by atinfinity** [comment]
I checked log via Web server of Create 3.

```
Dec 12 07:18:54 user.notice create-platform: [INFO] [1702365534.202752691] [mobility_monitor]: Lifecycle callback: on_configure
Dec 12 07:18:58 user.notice create-platform: [INFO] [1702365538.432919320] [create-platform]: Activating mobility_monitor node
Dec 12 07:18:58 user.notice create-platform: [INFO] [1702365538.433294812] [mobility_monitor]: Lifecycle callback: on_activate
Dec 12 07:18:58 user.notice create-platform: [INFO] [1702365538.435663999] [mobility_monitor]: New kidnap status: kidnap cleared
Dec 12 07:18:59 user.notice create-platform: [INFO] [1702365539.040102439] [_internal.mobility]: Received enable wheels request
Dec 12 07:18:59 user.notice create-platform: [INFO] [1702365539.102631961] [mobility_monitor]: Requested to enable wheels!
Dec 12 07:18:59 user.notice create-platform: [INFO] [1702365539.389320450] [mobility_monitor]: Updating ready to drive: true
Dec 12 07:18:59 user.notice create-platform: [INFO] [1702365539.390442063] [mobility_monitor]: Kidnap cleared! Wheels are now enabled!
Dec 12 07:18:59 user.notice create-platform: [INFO] [1702365539.433863371] [create-platform]: Started mobility_monitor node
Dec 12 07:18:59 user.notice create-platform: [INFO] [1702365539.434053600] [create-platform]: Configuring robot_state node
Dec 12 07:18:59 user.notice create-platform: [INFO] [1702365539.440272596] [robot_state]: Lifecycle callback: on_configure
Dec 12 07:19:10 user.notice create-platform: [INFO] [1702365550.630026340] [create-platform]: Activating robot_state node
Dec 12 07:19:10 user.notice create-platform: [INFO] [1702365550.631237922] [robot_state]: Lifecycle callback: on_activate
Dec 12 07:19:11 user.notice create-platform: [INFO] [1702365551.633011869] [create-platform]: Started robot_state node
Dec 12 07:19:11 user.notice create-platform: [INFO] [1702365551.633208088] [create-platform]: Configuring static_transform node
Dec 12 07:19:16 user.notice create-platform: [INFO] [1702365556.616494628] [create-platform]: Activating static_transform node
Dec 12 07:19:17 user.notice create-platform: [INFO] [1702365557.617855402] [create-platform]: Started static_transform node
Dec 12 07:19:17 user.notice create-platform: [INFO] [1702365557.651553503] [create-platform]: Ready to go!
Dec 12 07:19:19 user.notice ntpd: ntpd: bad address '3.irobot.pool.ntp.org'
Dec 12 07:19:24 user.notice ntpd: ntpd: bad address '2.irobot.pool.ntp.org'
```

> [mobility_monitor]: Lifecycle callback: on_configure

There is message of `mobility_monitor`. But, `mobility_monitor` is not displayed as the result of "ros2 node list".

> ntpd: bad address '3.irobot.pool.ntp.org'

This setting is default of Create 3. But this message was displayed.

**Comment by atinfinity** [comment]
@hilary-luo I'm investigating this problem. Could you give me your comment?

**Comment by atinfinity** [comment]
I checked log via Web server of Create 3.

```
Dec 12 08:43:06 9 user.notice ntpd: ntpd: setting time to 2023-12-12 08:43:06.613270 (offset +1541.708478s)
Dec 12 08:43:07 9 user.notice ntpd: Time has been adjusted
Dec 12 08:43:08 9 user.notice create-platform: [INFO] [1702370588.064755498] [create-platform]: Activating robot_state node
Dec 12 08:43:08 9 user.notice create-platform: [INFO] [1702370588.065135356] [robot_state]: Lifecycle callback: on_activate
Dec 12 08:43:09 9 user.notice create-platform: [INFO] [1702370589.067671780] [create-platform]: Started robot_state node
Dec 12 08:43:09 9 user.notice create-platform: [INFO] [1702370589.067877411] [create-platform]: Configuring static_transform node
Dec 12 08:43:13 9 user.notice create-platform: [INFO] [1702370593.888521380] [create-platform]: Activating static_transform node
Dec 12 08:43:14 9 user.notice create-platform: [INFO] [1702370594.996938131] [create-platform]: Started static_transform node
Dec 12 08:43:15 9 user.notice create-platform: [INFO] [1702370595.002020809] [create-platform]: Ready to go!
Dec 12 08:43:24 9 user.notice create-platform: [INFO] [1702370604.782943521] [system_health]: CPU usage: max 93 [%] mean 54 [%] RAM usage: 33/59 [MB]
Dec 12 08:43:38 9 user.notice mosquitto: 1702370618: New connection from 127.0.0.1 on port 1883.
Dec 12 08:43:38 9 user.notice mosquitto: 1702370618: New client connected from 127.0.0.1 as mosqpub/2161-iRobot-717 (c1, k60).
Dec 12 08:43:38 9 user.notice mosquitto: 1702370618: Client mosqpub/2161-iRobot-717 disconnected.
```

>  CPU usage: max 93 [%] mean 54 [%] RAM usage: 33/59 [MB]

I'm concerned that CPU usage is high.

> Client mosqpub/2161-iRobot-717 disconnected.

I'm concerned this message. Is the message okay?

**Comment by hilary-luo** [comment]
It sounds like you haven't configured the robot after the factory reset, did you reconfigure all of the networking etc? if so, did you reconfigure as simple discovery or discovery server?

**Comment by atinfinity** [comment]
I reconfigured network setting. As a result, I could not connect to RasPi4 via ssh. So, I try to install Raspberry Pi image.  
<https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image>

**Comment by atinfinity** [comment]
> So, I try to install Raspberry Pi image.

I installed Raspberry Pi image. As a result, this issue is resolved. So, I close this issue.
