### ISSUE TITLE
Simplification of TurtleBot4) Networking

### ISSUE THREAD

**Issue by alphalambdaepsilonxi** [turtlebot/turtlebot4#33]
I really like the concept of the Turtlebot4 - thanks a lot for designing it!
 
I would prefer if the icreate 3 is only connected to the Raspi4 using the USB interface to exchange data. It would be great to use the 2.4GHz Wifi only for setup and then disable it (not use it). 
Three reasons for the wish are - might cause instability since transfer of important data is stopped even during small wifi connection problems - additional effort for the use in corporate/campus networks (IT dislikes current concept with two separate wifi adapters) - simplicity.

**Comment by roni-kreinin** [comment]
This is something I am currently working on. See #26.

I am having some issues with routing multicast data from `usb0` to `wlan0` on the RPi. If you have any suggestions, please post them under #26.

Closing as duplicate.
