### ISSUE TITLE
 The display and LED do not turn on, and wired/wireless connections do not work.

### ISSUE THREAD

**Issue by gmchoi96** [turtlebot/turtlebot4#333]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Select One

### Package version

22.04 ros2 humble

### Type of issue

Other

### Actual behaviour

When I turn on Turtlebot, the LED light and display do not come on and wired/wireless connection is not possible. It seems to be a hardware problem.

![Turtlebot4](https://github.com/turtlebot/turtlebot4/assets/149559257/b1b73729-4d3d-405e-9aeb-dd210723fa46)

https://github.com/turtlebot/turtlebot4/assets/149559257/a921921d-0585-42ea-8548-d92e6f3ff8d2

**Comment by RustyCPR** [comment]
Hi @gmchoi96 
Can you please verify if the LCB ribbon cable is securely connected? Its loops underneath the PCB. 

![image](https://github.com/turtlebot/turtlebot4/assets/83372407/30b8cf19-ec61-4dea-8cbc-e0e103fc0b68)

**Comment by SangHyun-94** [comment]
@RustyCPR 
Hi 
I checked  LCB ribbon cable and it does not work even though I disconnected the cable and put it back in
it does not work

**Comment by RustyCPR** [comment]
Thanks @SangHyun-94  
I'll process an RMA for a replacement LCD. I have an existing support email with ROAS that I will reply to. 
Regards,
Rusty
