### ISSUE TITLE
OAK-D-Lite RGB/Stereo help

### ISSUE THREAD

**Issue by FishDentistry** [turtlebot/turtlebot4#335]
### Robot Model

Turtlebot4 Lite

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

apt show ros-$ROS_DISTRO-depthai ros-$ROS_DISTRO-depthai-ros ros-$ROS_DISTRO-depthai-bridge ros-$ROS_DISTRO-depthai-ros-msgs ros-$ROS_DISTRO-depthai-ros-driver

Package: ros-humble-depthai

Version: 2.23.0-1jammy.20231122.172531

Priority: optional

Section: misc

Maintainer: Sachin Guruswamy <sachin@luxonis.com>

Installed-Size: 20.8 MB

Depends: libc6 (>= 2.34), libgcc-s1 (>= 4.2), libopencv-core4.5d (>= 4.5.4+dfsg), libopencv-imgproc4.5d (>= 4.5.4+dfsg), libstdc++6 (>= 12), libopencv-dev, libusb-1.0-0-dev, nlohmann-json3-dev, ros-humble-ros-workspace

Homepage: https://www.luxonis.com/

Download-Size: 10.6 MB

APT-Manual-Installed: no

APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages

Description: DepthAI core is a C++ library which comes with firmware and an API to interact with OAK Platform

Package: ros-humble-depthai-ros

Version: 2.8.2-1jammy.20231206.084730

Priority: optional

Section: misc

Maintainer: sachin <sachin@luxonis.com>

Installed-Size: 43.0 kB

Depends: ros-humble-depthai, ros-humble-depthai-bridge, ros-humble-depthai-descriptions, ros-humble-depthai-examples, ros-humble-depthai-filters, ros-humble-depthai-ros-driver, ros-humble-depthai-ros-msgs, ros-humble-ros-workspace

Download-Size: 6,128 B

APT-Manual-Installed: yes

APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages

Description: The depthai-ros package

Package: ros-humble-depthai-bridge

Version: 2.8.2-1jammy.20231205.191714

Priority: optional

Section: misc

Maintainer: Sachin Guruswamy <sachin@luxonis.com>

Installed-Size: 456 kB

Depends: libc6 (>= 2.32), libgcc-s1 (>= 3.3.1), libopencv-calib3d4.5d (>= 4.5.4+dfsg), libopencv-core4.5d (>= 4.5.4+dfsg), libopencv-imgcodecs4.5d (>= 4.5.4+dfsg), libopencv-imgproc4.5d (>= 4.5.4+dfsg), libstdc++6 (>= 11), libboost-dev, libopencv-dev, ros-humble-camera-info-manager, ros-humble-composition-interfaces, ros-humble-cv-bridge, ros-humble-depthai, ros-humble-depthai-ros-msgs, ros-humble-image-transport, ros-humble-rclcpp, ros-humble-robot-state-publisher, ros-humble-ros-environment, ros-humble-sensor-msgs, ros-humble-std-msgs, ros-humble-stereo-msgs, ros-humble-tf2, ros-humble-tf2-geometry-msgs, ros-humble-tf2-ros, ros-humble-vision-msgs, ros-humble-xacro, ros-humble-ros-workspace

Download-Size: 126 kB

APT-Manual-Installed: no

APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages

Description: The depthai_bridge package

Package: ros-humble-depthai-ros-msgs

Version: 2.8.2-1jammy.20231205.183421

Priority: optional

Section: misc

Maintainer: Sachin Guruswamy <sachin@luxonis.com>

Installed-Size: 1,723 kB

Depends: libc6 (>= 2.14), libgcc-s1 (>= 3.3.1), libpython3.10 (>= 3.10.0), libstdc++6 (>= 11), ros-humble-fastcdr, ros-humble-builtin-interfaces, ros-humble-geometry-msgs, ros-humble-rclcpp, ros-humble-rosidl-default-generators, ros-humble-sensor-msgs, ros-humble-std-msgs, ros-humble-vision-msgs, ros-humble-ros-workspace

Download-Size: 129 kB

APT-Manual-Installed: no

APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages

Description: Package to keep interface independent of the driver

Package: ros-humble-depthai-ros-driver

Version: 2.8.2-1jammy.20231206.083259

Priority: optional

Section: misc

Maintainer: Adam Serafin <adam.serafin@luxonis.com>

Installed-Size: 2,786 kB

Depends: libc6 (>= 2.34), libconsole-bridge1.0 (>= 1.0.1+dfsg2), libgcc-s1 (>= 3.3.1), libopencv-core4.5d (>= 4.5.4+dfsg), libopencv-imgproc4.5d (>= 4.5.4+dfsg), libstdc++6 (>= 12), libtinyxml2-9 (>= 8.0.0), ros-humble-ament-cmake-auto, ros-humble-camera-calibration, ros-humble-cv-bridge, ros-humble-depthai, ros-humble-depthai-bridge, ros-humble-depthai-descriptions, ros-humble-depthai-examples, ros-humble-depthai-ros-msgs, ros-humble-diagnostic-msgs, ros-humble-diagnostic-updater, ros-humble-image-pipeline, ros-humble-image-transport, ros-humble-image-transport-plugins, ros-humble-pluginlib, ros-humble-rclcpp, ros-humble-rclcpp-components, ros-humble-sensor-msgs, ros-humble-std-msgs, ros-humble-std-srvs, ros-humble-vision-msgs, ros-humble-ros-workspace

Download-Size: 617 kB

APT-Manual-Installed: no

APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages

Description: Depthai ROS Monolithic node.

### Type of issue

Camera

### Expected behaviour

I have a simple subscriber node that subscribes to the /oakd/rgb/preview/image_raw topic and saves the images it receives using CVBridge/OpenCV. I'd like to be able to do the same with depth images received from the camera, from the /stereo/depth topic.

### Actual behaviour

The saved images from the topic are of a 250x250 resolution. Is there any way to increase this resolution? Or is there another topic better suited for this purpose? Also, I've read through the issues posted here regarding using the stereo camera and was wondering if it was possible to enable this feature without having to build from source. That is, is it possible to edit the relevant config file directly? 

### To Reproduce

The 250x250 images are visible in Rviz after adding an Image display. They appear the same there as they do when saved by my script

**Comment by atinfinity** [comment]
@FishDentistry 

> The saved images from the topic are of a 250x250 resolution.

This resolution is defined in [turtlebot4_bringup/config/oakd_lite.yaml](https://github.com/turtlebot/turtlebot4_robot/blob/humble/turtlebot4_bringup/config/oakd_lite.yaml).

```yaml
i_preview_size: 250
```

And, you can find the following parameter in this file.
As a result, `depthai_ros_driver` does not publish high resolution image.
If you need high resolution image, please set `true` to this parameter.

```yaml
i_publish_topic: false
```

> I'd like to be able to do the same with depth images received from the camera

Please see [turtlebot4_bringup/config/oakd_lite.yaml](https://github.com/turtlebot/turtlebot4_robot/blob/humble/turtlebot4_bringup/config/oakd_lite.yaml).
This configuration enabled only RGB camera.

I think that the following document may be helpful to capture depth image.
<https://github.com/luxonis/depthai-ros/tree/humble?tab=readme-ov-file#list-of-parameters>

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
