### ISSUE TITLE
Changing default network name and pass which is turtlebot4

### ISSUE THREAD

**Issue by Elhamhasanialavy** [turtlebot/turtlebot4#336]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

My question is about network setting!

### Type of issue

Networking

### Expected behaviour

during the process of 
turtlebot4-setup
I followed all the instructions and according to the picture it showd that we may change the SSID from turtlebot4 to MyNetwork and its password from Turtlebot4 to PassWord. 

I do clearly now that I only supposed to change the mode into client!

### Actual behaviour

After this change, I noticed all of my setting has been changed ( I do not have turtlbot4 as a network right now after booting up the bot as my network name has been changed). How can I restore previous setting!

### Error messages

```bash
In my turtlebot4, ip has changed to unknown
```

### To Reproduce

turtlebot4-setup

Client mode
SSID: MyNetwork
Password:MyPassword
Save

**Comment by RustyCPR** [comment]
Hi @Elhamhasanialavy 
If you want to restart everything then you can re-install the image:  https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#recovering-the-raspberry-pi

You can reset using the [setup tool](https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_setup.html#configuration-tools) but that requires for them to reconnect to the robot.
