### ISSUE TITLE
Problem in the /scan topic of turtlebot4 Lite

### ISSUE THREAD

**Issue by yoraoui** [turtlebot/turtlebot4#337]
### Robot Model

Turtlebot4 Lite

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

humble

### Expected behaviour

Hello, I expect that the /scan topic returns the data of the Lidar. 

### Actual behaviour

I don't receive any data from the lidar after I run these commands:
ros2 service call /stop_motor std_srvs/srv/Empty {}
ros2 service call /stop_motor std_srvs/srv/Empty {}

Also the Lidar spinning interrupts. 

### Error messages

```bash
Jan 07 12:41:57 ubuntu turtlebot4-start[1074]: [rplidar_composition-4] [ERROR] [1704631317.857308900] [rplidar_composition]: Failed to set scan mode
Jan 07 12:41:59 ubuntu turtlebot4-start[1074]: [rplidar_composition-4] [INFO] [1704631319.858090337] [rplidar_composition]: Start
```

### To Reproduce

![Screenshot from 2024-01-08 16-28-49](https://github.com/turtlebot/turtlebot4/assets/51831506/5e9e801c-b7c1-45b3-bbc1-0492bf14e695)

**Comment by hilary-luo** [comment]
@yoraoui That service is for the lidar motor and if you stop the lidar motor then it will be stopped and will not report data anymore. Start the lidar motor to resume getting data. Reassigning this issue as a troubleshooting issue.

**Comment by yoraoui** [comment]
I stopped and restarted with

ros2 service call /start_motor std_srvs/srv/Empty {}

However, the issue is still happening.

--

Pr. RAOUI Younès
Physics department,
Laboratory Conception and Systems,
Faculty of Sciences,
University Mohammed V in Rabat,
Adress : 4 Avenue Ibn Battouta, B.P. 1014, Rabat, Morocco,
GSM : +212 6 59 86 27 05
Email : ***@***.***



Le lun. 8 janv. 2024 à 16:57, Hilary Luo ***@***.***> a
écrit :

**Comment by RustyCPR** [comment]
Hi @yoraoui,
What occurs when you run the lidar with the `command:` `ros2 launch turtlebot4_bringup rplidar.launch.py`  ? 

If you still don't see anything on the `/scan ` topic can you please verify the RPLIDAR UDEV rules exist and try installing it again by following these instructions: https://turtlebot.github.io/turtlebot4-user-manual/software/sensors.html#connecting
