### ISSUE TITLE
Launching SLAM Locally

### ISSUE THREAD

**Issue by halimimaha** [turtlebot/turtlebot4#338]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

.

### Type of issue

Navigation (SLAM, Nav2 etc.)

### Expected behaviour

Hello,

I have a small question, please. How can I launch SLAM directly from the user's computer instead of launching it via SSH?

Thank you.

### Actual behaviour

.

### To Reproduce

.

**Comment by smatarCPR** [comment]
Hello,
Thank you for reaching out on our Github page. To launch SLAM on a remote computer without needing to SSH, you can follow the steps below:

1. On your remote computer ensure: you are running the same version of ROS 2 (Humble), and install the Turtlebot4 desktop packages with: `sudo apt update && sudo apt install ros-humble-turtlebot4-desktop`
2. Connect your Turtlebot to the Wi-Fi network (if you haven't already):
     1.  SSH into the Raspberry Pi and run the command `turtlebot4-setup`
     2. Enter the Wi-Fi Setup sub-menu
     3. Change the Wi-Fi mode from Access Point mode to Client Mode
     4. Change the SSID to the name of your Wi-Fi network
     5. Change the password to the Wi-Fi network password
     6. Select the save option you should now be back at the main menu of the Turtlebot setup menu
     7. Select the Apply Settings and confirm the changes being made. The Raspberry Pi should reboot and connect to your Wi- 
         Fi network
8. Run the following commands on your remote computer to connect the ROS environment from your remote computer to the Turtlebot 4: `source /opt/ros/humble/setup.bash` `export RMW_IMPLEMENTATION=rmw_fastrtps_cpp` `export ROS_DOMAIN_ID=0`
9. You can check that the connection has been made by running `ros2 topic echo /ip`, the IP address printed should match the one seen on the OLED display.
10. Setup the Create3 unit to communicate with the Raspberry Pi through Simple Discovery or through a Discovery server (if you are only using a single Turtlebot it is recommended you setup a Discovery Server:
Discovery Server:
    1.  For setting up a Discovery Server ensure that the Create3 has been updated to the latest firmware and has been factory reset to disconnect the Create3 from Wi-Fi networks (NOTE: The Create3 is not the same as the Raspberry Pi found in the Turtlebot, the Pi should still be connected to a Wi-Fi network)
    2. SSH into the Raspberry Pi and open the setup utility again with `turtlebot4-setup`
    3. Enter ROS Setup sub-menu, in there enter the Discovery Server sub-menu
    4. Enable the Discovery by setting the Enable to True
    5. Leave the IP address and Port as 127.0.0.1 and 11811
    6. Save the settings, navigate to the main menu, and apply settings. Exit the setup tool.
    7. Run the command `turtlebot4-source` to apply the new settings. Restart ROS with `turtlebot4-daemon-restart` or `ros2 daemon stop; ros2 daemon start`
    8. When you hear the Create3 chime, run the command `ros2 topic list` and ensure all ROS topics appear (you may need to run the command twice)
    9. Close the SSH session and on your remote computer obtain the setup script for Discovery Server setup using the following command `wget -qO - https://raw.githubusercontent.com/turtlebot/turtlebot4_setup/humble/turtlebot4_discovery/configure_discovery.sh | bash <(cat) </dev/tty`
    10. You will be prompted to enter the following: The Raspberry Pi Wi-Fi IP address, The Discovery Server IP address (Raspberry Pi IP by default), The Discovery Server port (11811 by default), The ROS_DOMAIN_ID of your robot (0 by default).
    11. Run the command `source ~/.bashrc` to have the changes take effect. You can verify this by running `ip route` and the output should be something along the lines of `192.168.186.0/24 via 10.0.0.121 dev wlp0s20f3` where 10.0.0.121 would be your Raspberry Pi IP, and wlp0s20f3 would be your Wi-Fi interface.
    12. Restart ROS 2 by running `ros2 daemon stop; ros2 daemon start`
Simple Discovery:
    1.  Access the Create3 Webserver by opening a web browser and going to the Raspberry Pi IP port 8080 (e.g. if the IP for your Pi is 10.0.0.121 you would go to 10.0.0.121:8080)
    2. Navigate to the connect tab and under the Connect to a 2.4 GHz Wi-Fi Network enter your Wi-Fi SSID and password in the respective text boxes (NOTE: The Create3 can only connect to 2.4 GHz Wi-Fi networks, it will not connect to 5 GHz networks).
    3. Click on the Connect button, the Create3 should connect to a network and play a chime sound
    4. Navigate to the Application tab and set ROS 2 Domain ID to 0, ROS 2 Namespace to an empty string, and RMW_IMPLEMENTATION to the [default](https://turtlebot.github.io/turtlebot4-user-manual/setup/networking.html#dds) for your ROS 2 version.
    5. Make sure that the Fast DDS discover server is disabled.
    6. On your remote computer create a directory named /etc/turtlebot4/ and within the directory create a file named setup.bash
    7. Edit the setup.bash file you just created and add the following lines 
    source /opt/ros/humble/setup.bash
    export ROS_DOMAIN_ID=0
    export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    8.  Save the file and edit the ~/.bashrc by adding the following line source /etc/turtlebot4/setup.bash
11. After setup you should be able to view the list of ROS topics from the Turtlebot by running `ros2 topic list`.
12. Install the Turtlebot4 Navigation packages to your remote computer by running `sudo apt install ros-humble-turtlebot4-navigation`
13. You should be able to launch SLAM from your remote computer, without having to SSH into the Turtlebot4, by running `ros2 launch turtlebot4_navigation slam.launch.py`

These instructions can be found in more detail on our online user manual: https://turtlebot.github.io/turtlebot4-user-manual/


Let me know how this process works for you.
Best Regards,
Saif
