### ISSUE TITLE
 Issue with Bluetooth Pairing of Controller and Robot

### ISSUE THREAD

**Issue by vubavikranth** [turtlebot/turtlebot4#342]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

![grafik](https://github.com/turtlebot/turtlebot4/assets/156912165/4c273706-0546-4dd0-8ea6-2a12cb726518)

### Type of issue

Other

### Expected behaviour

The controller and robot should be able to connect seamlessly over Bluetooth, either through manual or automatic pairing methods.

### Actual behaviour

The current behavior is that the pairing process fails, and the controller is unable to establish a connection with the robot. I have attached screenshots below that display the responses encountered during the pairing attempts.
![Pairing_Blueetoth1](https://github.com/turtlebot/turtlebot4/assets/156912165/3c358b07-9ddf-4edc-8c53-2cb5dd8bd8d2)
![Bluettoth_Pairing](https://github.com/turtlebot/turtlebot4/assets/156912165/361a6a02-8b0c-48e8-b0e4-4192c60c9dc3)

### Error messages

```bash
connect A0:5A:5D:=B:F9:77 Connected: yes
Failed to connect : org.bluez.Error.Failed br-connection-create-socket
[CHG] Device A0:5A:5D:=B:F9:77 Connected: yes 
[CHG] Device A0:5A:5D:=B:F9:77 Connected: no

[Wireless Controller] #connect A0:5A:5D:=B:F9:77
Attempting to comnnect to A0:5A:5D:=B:F9:77
Failed to connect: org.bluez.Error.InProgress br-connection-busy
Failed to connect: org.bluez.Error.Failed br-connection-create-socket
[CHG] Device A0:5A:5D:=B:F9:77 Connected: no
```

### To Reproduce

   1. Turn on the robot and controller.
   2. Enable the automatic pairing feature on the controller.
   3. Wait for the controller to automatically detect and attempt to connect with the robot.
   4. Observe the response received upon attempting to connect.

### Other notes

it also says there is a namespace that is not found how would I find it?

**Comment by atinfinity** [comment]
@vubavikranth I also encountered a similar problem.

I read <https://turtlebot.github.io/turtlebot4-user-manual/troubleshooting/faq.html#3-no-default-controller-available>.
And, I performed the following steps. As a result, I could connect to gamepad.

## 1. disable hciuart

```shell
sudo systemctl disable hciuart
sudo reboot
```

## 2. restart hciuart

```shell
sudo systemctl restart hciuart
```

## 3. connect gamepad

```shell
sudo bluetoothctl
connect MAC_ADDRESS
```

**Comment by vubavikranth** [comment]
@atinfinity I tried all and the "sudo systemctl restart hciuart" does not respond. And now even the dialogue box for the command " sudo bluetoothctl " also does not work like earlier.

**Comment by vubavikranth** [comment]
![pairing_bluetooth2](https://github.com/turtlebot/turtlebot4/assets/156912165/de5fc73d-7a39-4983-81b8-79b5d6c11de7)
The latest issue with the pairing of the bluetooth has evolved.

**Comment by smatarCPR** [comment]
Hello @vubavikranth ,
Apologies for the late reply on this. Would it be possible to try the following steps:
1. Open the bluetoothctl utility: `sudo bluetoothctl`
2. Remove the controller by running `remove A0:5A:5D:0B:F9:77`
3. Run the command `paired-devices`
4. Run the command `scan on` and place the controller into pairing mode
5. Wait for the controller MAC address to appear in the list of devices then run the command: `trust A0:5A:5D:0B:F9:77`
6. Run the command `pair A0:5A:5D:0B:F9:77`
7. Run the command `connect A0:5A:5D:0B:F9:77`
See if this method allows for connecting the controller. If the above process is unsuccessful, try resetting the controller using a SIM tool or a straightened paper clip, press the button for more than 5 seconds to reset the controller. 
![image](https://github.com/turtlebot/turtlebot4/assets/110051413/4fbc935a-2583-416c-9c38-b249544f8cf4)

Afterwards, try the pairing process again and see if the controller pairs.

Let me know how this process works for you. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by azhar-maxtech** [comment]
> Hello @vubavikranth , Apologies for the late reply on this. Would it be possible to try the following steps:
> 
> 1. Open the bluetoothctl utility: `sudo bluetoothctl`
> 2. Remove the controller by running `remove A0:5A:5D:0B:F9:77`
> 3. Run the command `paired-devices`
> 4. Run the command `scan on` and place the controller into pairing mode
> 5. Wait for the controller MAC address to appear in the list of devices then run the command: `trust A0:5A:5D:0B:F9:77`
> 6. Run the command `pair A0:5A:5D:0B:F9:77`
> 7. Run the command `connect A0:5A:5D:0B:F9:77`
>    See if this method allows for connecting the controller. If the above process is unsuccessful, try resetting the controller using a SIM tool or a straightened paper clip, press the button for more than 5 seconds to reset the controller.
>    ![image](https://private-user-images.githubusercontent.com/110051413/309877549-4fbc935a-2583-416c-9c38-b249544f8cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTM3NDEsIm5iZiI6MTcwOTc1MzQ0MSwicGF0aCI6Ii8xMTAwNTE0MTMvMzA5ODc3NTQ5LTRmYmM5MzVhLTI1ODMtNDE2Yy05YzM4LWIyNDk1NDRmOGNmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxOTMwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVlY2U1ZmM5OTk0NWViZTFiOTFjNmNjNTk0NjEwYWM2MTBlMzY3MDQ1MDRhNWNhY2M2ZDMzNmNlZmVhMWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nrv4Vr-GWCjGDAU34nZ8d2XkRk2NWoYbBYcgD1BmjF4)
> 
> Afterwards, try the pairing process again and see if the controller pairs.
> 
> Let me know how this process works for you. Looking forward to hearing from you soon. Best Regards, Saif

Hi, I am facing same issue right now and tried all the solutions advised by you but still no positive result.

**Comment by albertuswh** [comment]
i had the same issue here, it doesnt work

**Comment by smatarCPR** [comment]
Hello @albertuswh ,
I am very sorry to hear that. Are you seeing the light at the top of controller shine during the pairing process? What colour is the light flashing? 

Are you able to pair the controller with another bluetooth enabled device (such as a mobile phone or other computer)?

Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by vubavikranth** [comment]
Hello Saif,

Initially even I thought there should be wrong with the controller but it
works perfectly fine on a PC and also iPad .
The main issue is that the connection after the rebooting the robot and
while setting up WiFi and respectively Bluetooth with the command
turtlebot4-setup
It gets paired and connected but its operation does not reflect on the
robot. For example the robot doesn’t move and neither am I able to control
the options on the robots display.
Please let me know what you think regarding this issue.
Thanking you in advance.

Best regards,
Vikranth

**Comment by albertuswh** [comment]
Hi @smatarCPR 
The light was solid white, and I tried to connect the controller to my phone and it works fine.
I tried to connect the controller manually just as in the manual also i tried yours. but none of them seems to work.
I tried to figure out why, I think it's after I updated my Raspberry Pi. could it be the cause of it?

**Comment by albertuswh** [comment]
I resolved the issue by reflashing the RPi4 image, and I didnt update the RPi4. Then I do the sudo bluetoothctl command and just connect to the controller MAC address.

**Comment by vubavikranth** [comment]
Hey Albert ,
But are you able to move the robot with the help of a controller?

**Comment by smatarCPR** [comment]
Hello @vubavikranth ,
Would you be able to test the following pairing script? To run this script, extract the file and run the following set of commands:
`sudo apt install expect`
`chmod 755 p4pair`
`./p4pair <MAC of P4 Wireless Controller>`
Ensure that the controller is in pairing mode when the script is run. Let me know how this recommendation works for you. Looking forward to hearing from you soon.
Best Regards,
Saif M.

[p4pair.zip](https://github.com/turtlebot/turtlebot4/files/14654150/p4pair.zip)

**Comment by albertuswh** [comment]
Hi @vubavikranth 
yes i can connect and move the robot using controller. But each time its disconnected, I need to manually connect it again.
then I tried to update the RPi 4, then when i try to connect the bluetootg controller it wont connect

**Comment by smatarCPR** [comment]
Hello @vubavikranth ,
Have you tried using the p4pair script? Was it successful? Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
