### ISSUE TITLE
Issue with Source Installation

### ISSUE THREAD

**Issue by vubavikranth** [turtlebot/turtlebot4#343]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

![grafik](https://github.com/turtlebot/turtlebot4/assets/156912165/6347e03a-cb33-48c7-9c54-aaf45bb69ecd)

### Type of issue

Other

### Expected behaviour

Clear message of the installation of the package and cloning of the git repository 

### Actual behaviour

Fails to locate the file or the reposoitory 
![grafik](https://github.com/turtlebot/turtlebot4/assets/156912165/881ef790-4ad2-46ac-bd65-833aaff9606a)

### Error messages

```bash
~bash: cd: /home/ubuntu/turtlebot4_ws/src: No such file or directry
given path 'src' does not exist
```

### To Reproduce

1. run the command cd ~/turtlebot4_ws/src
git clone https://github.com/turtlebot/turtlebot4.git -b humble
2. Install dependencies 
cd ~/turtlebot4_ws
rosdep install --from-path src -yi --rosdistro humble
3. Build packages 
source /opt/ros/humble/setup.bash
colcon build --symlink-install

### Other notes

![grafik](https://github.com/turtlebot/turtlebot4/assets/156912165/756eac70-ea58-4fcd-9350-0ac2bcd95eae)

**Comment by smatarCPR** [comment]
Hello,
Thank you for reaching out on the Turtlebot 4 GIthub. Has the folder: turtlebot4_ws been created? Would it be possible to share the list of directories found in root (run `ls`).

If the directory turtlebot4_ws has not been created:
1. Create the directory `mkdir -p turtlebot4_ws/src`
2. Clone the github source code into turtlebot4_ws/src:
        `cd turtlebot4_ws/src`
        `git clone https://github.com/turtlebot/turtlebot4.git -b humble`
3. Install dependencies:
        `cd ~/turtlebot4_ws
         rosdep install --from-path src -yi --rosdistro humble`
4. Build packages
        `source /opt/ros/humble/setup.bash`
        `colcon build --symlink-install`

Let me know how this recommendation works for you.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
