### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by halimimaha** [turtlebot/turtlebot4#344]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Built from Source

### Package version

.

### Type of issue

Other

### Expected behaviour

.

### Actual behaviour

hello i have 2 Turtlebot4 and i have those error on logs what that mean ? and how to fix them ? 

first tb4 : 
Jan 16 15:00:40 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/aos_kvs_helper.c:51 errno:No such file or directory) Failed to stat file network.watchdog_interval_min
Jan 16 15:00:40 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/kvs_json.c:21 errno:No such file or directory) Failed to retrieve key "network.watchdog_interval_min"
Jan 16 15:00:40 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/aos_kvs_helper.c:51 errno:No such file or directory) Failed to stat file robot.disc_reconnect_sleep_sec
Jan 16 15:00:40 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/kvs_json.c:21 errno:No such file or directory) Failed to retrieve key "robot.disc_reconnect_sleep_sec"
Jan 16 15:00:40 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/aos_misc.c:86 errno:No such file or directory)  MODULE : network_manager CMD (sudo network_dhcp_arp_control.sh disable) failed with status = 1, ret = 256
Jan 16 15:00:46 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/mqtt_client.c:695 errno:Resource temporarily unavailable) firr_transfer failed
Jan 16 15:00:46 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/main.c:169 errno:Resource temporarily unavailable) Error publishing sta:0 FIRR request.
Jan 16 15:01:05 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/mqtt_client.c:695) firr_transfer failed
Jan 16 15:01:05 iRobot-044E749753D24C36A7B849C57D19487C daemon.err network[1470]: [ERROR] (src/discovery.c:407) falied to get cap from tsprime

seconde tb4 : 

Jan 17 14:00:37 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/aos_kvs_helper.c:51 errno:No such file or directory) Failed to stat file robot.disc_reconnect_sleep_sec
Jan 17 14:00:37 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/kvs_json.c:21 errno:No such file or directory) Failed to retrieve key "robot.disc_reconnect_sleep_sec"
Jan 17 14:00:37 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/aos_kvs_helper.c:51 errno:No such file or directory) Failed to stat file network.watchdog_interval_min
Jan 17 14:00:37 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/kvs_json.c:21 errno:No such file or directory) Failed to retrieve key "network.watchdog_interval_min"
Jan 17 14:00:37 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/aos_misc.c:86 errno:No such file or directory)  MODULE : network_manager CMD (sudo network_dhcp_arp_control.sh disable) failed with status = 1, ret = 256
Jan 17 14:00:43 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/mqtt_client.c:695 errno:Resource temporarily unavailable) firr_transfer failed
Jan 17 14:00:43 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/main.c:169 errno:Resource temporarily unavailable) Error publishing sta:0 FIRR request.
Jan 17 14:01:04 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/mqtt_client.c:695 errno:Resource temporarily unavailable) firr_transfer failed
Jan 17 14:01:04 iRobot-0676046B33C144E188F8A3337F160B2C daemon.err network[1467]: [ERROR] (src/discovery.c:407 errno:Resource temporarily unavailable) falied to get cap from tsprime

### To Reproduce

.

**Comment by smatarCPR** [comment]
Hello,
Thank you for reaching out on the Turtlebot Github support page. From the logs provided it seems that there is a network error on the units. Have you noticed any network related issues with these units?

I notice you mentioned building the unit from source. Were you unable to install using the Turtlebot 4 packages using apt?

My recommendation would be to reflash the Raspberry Pi SD card with the latest installation of ROS Humble following the instructions found here:
https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image

Let me know how this recommendation works for you.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
