### ISSUE TITLE
ROS DOMAIN ID saturated

### ISSUE THREAD

**Issue by halimimaha** [turtlebot/turtlebot4#346]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

.

### Type of issue

Navigation (SLAM, Nav2 etc.)

### Expected behaviour

.

### Actual behaviour

the problem I encountered is that: when I launch more than a single robot, everything crashes and nothing launches correctly, I knew where the problem comes from: all the robots I have are in the same ROS_DOMAIN_ID but each has its own namespace, as soon as I change the ROS_DOMAIN_ID for each robot everything is good but my codes are made for the same ROS_DOMAIN_ID I cannot communicate with all the robots, how can I fix this?

### To Reproduce

i launch those command for each robot, i have three :
ros2 launch turtlebot4_navigation localization.launch.py map:=second_floor_map.yaml namespace:=/robot1

ros2 launch turtlebot4_navigation nav2.launch.py namespace:=/robot1

ros2 launch turtlebot4_viz view_robot.launch.py namespace:=/robot1

**Comment by RustyCPR** [comment]
Hi @halimimaha 
Where are you launching the commands - on the RPi? or your remote PC? 

Are you running the RPi on 2.4GHz or 5GHz WiFi? 
Can you please send us some logs with the issue is occurring: https://iroboteducation.github.io/create3_docs/webserver/logs/

Thanks,
Rusty

**Comment by halimimaha** [comment]
thanks @RustyCPR  for ur reply !

i lanch the two first commands on the RPI and the third one on my PC.

The  RPi is running on 5GHz WiFi. 

Just for ur info the issue was fixed with a bridge between every ROS DOMAIN ID assigned to the robots !
Thank you so much for ur help !
