### ISSUE TITLE
Bumper cannot be disabled

### ISSUE THREAD

**Issue by halimimaha** [turtlebot/turtlebot4#353]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Actual behaviour

I followed this tutorial: https://iroboteducation.github.io/create3_docs/api/reflexes/ but when I send the command to disable the bumber it doesn't work, the bumber is still activate, any suggestions ? 

### To Reproduce

i sent this command : 

ros2 param set /robot1/motion_control reflexes.REFLEX_BUMP false

i tied also to add "reflexes.REFLEX_BUMP: false" in the end of this script in web server of create 3 :

motion_control:
ros__parameters:
safety_override: "none"
reflexes.REFLEX_BUMP: "false"

**Comment by nisarganc** [comment]
It worked when I added these lines to ROS 2 parameters file in web server of create 3:
motion_control:
  ros__parameters:
    safety_override: "full"
    reflexes_enabled: false

Note that false is a boolean and not a string!!

**Comment by nisarganc** [comment]
I had been facing the same issue and following these steps helped me disable all the reflexes. 
1. Update the Create 3 firmware to latest version (H2.6) as well as all packages on Raspberry Pi packages (sudo apt update && sudo apt upgrade)
2. Edit ros config script in web server of Create 3 as follows:
/robot1/motion_control:
    ros__parameters:
        safety_override: "full"
        reflexes_enabled: false

Note that new firmware update asks you to add namespace of the robot for the motion_control node and reflex parameters are boolean and not string.
