### ISSUE TITLE
Switch on turtlebot 4 without docking station

### ISSUE THREAD

**Issue by CycleMark** [turtlebot/turtlebot4#357]
### Robot Model

Turtlebot4 Lite

### ROS distro

Galactic

### Networking Configuration

Discovery Server

### OS

Ubuntu 20.04

### Built from source or installed?

Installed

### Package version

Galatic

### Type of issue

Other

### Expected behaviour

For the life of me I can't find the answer to this. Is it possible to power on the TB4 without having to place in on the dock? 

Thanks

Mark

### Actual behaviour

Power on bot without dock

### To Reproduce

N/A

**Comment by hilary-luo** [comment]
No, unfortunately you do need to place it on the docking station to turn it on. This restriction comes from the create3 base that the robot is built from.

**Comment by CycleMark** [comment]
OKay thanks - an annoying "feature" - will close the issue [if anyone finds a way to hack around this would love to know]

Cheers

Mark
