### ISSUE TITLE
ROS2 Comms Issues

### ISSUE THREAD

**Issue by CycleMark** [turtlebot/turtlebot4#370]
### Robot Model

Turtlebot4 Lite

### ROS distro

Galactic

### Networking Configuration

Discovery Server

### OS

Ubuntu 20.04

### Built from source or installed?

Installed

### Package version

galatic

### Type of issue

Networking

### Expected behaviour

Hi,

Having a lot of problems with the reliability of TB4 internal comms. To limits the issues this is all being done on the robot alone (i.e. no PC involved)

I get very intermitted service and/or topic communications. As an example regardless of if I bring ROS2 up as a service or from the command line (ros2 service call /stop_motor std_srvs/srv/Empty)

More often than not ROS2 can't communicate with, in this example, services. As you can see below it can "see" the service. But ask if to interact with it is doesn't know its there - just waits indefinitely for it to come up. Similar cases happen for topics. ROS2 can see them but doesn't always get data from them (ros2 topic echo <topic_name>) for example.

![image](https://github.com/turtlebot/turtlebot4/assets/27418725/20e75651-cc2e-4fdd-be67-205a46bf8e77)

DDS set up is as follows:

![image](https://github.com/turtlebot/turtlebot4/assets/27418725/f8f231d5-a064-4be3-b8d6-b5d1e80e41c1)

If this a known problem? Do you have any suggestions on how to improve/fix the situation. Sometimes it works, sometimes not. Power cycling the iCreate doesn't make a difference. I want to have the robot/system come up and just work.

Thanks

Mark

### Actual behaviour

Intermittent/Unreliable comms from services/topics either at command line or application/api

### To Reproduce

See command lines above

**Comment by smatarCPR** [comment]
Hello @CycleMark ,
Thank you for reaching out on the official Turtlebot 4 Github page. With regards to your ongoing issues is it possible to upgrade the Turtlebot 4 to use Ubuntu 22.04 and ROS 2 Humble? We find that this version of ROS 2 and Ubuntu to be more stable and efficient compared to ROS Galactic.

To upgrade to ROS 2 Humble:
1. Find the latest TurtleBot 4 Raspberry Pi images at http://download.ros.org/downloads/turtlebot4/
2. Download the latest image and extract it.
3. Power off your robot and then remove the microSD card from the Raspberry Pi.
4. Insert the microSD card into your PC. You may need an adapter.
5. Install the imaging tool dcfldd: `sudo apt install dcfldd`
6. Identify the SD card using `sudo fdisk -l`
7. If you wish to back up the contents on the SD card: `sudo dd if=/dev/<SD_NAME> of=<IMAGE_PATH> bs=1M`
8. Get the SD flash script from turtlebot4_setup: `wget https://raw.githubusercontent.com/turtlebot/turtlebot4_setup/humble/scripts/sd_flash.sh`
9. Flash the SD Card: `bash sd_flash.sh /path/to/downloaded/image`
10. Be sure to flash the corresponding firmware to the Create3 Unit.

If you do upgrade to ROS 2 Humble, be sure to continue to use Discovery server. After setting up discovery server if you find the issue persists, try setting up NTP syncing between the Raspberry Pi and the Create3 Unit by running the command `server 192.168.186.3 prefer iburst minpoll 4 maxpoll 6` on the Raspberry Pi.

Let me know how this recommendation works for you. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by CycleMark** [comment]
Thanks - I'll give this a go and revert

**Comment by smatarCPR** [comment]
Hello @CycleMark ,
Any update on this? Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by CycleMark** [comment]
Hi Saif,

Sorry too time to reply. Successfully upgraded ROS version and the Create 3. Pleased to report it looks much more stable now. A little slow to respond sometime but the topics are at least there - consistently.

Thanks for the help

Mark

**Comment by smatarCPR** [comment]
Hello @CycleMark ,
That is good to hear. I will go ahead and close this issue. Should you encounter any follow up issues, do not hesitate to reach out by simply replying to this thread or opening up a new issue.
Best Regards,
Saif
