### ISSUE TITLE
Rplidar is not working

### ISSUE THREAD

**Issue by ajjaya18** [turtlebot/turtlebot4#384]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

Package: ros-humble-turtlebot4-simulator
Version: 1.0.1-1jammy.20240304.161058
Priority: optional
Section: misc
Maintainer: rkreinin <rkreinin@clearpathrobotics.com>
Installed-Size: 42.0 kB
Depends: ros-humble-turtlebot4-ignition-bringup, ros-humble-turtlebot4-ignition-gui-plugins, ros-humble-turtlebot4-ignition-toolbox, ros-humble-ros-workspace
Download-Size: 5,112 B
APT-Manual-Installed: yes
APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages
Description: TODO: Package description

### Type of issue

LIDAR

### Expected behaviour

I hope that the robot detects the objects around it.

### Actual behaviour

The robot doesn't detect anything around it.

### To Reproduce

I run this command  when I am generating a map. 
1. ros2 launch turtlebot4_navigation slam.launch.py
2. in other terminal is ros2 launch turtlebot4_viz view_robot.launch.py
3. in other terminal is ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py
![Screenshot from 2024-03-21 16-06-56](https://github.com/turtlebot/turtlebot4/assets/93724428/7125ff81-614e-4523-868c-1d8791e9d528)

**Comment by ajjaya18** [comment]
![Screenshot from 2024-03-21 16-06-56](https://github.com/turtlebot/turtlebot4/assets/93724428/78177f6d-3840-4a56-b51c-4d7d1d3df596)

**Comment by ajjaya18** [comment]
@hilary-luo

**Comment by smatarCPR** [comment]
Hello @ajjaya18 ,
This issue is being closed per your comments on #389. If you believe this to be a mistake, feel free to reopen this thread by replying to this message.
Best Regards,
Saif
