### ISSUE TITLE
Nav2 Goal Tool problem

### ISSUE THREAD

**Issue by ValentinLeglise** [turtlebot/turtlebot4#385]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

*

### Type of issue

Navigation (SLAM, Nav2 etc.)

### Expected behaviour

In Rviz, after defining the robot's initial 2D point, my customer uses the Nav2 Goal Tool and then the robot move to the goal pose.

### Actual behaviour

When my customer tries to move the robot by clicking on the map in Rviz with the Nav2 Goal Tool, he gets the erro "Goal was rejected by server", and the robot doesn't move.

### To Reproduce

" I added these lines to the .bashrc file, and I execute "source .bashrc" in all new terminals.

CYCLONEDDS_URI='<CycloneDDS><Domain><General><DontRoute>true</></></></>'
export CYCLONEDDS_URI='<CycloneDDS><Domain><General><DontRoute>true</></></></>'
source /etc/turtlebot4/setup.bash
source /etc/turtlebot4_discovery/setup.bash

I follow these steps:

$ ros2 launch turtlebot4_navigation localization.launch.py map:=map2.yaml
$ ros2 launch turtlebot4_navigation nav2.launch.py
$ ros2 launch turtlebot4_viz view_robot.launch.py

Then I define 2D Pose and click on the goal with Nav2 goal tool.
"

**Comment by ValentinLeglise** [comment]
Hello,

Is it possible to have an answer for this ?

Best regards.

**Comment by ValentinLeglise** [comment]
Hello,

I'm adding details about what my client did:

"
If I execute ros2 topic echo /clicked_point and then I click in the map with Publish point tool the result is:

lubuntu@lubuntu-virtualbox:~$ ros2 topic echo /clicked_point
header:
  stamp:
    sec: 1712170029
    nanosec: 560450592
  frame_id: map
point:
  x: -0.0640483945608139
  y: 0.49885591864585876
  z: -0.001434326171875
---

If I click on Nav2 Goal tool there isn't any result in ros2 topic echo /clicked_point.

If I define 2D Estimate Pose the message in "ros2 launch turtlebot4_navigation [localization.launch.py](http://localization.launch.py/) map:=map_name.yaml" terminal is:

[amcl-2] [INFO] [1712171035.497726404] [amcl]: initialPoseReceived
[amcl-2] [WARN] [1712171035.497853082] [amcl]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1712171035.497794 but the latest data is at time 1712171024.695519, when looking up transform from frame [base_link] to frame [odom])
[amcl-2] [INFO] [1712171035.497879207] [amcl]: Setting pose (1712171035.497879): -0.371 0.112 -0.044

Then, I select Nav2 Goal and click over the map in rviz window, the message in rviz is:

[rviz2-1] [INFO] [1712171035.497385713] [rviz2]: Setting estimate pose: Frame:map, Position(-0.370674, 0.112453, 0), Orientation(0, 0, -0.0221002, 0.999756) = Angle: -0.0442039
[rviz2-1] Start navigation
[rviz2-1] [ERROR] [1712171060.108202585] [rviz_navigation_dialog_action_client]: navigate_to_pose action server is not available. Is the initial pose set?
"

**Comment by hilary-luo** [comment]
He needs to set his initial pose in order to be able to use the navigate to commands. It seems that he is unable to because his computer / robot times are not synced, they are catually off by roughly 10 seconds. 

> [amcl]: Failed to transform initial pose in time (Lookup would require extrapolation into the future. Requested time 1712171035.497794 but the latest data is at time 1712171024.695519, when looking up transform from frame [base_link] to frame [odom])

By default the robot will sync with the internet so the easiest thing it generally to ensure that your PC is also syncing time with the internet (default Ubuntu servers). @RustyCPR @smatarCPR I will leave it to you guys to guide the conversation from here as necessary.

**Comment by ValentinLeglise** [comment]
Hello,

Thank you for your reply. 

So concretely, my customer has to make sure that his PC and the robot are connected to the same internet network? Or does he have to do something else specific?

Best regards.

**Comment by smatarCPR** [comment]
Hello @ValentinLeglise ,
Yes, please ensure that your customer has their PC and Turtlebot 4 connected to the same internet network.

A few items they can check after performing this is ensuring that the their computer is syncing it's time using the internet and that it is the same as the time seen on the Raspberry Pi and Create3. They can check this using timedatectl per the instructions found here: https://ubuntu.com/server/docs/use-timedatectl-and-timesyncd

Let me know how these recommendations work for them. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by ValentinLeglise** [comment]
Hello,

Thank you for your response.

My customer has set the same time zone and configured an NTP server. You can see a video attached
[Lubuntu ROS2-screen0.webm](https://github.com/turtlebot/turtlebot4/assets/148329757/27e2a756-7718-478a-82ea-9328b16558a6)

But he still has problems. This is the rviz output:


[rviz2-1] [INFO] [1712860064.269354609] [rviz2]: Setting estimate pose: Frame:map, Position(-0.526121, -3.19067, 0), Orientation(0, 0, -0.111025, 0.993818) = Angle: -0.22251
[rviz2-1] Start navigation
[rviz2-1] [ERROR] [1712860096.166775746] [rviz_navigation_dialog_action_client]: navigate_to_pose action server is not available. Is the initial pose set?

and the other terminal:

[amcl-2] [INFO] [1712860064.269593607] [amcl]: initialPoseReceived
[amcl-2] [WARN] [1712860064.270124668] [amcl]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1712860064.270090 but the latest data is at time 1712860064.134059, when looking up transform from frame [base_link] to frame [odom])
[amcl-2] [INFO] [1712860064.270412330] [amcl]: Setting pose (1712860064.270412): -0.526 -3.191 -0.223


and other terminal

[controller_server-1] [INFO] [1712859031.377621964] [local_costmap.local_costmap]: StaticLayer: Resizing static layer to 153 X 304 at 0.050000 m/pix

What should he do ?

Best regards, Valentin.

**Comment by ValentinLeglise** [comment]
Hello,

Please is it possible to have a response ? Its pretty urgent.

Best regards, Valentin

**Comment by smatarCPR** [comment]
Hello Valentin,
Apologies for the late reply on this. While the video does show that the times reported are synced to the second, it appears that based on the amcl-2 error output, there is about 0.15s of discrepancy between the devices:

[amcl-2] [WARN] [1712860064.270124668] [amcl]: Failed to transform initial pose in time (Lookup would require extrapolation into the future. Requested time **1712860064.270090** but the latest data is at time **1712860064.134059**, when looking up transform from frame [base_link] to frame [odom])

Based on the information provided, running a discovery server setup, what you will need to do is to make sure that your laptop is also syncing time with the internet and these should all match. 

If you still seem to be seeing issues then it could be helpful to reboot the robot and your PC and potentially restart the ntpd from the create3 webserver. Similarly try forcing a time sync on your laptop. (More details on how to check last time sync etc on ubuntu [here](https://ubuntu.com/server/docs/use-timedatectl-and-timesyncd). Run the command: `systemctl status systemd-timesyncd` and see when the timesync last occurred. For the Raspberry Pi, you can use `systemctl status chrony` to see when the last sync was and you can force a sync by restarting the chrony service.

I also notice that it appears that the client is using a virtual machine, does a similar issue arise if they are running on a system that is running Ubuntu natively?

Let me know the results of these checks. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by ValentinLeglise** [comment]
Hello,

Thank you for your response. I will share these information to my customer.

Yes he uses a VM because he doesn't have Ubuntu native machine.

I will let you know the results.
Best regards, Valentin.

**Comment by ValentinLeglise** [comment]
Hello, 

I've got some news. The customer thinks he has solved the synchronization problem. He had a first error (again) and then he had two successful attempts.

"[amcl-2] [INFO] [1713812213.103042274] [amcl]: initialPoseReceived
[amcl-2] [WARN] [1713812213.103188216] [amcl]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1713812213.103157 but the latest data is at time 1713812213.100003, when looking up transform from frame [base_link] to frame [odom])
[amcl-2] [INFO] [1713812213.103201048] [amcl]: Setting pose (1713812213.103201): -2.218 1.344 -0.044


[amcl-2] [INFO] [1713812311.987260738] [amcl]: initialPoseReceived
[amcl-2] [INFO] [1713812311.987758227] [amcl]: Setting pose (1713812311.987758): -2.178 1.494 -0.144


[amcl-2] [INFO] [1713812386.537784338] [amcl]: initialPoseReceived
[amcl-2] [INFO] [1713812386.537843305] [amcl]: Setting pose (1713812386.537843): -2.177 1.510 0.104"

However, he still has problems navigating. According to the customer, the robot somble accepts the initial pose, but when he clicks on Rviz to make it move, he gets the following error:

"[rviz2-1] Start navigation
[rviz2-1] [ERROR] [1713812370.525654847] [rviz_navigation_dialog_action_client]: navigate_to_pose action server is not available. Is the initial pose set?
[rviz2-1] [INFO] [1713812386.537132885] [rviz2]: Setting estimate pose: Frame:map, Position(-2.17687, 1.51047, 0), Orientation(0, 0, 0.0517994, 0.998658) = Angle: 0.103645
[rviz2-1] Start navigation
[rviz2-1] [ERROR] [1713812403.632853279] [rviz_navigation_dialog_action_client]: navigate_to_pose action server is not available. Is the initial pose set?"

Do you know where it might come from?
Thanks for your help.

**Comment by smatarCPR** [comment]
Hello @ValentinLeglise ,
It is good to hear that the time sync issue has been resolved. With regards to the current issue regarding the action server, would it be possible for the client to share the full commands they are running and the full terminal outputs from the three command terminals?

We'll take a look at the full details and let you know when we find the cause of this error. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by ValentinLeglise** [comment]
Hello,

Sorry for this late reply.

There you can find the output of the 3 commands: 

[output.txt](https://github.com/turtlebot/turtlebot4/files/15290922/output.txt)

Hope this will be useful.
Best regards, Valentin.

**Comment by ValentinLeglise** [comment]
Hello,

would it be possible to have a quick answer please?

Thanks for your understanding.
Kind regards, Valentin.

**Comment by ValentinLeglise** [comment]
Hello CP.

Sorry to bother you again, but this ticket has been running for over a month and we need to finish it as soon as possible. Would it be possible to get an answer soon? Best regards, Valentin.

**Comment by smatarCPR** [comment]
Hello @ValentinLeglise ,
Apologies for the late reply on this. Reviewing the logs provided, there appears to be an underlying issue with Nav2:
```
[controller_server-1] [INFO] [1714753099.450773148] [local_costmap.local_costmap]: start
[controller_server-1] [INFO] [1714753099.654741214] [controller_server]: Creating bond (controller_server) to lifecycle manager.
[controller_server-1] [WARN] [1714753101.450932432] [local_costmap.local_costmap]: Can't update static costmap layer, no map received
[lifecycle_manager-8] [ERROR] [1714753101.686267488] [lifecycle_manager_navigation]: Server controller_server was unable to be reached after 4.00s by bond. This server may be misconfigured.
[lifecycle_manager-8] [ERROR] [1714753101.686784340] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
[controller_server-1] [WARN] [1714753103.450996255] [local_costmap.local_costmap]: Can't update static costmap layer, no map received
[lifecycle_manager-8] terminate called after throwing an instance of 'statemap::TransitionUndefinedException'
[lifecycle_manager-8]   what():  no such transition in current state
[ERROR] [lifecycle_manager-8]: process has died [pid 3696, exit code -6, cmd '/opt/ros/humble/lib/nav2_lifecycle_manager/lifecycle_manager --ros-args --log-level info --ros-args -r __node:=lifecycle_manager_navigation -r __ns:=/ --params-file /tmp/launch_params_cqyf1t1p --params-file /tmp/launch_params_rpjvliy7 --params-file /tmp/launch_params_eo7hts76 -r /global_costmap/scan:=/scan -r /local_costmap/scan:=/scan'].
``` 

The most likely cause for these errors could be due to a lack of resources available to the virtual machine running Ubuntu. If the client has the option available to them, swapping to a system running Ubuntu natively is highly recommended.

If they cannot switch to such a system, allocating more resources to the VM may be a workaround.

Let me know which option is taken and how this recommendation works for your client. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by ValentinLeglise** [comment]
Hello,

They are forced to use a virtual machine. What resources do they need and how they can get it ?

Best regards

**Comment by smatarCPR** [comment]
Hello @ValentinLeglise ,
What are the current settings for the VM (i.e. what processor have they virtualized, how much RAM and storage has been allocated to the machine?)

What type of machine is hosting the VM? Is it a standard desktop/laptop or a server?

Does the VM have its network settings bridged/cloned from the host machine, or does it use a virtual network adapter?

Looking forward to hearing from you soon.
Best Regards,
Saif M.

**Comment by ValentinLeglise** [comment]
Hi,

The machine is a laptop with Windows 10, CPU i7-12800H 2.40Ghz and 32 GB of RAM Memory.

The VM is a Virtual Box VM with 2048 MB RAM, 2 CPU's,  25GB Hard disk and Bridget Adapter Network.

Regards.

**Comment by ValentinLeglise** [comment]
Hello,

Is it possible to have a response for this ?

Best regards, Valentin.

**Comment by smatarCPR** [comment]
Hello @ValentinLeglise ,
Apologies for the late reply on this. Looking at the resources listed, our first recommendation is to increase the RAM available to the VM. The client can start by setting the amount available to 4 GB or 8 GB and see how this affects performance. ANother item they can modify is the disk space available, increasing from 25 GB to 40 GB or more.

Ideally however, the client should run Linux natively as that is the supported platform for interfacing with a Turtlebot4.

Let me know if you have any questions or if I can help with anything else.
Best Regards,
Saif M.

**Comment by ValentinLeglise** [comment]
Hello,

Sorry for the late reply. Here is my customer's response:

"I have increased the resources of the virtual machine, but it still doesn't work. The error I'm getting is as follows:

[rviz2-1] Start navigation
[rviz2-1] [INFO] [1719309944.970291794] [rviz_navigation_dialog_action_client]: NavigateToPose will be called using the BT Navigator default behaviour tree.
[rviz2-1] [ERROR] [1719309944.970918850] [rviz_navigation_dialog_action_client]: Goal has been rejected by the server.
"
Is this error always due to a lack of resources?

Best regards, Valentin.

**Comment by ValentinLeglise** [comment]
Hello ClearPath,

Is it possible to have an answer for this please ?

Best regards, Valentin.

**Comment by ValentinLeglise** [comment]
Hello,

It's been nearly two weeks since I've had a reply regarding this ticket. Would it be possible to get a reply?

Best regards

**Comment by smatarCPR** [comment]
Hello @ValentinLeglise ,
Apologies for the late reply. Regarding this matter:
It is expected that the action server rejects the goal based on the initial error the client was observing:
```
[controller_server-1] [INFO] [1714753099.450773148] [local_costmap.local_costmap]: start
[controller_server-1] [INFO] [1714753099.654741214] [controller_server]: Creating bond (controller_server) to lifecycle manager.
[controller_server-1] [WARN] [1714753101.450932432] [local_costmap.local_costmap]: Can't update static costmap layer, no map received
[lifecycle_manager-8] [ERROR] [1714753101.686267488] [lifecycle_manager_navigation]: Server controller_server was unable to be reached after 4.00s by bond. This server may be misconfigured.
[lifecycle_manager-8] [ERROR] [1714753101.686784340] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
[controller_server-1] [WARN] [1714753103.450996255] [local_costmap.local_costmap]: Can't update static costmap layer, no map received
[lifecycle_manager-8] terminate called after throwing an instance of 'statemap::TransitionUndefinedException'
[lifecycle_manager-8]   what():  no such transition in current state
[ERROR] [lifecycle_manager-8]: process has died [pid 3696, exit code -6, cmd '/opt/ros/humble/lib/nav2_lifecycle_manager/lifecycle_manager --ros-args --log-level info --ros-args -r __node:=lifecycle_manager_navigation -r __ns:=/ --params-file /tmp/launch_params_cqyf1t1p --params-file /tmp/launch_params_rpjvliy7 --params-file /tmp/launch_params_eo7hts76 -r /global_costmap/scan:=/scan -r /local_costmap/scan:=/scan'].
``` 
The launch of the nav2 stack failed and thus there is no server to receive the goal and it will be rejected. Most likely the failure to launch is due to a lack of resources, you can have the client try increasing CPU resources available or lengthening the Nav2 Bond timeout to see if more time is sufficient to get all components running and communicating.

However, as stated before, virtual machines are not a supported platform and we strongly urge the client to transition to a machine running Linux natively.

 If they want to modify the Nav2 bond timer they can make a copy of the nav2.yaml, modify it and then pass it in when they launch the turtlebot4 nav2 node. For documentation on bond_timeout and how that is set in a yaml file see https://docs.nav2.org/configuration/packages/configuring-lifecycle.html#parameters. 

Let me know how these recommendations work for you. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif

**Comment by patham9** [comment]
What does it mean for a VM not to be a supported platform? The guest OS has no idea if it is running in a VM or not, nor should it need to assume to run on real hardware or not. If ROS2 cannot deal with timing characteristics that is a flaw that will not only show up in a VM. Yes it happens more often there, but with multiple processes running there is no timing guarantee on a native OS either, timing variations shouldn't crash ROS.

**Comment by hilary-luo** [comment]
@patham9 ROS 2 and Turtlebot4 *should* run perfectly well using VM's given that they are set up properly with the required resources and appropriate networking configuration. However, the level of user that is learning ROS 2 with Turtlebot4 tends not to be equipped to configure VM's properly, commonly facing resource starvation among other issues. These users need to be using native systems to reduce the troubleshooting scope of their system both for their sake and for ours. It is not a realistic goal for us to be supporting the various issues of setting up VMs. Therefore we officially do not provide support for VM setups for the Turtlebot 4 product although many advanced users may be using VM's or containers. We try to provide troubleshooting suggestions where we can, when users report using a VM, but we are not able to go to the extent of trying to replicate such issues or dig too much into how any one VM is configured. That is what it means for VM's to not be supported in this context. You are free to do it but we can't provide support for it.

**Comment by patham9** [comment]
@hilary-luo: I see, this makes sense. Thank you for clarifying!
