### ISSUE TITLE
How to get stereo and depth camera topics on turtlebot4

### ISSUE THREAD

**Issue by arkcom55** [turtlebot/turtlebot4#386]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

No sure what package(s)

### Type of issue

Camera

### Expected behaviour

Access stereo camera and depth camera ROS topics

### Actual behaviour

Only see single camera topics:
/oakd/rgb/preview/camera_info
/oakd/rgb/preview/image_raw

### To Reproduce

ros2 topic list

### Other notes

Tutorial anywhere on accessing stereo/depth?

**Comment by RustyCPR** [comment]
Hi @arkcom55 
Please don't open duplicate issues.  
I did reply to your questions here: https://github.com/turtlebot/turtlebot4/issues/377#issuecomment-2018799150
Please reply to #377 if you have further questions or concerns. 
Thank you,
Rusty
