### ISSUE TITLE
map topic is not showing, also map is not showing in rviz when I run the tutorial https://turtlebot.github.io/turtlebot4-user-manual/tutorials/generate_map.html

### ISSUE THREAD

**Issue by shivakarnati** [turtlebot/turtlebot4#391]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

ros2 humble 

### Expected behaviour

When I check the map after launching `ros2 launch turtlebot4_navigation slam.launch.py` or `ros2 launch turtlebot4_navigation slam.launch.py sync:=false` files, I do not see any map in the rviz. 
It gives the following error:`
[async_slam_toolbox_node-1] [INFO] [1712162865.067868814] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link' at time 1712162864.932 for reason 'discarding message because the queue is full'
`
![image](https://github.com/turtlebot/turtlebot4/assets/38187230/45da4139-615f-43b3-9153-13c9c21c3eb9)

### Actual behaviour

When I run the command `ros2 launch turtlebot4_viz view_robot.launch.py`, I get this error.
`
[rviz2-1] [INFO] [1712162996.638737634] [rviz2]: Message Filter dropping message: frame 'rplidar_link' at time 1712162995,332 for reason 'discarding message because the queue is full'`

I check the other relevant issues https://github.com/turtlebot/turtlebot4/issues/181 and https://github.com/turtlebot/turtlebot4/issues/141 still the problem is not solvable. 

Please suggest me what I can do about it. Thank you!

### To Reproduce

ros2 launch turtlebot4_navigation slam.launch.py sync:=false

**Comment by smatarCPR** [comment]
Hello @shivakarnati ,
Thank you for reaching out on the Turtlebot 4 Github. 

Are you currently launching the navigation when SSH'ed into the Turtlebot or on your remote computer? Have you remembered to source your ROS 2 environment before beginning launching the launch files?

I notice you are using a simple discovery setup, is the option to switch to a discovery server available to you? If so, I would recommend switching to discovery server, the communication seems to be more stable when a discovery server setup is used.

If you wish to remain with the simple discovery setup, check to ensure that the your computer is syncing it's time using the internet and that it is the same as the time seen on the Raspberry Pi and Create3. You can check this using timedatectl per the instructions found here: https://ubuntu.com/server/docs/use-timedatectl-and-timesyncd 

Let me know how these recommendations work for you. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by philippejuhel** [comment]
Hi, 

I had the same problems as above (+ some other problems like not all the topics on my computer and teleop_twist_keyboard doesn't work on my computer but works on the RPi).
I switched from simple discovery to discovery server and now everything is OK (SLAM, all topics and  teleop_twist_keyboard).
Thank you!

**Comment by shivakarnati** [comment]
> Hello @shivakarnati , Thank you for reaching out on the Turtlebot 4 Github.
> 
> Are you currently launching the navigation when SSH'ed into the Turtlebot or on your remote computer? Have you remembered to source your ROS 2 environment before beginning launching the launch files?
> 
> I notice you are using a simple discovery setup, is the option to switch to a discovery server available to you? If so, I would recommend switching to discovery server, the communication seems to be more stable when a discovery server setup is used.
> 
> If you wish to remain with the simple discovery setup, check to ensure that the your computer is syncing it's time using the internet and that it is the same as the time seen on the Raspberry Pi and Create3. You can check this using timedatectl per the instructions found here: https://ubuntu.com/server/docs/use-timedatectl-and-timesyncd
> 
> Let me know how these recommendations work for you. Looking forward to hearing from you soon. Best Regards, Saif

**Comment by shivakarnati** [comment]
Hello @smatarCPR ,

Thank you for your reply. I tried the Discovery server settings in Turtlebot and in my PC. But it still gives the same error **"No map received"**. And the Global Error is : **"No tf data. Actual error: Frame [map] does not exist"**.

**Comment by smatarCPR** [comment]
Hello @shivakarnati ,
Let's check a few items to ensure there is full communication across the system:
1. Run `ros2 topic list` do you see the common topics from the Create3 such as battery_state and odom.
2. Are you able to echo these topics and get clean, relevant data?
3. If not, what is the output of `ip route` is it similar to 192.168.186.0/24 via 10.0.0.121 dev wlp0s20f3 where 10.0.0.121 would be your Raspberry Pi IP, and wlp0s20f3 would be your Wi-Fi interface?
Are you able to share full terminal outputs? Please do so if you can.

Looking forward to hearing from you soon.
Best Regards,
Saif M.

**Comment by albertuswh** [comment]
Hi @smatarCPR im facing the same problem, and answering your question
1. i can run the topic list, and it showed the same topics as the RPi4
2. I can get clear data, when echoing to cmd_vel topic from my PC

further help will be much appreciated thank you

**Comment by smatarCPR** [comment]
Hello @shivakarnati ,
Any updates on this? Thanks!

Hello @albertuswh ,
I see you opened #409, but it appears you were able to resolve the matter there. Let me know if that is not the case.

Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by shivakarnati** [comment]
Hello @smatarCPR , Thank you for your reply. I can see the common topics, and services from the robot. I can echo those topics as well. Yes, I am using the same wifi router for my PC and to the robot. I didn't understand your point on sharing terminal outputs?. Could you please elaborate it more?

I am still facing the same issue.
Thank you.

**Comment by smatarCPR** [comment]
Hello @shivakarnati ,
When running the navigation SLAM launch.py file in a terminal copy and paste the data outputted in that terminal and send it to us in this ticket. Looking forward to hearing from you soon.
Best Regards,
Saif M.

**Comment by shivakarnati** [comment]
Hello @smatarCPR ,

Please do find the screenshot here. 
![Screenshot from 2024-06-06 16-37-08](https://github.com/turtlebot/turtlebot4/assets/38187230/32b5d8a5-8cb1-4c4d-8667-25f230206093)

```
shivakrishnakarnati@pop-os:~$ ros2 launch turtlebot4_viz view_robot.launch.py
[INFO] [launch]: All log files can be found below /home/shivakrishnakarnati/.ros/log/2024-06-06-16-33-13-221834-pop-os-994702
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [994713]
[rviz2-1] [INFO] [1717684393.810030961] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1717684393.810323389] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-1] [INFO] [1717684393.834409749] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1717684395.125203348] [rviz2]: Message Filter dropping message: frame 'laser' at time 1717684394.004 for reason 'discarding message because the queue is full'
[rviz2-1] [INFO] [1717684395.317812374] [rviz2]: Message Filter dropping message: frame 'laser' at time 1717684394.102 for reason 'discarding message because the queue is full'
```

**Comment by smatarCPR** [comment]
Hello @shivakarnati ,
Apologies for the late reply on this. A quick note regarding the output shared, the message seen in the terminal:
`[rviz2-1] [INFO] [1717684395.317812374] [rviz2]: Message Filter dropping message: frame 'laser' at time 1717684394.102 for reason 'discarding message because the queue is full'`
Is a very common message and unfortunately does not narrow down what is breaking in mapping toolkit.

Are you in a separate command terminal running the command: `ros2 launch turtlebot4_navigation slam.launch.py`? If so, would it be possible to share the output of that terminal?

Additionally, perhaps the system logs may have some useful information within them. Please run the following command, while SSH'ed into the Turtlebot: `journalctl -b > turtlebot4_log.txt` and share with us the generated log text file.

Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
