### ISSUE TITLE
Rtabmap mapping navigation

### ISSUE THREAD

**Issue by imnulhaqueruman** [turtlebot/turtlebot4#399]
### Describe the the feature you would like

With SLAM navigation i want to rtabmap mapping navigation 

### Motivation and impact

FOR 3d Model

**Comment by smatarCPR** [comment]
Hello @imnulhaqueruman ,
Thank you for reaching out on the Turtlebot 4 Github. With regards to the implementation of rtabmap, you will need to reference the Nav2 documentation. The Turtlebot4 uses Nav2 for SLAM, Localization and general navigation. Nav2 offers a number of different plugins and different algorithms for various different needs and use cases. You can review the [Nav2 documentation](https://navigation.ros.org/) to see if they offer the plugins that you are looking for and if they don't, there are instructions on how to build your own plugins as well. If you want to request a feature for Nav2 you can do so on their [repository](https://github.com/ros-planning/navigation2).

To run your Turtlebot4 with custom settings, make a copy of the default [slam config](https://github.com/turtlebot/turtlebot4/blob/humble/turtlebot4_navigation/config/slam.yaml) and make your changes. You can then pass your custom config file when you launch slam
ros2 launch turtlebot4_navigation slam.launch.py params:=/full/path/to/slam.yaml

You can do the same thing with the localization and nav2 launch configs / files.

I hope this has sufficiently cleared everything up.
Best Regards,
Saif
