### ISSUE TITLE
ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=false map:=office.yaml, stuck at creating map

### ISSUE THREAD

**Issue by aalghooneh** [turtlebot/turtlebot4#40]
- Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed: this repo
 - Package version: (current version)

 **Expected behaviour**
map getting published into /map topic

 **Actual behaviour**
stuck at creating map

**To Reproduce**
have an example map (yaml and pgm)
ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=false map:=office.yaml

** The log I recieve:
[INFO] [launch]: All log files can be found below /home/dastan/.ros/log/2022-08-31-14-32-10-043223-dastan-Alienware-m17-R4-900
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [1562]
[INFO] [controller_server-2]: process started with pid [1564]
[INFO] [planner_server-3]: process started with pid [1566]
[INFO] [recoveries_server-4]: process started with pid [1568]
[INFO] [bt_navigator-5]: process started with pid [1570]
[INFO] [waypoint_follower-6]: process started with pid [1572]
[INFO] [lifecycle_manager-7]: process started with pid [1574]
[lifecycle_manager-7] [INFO] [1661970730.658722390] [lifecycle_manager_navigation]: Creating
[lifecycle_manager-7] [INFO] [1661970730.661927029] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[lifecycle_manager-7] [INFO] [1661970730.665260219] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-7] [INFO] [1661970730.666282494] [lifecycle_manager_navigation]: Configuring controller_server
[planner_server-3] [INFO] [1661970730.666370719] [planner_server]: 
[planner_server-3] 	planner_server lifecycle node launched. 
[planner_server-3] 	Waiting on external lifecycle transitions to activate
[planner_server-3] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-3] [INFO] [1661970730.667765918] [planner_server]: Creating
[recoveries_server-4] [INFO] [1661970730.671075801] [recoveries_server]: 
[recoveries_server-4] 	recoveries_server lifecycle node launched. 
[recoveries_server-4] 	Waiting on external lifecycle transitions to activate
[recoveries_server-4] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-2] [INFO] [1661970730.675800174] [controller_server]: 
[controller_server-2] 	controller_server lifecycle node launched. 
[controller_server-2] 	Waiting on external lifecycle transitions to activate
[controller_server-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-5] [INFO] [1661970730.678730856] [bt_navigator]: 
[bt_navigator-5] 	bt_navigator lifecycle node launched. 
[bt_navigator-5] 	Waiting on external lifecycle transitions to activate
[bt_navigator-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-5] [INFO] [1661970730.678847337] [bt_navigator]: Creating
[controller_server-2] [INFO] [1661970730.679701290] [controller_server]: Creating controller server
[waypoint_follower-6] [INFO] [1661970730.684336340] [waypoint_follower]: 
[waypoint_follower-6] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-6] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-6] [INFO] [1661970730.686245160] [waypoint_follower]: Creating
[controller_server-2] [INFO] [1661970730.689931162] [local_costmap.local_costmap]: 
[controller_server-2] 	local_costmap lifecycle node launched. 
[controller_server-2] 	Waiting on external lifecycle transitions to activate
[controller_server-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-2] [INFO] [1661970730.690390687] [local_costmap.local_costmap]: Creating Costmap
[planner_server-3] [INFO] [1661970730.690599549] [global_costmap.global_costmap]: 
[planner_server-3] 	global_costmap lifecycle node launched. 
[planner_server-3] 	Waiting on external lifecycle transitions to activate
[planner_server-3] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-3] [INFO] [1661970730.690976872] [global_costmap.global_costmap]: Creating Costmap
[controller_server-2] [INFO] [1661970730.832146601] [controller_server]: Configuring controller interface
[controller_server-2] [INFO] [1661970730.832522311] [controller_server]: getting goal checker plugins..
[controller_server-2] [INFO] [1661970730.832810877] [controller_server]: Controller frequency set to 20.0000Hz
[controller_server-2] [INFO] [1661970730.832841869] [local_costmap.local_costmap]: Configuring
[controller_server-2] [INFO] [1661970730.838050686] [local_costmap.local_costmap]: Using plugin "voxel_layer"
[controller_server-2] [INFO] [1661970730.842869319] [local_costmap.local_costmap]: Subscribed to Topics: scan
[controller_server-2] [INFO] [1661970730.858676538] [local_costmap.local_costmap]: Initialized plugin "voxel_layer"
[controller_server-2] [INFO] [1661970730.858712543] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-2] [INFO] [1661970730.865376682] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[controller_server-2] [INFO] [1661970730.881550470] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-2] [INFO] [1661970730.890128043] [controller_server]: Created goal checker : general_goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-2] [INFO] [1661970730.899191455] [controller_server]: Controller Server has general_goal_checker  goal checkers available.
[controller_server-2] [INFO] [1661970730.900958367] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-2] [INFO] [1661970730.904272272] [controller_server]: Setting transform_tolerance to 0.200000
[controller_server-2] [INFO] [1661970730.929664873] [controller_server]: Using critic "RotateToGoal" (dwb_critics::RotateToGoalCritic)
[controller_server-2] [INFO] [1661970730.931699625] [controller_server]: Critic plugin initialized
[controller_server-2] [INFO] [1661970730.932111446] [controller_server]: Using critic "Oscillation" (dwb_critics::OscillationCritic)
[controller_server-2] [INFO] [1661970730.933774028] [controller_server]: Critic plugin initialized
[controller_server-2] [INFO] [1661970730.934158261] [controller_server]: Using critic "BaseObstacle" (dwb_critics::BaseObstacleCritic)
[controller_server-2] [INFO] [1661970730.934876633] [controller_server]: Critic plugin initialized
[controller_server-2] [INFO] [1661970730.935316343] [controller_server]: Using critic "GoalAlign" (dwb_critics::GoalAlignCritic)
[controller_server-2] [INFO] [1661970730.936519301] [controller_server]: Critic plugin initialized
[controller_server-2] [INFO] [1661970730.936972256] [controller_server]: Using critic "PathAlign" (dwb_critics::PathAlignCritic)
[controller_server-2] [INFO] [1661970730.938189290] [controller_server]: Critic plugin initialized
[controller_server-2] [INFO] [1661970730.938670617] [controller_server]: Using critic "PathDist" (dwb_critics::PathDistCritic)
[controller_server-2] [INFO] [1661970730.939442213] [controller_server]: Critic plugin initialized
[controller_server-2] [INFO] [1661970730.939864084] [controller_server]: Using critic "GoalDist" (dwb_critics::GoalDistCritic)
[controller_server-2] [INFO] [1661970730.940777245] [controller_server]: Critic plugin initialized
[controller_server-2] [INFO] [1661970730.940805256] [controller_server]: Controller Server has FollowPath  controllers available.
[lifecycle_manager-7] [INFO] [1661970730.948255805] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-3] [INFO] [1661970730.948452984] [planner_server]: Configuring
[planner_server-3] [INFO] [1661970730.948484164] [global_costmap.global_costmap]: Configuring
[planner_server-3] [INFO] [1661970730.957214253] [global_costmap.global_costmap]: Using plugin "static_layer"
[planner_server-3] [INFO] [1661970730.962870299] [global_costmap.global_costmap]: Subscribing to the map topic (/map) with transient local durability
[planner_server-3] [INFO] [1661970730.964365169] [global_costmap.global_costmap]: Initialized plugin "static_layer"
[planner_server-3] [INFO] [1661970730.964468397] [global_costmap.global_costmap]: Using plugin "obstacle_layer"
[planner_server-3] [INFO] [1661970730.968843968] [global_costmap.global_costmap]: Subscribed to Topics: scan
[planner_server-3] [INFO] [1661970730.980951112] [global_costmap.global_costmap]: Initialized plugin "obstacle_layer"
[planner_server-3] [INFO] [1661970730.981014926] [global_costmap.global_costmap]: Using plugin "inflation_layer"
[planner_server-3] [INFO] [1661970730.984274319] [global_costmap.global_costmap]: Initialized plugin "inflation_layer"
[planner_server-3] [INFO] [1661970730.993258061] [planner_server]: Created global planner plugin GridBased of type nav2_navfn_planner/NavfnPlanner
[planner_server-3] [INFO] [1661970730.993293318] [planner_server]: Configuring plugin GridBased of type NavfnPlanner
[planner_server-3] [INFO] [1661970731.002537884] [planner_server]: Planner Server has GridBased  planners available.
[lifecycle_manager-7] [INFO] [1661970731.012004335] [lifecycle_manager_navigation]: Configuring recoveries_server
[recoveries_server-4] [INFO] [1661970731.012187081] [recoveries_server]: Configuring
[recoveries_server-4] [INFO] [1661970731.018389360] [recoveries_server]: Creating recovery plugin spin of type nav2_recoveries/Spin
[recoveries_server-4] [INFO] [1661970731.019371983] [recoveries_server]: Configuring spin
[recoveries_server-4] [INFO] [1661970731.025653523] [recoveries_server]: Creating recovery plugin backup of type nav2_recoveries/BackUp
[recoveries_server-4] [INFO] [1661970731.026505992] [recoveries_server]: Configuring backup
[recoveries_server-4] [INFO] [1661970731.030151839] [recoveries_server]: Creating recovery plugin wait of type nav2_recoveries/Wait
[recoveries_server-4] [INFO] [1661970731.031059605] [recoveries_server]: Configuring wait
[lifecycle_manager-7] [INFO] [1661970731.036513625] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-5] [INFO] [1661970731.036735907] [bt_navigator]: Configuring
[lifecycle_manager-7] [INFO] [1661970731.108488468] [lifecycle_manager_navigation]: Configuring waypoint_follower
[waypoint_follower-6] [INFO] [1661970731.108680563] [waypoint_follower]: Configuring
[waypoint_follower-6] [INFO] [1661970731.115594117] [waypoint_follower]: Created waypoint_task_executor : wait_at_waypoint of type nav2_waypoint_follower::WaitAtWaypoint
[lifecycle_manager-7] [INFO] [1661970731.118450380] [lifecycle_manager_navigation]: Activating controller_server
[controller_server-2] [INFO] [1661970731.118693230] [controller_server]: Activating
[controller_server-2] [INFO] [1661970731.118723926] [local_costmap.local_costmap]: Activating
[controller_server-2] [INFO] [1661970731.118734808] [local_costmap.local_costmap]: Checking transform
[controller_server-2] [INFO] [1661970731.118808946] [local_costmap.local_costmap]: start
[controller_server-2] [INFO] [1661970731.169385673] [controller_server]: Creating bond (controller_server) to lifecycle manager.
[lifecycle_manager-7] [INFO] [1661970731.272397904] [lifecycle_manager_navigation]: Server controller_server connected with bond.
[lifecycle_manager-7] [INFO] [1661970731.272431736] [lifecycle_manager_navigation]: Activating planner_server
[planner_server-3] [INFO] [1661970731.272654198] [planner_server]: Activating
[planner_server-3] [INFO] [1661970731.272676156] [global_costmap.global_costmap]: Activating
[planner_server-3] [INFO] [1661970731.272689003] [global_costmap.global_costmap]: Checking transform
[planner_server-3] [INFO] [1661970731.272717282] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970731.772769911] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970732.272763118] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970732.772765076] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970733.272764234] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970733.772768849] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970734.272770253] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970734.772769586] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970735.272766967] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970735.772767446] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970736.272766793] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970736.772780841] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970737.272763947] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-3] [INFO] [1661970737.772733150] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist

**Other notes**
it only publishes map when I pass sync for slam argument

**Comment by roni-kreinin** [comment]
Are you launching this from the directory that `office.yaml` and `office.pgm` are located in? If not, try using the absolute path.

**Comment by aalghooneh** [comment]
@roni-kreinin , I am at the directory, though even including the absolute path doesn't help

**Comment by roni-kreinin** [comment]
Does setting localization to `true` not work either?

**Comment by aalghooneh** [comment]
@roni-kreinin it doesn't! When you replicate this, Does it work for you?
or even something like this:
ros2 run nav2_map_server map_server $PWD/map.yaml
it locks in creating map.

Edit: ros2 lifecycle set /map_server configure solves the nav2 problem

**Comment by roni-kreinin** [comment]
It does work for me with localization. Have you tried creating your own map and testing with that?
