### ISSUE TITLE
Rviz fixed frame [map] doesnt exist 

### ISSUE THREAD

**Issue by albertuswh** [turtlebot/turtlebot4#409]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

-

### Type of issue

Navigation (SLAM, Nav2 etc.)

### Expected behaviour

showing visualize of lidar

### Actual behaviour

not showing any in rviz

### Error messages

```bash
no tranform from [...] to [map]
frame [map] doesnt exist

```

### To Reproduce

im following the steps on user manual generating map
start the SLAM launch py then launch the rviz

**Comment by albertuswh** [comment]
![Screenshot from 2024-05-08 19-32-57](https://github.com/turtlebot/turtlebot4/assets/134570133/501c05b6-d1fa-4e5f-a12a-6214e6b3ed4b)

**Comment by albertuswh** [comment]
The reason that the map doesn't exist is because the SLAM isn't ready to use, once it is ready it works fine

**Comment by smatarCPR** [comment]
Hello @albertuswh ,
Thank you for reaching out on the Turtlebot 4 Github page. Are you still encountering issues with RVIZ and SLAM?

If so, do let me know, and if possible provide the commands and the full terminal outputs of those commands.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
