### ISSUE TITLE
I cannot connect the Raspberry using ethernet  

### ISSUE THREAD

**Issue by nidia-bucarelli** [turtlebot/turtlebot4#42]
I am trying to SSH into the Pi over ethernet using the instructions from this link: https://turtlebot.github.io/turtlebot4-user-manual/troubleshooting/faq.html#access-the-rpi-over-ethernet. I am using Windows. I was able to connect the Pi through an adapter (ethernet - USB). However, I cannot set the manual connection. I get an error. See images below. 

<img width="583" alt="Capture2" src="https://user-images.githubusercontent.com/112603498/187829851-921c0152-f5db-4b58-93d2-fcca780604ee.PNG">
<img width="495" alt="Capture" src="https://user-images.githubusercontent.com/112603498/187829849-caf9fbbd-65f8-4eda-ab2f-62668ed9e6ab.PNG">

I am trying to use this approach because after doing ssh ubuntu@10.42.1 and trying to connect to the university WIFI, the AP is not visible anymore and I cannot see the device connected when i do `ros2 topic echo /ip`. The screen is also off/black. The robot is ON.

**Comment by roni-kreinin** [comment]
Can you scroll down to show the rest of the settings?

Also you want to set your IP address on the `192.168.185` subnet, and set the gateway to `192.168.185.1`.

If its possible to set DNS to automatic, do that.

**Comment by nidia-bucarelli** [comment]
I cannot make DNS automatic.
I changed the settings as instructed, still getting an error.
<img width="349" alt="Capture" src="https://user-images.githubusercontent.com/112603498/187963540-6692cdc6-ccc4-479a-9dee-f7b3e35fcdc0.PNG">


There are no many additional settings:
<img width="326" alt="Capture1" src="https://user-images.githubusercontent.com/112603498/187963570-e75cda3a-07e9-4eb4-9d8d-b90364b4dce8.PNG">

**Comment by nidia-bucarelli** [comment]
I was able to get connected to the PI using ssh ubuntu@192.168.185.3. 
But the Pi does not want to connect to the Internet. 

I tried an open network and my phone as a Hostpost. Nothing is working. 

<img width="597" alt="Capture" src="https://user-images.githubusercontent.com/112603498/187981980-4898d08c-8089-4556-bd6f-02ab9fb56276.PNG">

<img width="594" alt="Capture1" src="https://user-images.githubusercontent.com/112603498/187982010-832c019e-3436-4273-98ba-9e3762252bcb.PNG">

**Comment by roni-kreinin** [comment]
Can you try using single quotation marks around the ssid and password? i.e. `sudo wifi.sh -s 'Nidia Bucarelli (2)' `.

**Comment by nidia-bucarelli** [comment]
I just tried that using my phone as a Host. It seems to be working. The screen is now ON and I can see the ip address. 

But I cannot make it work with the open network.  
I am using  `sudo wifi.sh -s 'IllinoistNet_Guest' -r US && sudo reboot`  and I am not getting a connection. Any feedback?

**Comment by roni-kreinin** [comment]
The `wifi.sh` script does not currently account for open networks. I will make a change to fix that.

Meanwhile you can manually edit the netplan configuration.

`sudo nano /etc/netplan/50-cloud-init.yaml`

Under the `wifis` section you should see something like:

```
access-points:
    "IllinoistNet_Guest":
        password: ""
```

You will want to delete the `password: ""` line, and add `{}` after the SSID like this:

```
access-points:
    "IllinoistNet_Guest": {}
```

Save those changes and then call `sudo netplan apply && sudo reboot`.

Let me know if that works for you.

**Comment by nidia-bucarelli** [comment]
Thank you!
I changed the file. I saved it as instructed. It still does not work. I have pasted some pictures below.
Any feedback?  


<img width="947" alt="Capture1" src="https://user-images.githubusercontent.com/112603498/188017922-96a6aebd-91f7-419c-be2c-11dacc21dd9e.PNG">

<img width="477" alt="Capture2" src="https://user-images.githubusercontent.com/112603498/188018146-fe3dc07b-fe82-4935-9c4a-14c0c980144d.PNG">


<img width="435" alt="Capture 3" src="https://user-images.githubusercontent.com/112603498/188018163-2a8d5673-2ff9-47ee-8f9b-3c8b70269f80.PNG">

**Comment by nidia-bucarelli** [comment]
I also tried to use a WIFI from a router using `sudo wifi.sh -s 'NidiaRouter' -p '12345678' -r  US && sudo reboot` . It did not want to work either. The screen is still ON, and it shows the IP address that is shown when I use my phone, but it is not connected.

So far, I can get internet only if i use my hostpost.

**Comment by nidia-bucarelli** [comment]
I solved this issue. Thanks!
