### ISSUE TITLE
Can robot use humble and pc use galactic?

### ISSUE THREAD

**Issue by tedhuang96** [turtlebot/turtlebot4#436]
### Robot Model

Turtlebot4 Standard

### ROS distro

Galactic

### Networking Configuration

Simple Discovery

### OS

Ubuntu 20.04

### Built from source or installed?

Installed

### Package version

in our case currently the robot uses ROS Humble with Ubuntu 22, and the PC uses ROS galactic with Ubuntu 20.

### Type of issue

Networking

### Expected behaviour

Expected the ros2 topic list yields the same results on PC and on robot.

### Actual behaviour

But the PC only has two default topics. The PC failed to connect to the robot. 

### To Reproduce

1. Follow simple discovery, and we choose galactic, where in our case currently the robot uses ROS Humble, and the PC uses ROS galactic.

### Other notes

Does that mean the robot and the PC must use the same version of ROS2 in order to build connection successfully? Currently the robot uses ROS Humble, and the PC uses ROS galactic.

**Comment by RustyCPR** [comment]
Hi @tedhuang96 
We recommend users run the same OS on both TB4 and remote PCs. 
You are welcome to try it but it's not something we will support if issues arise. 
Best regards,
Rusty

**Comment by tedhuang96** [comment]
Thanks!
