### ISSUE TITLE
Turtlebot4 gazebo simulator cmd_vel topic issue

### ISSUE THREAD

**Issue by dartik24** [turtlebot/turtlebot4#439]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Built from Source

### Package version

Not known

### Type of issue

Navigation (SLAM, Nav2 etc.)

### Expected behaviour

When running the turtlebot4 gazebo simulation for ros2 humble and publishing data to cmd_vel topic the robot should move accordingly within the simulation.

### Actual behaviour

When running the turtlebot4 gazebo simulation for ros2 humble there no reaction/very delayed reaction to published data in cmd_vel topic. 

### Error messages

```bash
N/A
```

### To Reproduce

Launch the simulation via the command below:
ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py slam:=true nav2:=true rviz:=true
Run any simple publisher to the cmd_vel topic.

**Comment by smatarCPR** [comment]
Hello @dartik24 ,
Thank you for reaching out on the Turtlebot4 Github page. I am very sorry to hear that you are having issues with the simulator. Out of curiosity, did you press the play button found in the bottom left right corner?
![image](https://github.com/turtlebot/turtlebot4/assets/110051413/f1ceb65d-d82f-4cad-9e56-f200c4df48ca)
Let me know if you have. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by dartik24** [comment]
Yes the play button is pressed, the robot briefly moves off the dock but then it does not respond to any further movement commands from either the keyboard or on screen commands.

**Comment by smatarCPR** [comment]
Hello @dartik24 ,
Would it be possible to share some screenshots, and the terminal output from the terminal which launched Gazebo?

Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by dartik24** [comment]
![Screenshot 2024-07-08 160306](https://github.com/turtlebot/turtlebot4/assets/89485758/3373b6c9-2249-44d2-9011-32a92c0b27e4)
This issue repeats continuously after bootup.
Additionally it should be noted this is being ran in WSL2 however the same issue persists when running on a Linux native machine.

**Comment by dartik24** [comment]
![20240709_125442](https://github.com/turtlebot/turtlebot4/assets/89485758/4369498e-60f1-4ae0-9e5f-378897ee7afc)

Upon further testing here are some additional errors which pop up after setting the robot into undocked mode.

**Comment by aharshac** [comment]
@dartik24 How did you solve this?

**Comment by dartik24** [comment]
@aharshac This issue is not fully solved, I closed it and re opened it here https://github.com/turtlebot/turtlebot4/issues/441 for a more concise summary.
