### ISSUE TITLE
Camera not consistently working

### ISSUE THREAD

**Issue by xylhal** [turtlebot/turtlebot4#442]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

Not sure what version it is

### Type of issue

Camera

### Expected behaviour

OAKD Camera to consistently publish images

### Actual behaviour

I observed multiple issues:

1. The `/oakd` topics are not always consistently present when list the topics
2. The most common behavior I have observed is that the topic is present, but when I visualize it in Rviz, the preview just shows a blank image (despite the Turtlebot being undocked)
3. Sometimes, when I restart Rviz and the turtlebot, there is initial image that is shown in the Rviz, but it freezes at the same image even if I move the Turtlebot
4. When I attempt to echo the topic `/oakd/rgb/preview/image_raw`, I get the warning that "A message was lost !!!"

### To Reproduce

1. Undock the turtlebot
2. `ros2 launch turtlebot4_viz view_robot.launch.py`

**Comment by RustyCPR** [comment]
Hi there @xylhal  
Thanks for reaching out. 

"Sometimes, when I restart Rviz and the turtlebot, " after rebooting are you sshing in again and relaunching RVIZ? 
Can you please provide the terminal outputs with any errors? 

Thank you,
Rusty

**Comment by xylhal** [comment]
Hi there @RustyCPR 

I'm actually not launching rviz from the RPi. I am running everything remotely from another machine. So, I didn't do any ssh. What I meant by restarting rviz and turtlebot simply means physically restarting the turtlebot and creating a new terminal on my remote machine to start rviz.

I've attached 5 images below. 
1. Screenshot from view_robot.launch.py
![robot_launch_terminal](https://github.com/user-attachments/assets/0e77176a-b493-411a-ae3e-9b913d990bb9)
2. Screenshot from Rviz when view_robot.launch.py is running in the terminal
![robot_launch](https://github.com/user-attachments/assets/34317d5e-e8c4-4a8b-9b2b-667fec61b327)
3. Screenshot from view_model.launch.py
![model_launch](https://github.com/user-attachments/assets/78ae4d97-e371-4fa7-b950-4b0e5ebc166b)
4. Screenshot from Rviz when view_model.launch.py is running in the terminal
![model_launch_terminal](https://github.com/user-attachments/assets/c3417750-7504-426d-9a0e-0710723e26d4)
5. Terminal when I echo the camera topic
![echo_topic](https://github.com/user-attachments/assets/f5c37d1c-0042-4ef6-bbbd-3f6b0eba786f)

Please let me know how else can I debug this?

**Comment by xylhal** [comment]
I would add that I realize sometimes the terminal does print some messages when echoing the topic, but the Rviz remains blank.
![Screenshot from 2024-07-23 12-01-15](https://github.com/user-attachments/assets/373bb9d0-3105-4f78-a1db-6d30c350c181)

**Comment by RustyCPR** [comment]
Hi @xylhal 

Run: `ros2 launch turtlebot4_viz view_model.launch.py` if your not using mapping

Point 5 image with error "`A message was lost!!!`" What type of wifi network are you running? 
If you're on a 2.4GHz network can you try a faster 5GHz?  

Regards,
Rusty

**Comment by xylhal** [comment]
Hi @RustyCPR 

I was using 5 GHz all along, but the problem has mainly gone away, though I'm not sure why. I'm facing another issue now, which I will open in a separate issue.
