### ISSUE TITLE
Issues with Pairing Controller

### ISSUE THREAD

**Issue by Leo-Gut28** [turtlebot/turtlebot4#448]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

1.0.0-1jammy.20240530.114115 (ros-humble-turtlebot4-desktop)

### Expected behaviour

Controller light turns blue when home button is pressed

### Actual behaviour

Light blinks white/light blue as if it the controller isn't paired

### Error messages

```bash
ubuntu@ubuntu:~$ systemctl status bluetooth
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-07-26 17:57:46 UTC; 9min ago
       Docs: man:bluetoothd(8)
   Main PID: 1438 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 4422)
     Memory: 2.0M
        CPU: 541ms
     CGroup: /system.slice/bluetooth.service
             └─1438 /usr/lib/bluetooth/bluetoothd

Jul 26 17:57:47 ubuntu bluetoothd[1438]: Failed to set privacy: Rejected (0x0b)
Jul 26 17:57:51 ubuntu bluetoothd[1438]: src/adv_monitor.c:btd_adv_monitor_power_down() Unexpected NULL btd_adv_monitor_manager object upon power down
Jul 26 17:58:21 ubuntu bluetoothd[1438]: profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info
Jul 26 17:58:52 ubuntu bluetoothd[1438]: profiles/input/device.c:control_connect_cb() connect to A0:5A:5D:7E:71:02: Function not implemented (38)
Jul 26 17:59:14 ubuntu bluetoothd[1438]: profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info
Jul 26 17:59:19 ubuntu bluetoothd[1438]: profiles/input/device.c:control_connect_cb() connect to A0:5A:5D:7E:71:02: Host is down (112)
```

### To Reproduce

I ran into some issues so I had to reflash the SD card following the instructions [here](https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html). I downloaded the ['turtlebot4_standard_humble_1.0.0.zip'](http://download.ros.org/downloads/turtlebot4/), and got the turtlebot4 up and running again. Controller didn't appear to be paired so i followed the instructions to connect the controller.

### Other notes

It says that the controller is paired, I've tried removing it and then repairing but nothing seems to work. 
![Screenshot from 2024-07-26 11-13-11](https://github.com/user-attachments/assets/9735932a-ddf0-4297-ae71-db0c860d97f1)
![Screenshot from 2024-07-26 11-08-57](https://github.com/user-attachments/assets/443661b3-4592-4216-9102-12813c401dfc)

**Comment by RustyCPR** [comment]
Hi @Leo-Gut28 

There are a few tickets that have addressed this issue. 

1. Can you try the instructions here: https://github.com/turtlebot/turtlebot4/issues/369#issuecomment-1977504336

2. There is also a pairing script another customer created that helps with the BT pairing process, download the file and run it locally: https://github.com/turtlebot/turtlebot4/issues/342#issuecomment-2007741779

If you are still seeing errors please share the full terminal outputs from the untrust / remove / trust / pair and connect commands being run in the terminal.

Regards,
Rusty

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
