### ISSUE TITLE
oak-No-available-devices,No ip/mxid specified, connecting to the next available device

### ISSUE THREAD

**Issue by Ragnar7982** [turtlebot/turtlebot4#449]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Built from Source

### Package version

ros2 launch depthai_ros_driver camera.launch.py
ros2 launch depthai_ros_driver rtabmap.launch.py

### Type of issue

Camera

### Expected behaviour

I'm using Turtlebot4 and OAK-D-PRO camera, when I run ros2 launch depthai_ros_driver camera.launch.py and ros2 launch depthai_ros_driver rtabmap.launch.py at raspberry pi 4 and PC, they both are showing:
[component_container-1] [ERROR] [1722069326.994750652] [oak]: No available devices
[component_container-1] [INFO] [1722069326.995011005] [oak]: No ip/mxid specified, connecting to the next available device.
Here is [output.txt](https://github.com/user-attachments/files/16398778/output.txt) for more details.

And I've put "export export DEPTHAI_DEBUG=1" to bashrc, also type " echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee /etc/udev/rules.d/80-movidius.rules
sudo udevadm control --reload-rules && sudo udevadm trigger" then unplug camera, it's USB3.0 connected to raspberry pi 4.

### Actual behaviour

I've tried OAK-D-PRO when Turtlebot4 navgation, so the camera should work fine, can someone tell me where might the problem is?

### Error messages

```bash
[component_container-1] [ERROR] [1722069326.994750652] [oak]: No available devices
[component_container-1] [INFO] [1722069326.995011005] [oak]: No ip/mxid specified, connecting to the next available device.
Here is [output.txt](https://github.com/user-attachments/files/16398778/output.txt) for more details.

And I've put "export export DEPTHAI_DEBUG=1" to bashrc, also type " echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee /etc/udev/rules.d/80-movidius.rules
sudo udevadm control --reload-rules && sudo udevadm trigger" then unplug camera, it's USB3.0 connected to raspberry pi 4.
```

### To Reproduce

1.ros2 launch depthai_ros_driver camera.launch.py
2.[component_container-1] [ERROR] [1722069326.994750652] [oak]: No available devices
[component_container-1] [INFO] [1722069326.995011005] [oak]: No ip/mxid specified, connecting to the next available device.

**Comment by RustyCPR** [comment]
Hi @Ragnar7982 
Your comment: _I run ros2 launch depthai_ros_driver camera.launch.py and ros2 launch depthai_ros_driver rtabmap.launch.py at raspberry pi 4 and PC, they both are showing_
Those services are already running, are you running  `sudo systemctl stop turtlebot4.service` before running the services? 

Also the camera will not publish images while the TB4 is on the charge dock. 

Regards,
Rusty

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
