### ISSUE TITLE
Navigation with rviz on already mapped room doesn't work properly

### ISSUE THREAD

**Issue by Kohl-Stefan** [turtlebot/turtlebot4#45]
- OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Installed: turtlebot4-navigation 
 - Package version: 0.1.0-1focal.20220526.144025

I would like to navigate through an already mapped room with
`ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=room1.yaml` by using the "Nav2 Goal" tool in Rviz. 

The path planning seems to work since I can see the planned path on the map. Then the Turtlebot starts driving towards the goal but always stops after a few seconds. Then it rotates a 90 degrees to the left and stops. Also, the robot disappears from the Rviz map at that point. Only a white circle remains on the map.

Provide the steps to reproduce:
1. `ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=room1.yaml`
2. `ros2 launch turtlebot4_viz view_robot.launch.py`
3. "2D Pose Estimate" via Rviz button
4. set goal position via "Nav2 Goal" Rviz button 

![Screenshot from 2022-09-07 13-07-24](https://user-images.githubusercontent.com/83010174/188889813-98c16060-f25e-49ef-88ce-b3b098092541.png)
![Screenshot from 2022-09-07 13-10-09](https://user-images.githubusercontent.com/83010174/188889815-9ce6f760-1345-41c8-813f-05dad0f1f9ad.png)
![Screenshot from 2022-09-07 13-10-26](https://user-images.githubusercontent.com/83010174/188889818-286f14ea-9f6a-4ea3-938d-ea614c546149.png)
![Screenshot from 2022-09-07 13-10-29](https://user-images.githubusercontent.com/83010174/188889824-f3cf49ff-54e2-4bf1-ae9f-2b0f3a769994.png)
![Screenshot from 2022-09-07 13-10-43](https://user-images.githubusercontent.com/83010174/188889829-f4e9567c-c705-497b-bcde-f7695a6e6067.png)

ng message: frame 'rplidar_link' at time 1650561325.481 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[amcl-3] [INFO] [1662559373.568960502] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561325.616 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[amcl-3] [INFO] [1662559373.703885400] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561325.751 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[amcl-3] [INFO] [1662559373.798524471] [amcl]: createLaserObject
[controller_server-5] [INFO] [1662559373.810913796] [local_costmap.local_costmap]: start
[controller_server-5] [INFO] [1662559373.811551888] [controller_server]: Creating bond (controller_server) to lifecycle manager.
[controller_server-5] [WARN] [1662559373.819605095] [controller_server]: New publisher discovered on topic '/odom', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
[amcl-3] [INFO] [1662559373.853383897] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561325.899 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[lifecycle_manager-10] [INFO] [1662559373.921235707] [lifecycle_manager_navigation]: Server controller_server connected with bond.
[lifecycle_manager-10] [INFO] [1662559373.921283533] [lifecycle_manager_navigation]: Activating planner_server
[planner_server-6] [INFO] [1662559373.921678249] [planner_server]: Activating
[planner_server-6] [INFO] [1662559373.921712076] [global_costmap.global_costmap]: Activating
[planner_server-6] [INFO] [1662559373.921725339] [global_costmap.global_costmap]: Checking transform
[planner_server-6] [INFO] [1662559373.921797183] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Lookup would require extrapolation into the past.  Requested time 1650561326.905968 but the earliest data is at time 1650561327.463540, when looking up transform from frame [base_link] to frame [map]
[amcl-3] [INFO] [1662559373.987136315] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561326.034 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[amcl-3] [INFO] [1662559374.154602936] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561326.182 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[amcl-3] [INFO] [1662559374.269564458] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561326.316 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[planner_server-6] [INFO] [1662559374.421865831] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Lookup would require extrapolation into the past.  Requested time 1650561327.400777 but the earliest data is at time 1650561327.463540, when looking up transform from frame [base_link] to frame [map]
[amcl-3] [INFO] [1662559374.555694297] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561326.599 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[amcl-3] [INFO] [1662559374.685399442] [amcl_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561326.734 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[planner_server-6] [INFO] [1662559374.922096745] [global_costmap.global_costmap]: start
[planner_server-6] [INFO] [1662559374.975566476] [planner_server]: Activating plugin GridBased of type NavfnPlanner
[planner_server-6] [INFO] [1662559374.975632558] [planner_server]: Creating bond (planner_server) to lifecycle manager.
[lifecycle_manager-10] [INFO] [1662559375.078548460] [lifecycle_manager_navigation]: Server planner_server connected with bond.
[lifecycle_manager-10] [INFO] [1662559375.078657359] [lifecycle_manager_navigation]: Activating recoveries_server
[recoveries_server-7] [INFO] [1662559375.079378262] [recoveries_server]: Activating
[recoveries_server-7] [INFO] [1662559375.079462055] [recoveries_server]: Activating spin
[recoveries_server-7] [INFO] [1662559375.079492975] [recoveries_server]: Activating backup
[recoveries_server-7] [INFO] [1662559375.079511778] [recoveries_server]: Activating wait
[recoveries_server-7] [INFO] [1662559375.079530541] [recoveries_server]: Creating bond (recoveries_server) to lifecycle manager.
[lifecycle_manager-10] [INFO] [1662559375.184980144] [lifecycle_manager_navigation]: Server recoveries_server connected with bond.
[lifecycle_manager-10] [INFO] [1662559375.185083280] [lifecycle_manager_navigation]: Activating bt_navigator
[bt_navigator-8] [INFO] [1662559375.185642007] [bt_navigator]: Activating
[bt_navigator-8] [PublisherZMQ] Server quitting.
[bt_navigator-8] [PublisherZMQ] just died. Exeption Context was terminated
[bt_navigator-8] [PublisherZMQ] Publisher quitting.
[bt_navigator-8] [PublisherZMQ] just died. Exeption Context was terminated
[bt_navigator-8] [INFO] [1662559375.715954949] [bt_navigator]: Creating bond (bt_navigator) to lifecycle manager.
[planner_server-6] [INFO] [1662559375.748013939] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561328.282 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[controller_server-5] [INFO] [1662559375.748014332] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561328.282 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[lifecycle_manager-10] [INFO] [1662559375.829973315] [lifecycle_manager_navigation]: Server bt_navigator connected with bond.
[lifecycle_manager-10] [INFO] [1662559375.830126714] [lifecycle_manager_navigation]: Activating waypoint_follower
[waypoint_follower-9] [INFO] [1662559375.831488187] [waypoint_follower]: Activating
[waypoint_follower-9] [INFO] [1662559375.831620008] [waypoint_follower]: Creating bond (waypoint_follower) to lifecycle manager.
[lifecycle_manager-10] [INFO] [1662559375.940733217] [lifecycle_manager_navigation]: Server waypoint_follower connected with bond.
[lifecycle_manager-10] [INFO] [1662559375.940900818] [lifecycle_manager_navigation]: Managed nodes are active
[lifecycle_manager-10] [INFO] [1662559375.940947556] [lifecycle_manager_navigation]: Creating bond timer...
[planner_server-6] [INFO] [1662559460.257804589] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561413.004 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[planner_server-6] [INFO] [1662559460.391422384] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561413.140 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[bt_navigator-8] [INFO] [1662559474.501085944] [bt_navigator]: Begin navigating from current location to (1.00, 1.02)
[controller_server-5] [INFO] [1662559474.522201890] [controller_server]: Received a goal, begin computing control effort.
[controller_server-5] [WARN] [1662559474.522271011] [controller_server]: No goal checker was specified in parameter 'current_goal_checker'. Server will use only plugin loaded general_goal_checker . This warning will appear once.
[controller_server-5] [INFO] [1662559475.572500056] [controller_server]: Passing new path to controller.
[planner_server-6] [INFO] [1662559476.100810147] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561428.848 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[controller_server-5] [ERROR] [1662559476.122619846] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.122651885] [tf_help]: Data time: 1650561429s 102747945ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.122740744] [controller_server]: Unable to transform robot pose into global plan's frame
[controller_server-5] [ERROR] [1662559476.172638845] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.172660070] [tf_help]: Data time: 1650561429s 152367113ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.172694611] [controller_server]: Unable to transform robot pose into global plan's frame
[ERROR] [amcl-3]: process has died [pid 10179, exit code -11, cmd '/opt/ros/galactic/lib/nav2_amcl/amcl --ros-args -r __node:=amcl --params-file /tmp/tmpeqvq7n1g -r /tf:=tf -r /tf_static:=tf_static'].
[controller_server-5] [ERROR] [1662559476.222662329] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.222684293] [tf_help]: Data time: 1650561429s 198682642ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.222716003] [controller_server]: Unable to transform robot pose into global plan's frame
[planner_server-6] [INFO] [1662559476.234666411] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561428.983 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[controller_server-5] [ERROR] [1662559476.272659614] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.272701806] [tf_help]: Data time: 1650561429s 263685562ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.272736334] [controller_server]: Unable to transform robot pose into global plan's frame
[controller_server-5] [ERROR] [1662559476.322652384] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.322680234] [tf_help]: Data time: 1650561429s 312596865ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.322719845] [controller_server]: Unable to transform robot pose into global plan's frame
[controller_server-5] [ERROR] [1662559476.372619297] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.372652432] [tf_help]: Data time: 1650561429s 359513709ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.372701858] [controller_server]: Unable to transform robot pose into global plan's frame
[planner_server-6] [INFO] [1662559476.382329538] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561429.131 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[controller_server-5] [ERROR] [1662559476.422567640] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.422592091] [tf_help]: Data time: 1650561429s 407522001ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.422626783] [controller_server]: Unable to transform robot pose into global plan's frame
[controller_server-5] [ERROR] [1662559476.422659556] [controller_server]: Controller patience exceeded
[controller_server-5] [WARN] [1662559476.422720119] [controller_server_rclcpp_node]: [follow_path] [ActionServer] Aborting handle.
[controller_server-5] [INFO] [1662559476.441462962] [local_costmap.local_costmap]: Received request to clear entirely the local_costmap
[controller_server-5] [INFO] [1662559476.442254974] [controller_server]: Received a goal, begin computing control effort.
[planner_server-6] [INFO] [1662559476.518317482] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561429.265 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
[controller_server-5] [INFO] [1662559476.612480778] [controller_server]: Passing new path to controller.
[controller_server-5] [ERROR] [1662559476.612880332] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.612903766] [tf_help]: Data time: 1650561429s 599372561ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.612959105] [controller_server]: Unable to transform robot pose into global plan's frame
[controller_server-5] [WARN] [1662559476.613131744] [controller_server]: Control loop missed its desired rate of 20.0000Hz
[controller_server-5] [ERROR] [1662559476.613268880] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.613283246] [tf_help]: Data time: 1650561429s 599372561ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.613332388] [controller_server]: Unable to transform robot pose into global plan's frame
[controller_server-5] [ERROR] [1662559476.663676390] [tf_help]: Transform data too old when converting from odom to map
[controller_server-5] [ERROR] [1662559476.663702163] [tf_help]: Data time: 1650561429s 662789474ns, Transform time: 1650561428s 865311147ns
[controller_server-5] [WARN] [1662559476.663743423] [controller_server]: Unable to transform robot pose into global plan's frame
[planner_server-6] [INFO] [1662559476.666421739] [global_costmap.global_costmap_rclcpp_node]: Message Filter dropping message: frame 'rplidar_link' at time 1650561429.413 for reason 'the timestamp on the message is earlier than all the data in the transform cache'

**Comment by roni-kreinin** [comment]
Can you run `sudo apt install ros-galactic-turtlebot4-navigation` to update navigation to 0.1.1? There was a bug in 0.1.0 that caused the AMCL node to die like it does in this case.

**Comment by Kohl-Stefan** [comment]
Yes now it is working thank you.
