### ISSUE TITLE
[Generate a map] tutorial error - no map

### ISSUE THREAD

**Issue by twintwin0243** [turtlebot/turtlebot4#457]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

ros2 humble

### Type of issue

Select One

### Expected behaviour

With
`ros2 launch turtlebot4_navigation slam.launch.py`
and
`ros2 launch turtlebot4_viz view_robot.launch.py`

I wanted to follow the "Generating a map" tutorial.  According to the tutorial I should be able to see the map.

### Actual behaviour

- run `ros2 launch turtlebot4_navigation slam.launch.py` and `ros2 launch turtlebot4_viz view_robot.launch.py` to generate a map, but no map is received.

- I saw the error like the picture. I also checked other related issues on GitHub, but the issue is still not resolved. What should I do?

![image](https://github.com/user-attachments/assets/4826f410-1019-4c13-8292-e4cf2d51eb0d)

- Originally, my Ubuntu's rviz window would pop up, but now it doesn't pop up with the error message below.

![image](https://github.com/user-attachments/assets/dbee5ff5-4d91-4ab5-bbc2-d460fa7511bb)

-  Additionally, I upload a screen of running `ros2 topic list` and the output of the `timestamp`. Please recommend me what to do. thank you.

![image](https://github.com/user-attachments/assets/b7b37319-9f16-4485-ba8a-9ab9c60ea74e)

![image](https://github.com/user-attachments/assets/43cb48db-6dc8-49f1-bead-42528bdbef16)

### To Reproduce

1. confirm turtlebot is running and all hardware is connected
2. $ ros2 launch turtlebot4_navigation slam.launch.py
3. $ ros2 launch turtlebot4_viz view_robot.launch.py
4. An error occurred !

### Other notes

- I did not follow the tutorial's [Create a node], which is the previous step of [Generate a map], but ran [Generate a map] right away. Is there a problem here?

- And I can't see the [Generate a map] official site. Can't I go to the official site?

thank you.

**Comment by smatarCPR** [comment]
Hello @twintwin0243,
Thank you for reaching out on the Turtlebot 4 Github page. I am very sorry to hear that your are having issues with one of our products.

A couple of observations from the provided details:

- It appears you are attempting to launch the RVIZ command while SSH'ed into the Turtlebot. This should not be the case. The RVIZ command is to be run on the remote computer used to interface with the Turtlebot. The Turtlebot does not have a display connected by default, which is seen in the error message from the RVIZ launch command.
- You mentioned using a simple discovery setup, are you able to view and echo topics from the Turtlebot on your remote computer?
- Are you able to launch RVIZ on your computer and view the Turtlebot model without issue? Can you see the lidar scan data in RVIZ?

Let me know the results of these checks. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
