### ISSUE TITLE
starting TF4, the Wi-Fi is not available.

### ISSUE THREAD

**Issue by taara67** [turtlebot/turtlebot4#464]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

turtlebot4-desktop

### Type of issue

Networking

### Expected behaviour

When TF4 starts up,
Wireless LAN is available.

### Actual behaviour

wifi is not available for about 30 minutes

### To Reproduce

I basically set it up according to the manual.
I also set up NTP to deal with the network not being stable at startup.
But it didn't solve the problem.
These images below are the results of packet capture.
The Rpi was multicasting heartbeat messages within the LAN about 1000 times per second.
If you know anything about it, please let me know.

![RTPS_packet_1](https://github.com/user-attachments/assets/073268ca-1886-454b-bdb5-f9c855693c63)

![RTPS_packet2](https://github.com/user-attachments/assets/f4b1f1e8-04cc-42a5-a101-aacede06f239)

![Error_from_Rpi](https://github.com/user-attachments/assets/56f76195-ec02-4f20-9bd3-4221d09564e7)

**Comment by smatarCPR** [comment]
Hello @taara67 ,
Thank you for reaching out on the Turtlebot 4 Github page. I am very sorry to hear that you are encountering issues with your Turtlebot 4 unit.

I was wondering if you could provide some additional details regarding this issue. Specifically:

- When you mention Wi-Fi not being available for 30 minutes, are you referring to the time it takes for the Turtlebot4 network to appear after powering on the Turtlebot or is this the time it takes before the Turtlebot 4 connects to the specified network and receives/reports an IP address?
- Are you able to connect to the Turtlebot 4 using an ethernet connection (https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#recovering-the-raspberry-pi)? If so, do you also encounter a similar delay or is the ethernet connection established quickly?
- Would it be possible to share the log files from the Raspberry Pi? These can be generated using the command: `journalctl -b > turtlebot4_log.txt`

Looking forward to hearing from you soon!
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
