### ISSUE TITLE
I can't set up the robot initial location in rviz, when I launch nav_bringup.launch.py

### ISSUE THREAD

**Issue by orangelee89** [turtlebot/turtlebot4#465]
### Robot Model

Turtlebot4 Lite

### ROS distro

Galactic

### Networking Configuration

Simple Discovery

### OS

Ubuntu 20.04

### Built from source or installed?

Built from Source

### Package version

ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=/home/lee/out_door.yaml 

### Expected behaviour

RPI：
ros2 launch turtlebot4_bringup lite.launch.py

host：
ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=/home/lee/cris_map.yaml

ros2 launch turtlebot4_viz view_robot.launch.py  

after the command,set initial robot pose by :
![image](https://github.com/user-attachments/assets/d5aab311-fd67-4a1e-a477-6239443d3a71)

then I can use nav2 goal to navigate .

### Actual behaviour

when I run the command ,I got the info like it in host pc:
ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=/home/lee/cris_map.yaml
![image](https://github.com/user-attachments/assets/ef668d2d-eb37-4171-be1f-73a6f15e0b5d)

then I set the innitial pose by 2d pose estimate in rviz, there is nothing as below:
![image](https://github.com/user-attachments/assets/4116933b-746e-456e-98aa-7ae44e7179fe)

### To Reproduce

when I run the command ,I got the info like it in host pc:
ros2 launch turtlebot4_navigation nav_bringup.launch.py slam:=off localization:=true map:=/home/lee/cris_map.yaml
![image](https://github.com/user-attachments/assets/ef668d2d-eb37-4171-be1f-73a6f15e0b5d)

then I set the innitial pose by 2d pose estimate in rviz, there is nothing as below:
![image](https://github.com/user-attachments/assets/4116933b-746e-456e-98aa-7ae44e7179fe)

**Comment by RustyCPR** [comment]
Hi @orangelee89 
Galactic is no longer supported and EoL. Could you please update to Humble and retry? 
Thank you,
Rusty
