### ISSUE TITLE
Network Problem, It is Urgent

### ISSUE THREAD

**Issue by Tanjim13** [turtlebot/turtlebot4#47]
![ISSUE](https://user-images.githubusercontent.com/18646128/190108514-19152c5e-c9f0-4efc-93ed-b3af7d29ce36.jpg)
Hey, I have a problem with turtlebot4 connection. After ssh into raspberry pi, when I want to work, my connection is disconnected automatically. Do you have any suggestions? I have tried with another bot. Does it have any issue with the router? I am using TP-Link AC1900 Smart WiFi Router. I can not update or upgrade the packages of the raspberry pi.

**Comment by Tanjim13** [comment]
@roni-kreinin , can you kindly tell me what is the problem? I want to know the network requirements. Let me know as soon as possible. And it is more like a router thing cause if I change the router it works. Please let me know what is the problem, I need to sort out this problem as soon as possible.

**Comment by roni-kreinin** [comment]
@Tanjim13 this does seem to be an issue with your router. You may need to go into its settings and see if there is a firewall or some security settings that are blocking this. I personally use a TP-Link Archer-C1200 with default settings and haven't run into this issue before. There are some solutions posted [here](https://askubuntu.com/questions/899009/sudo-apt-update-always-giving-clearsigned-file-isnt-valid-got-nosplit-does) that may help you.

**Comment by Tanjim13** [comment]
@roni-kreinin , Thank you for the response. Yes, I have figured it out. The router was in access point mode. I need to change it to router mode. So, it is working fine.
