### ISSUE TITLE
Bug report with latest TB4 standard humble Image

### ISSUE THREAD

**Issue by ValentinLeglise** [turtlebot/turtlebot4#474]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

*

### Expected behaviour

Can SSH into the robot after connected to access point Turtlebot4

### Actual behaviour

![Screenshot from 2024-09-20 11-54-28](https://github.com/user-attachments/assets/f22abb37-f77b-46e6-b86d-2d71c584e223)

I tried to reflashed 2 robots standard, with the good image downloaded there: http://download.ros.org/downloads/turtlebot4/

I ve never had this problem before. It appears specifically when the new version of the image (turtlebot4_standard_humble_1.0.4.img). Maybe there is a problem with this new image.

### To Reproduce

1. Connect access point Turtlebot4
2. "ssh ubuntu10.42.0.1"

**Comment by aharshac** [comment]
@ValentinLeglise The SSH output explains both why this problem occurs and how you could solve it.

This is not a problem with the Turtlebot image, but rather a _feature_ of SSH. 
When you re-flashed the image, a new SSH key was created, but your PC remembers the Pi with its old fingerprint as defined in `/home/vleglise/.ssh/known_hosts` at line 3.

You can remove the old key with `ssh-keygen -f "/home/vleglise/.ssh/known_hosts" -R "10.42.0.1"`

Further, you could disable host key checking either when logging in to SSH with `ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@10.42.0.1` or by adding an entry to the `~/.ssh/config` file:

```
Host 10.42.*.*
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
```
This disables the host key checking for the 10.42.\*.\* subnet.
