### ISSUE TITLE
/cmd_vel no subscribers

### ISSUE THREAD

**Issue by dmorris0** [turtlebot/turtlebot4#481]
### Robot Model

Turtlebot4 Lite

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

```
ubuntu@ubuntu:~$ dpkg -s ros-$ROS_DISTRO-turtlebot4-PACKAGE_WITH_ISSUE
dpkg-query: package 'ros-humble-turtlebot4-package_with_issue' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
```

### Type of issue

Other

### Expected behaviour

When I publish to /cmd_vel, or use teleop, I expect the bot to move.  

### Actual behaviour

My turtlebot does not respond to Teleop or /cmd_vel.  When I view info on the /cmd_vel topic I see that it has a publisher but no subscriber -- I expect it to have a subscriber and no publisher as I'm not publishing anything.  On the Turtlebot I get:
```
~$ ros2 topic info /cmd_vel
Type: geometry_msgs/msg/Twist
Publisher count: 1
Subscription count: 0
```
From my PC, I get 2 publishers:
```
~$ ros2 topic info /cmd_vel
Type: geometry_msgs/msg/Twist
Publisher count: 2
Subscription count: 0
```
I can see contents of other topics, like /tf fine.  

### To Reproduce

I installed the latest firmware on the Create and did a factory reset.

I reinstalled the latest RPi image like here: https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image

I followed all the instructions on setting up the Discovery Server here: https://turtlebot.github.io/turtlebot4-user-manual/setup/discovery_server.html

**Comment by smatarCPR** [comment]
Hello @dmorris0 
Thank you for reaching out on the Turtlebot 4 Github page. I am very sorry to hear you are having an issue with one of our products.

I notice that you are using a discovery server setup, have you added an namespace to your environment or is there no namespace? If you have not yet implemented a namespace, it is strongly recommended you do.

If after implementing a namespace, the issue still persists send the turtlebot logs generated by the command: `journalctl -b > turtlebot4_log.txt`

Let me know how this recommendation works for you. Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by dmorris0** [comment]
@smatarCPR Thank you for the namespace suggestion.  When I set the namespace, then the new cmd_vel with namespace had a subscriber and I could control the Turtlebot!
