### ISSUE TITLE
 LiDAR Obstruction by Pillars and Camera on TurtleBot4 Standard Model

### ISSUE THREAD

**Issue by siwon0305** [turtlebot/turtlebot4#485]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Simple Discovery

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

![Screenshot from 2024-10-24 15-07-22](https://github.com/user-attachments/assets/c5ace7c6-ab4f-4c22-b763-05d783ff8dd7)

### Expected behaviour

I expect the LiDAR sensor on the TurtleBot4 Standard model to accurately detect and scan the surrounding environment without being obstructed by the robot's four pillars and the camera mounted directly behind it. Despite the presence of these structural components, the LiDAR should maintain a clear and unobstructed field of view to ensure reliable detection of obstacles and effective navigation.
----------------------------------
1. Is there any specific processing or configuration in the TurtleBot4 software that prevents the LiDAR from being obstructed by the pillars and camera?
2. If such processing exists, could you please direct me to the relevant folders and code sections where this is implemented?

### Actual behaviour

-

### Error messages

```bash
-
```

### To Reproduce

-

### Other notes

-

**Comment by hilary-luo** [comment]
@siwon0305 The standoffs and camera mount are solid objects and the lidar cannot see through them. These are very small regions that are blocked so it should not impact operation. The robot has full view of its environment between these obstructions and can fully map and navigate with the visible regions. If these small obstructions are a problem for you then you can remove the standoffs and replace them with screws to secure the pcba down and/or remove the camera.

Feel free to elaborate if this did not answer your question.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
