### ISSUE TITLE
ros2 launch depthai_examples yolov4_publisher.launch.py not publishing topics

### ISSUE THREAD

**Issue by Tanjim13** [turtlebot/turtlebot4#51]
I am having a problem with this script. When I echo topics of this script it is not showing me any data on the terminal. I have tried to echo "/color/yolov4_Spatial_detections, /color/image, /stereo/depth" topics which should be published according to the script. Even I do not see any errors.
![Screenshot 2022-09-21 at 12 32 54 PM](https://user-images.githubusercontent.com/18646128/191561033-f0272040-d955-4667-a556-384527413e78.png)

**Comment by roni-kreinin** [comment]
I am seeing the same thing. This is an issue with the `depthai_examples` package though, so can you move this issue to https://github.com/luxonis/depthai-ros-examples?

**Comment by Tanjim13** [comment]
I have already posted it in their forum.

**Comment by roni-kreinin** [comment]
Issue discussed at https://github.com/luxonis/depthai-ros/issues/140
