### ISSUE TITLE
Ros2 topic list does not show the Create3 is publishing topics for turtebot4 lite

### ISSUE THREAD

**Issue by Srimathi-tw** [turtlebot/turtlebot4#53]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic

 **Expected behaviour**
After following the setup instruction [https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html) with **turtlebot 4 lite** on typing `ros2 topic list` in pc it should show create 3 topics

 **Actual behaviour**
On typing `ros2 topic list` it runs in an infinite loop(we are not able to see anything in logs)

**To Reproduce**
Follow the setup with turtlebot4 lite in [https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html)

**Comment by roni-kreinin** [comment]
Can you try calling `killall _ros2_daemon` and then run `ros2 topic list` again?

**Comment by Srimathi-tw** [comment]
The above mentioned resolution works with our personal hotspot. But we want to try using corporate hotspot, so we tried following this link [https://iroboteducation.github.io/create3_docs/setup/xml-config/](https://iroboteducation.github.io/create3_docs/setup/xml-config/)

We used the below code 
```
<CycloneDDS>
  <Domain>
    <Id>any</Id>
    <General>
      <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
      <AllowMulticast>false</AllowMulticast>
      <EnableMulticastLoopback>true</EnableMulticastLoopback>
    </General>
    <Discovery>
      <ParticipantIndex>0</ParticipantIndex>
      <Peers>
        <Peer Address="${ROBOT_IP}:7410"/>
      </Peers>
    </Discovery>
  </Domain>
</CycloneDDS>

```
and changed `${ROBOT_IP}` to our custom Robot IP, but on doing `ros2 topic list` we only see 
```
/parameter_events
/rosout
```
. Could you please help us with steps for connecting to corporate wifi?

**Comment by roni-kreinin** [comment]
Did you use the RPi4 IP or Create 3 IP for the `${ROBOT_IP}`?

**Comment by Srimathi-tw** [comment]
We were using raspberry pi IP address

**Comment by roni-kreinin** [comment]
I believe for the create 3 instructions you should be using the Create 3's WiFi IP.

**Comment by Srimathi-tw** [comment]
@roni-kreinin tried create 3's ip still didn't work. Any pointers on how we can connect the bot to corporate wifi?

**Comment by roni-kreinin** [comment]
I would recommend making an issue at https://github.com/eclipse-cyclonedds/cyclonedds. They will be much more familiar with this.

**Comment by Srimathi-tw** [comment]
Thanks @roni-kreinin will close this issue then.
