### ISSUE TITLE
Connecting Turtlebot 4 to the virtual machine(UTM, VirtualBox,etc)

### ISSUE THREAD

**Issue by Tanjim13** [turtlebot/turtlebot4#54]
Hi, 
I am trying to connect my turtlebots using a virtual machine(UTM, VirtualBox, ). When I try it without virtual box(such as a directly Linux-installed laptop), I get the topic list from Turtlebot 4 on my laptop without ssh.  But I do not get the list when I try with the virtual machine installed Linux if I do not ssh into raspberry pi. Can you let me know the reasons and how to set up for virtual machine?

**Comment by Tanjim13** [comment]
I am attaching some screenshots to make it clear. 1st screenshot is of .bashrc file of my VirtualBox terminal. The second ss shows one virtualbox terminal and one rpi's terminal. And third ss is my virtual box terminal's ifconfig. 
![Screenshot 2022-09-23 at 12 49 31 PM](https://user-images.githubusercontent.com/18646128/192012989-c5eef4f1-9d6e-4cb5-a66e-d67defd98ab9.png)
![Screenshot 2022-09-23 at 12 54 19 PM](https://user-images.githubusercontent.com/18646128/192013004-8a1efe40-c2a1-4f1a-8ee4-4f79deb806cd.png)
![Screenshot 2022-09-23 at 12 45 33 PM](https://user-images.githubusercontent.com/18646128/192013554-64dbab64-72a2-4644-8c30-195d59002115.png)

**Comment by tonybaltovski** [comment]
Is the VM set to `bridge-mode` for the networking adaptor?

**Comment by Tanjim13** [comment]
@tonybaltovski, No, it is in NAT mode.
![Screenshot 2022-09-23 at 4 12 39 PM](https://user-images.githubusercontent.com/18646128/192049485-fcb96dbe-d8c2-4844-a1f0-7ddf39819c73.png)

**Comment by tonybaltovski** [comment]
Using NAT will put the VM on a separate network whereas using bridge mode will put it on the same network.  Use bridge mode to connect to the Raspberry Pi.

**Comment by Tanjim13** [comment]
@tonybaltovski Thank you so much. It worked.
