### ISSUE TITLE
Want to use turtlebot4 audio

### ISSUE THREAD

**Issue by Tanjim13** [turtlebot/turtlebot4#57]
Hi, I am trying to figure out how to work on the audio note of turtlebot4. I want to play some audio(Hi, How are you?) using the turtlebot 4 speaker. Is it possible? How to do so? Thank you.

**Comment by roni-kreinin** [comment]
You can control the Create 3 speaker using an [Audio Note](https://github.com/iRobotEducation/irobot_create_msgs/blob/galactic/msg/AudioNote.msg) message, or the [Audio Note Sequence](https://github.com/iRobotEducation/irobot_create_msgs/blob/galactic/action/AudioNoteSequence.action) action. I don't believe the Create 3 currently supports playing an actual audio file.

**Comment by Tauhid-Tanjim13** [comment]
Yes, I can only make beep beep noise with different hz. But I cannot convert text to speech. I think I will need to plug in a separate speaker to add this feature. Do you have any suggestion or resources how to do so? Thank you.
