### ISSUE TITLE
Communication LED is off, not working, why? How to fix it?

### ISSUE THREAD

**Issue by Tanjim13** [turtlebot/turtlebot4#59]
I am working with 6 Turtlebot 4 under the same router. Frequently, the COMM LED turns off automatically. I want to know the reason. I have separated them with different ROS_DOMAIN_ID  What is the proper and fastest way to turn on or fix the issue with COMM Led?

**Comment by roni-kreinin** [comment]
The COMM led being off indicates that the connection between the RPI4 and Create3 is not up. It may be that the Create 3 or RPi lose WiFi connection at some point. I would recommend trying to use FastRTPS as it will maintain the USB-C connection even if WiFi drops. Take a look at the tutorial [here](https://turtlebot.github.io/turtlebot4-user-manual/tutorials/multiple_robots.html#setting-the-environment-variable) for instructions on how to easily switch RMW's.

**Comment by Tanjim13** [comment]
@roni-kreinin , I have followed the instruction. I did it by creating and running ros_config.sh script in /usr/local/bin of RPI 4 of the turtlebot. But the problem is when I separate two turtlebots with different ROS_DOMAIN_ID and set RMW_IMPLEMENTATION to rmw_fastrtps_cpp using ros_config.sh, under the same wifi router, the IP address of both robots starts to blink. The last 3digits of IP addresses start to exchange among each other. For example, Turtlebot1 with domain_id 1 has IP address 192.168.0.106 and is switching to Turtlebot2's (domain_id 5) IP address 192.168.0.119 and vice versa. The remaining turtlebots(4 of them still using cyclone_dds) start making chiming sounds but not blinking. If I shut down one turtlebot that is using fastrtps, then the blinking/exchanging of other turtlebot stops. 

What should I do? 

Another thing is that it is not helping me to turn on the comm led.

**Comment by roni-kreinin** [comment]
I forgot to add to the instructions that you also need to update your `install.py` script. You can find the updated script [here](https://github.com/turtlebot/turtlebot4_setup/blob/roni-kreinin/domain_id/scripts/install.py). Download it and move it to `/usr/local/bin/`, then run the `ros_config.sh` script again.

**Comment by Tanjim13** [comment]
@roni-kreinin , It worked for those two turtlebot4. But when I tried with another one, the led lights, with led display is gone. But I could ssh into it using previous IP address.Then I ssh into it using ethernet cable with 192.168.185.3. But after using sudo wifi.sh -a it is showing me turtlebot4 wifi. But still led light and display is not working. How to fix this?

**Comment by roni-kreinin** [comment]
`sudo wifi.sh -a` puts the RPi back into AP mode. You need to connect it to the same WiFi network as the Create3.

**Comment by Tauhid-Tanjim13** [comment]
The problem is that turtlebot is working but the led display or lights are not turning on. I know how to connect to Create3 under same wifi. But LED light or display is not working. Even the three LED Light are not turning on (MTR,POWER, WIFI).

**Comment by roni-kreinin** [comment]
You can check the logs of the turtlebot4 service with `sudo journalctl -u turtlebot4 -r`. You might need to restart the service with `sudo systemctl restart turtlebot4`.

**Comment by Tanjim13** [comment]
I solve it using this command. sudo apt-get install -y ros-galactic-rmw-fastrtps-cpp
Cause it is not installed in our turtlebots's RPI. I think this the reason when I switch to rmw_fastrtps_cpp, my led lights and display turns off.
I might be wrong. But it is solved after installing this package.
sudo journalctl -u turtlebot4 -r
I saw errors in rmw implementation in the log file previously.
Oct 05 22:46:24 ubuntu turtlebot4-start[2032]: [ERROR] [1665009984.415286988] [rcl]: Error getting RMW implementation identifier / RMW implementation not installed (expected identifier of 'rmw_fastrtps_cpp'), with error message 'failed to load shared library 'librmw_fastrtps_cpp.so'>

**Comment by Tanjim13** [comment]
@roni-kreinin , I am still facing problem. It is very slow when students work with the six turtlebot4  simultaneously. So, should I add more routers? Or can I solve it in another way? Sometimes, COMM led is off for 20-30 seconds. What more can I do to make the turtlebot response smoothly under the same router? Or how many bots should I place under a router that will not slow it down?

**Comment by roni-kreinin** [comment]
@Tanjim13 I would like to figure out if this is a bandwidth or signal strength issue. Can you answer the following questions:

- Does the COMM led turn off while the robot is driving around or when it is standing still? 
- How strong is the WiFi signal for both 2.4 and 5GHz in the area that you are testing? You can check with a phone or laptop.
- Next time the COMMs light turns off, can you retrieve the logs from the Create 3 [webserver](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html#access-the-webserver-v013-or-higher) and upload them here?
- Can you also call `ros2 topic list` from a remote PC when the light turns off? To check that the RPi4 topics still publish.
- Can you check the framerate of the camera stream with `ros2 topic hz /color/preview/image`? It should be publishing at 30hz.
- Can you test one of the robots that is having this issue on its own? Does the issue persist if it is the only robot powered on?

**Comment by Tanjim13** [comment]
@roni-kreinin,

-  Sometimes, It goes off while driving (both in fastrtps & cyclonedds mode). But in fastrtps mode, it comes back after a few seconds. Another problem is that it is very slow when we run programs using virtual machines in fastrtps mode without ssh into RPI compare to cyclonedds. 
- For 5GHz:, RSSI: -45dBm, Noise: -93dBm, TxRate: 867Mbps...  2.4GHz: RSSI: -34dBm, Noise: -88~-93dBm, TxRate: 145Mbps
I will try to answer the rest of the questions when I work with them again.

**Comment by Tanjim13** [comment]
@roni-kreinin , I tried to retrieve logs from create3 webserver, but it did not work. I tried 192.168.0.103:8080, but it did not let me go to the site.
ros2 topic hz /color/preview/image it worked fine.. I will investigate it further.
fastrtps is very slow compare to cyclonedds.

**Comment by Tauhid-Tanjim13** [comment]
Hi @roni-kreinin , I want a suggestion. If I add routers to the turtlebot4 will it create any difference? Also if I use fastrtps do I need to change anything in my local linux machines? like changing in my ~/.bashrc file? I found fastrtps is very slow compare to cyclonedds. When I work alone, it is okay to work. But if multiple users in a same room working with 4-7 turtlebots simultaneously, I find comm stops working on few of them. Even in fastrtps it turns off and on.

**Comment by Tanjim13** [comment]
@roni-kreinin, I can access to Create3 webserver using the IP address of the iRobot-8XXXXXXXXXX device from the Router's connected devices. So, I checked that the version of Firmware version is G.2.2. 
Another turtlebot4 has come to the lab recently and I can access the web server using the IP address of RPI with 8080 port. The firmware version of this turtlebot4 is G.3.1. 

Another thing is that even if I use the IP address of the iRobot directly it does not let me update the firmware. So, I manually upgraded the firmware of one of the robots.

So, should I update the firmware of the create3 base? Will it solve the problem?

Also, can you clarify that this is happening because of turtlebot4's image version? Because I can use port 8080 only on the latest Turtlebot4 but not with other turtlebots. How do I upgrade this? Do I need to set up a new Turtlebot4 image from this [link](http://download.ros.org/downloads/turtlebot4/)? Or I can skip this.

I will try to send you the log files from the webserver next time when we will work with more robots simultaneously and if the COMM goes off.

**Comment by Tanjim13** [comment]
![Screenshot 2022-11-07 at 9 47 11 PM](https://user-images.githubusercontent.com/18646128/200463329-fadb56e8-aee9-41d8-b98f-fa11c9ceccc5.png)

The other two turtlebots are connected to another router in the same room.
![Screenshot 2022-11-07 at 9 51 48 PM](https://user-images.githubusercontent.com/18646128/200463982-50e7b317-d25c-4d49-8b3d-18bf6ec4d8b8.png)
![Screenshot 2022-11-07 at 9 53 35 PM](https://user-images.githubusercontent.com/18646128/200463985-043123a1-ffc3-4ff1-afbd-ea1412dfb7cd.png)
![Screenshot 2022-11-07 at 9 53 45 PM](https://user-images.githubusercontent.com/18646128/200463987-2df8d34a-76f9-4a28-b1e0-dfb0c1c0ef22.png)

**Comment by roni-kreinin** [comment]
@Tanjim13 Sorry for the delay.

I would recommend updating any robots you have to G.3.1 to have all of the latest Create 3 features and bug fixes. As for accessing the webserver with the 8080 port, that is only installed by default on the 0.1.3 image in the link you mentioned. You can manually add it to an older image if you want by copying [this](https://github.com/turtlebot/turtlebot4_setup/blob/galactic/conf/webserver.service) file to `/etc/systemd/system/` and then calling `sudo systemctl enable webserver.service`.

Regarding the comms issue, the easiest solution is likely to just use 2 routers and have 3 robots on each. There is an update coming that adds discovery server support to the Create 3, but until then there isn't a great solution.

**Comment by Tanjim13** [comment]
@roni-kreinin Thank you so much.

I will look into it.

**Comment by roni-kreinin** [comment]
Closing as stale. Feel free to reopen if the issue persists.
