### ISSUE TITLE
Place the plate higher

### ISSUE THREAD

**Issue by gdesimone97** [turtlebot/turtlebot4#60]
Hi, I need to place the plate higher. 
How can I do this? 
Where can I buy this taller component?

![image](https://user-images.githubusercontent.com/44608428/193601781-8bd2f595-de77-479e-a709-cc2159553fd7.png)
![image (1)](https://user-images.githubusercontent.com/44608428/193601770-6a90c5d9-34de-433a-817d-bb84318e9880.png)

Best regards,
Giuseppe De Simone, PhD

**Comment by apopielas** [comment]
Hi! You can use any M4X0.7 Male-Female Standoffs. [Mcmaster Carr has some that would work](https://www.mcmaster.com/spacers/threaded-standoffs/system-of-measurement~metric/system-of-measurement~metric/thread-size~m4/material~aluminum/). Any other hardware supplier will also likely have them.

Just get enough to adjust the height to what you need. 

The standoffs we use on the TTB4 are made in quantity at a machine shop so you can also reach out to a local machine shop and see what they can do.

**Comment by gdesimone97** [comment]
Thank you very much for your reply
