### ISSUE TITLE
Facing issues with turtlebot4_ignition_bringup 

### ISSUE THREAD

**Issue by Tanjim13** [turtlebot/turtlebot4#67]
Whenever I run this command: ros2 launch turtlebot4_ignition_bringup ignition.launch.py
My turtlebot4's  **comm, wifi and batt leds** start blinking.  
And ip address switches between UNKNOWN and 192.168.0.103 (turtlebot's ip) very rapidly.
Is it the case Gazebo is only for virtual turtlebot not for physical turtlebot?

**Comment by roni-kreinin** [comment]
You need to use a different ROS_DOMAIN_ID if you are running the simulation and a real robot concurrently. Otherwise the ros2 topics of the simulation will interfere with the robot.

**Comment by Tanjim13** [comment]
Okay, I will try and let you know. Thank you.

**Comment by roni-kreinin** [comment]
@Tanjim13 Did this resolve your issue?

**Comment by Tanjim13** [comment]
@roni-kreinin, I have not checked it yet. If I failed to resolve it, I will open it again. Now I am closing this issue. Hope it will work.
