### ISSUE TITLE
how can i get data from turtlebot4 clearpath to remote pc

### ISSUE THREAD

**Issue by moon891031** [turtlebot/turtlebot4#69]
**Please provide the following information:**
 - OS: turtlebot4 Clearpath Ubuntu 20.04 & remote pc ubuntu 20.04 
 - ROS Distro: turtlebot4 standard- galactic & remote pc - galactic 
 
 **Expected behaviour**
      i expected 'ros2 topic echo /odom' on remote pc 
      i thought it can receive data. 
     but there is no /odom 

    i set up on turtlebot4 : 
              bashrc -> 'export RMW_IMPLEMENTATION=rmw_fastrtps_cpp'  
              
   remote pc only conneting wifi, and ros2 

  and turtlebot can move by my wireless controller ps4 
   
  and when run to rviz on remote pc , there is no global status. and robotmodel 

  and i tried to pub like this 'ros2 topic pub --rate 1 /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.5, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 1.0}}"' on remote PC then no action 
 
 but on turtlebot4 did 'ros2 topic pub --rate 1 /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.5, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 1.0}}"'  is working 

 and i use our place iptime, turtlebot connected 5Ghz, my computer Pc using wirelessLan receiver connected 5Ghz, create3? i don't know  

so how can i get the data from turtlebot4 to remote pc . what is problem?? plz help me... i spent time too many T.T

 **Actual behaviour**
 ssh-> into turtlebot4 clearpth : 
     $ros2 topic list 
           result:
                /battery_state
                /cmd_audio
                /cmd_lightring
                /cmd_vel
                /color/preview/camera_info
                /color/preview/image
                /diagnostics
                /diagnostics_agg
                /diagnostics_toplevel_state
                /dock
                /hazard_detection
                /hmi/buttons
                /hmi/display
                /hmi/display/message
                /hmi/led
                /imu
                /interface_buttons
                /ip
                /ir_intensity
                /ir_opcode
                /joint_states
                /joy
                /joy/set_feedback
                /kidnap_status
                /mouse
                /odom
                /parameter_events
                /robot_description
                /robot_state/transition_event
                /rosout
                /scan
                /slip_status
                /static_transform/transition_event
                /stereo/camera_info
                /stereo/depth
                /stop_status
                /system_monitor/transition_event
                /tf
                /tf_static
                /wheel_status
                /wheel_ticks
                /wheel_vels

 remote pc :
      $ros2 topic list 
       result : 
            /battery_state
            /cmd_vel
            /color/preview/camera_info
            /color/preview/image
            /diagnostics
            /diagnostics_agg
            /diagnostics_toplevel_state
            /dock
            /hazard_detection
            /hmi/buttons
            /hmi/display
            /hmi/display/message
            /hmi/led
            /imu
            /interface_buttons
            /ip
            /joint_states
            /joy
            /joy/set_feedback
            /mouse
            /parameter_events
            /robot_description
            /rosout
            /scan
            /stereo/camera_info
            /stereo/depth
            /tf
            /tf_static
            /wheel_status
    

+ 
i ran on remotepc 
ros2 launch turtlebot4_navigation slam_sync.launch.py
ros2 launch turtlebot4_viz view_robot.launch.py 

![Screenshot from 2022-10-19 18-03-40](https://user-images.githubusercontent.com/101680018/196647050-81d42b66-13dd-4ea2-a5e0-5126ca8f2e54.png)

ros2 launch turtlebot4_viz view_model.launch.py

![Screenshot from 2022-10-19 18-04-58](https://user-images.githubusercontent.com/101680018/196647348-faab9819-0986-4e47-a49d-70d8746cc999.png)
![Screenshot from 2022-10-19 18-05-46](https://user-images.githubusercontent.com/101680018/196647574-ad4d632d-39b4-4ab7-a240-93012a966afb.png)

**Comment by moon891031** [comment]
hello 
maybe remote pc cannot communication with Create3 Data , just RPI4 data. 
on remote pc , only can echo /cmd_vel, can not echo /odom

**Comment by HSmoon1031** [comment]
anybody there~~~~~~~~~~~~~? plz give me hint~~~~~~~~~~~~~```

**Comment by roni-kreinin** [comment]
The Create3 needs to be connected to a 2.4GHz network that is bridged with your 5GHz network. Otherwise data will only be sent over USB to RPi4, and not to your remote PC.
