### ISSUE TITLE
RPi 4 doesn't support Ubuntu 20.04

### ISSUE THREAD

**Issue by Alaric102** [turtlebot/turtlebot4#76]
I have read that RPi4 doesn't support Ubuntu 20.04 anymore. I tried to install your image from [here](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html#install-latest-raspberry-pi-image) - It doesn't work. Also, I tried to install the official versions from Ubuntu web site - the result is same. 

When I turn on the RPi4 with any Ubuntu 20.04 the red diode is lightning stable, the green one is flashing for 5-10 seconds (I have read that it must flash ~20 sec) and after blinking. My screen light is also blinking.

So, what should I do if no options to install Ubuntu 20.04 on my RPi4?

**Comment by roni-kreinin** [comment]
RPi4 does support 20.04 and the image should work. Which screen light is blinking? The Turtlebots?
