### ISSUE TITLE
Consolidating all configuration scripts into a simple CLI.

### ISSUE THREAD

**Issue by roni-kreinin** [turtlebot/turtlebot4#77]
**Describe the the feature you would like**
For the Humble release we are looking to simplify TurtleBot 4 configuration by combining the [setup scripts](https://github.com/turtlebot/turtlebot4_setup/tree/galactic/scripts) into a single script that would have a simple menu with options for Wi-Fi setup, ROS configuration, `robot_upstart` install/uninstall, and more.

We are looking for some feedback from the community on your experience with the current way that we do robot configuration, and what your thoughts are on this approach. If you have any ideas or suggestions please let us know.

**Comment by escortKwon** [comment]
@roni-kreinin I have some issues transferring between RP4 and iCreate3. Therefore, I hope the procedure or process of connecting both of them could be renewed or got better. I have followed instructions from User Manual or retail dealer but there were no better results than keeping original state. Thanks!

**Comment by alexswerner** [comment]
I agree that to start working with this robot, this are rather complicated. Especially considering that this is a robot targetting beginners. I am not easily convinced that GUIs (even text mode) are always a gain, but here it is a good option. Even better however would be sane(r) defaults (e.g. fastdds) and a network setup which is less involved/more robust (no base wifi).

**Comment by roni-kreinin** [comment]
Here is a sample of the CLI wifi setup, let me know what you think:

![wifi_setup](https://user-images.githubusercontent.com/59886299/202585202-93e0473c-a139-456d-a78b-34584d407056.gif)

@alexswerner FastDDS will be the default RMW for Humble and we will ship robots with it as the default. It will also be much easier to switch between RMW using this tool. 

Regarding #26, we have found a configuration using Discovery Servers that works. iRobot is testing it and will be adding options for this to the Create3 webserver. I will add similar options to this CLI tool to make it as easy as possible to set up. There will be some configuration required on the user PC as well but I think it should be fairly simple. We still need to test performance with many robots on the same network, but I think we will see significant improvements.

**Comment by alexswerner** [comment]
Looks helpful. Small suggestion: I suggest to put the line which switches from AP to client above the SSID etc.

**Comment by roni-kreinin** [comment]
Humble has been released with the `turtlebot4_setup` tool.
