### ISSUE TITLE
Requesting sdf models to be uploaded in ignition gazebo fuel 

### ISSUE THREAD

**Issue by MithunKinarullathil** [turtlebot/turtlebot4#8]
**Describe the the feature you would like**
Hi, we are (mov.ai) currently using the [ignition gazebo fuel repository](https://app.gazebosim.org/dashboard) to easily test the models and worlds for our simulations using our [opensource platform](https://github.com/MOV-AI/movai-flow). We would love to test out the turtlebot4 simulator and make demos out of it. Could I kindly request you if it's possible to make the models available in the ignition fuel repository? Thank you.

**Other notes**

**Comment by roni-kreinin** [comment]
I'll look into it.

**Comment by MithunKinarullathil** [comment]
Great, thanks.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you do not feel like your request has been addressed fully then feel free to reopen the issue and restart the dialog.
