### ISSUE TITLE
TB4 cameras not working

### ISSUE THREAD

**Issue by bld7** [turtlebot/turtlebot4#80]
I cannot get the cameras working. Please advise.
I tried
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py
which resulted in the following error message:

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-20-03-53-57-055146-ubuntu-1485
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgb_stereo_node-1]: process started with pid [1487]
[rgb_stereo_node-1] terminate called after throwing an instance of 'std::runtime_error'
[rgb_stereo_node-1]   what():  No available devices
[rgb_stereo_node-1] Stack trace (most recent call last):
[rgb_stereo_node-1] #11   Object "/opt/ros/galactic/lib/depthai_examples/rgb_stereo_node", at 0xaaaae4008d37, in 
[rgb_stereo_node-1] #10   Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffff8104de0f, in __libc_start_main
[rgb_stereo_node-1] #9    Object "/opt/ros/galactic/lib/depthai_examples/rgb_stereo_node", at 0xaaaae4007ce7, in 
[rgb_stereo_node-1] #8    Object "/opt/ros/galactic/lib/aarch64-linux-gnu/libdepthai-core.so", at 0xffff815951f3, in dai::Device::Device(dai::Pipeline const&)
[rgb_stereo_node-1] #7    Object "/opt/ros/galactic/lib/aarch64-linux-gnu/libdepthai-core.so", at 0xffff815a730f, in dai::DeviceBase::DeviceBase(dai::OpenVINO::Version)
[rgb_stereo_node-1] #6    Object "/opt/ros/galactic/lib/aarch64-linux-gnu/libdepthai-core.so", at 0xffff8159d7e7, in dai::DeviceBase::tryGetDevice()
[rgb_stereo_node-1] #5    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff81263573, in __cxa_throw
[rgb_stereo_node-1] #4    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff8126327f, in std::terminate()
[rgb_stereo_node-1] #3    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff8126321b, in 
[rgb_stereo_node-1] #2    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffff812658cb, in __gnu_cxx::__verbose_terminate_handler()
[rgb_stereo_node-1] #1    Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffff8104daab, in abort
[rgb_stereo_node-1] #0    Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffff81060d78, in gsignal
[rgb_stereo_node-1] Aborted (Signal sent by tkill() 1487 1000)
[ERROR] [rgb_stereo_node-1]: process has died [pid 1487, exit code -6, cmd '/opt/ros/galactic/lib/depthai_examples/rgb_stereo_node --ros-args --params-file /tmp/launch_params_8ck821ib --params-file /tmp/launch_params_s4346vbw --params-file /tmp/launch_params_185e583r --params-file /tmp/launch_params_3l741p98 --params-file /tmp/launch_params_utc5x_jq --params-file /tmp/launch_params_g62vq4f3 --params-file /tmp/launch_params_7orrfo9l --params-file /tmp/launch_params_32cmpp0_ --params-file /tmp/launch_params_7pui7c3i --params-file /tmp/launch_params_9inj9esh --params-file /tmp/launch_params_5ywqa6z7 --params-file /tmp/launch_params_7f_9ol5y --params-file /tmp/launch_params_jrjfab0y --params-file /tmp/launch_params__jxxgrmf'].

I also tried
ubuntu@ubuntu:~$ ros2 launch depthai_examples mobile_publisher.launch.py
which resulted in the following error message.

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-21-22-13-34-244676-ubuntu-1490
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [mobilenet_node-1]: process started with pid [1493]
[INFO] [robot_state_publisher-2]: process started with pid [1495]
[robot_state_publisher-2] Link oak-d_frame had 5 children
[robot_state_publisher-2] Link oak_imu_frame had 0 children
[robot_state_publisher-2] Link oak_left_camera_frame had 1 children
[robot_state_publisher-2] Link oak_left_camera_optical_frame had 0 children
[robot_state_publisher-2] Link oak_model_origin had 0 children
[robot_state_publisher-2] Link oak_rgb_camera_frame had 1 children
[robot_state_publisher-2] Link oak_rgb_camera_optical_frame had 0 children
[robot_state_publisher-2] Link oak_right_camera_frame had 1 children
[robot_state_publisher-2] Link oak_right_camera_optical_frame had 0 children
[robot_state_publisher-2] [INFO] [1669068815.447841295] [oak_state_publisher]: got segment oak-d-base-frame
[robot_state_publisher-2] [INFO] [1669068815.448166718] [oak_state_publisher]: got segment oak-d_frame
[robot_state_publisher-2] [INFO] [1669068815.451300333] [oak_state_publisher]: got segment oak_imu_frame
[robot_state_publisher-2] [INFO] [1669068815.451395536] [oak_state_publisher]: got segment oak_left_camera_frame
[robot_state_publisher-2] [INFO] [1669068815.451514794] [oak_state_publisher]: got segment oak_left_camera_optical_frame
[robot_state_publisher-2] [INFO] [1669068815.451575256] [oak_state_publisher]: got segment oak_model_origin
[robot_state_publisher-2] [INFO] [1669068815.451621274] [oak_state_publisher]: got segment oak_rgb_camera_frame
[robot_state_publisher-2] [INFO] [1669068815.451656255] [oak_state_publisher]: got segment oak_rgb_camera_optical_frame
[robot_state_publisher-2] [INFO] [1669068815.451689014] [oak_state_publisher]: got segment oak_right_camera_frame
[robot_state_publisher-2] [INFO] [1669068815.451722921] [oak_state_publisher]: got segment oak_right_camera_optical_frame
[mobilenet_node-1] [18443010E197631200] [200.730] [system] [error] Attempted to start Color camera - NOT detected!

**Comment by roni-kreinin** [comment]
@bld7 Can you disconnect the cameras USB cable, then reconnect it, call `dmesg` on the RPi, and paste the logs here? You should see logs similar to this:

```
[329267.092099] usb 1-5.3.3: new high-speed USB device number 62 using xhci_hcd
[329267.200596] usb 1-5.3.3: New USB device found, idVendor=03e7, idProduct=2485, bcdDevice= 0.01
[329267.200599] usb 1-5.3.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[329267.200600] usb 1-5.3.3: Product: Movidius MyriadX
[329267.200602] usb 1-5.3.3: Manufacturer: Movidius Ltd.
[329267.200603] usb 1-5.3.3: SerialNumber: 03e72485
```

**Comment by bld7** [comment]
Here's the logs
[  489.003651] usb 1-1.2: USB disconnect, device number 6
[  509.196487] usb 1-1.2: new high-speed USB device number 7 using xhci_hcd
[  509.297255] usb 1-1.2: New USB device found, idVendor=03e7, idProduct=2485, bcdDevice= 0.01
[  509.297263] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  509.297267] usb 1-1.2: Product: Movidius MyriadX
[  509.297271] usb 1-1.2: Manufacturer: Movidius Ltd.
[  509.297274] usb 1-1.2: SerialNumber: 03e72485

**Comment by roni-kreinin** [comment]
And it still does not launch with `ros2 launch turtlebot4_bringup oakd.launch.py`?

**Comment by bld7** [comment]
No it does not work. The error message has changed:
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-22-17-40-09-232802-ubuntu-1654
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgb_stereo_node-1]: process started with pid [1656]
[rgb_stereo_node-1] [18443010E197631200] [930.817] [system] [error] Attempted to start Color camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [930.817] [system] [error] Attempted to start Mono Left camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [930.817] [system] [error] Attempted to start Mono Right camera - NOT detected!

**Comment by roni-kreinin** [comment]
Is the `turtlebot4` service still running in the background? You can check with `sudo systemctl status turtlebot4`.

**Comment by bld7** [comment]
It appears to be. Here is the displayed result in the terminal:
ubuntu@ubuntu:~$ sudo systemctl status turtlebot4
● turtlebot4.service - "bringup turtlebot4"
     Loaded: loaded (/lib/systemd/system/turtlebot4.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-04-21 12:54:49 UTC; 7 months 2 days ago
   Main PID: 757 (turtlebot4-star)
      Tasks: 82 (limit: 4435)
     CGroup: /system.slice/turtlebot4.service
             ├─ 757 /bin/bash /usr/sbin/turtlebot4-start
             ├─1022 /usr/bin/python3 /opt/ros/galactic/bin/ros2 launch /tmp/turtlebot4.launch.py
             ├─1121 /opt/ros/galactic/lib/turtlebot4_node/turtlebot4_node --ros-args --params-file /opt/ros/galactic/share/turtlebot4_bringup/config/>
             ├─1123 /opt/ros/galactic/lib/turtlebot4_base/turtlebot4_base_node --ros-args --params-file /opt/ros/galactic/share/turtlebot4_bringup/co>
             ├─1125 /opt/ros/galactic/lib/joy_linux/joy_linux_node --ros-args -r __node:=joy_linux_node
             ├─1127 /opt/ros/galactic/lib/teleop_twist_joy/teleop_node --ros-args -r __node:=teleop_twist_joy_node --params-file /opt/ros/galactic/sh>
             ├─1129 /opt/ros/galactic/lib/diagnostic_aggregator/aggregator_node --ros-args --params-file /opt/ros/galactic/share/turtlebot4_diagnosti>
             ├─1131 /usr/bin/python3 /opt/ros/galactic/lib/turtlebot4_diagnostics/diagnostics_updater --ros-args
             ├─1133 /opt/ros/galactic/lib/rplidar_ros/rplidar_composition --ros-args -r __node:=rplidar_composition --params-file /tmp/launch_params_>
             └─1137 /opt/ros/galactic/lib/robot_state_publisher/robot_state_publisher --ros-args -r __node:=robot_state_publisher --params-file /tmp/>

Nov 22 17:13:26 ubuntu turtlebot4-start[1022]: [rgb_stereo_node-8] #2    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffffa15af8cb, in __gnu_>
Nov 22 17:13:26 ubuntu turtlebot4-start[1022]: [rgb_stereo_node-8] #1    Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffffa1397aab, in abort
Nov 22 17:13:26 ubuntu turtlebot4-start[1022]: [rgb_stereo_node-8] #0    Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffffa13aad78, in gsignal
Nov 22 17:13:26 ubuntu turtlebot4-start[1022]: [rgb_stereo_node-8] Aborted (Signal sent by tkill() 1135 1000)
Nov 22 17:13:27 ubuntu turtlebot4-start[1022]: [ERROR] [rgb_stereo_node-8]: process has died [pid 1135, exit code -6, cmd '/opt/ros/galactic/lib/dept>
Nov 22 17:16:11 ubuntu turtlebot4-start[1022]: [turtlebot4_node-1] [INFO] [1669137371.022639427] [turtlebot4_node]: Undocking
Nov 22 17:16:11 ubuntu turtlebot4-start[1022]: [turtlebot4_node-1] [INFO] [1669137371.022790425] [turtlebot4_node]: Waiting for undock action server
Nov 22 17:16:12 ubuntu turtlebot4-start[1022]: [turtlebot4_node-1] [INFO] [1669137372.023226400] [turtlebot4_node]: undock action server available, s>
Nov 22 17:16:12 ubuntu turtlebot4-start[1022]: [turtlebot4_node-1] [INFO] [1669137372.109440246] [turtlebot4_node]: undock goal accepted by server, w>
Nov 22 17:16:17 ubuntu turtlebot4-start[1022]: [turtlebot4_node-1] [INFO] [1669137377.681337752] [turtlebot4_node]: undock goal succeeded

**Comment by roni-kreinin** [comment]
It looks like it was crashing there too. Would you happen to have a USB-C to USB-C cable that you could connect to one of the PCBA USB-C ports? Or another USB-A to USB-C cable that you could replace the current one with? I'm interested to see if the issue is with the camera or the cable. Also make sure that it is plugged into one of the blue USB 3.0 ports if you are using a USB-A cable.

**Comment by bld7** [comment]
I used the extra USB-A to USB-C cable sent with the TB4.
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py gives the same error message as the one I first sent you - No available devices.

**Comment by bld7** [comment]
I checked the USB-C and it did not have a good connection. I removed the camera and tried again. Same error:
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-22-18-27-51-496749-ubuntu-1844
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgb_stereo_node-1]: process started with pid [1846]
[rgb_stereo_node-1] [18443010E197631200] [23.599] [system] [error] Attempted to start Color camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [23.599] [system] [error] Attempted to start Mono Left camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [23.599] [system] [error] Attempted to start Mono Right camera - NOT detected!

**Comment by roni-kreinin** [comment]
Just to be safe can you try this:
- Unplug the USB-C again
- Disable the `turtlebot4` service - `sudo systemctl disable turtlebot4`
- Reboot the RPi - `sudo reboot`
- Wait for SSH session to reconnect
- Plug the camera back in and run `ros2 launch turtlebot4_bringup oakd.launch.py`

**Comment by bld7** [comment]
Went through your list with the new cable. Same error:
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-22-19-59-50-456904-ubuntu-1314
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgb_stereo_node-1]: process started with pid [1316]
[rgb_stereo_node-1] [18443010E197631200] [25.979] [system] [error] Attempted to start Color camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [25.979] [system] [error] Attempted to start Mono Left camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [25.979] [system] [error] Attempted to start Mono Right camera - NOT detected!

**Comment by saching13** [comment]
@bld7  
- is this OAK-D-Lite or OAK-D-Pro ?
- Can you run the launch command with a prefix of `DEPTHAI_LEVEL=debug` and share the logs please ?

**Comment by bld7** [comment]
We bought a standard TB4, so it should be an OAK-D-Pro.
I executed the command:
ubuntu@ubuntu:~$ ros2 launch turtlebot4_bringup oakd.launch.py DEPTHAI_LEVEL:=debug
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-23-19-32-35-886942-ubuntu-1361
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgb_stereo_node-1]: process started with pid [1363]
[rgb_stereo_node-1] [18443010E197631200] [283.076] [system] [error] Attempted to start Color camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [283.076] [system] [error] Attempted to start Mono Left camera - NOT detected!
[rgb_stereo_node-1] [18443010E197631200] [283.076] [system] [error] Attempted to start Mono Right camera - NOT detected!

Killed with Ctrl-C

Log file contents:
ubuntu@ubuntu:~/.ros/log/2022-11-23-19-36-31-960629-ubuntu-1395$ more launch.log
1669232191.9693925 [INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-23-19-36-31-960629-ubuntu-1395
1669232191.9702470 [INFO] [launch]: Default logging verbosity is set to INFO
1669232192.7112648 [INFO] [rgb_stereo_node-1]: process started with pid [1397]
1669232225.9028938 [WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
1669232227.0280821 [INFO] [rgb_stereo_node-1]: process has finished cleanly [pid 1397]

**Comment by roni-kreinin** [comment]
@bld7 Can you try launching it like this: `DEPTHAI_LEVEL=debug ros2 launch turtlebot4_bringup oakd.launch.py`?

**Comment by bld7** [comment]
The terminal output is given in the attached file.

[terminal_output.txt](https://github.com/turtlebot/turtlebot4/files/10106628/terminal_output.txt)

**Comment by roni-kreinin** [comment]
@saching13 Do you see anything in the logs that would help?

**Comment by bld7** [comment]
The content for the two log files I found are:
ubuntu@ubuntu:~/.ros/log/2022-11-28-18-45-05-765776-ubuntu-1720$ more launch.log 
1669661105.7743659 [INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-11-28-18-45-05-765776-ubuntu
-1720
1669661105.7752223 [INFO] [launch]: Default logging verbosity is set to INFO
1669661106.5147333 [INFO] [rgb_stereo_node-1]: process started with pid [1722]
1669661143.9237084 [WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
1669661145.0544739 [INFO] [rgb_stereo_node-1]: process has finished cleanly [pid 1722]

and
ubuntu@ubuntu:~/.ros/log$ more rgb_stereo_node_1722_1669661106701.log
[INFO] [1669661143.922794789] [rclcpp]: signal_handler(signal_value=2)

**Comment by bld7** [comment]
Ever since I executed the  commands suggested earlier:

    Unplug the USB-C again
    Disable the turtlebot4 service - sudo systemctl disable turtlebot4
    Reboot the RPi - sudo reboot
    Wait for SSH session to reconnect
    Plug the camera back in and run ros2 launch turtlebot4_bringup oakd.launch.py

The LCD display and LEDs above the display are dark. Plus a number of nodes are not starting up, for example the nodes
/turtlebot4_base_node
/turtlebot4_diagnostics
/turtlebot4_node

What should I do to resolve these problems?

**Comment by roni-kreinin** [comment]
@bld7 You can run `sudo systemctl enable turtlebot4` to re-enable the service, then `sudo systemctl start turtlebot4` to start it up.

**Comment by saching13** [comment]
@bld7  sorry for the delay. Can you run [this](https://github.com/luxonis/depthai-python/blob/main/examples/calibration/calibration_dump.py) script and share the dump from it ?
it looks like some new config we added might be missing. 
And also can you check which version of depthai is used here ?

**Comment by bld7** [comment]
I tried running the script, but it cannot find the module depthai. How do I go about running the script?
The version of depthai is 2.15.4 (taken from packge.xml).

**Comment by saching13** [comment]
There is a install_requirements.py script in that repo which installs python version api needed for the script.

**Comment by bld7** [comment]
See the attached file for the script output.
[calibration_dump_terminal_output.txt](https://github.com/turtlebot/turtlebot4/files/10158409/calibration_dump_terminal_output.txt)

**Comment by saching13** [comment]
looks like depthai-core version is old. it should be 2.17+ for that configuration.
 can you try installing the newest version using `ros-<dist>depthai`

**Comment by bld7** [comment]
sudo apt install ros-galactic-depthai installed version 2.19.1.
There still is a problem, since ros2 launch turtlebot4_bringup oakd.launch.py displayed
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-12-07-19-50-29-474110-ubuntu-3049
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rgb_stereo_node-1]: process started with pid [3051]
[ERROR] [rgb_stereo_node-1]: process has died [pid 3051, exit code -11, cmd '/opt/ros/galactic/lib/depthai_examples/rgb_stereo_node --ros-args --params-file /tmp/launch_params_zpncituv --params-file /tmp/launch_params_8piwaucf --params-file /tmp/launch_params_i3yzrsob --params-file /tmp/launch_params_1xizdewc --params-file /tmp/launch_params_ej9655kc --params-file /tmp/launch_params_74skpchf --params-file /tmp/launch_params_74xx7jw_ --params-file /tmp/launch_params_dkltp__5 --params-file /tmp/launch_params_nzg_p28q --params-file /tmp/launch_params_4anszgsu --params-file /tmp/launch_params_rvy91aa4 --params-file /tmp/launch_params_o6j4zwm6 --params-file /tmp/launch_params_wrvhsq4v --params-file /tmp/launch_params_ops49zz7'].

**Comment by saching13** [comment]
Can you send me full error ?
And try with stereo_inertial_node too

**Comment by bld7** [comment]
Attached is the output from
ros2 launch -d turtlebot4_bringup oakd.launch.py
and
ros2 launch -d depthai_examples stereo_inertial_node.launch.py
[oakd_debug_output.txt](https://github.com/turtlebot/turtlebot4/files/10186708/oakd_debug_output.txt)

**Comment by saching13** [comment]
`ros2 launch -d turtlebot4_bringup oakd.launch.py` on this can you do this instead `DEPTHAI_LEVEL=debug ros2 launch turtlebot4_bringup oakd.launch.py`


`ros2 launch -d depthai_examples stereo_inertial_node.launch.py` it looks like working. Stopped by interrupt 
> [INFO] [stereo_inertial_node-1]: sending signal 'SIGINT' to process[stereo_inertial_node-1]


Crash seems to be because of RVIZ in it. WHich can be disabled by adding argument  `enableRviz=false`

**Comment by bld7** [comment]
The output from 
DEPTHAI_LEVEL=debug ros2 launch turtlebot4_bringup oakd.launch.py
and
ros2 launch -d depthai_examples stereo_inertial_node.launch.py enableRviz:=false
is attached in the file.
[oakd_output_dec10_2022.txt](https://github.com/turtlebot/turtlebot4/files/10200377/oakd_output_dec10_2022.txt)

**Comment by roni-kreinin** [comment]
@bld7 At this point I would recommend re-installing the RPI image by following the instructions here https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html#install-latest-raspberry-pi-image.

**Comment by saching13** [comment]
@bld7  looks like the issue was rviz2 package not being there. I added additional condition to remove that on the stereo_inertial_node [here](https://github.com/luxonis/depthai-ros/commit/04886e65141a48ce55fc0cc615c22b5e2023b6f9) and removed from rgb_stereo_node launch file.

Can you try it out and let me know if it fixes the problem ?

**Comment by bld7** [comment]
@roni-kreinin I re-installed the latest RPI image. Executing ros2 launch turtlebot4_bringup oakd.launch.py still produced an error. See the attached file.
[output_after_rpi_image_reinstall.txt](https://github.com/turtlebot/turtlebot4/files/10385336/output_after_rpi_image_reinstall.txt)

**Comment by roni-kreinin** [comment]
@bld7 Try running the following to fix the udev rules:

```
echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee /etc/udev/rules.d/80-movidius.rules
sudo udevadm control --reload-rules && sudo udevadm trigger
```

**Comment by bld7** [comment]
@saching13 The stereo_inertial_node.launch.py file had a number of differences compared to your new one, so I copied your complete file.  The output from
DEPTHAI_LEVEL=debug ros2 launch turtlebot4_bringup oakd.launch.py
and
ros2 launch -d depthai_examples stereo_inertial_node.launch.py enableRviz:=false
are attached. Note that I put in the original RPI sd card to continue with where we left off earlier.
[stereo_inertial_launch_output.txt](https://github.com/turtlebot/turtlebot4/files/10386292/stereo_inertial_launch_output.txt)
[oakd_launch_output.txt](https://github.com/turtlebot/turtlebot4/files/10386293/oakd_launch_output.txt)

**Comment by bld7** [comment]
@roni-kreinin  I executed the udev rule fix you sent using the new RPI image. The ros2 launch turtlebot4_bringup oakd.launch.py output and the DEPTHAI_LEVEL=debug ros2 launch turtlebot4_bringup oakd.launch.py ouput are attached. Note that I had this same error last year with the old image, and at that time I tried the same udev rules fix from the luxonis site.
[udev_rules_fix_output.txt](https://github.com/turtlebot/turtlebot4/files/10386356/udev_rules_fix_output.txt)

**Comment by saching13** [comment]
> [rgb_stereo_node-1]   what():  Failed to connect to device, error message: X_LINK_DEVICE_ALREADY_IN_USE

It looks like there might be another node already running which connected to the device.

**Comment by roni-kreinin** [comment]
@bld7 The turtlebot4 service will be enabled with the new image. You can disable it again with `sudo systemctl disable turtlebot4`

**Comment by roni-kreinin** [comment]
Closing as stale.
