### ISSUE TITLE
Unable to Connect Bluetooth Controller - No default controller available

### ISSUE THREAD

**Issue by CycleMark** [turtlebot/turtlebot4#86]
Hi - I have the Turtlebot4 Lite.

I'm trying to connect a BT controller - Specifically - https://www.amazon.co.uk/gp/product/B08XY86472/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

![TurtleBot4 BT Issues](https://user-images.githubusercontent.com/27418725/204312787-daac771c-6481-4955-bedc-611cdf883ada.png)

For example command:
sudo bluetoothctl --agent=NoInputNoOutput show

is kicking back with:

No default controller available

Much searching of the internet suggested trying 

 sudo systemctl start hciuart

Which fails - but not with much info
: Failed to start Configure Bluetooth Modems connected by UART

I've attached a Screen shot of the various probelms.

Anyone else had/seen/resolved these issues.

Kind Regards

Mark

**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: (Galactic
 - installed:
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)

**Comment by roni-kreinin** [comment]
@CycleMark Can you try the following:

```
sudo systemctl disable hciuart
sudo reboot
```
When it boots, SSH in again and call `sudo systemctl restart hciuart`, then try to run `sudo bluetoothctl` again.

**Comment by CycleMark** [comment]
Hi @roni-kreinin - Thanks for that. It seems to have worked, to a point in that I've had to re-run is at boot time a few times.

Oddly - whilst /cmd/vel is now showing output it's seem laggy and the robot isn't moving turtlebot_bringup et al is running. Any think I can look at?

Thanks

Mark

**Comment by roni-kreinin** [comment]
@CycleMark If you are using CycloneDDS its possible that the Create 3 may have gone into an error state from losing the `usb0` connection on RPi reboots. Try restarting the application using the webserver.

**Comment by CycleMark** [comment]
Hi @roni-kreinin  - Thanks. BT issue seems to be resolved. But iCreate/RPi interface very flakey. Will open a new Issue.

Mark
