### ISSUE TITLE
TB4 color camaera is working but streo/depth Topic is not working

### ISSUE THREAD

**Issue by rhyeonwoo** [turtlebot/turtlebot4#93]
Used 
ubuntu : 20.04
ros distro : Ros2 Galactic
robot : TB4 standard

As the title says, the camera comes out, But I cannot get stereo/depth topic well

I unplugged and re-connected the camera line, and I turned off and on the robot, but it still doesn't work.

Please check the attached photo 

![turtlebot4 -2](https://user-images.githubusercontent.com/100173088/206942446-a6732e02-8d2d-4168-b4ba-81027a217b12.png)
![turtlebot4 -1](https://user-images.githubusercontent.com/100173088/206942456-ec69387e-f021-468d-85f1-cfb400074ad8.png)

What's the problem? I want to know.
Thank you.

**Comment by roni-kreinin** [comment]
@rhyeonwoo Where are you having issues getting the depth image? It looks like your `ros2 topic echo` is working.

**Comment by rhyeonwoo** [comment]
In the same way , In front of my desk, the other TB4 get stereo/depth topic well.
I all waved in the same way.
only this robot doesn't change the data from zero.

I tested it by connecting the camera  of a well-functioning robot and found the /stereo/depth topic without any problems.

If it doesn't come out, is there any other way to try it?
Thank you my problem help.

update
In addition, there are additional robots with the same symptoms.

**Comment by roni-kreinin** [comment]
@rhyeonwoo Can you test out some of the other depthai nodes such as https://github.com/luxonis/depthai-ros/blob/ros-release/depthai_examples/launch/stereo.launch.py?
