### ISSUE TITLE
Appear name of RPi AP 'turtlebot4', but cannot connect WIFI with Infinity loading

### ISSUE THREAD

**Issue by Navifra-Tobey** [turtlebot/turtlebot4#94]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed:
 - Package version: 

 **Expected behaviour**
if appear name of RPi AP "Turtlebot4" and click and type passward 'Turtlebot4'(after ringing create3.), so wifi will be connected -> ssh ubuntu@~.~.~.~ in terminal -> connect my PC and RPI4

 **Actual behaviour**
AP is detected, but i cannot connect RPI wifi and my PC with infinity loading. so SSH is not working.

**To Reproduce**
Provide the steps to reproduce:
1. reboot robot and RPi - not working 
2. connect ethernet port of RPi and USB port of my PC with adapter - working :) but i want to connect with wifi :(

**Other notes**
it happened after edit "cyclonedds_pc.xml"

**Comment by roni-kreinin** [comment]
If you can connect with ethernet, can you SSH in and connect the RPI to your WiFi network?

**Comment by Navifra-Tobey** [comment]
oh. my mistake... i understand form your comment, i misunderstand the manual :(

now it's working!! thank you
