### ISSUE TITLE
TurtleBot 4 Lite can't undock

### ISSUE THREAD

**Issue by MathisGodard** [turtlebot/turtlebot4#95]
Hello,

A customer bought the new turtlebot 4 lite, and he has some problems with the undock of the robot. 

He follows the [start guide on your git](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html). He uses Thinkpad E580 with Ubuntu 20.04 LTS focal fossa to communicate with the robot. He can access to the robot via SSH, he can do "ros2 topic echo /ip" and he can "ros2 topic list"

But when he tries to undock manually, the robot is not moving : "ros2 run turtlebot4_tests ros_tests". When he tries the LED control, that is not working too. 

He doesn't have error message. 

Best regards, Mathis.

**Comment by roni-kreinin** [comment]
Can you paste the output of `ros2 topic list`? It sounds like there is no communication with the Create 3 base.

**Comment by MathisGodard** [comment]
Hello, Thanks for your repply.

![image](https://user-images.githubusercontent.com/39947894/211537052-3d8fc547-7ebf-4132-bcc4-8673a4f70005.png)

Best regards, Mathis.

**Comment by roni-kreinin** [comment]
@MathisGodard So the Create 3 topics are not showing there, only the ones used by the RPi. Has the Create 3 been connected to WiFi and configured with the same ROS_DOMAIN_ID?

**Comment by MathisGodard** [comment]
Hello,

The Create3 platform is in ROS_DOMAIN_ID 0, and to be sure I exported ROS_DOMAIN_ID=0 on my development PC and on the rpi I checked the line already exists in the bashrc.

I see when I connect to the Create3 web page, I never have an IP address, whereas in the tutorial there is one
I have that : 
![image](https://user-images.githubusercontent.com/39947894/212847820-aa61ed17-bd8b-4663-b25c-b4504a234ecf.png)

I'm desperately stuck on this page:
![image](https://user-images.githubusercontent.com/39947894/212848229-5e01f98a-9474-4f03-bda7-72cfb20fc564.png)

I also configured my router to be 2.4GHz because there was a note on it but nothing helped.

If is possible, we can do a remote session to be repaired if it is easier

![Screenshot from 2023-01-16 22-08-53](https://user-images.githubusercontent.com/39947894/212848546-1ecd8eae-2afa-4732-9e0e-4f8f294a7fc6.png)

This case is really urgent.
Best regards, Mathis.

**Comment by roni-kreinin** [comment]
Do you have another 2.4GHz router you could test with? Or maybe just a hotspot from a phone?

**Comment by MathisGodard** [comment]
I managed to make the platform work. I changed the router to only use 2.4GHz and not 2.4 and 5GHz, I guess that was the problem.

**Comment by roni-kreinin** [comment]
The 2.4 and 5GHz networks may not have been bridged. There will be a new firmware update for the Create 3 soon that will allow for TB4 to operate on just the RPi WiFi. It should fix networking issues like this.

**Comment by roni-kreinin** [comment]
@MathisGodard Please try using the FastDDS discovery server as mentioned [here](https://github.com/turtlebot/turtlebot4/issues/26#issuecomment-1416310217).
